### PR TITLE
Use NumbaTypeError instead of TypeError in reshape, transpose, astype

### PR DESCRIPTION
**Pull request by lericson**
I'm not sure if I'm missing something here, but my code breaks 0.58.1 → 0.60 without these changes.

### CODE REVIEW

**Comment by lericson** [comment]
Code that breaks:

```python
"""Deduplicate line segments by expanding them to their largest overlapping
segment endpoints.

For example, if three segments are situated like this (but on top of each
other)

    --
     ---
       ----

we generate three segments

    ----
    -------
     ------

This routine is applied again until the three segments will be identical
and can be collapsed into one segment, dedupe() does this.
"""

import numpy as np
from numba import njit

norm_tol  = 1e-12
y_tol = 1e-4


@njit('uint32(float64[:, :, ::1], bool_[::1], float64)')
def _expand_overlapping_broadcasting(segs, where, y_tol=y_tol):

    # Unused
    where

    num_updated = 0
    segs_ = np.empty_like(segs)

    # Shorthands. Segments span a-b, where a = (x1, y1) and b = (x2, y2).
    A_, B_  = segs_[:, 0, :], segs_[:, 1, :]
    X1_, Y1_ = A_[:, 0], A_[:, 1]
    X2_, Y2_ = B_[:, 0], B_[:, 1]

    for i in range(segs.shape[0]):

        # Translate so current segment starts at a = (0, 0) and ends at b = (x, y).
        t_i      = segs[i, 0, :]
        x_i, y_i = segs[i, 1] - t_i

        norm = np.sqrt(x_i**2 + y_i**2)
        #if norm < 1e-9:
        #    continue
        assert norm_tol < norm

        # Rotate all segments so current segment ends at b' = (x', 0) where x' = |x, y|.
        R_i = np.array([[x_i, -y_i],
                        [y_i,  x_i]]) / norm

        for j in range(segs_.shape[0]):
            segs_[j] = (segs[j] - t_i) @ R_i
            #np.dot(segs_t[j], R_i, out=segs_[j])
            if X2_[j] < X1_[j]:
                A_j_tmp = A_[j].copy()
                A_[j] = B_[j]
                B_[j] = A_j_tmp

        assert np.allclose(A_[i], 0.0)
        assert np.isclose(X2_[i], norm)
        assert np.isclose(Y2_[i], 0.0)

        # Flip segments (a,b) to (b,a) s.t. x1 <= x2.
        #flip = X2_ < X1_
        #A_[flip], B_[flip] = B_[flip].copy(), A_[flip].copy()
        #assert np.all(X1_ <= X2_)

        # Segment is collinear if it's on the X axis
        collinear = (np.abs(Y1_) < y_tol) & (np.abs(Y2_) < y_tol)

        # Check if other segment's X coordinates are inside this line
        overlap_x1 = (0.0 <= X1_) & (X1_ <= X2_[i])
        overlap_x2 = (0.0 <= X2_) & (X2_ <= X2_[i])

        selected = collinear & (overlap_x1 | overlap_x2)

        x1_min = np.min(X1_[selected])
        x2_max = np.max(X2_[selected])

        # Invert and put back into original array. Overwrite all overlapping
        # line segments with the same maximum line segment, which is exactly
        # collinear with segs[i].
        update = selected & ~(np.isclose(X1_, x1_min) & np.isclose(X2_, x2_max))
        new_seg = np.array([[x1_min, 0.0],
                            [x2_max, 0.0]])
        segs[update] = (new_seg @ R_i.T) + t_i
        num_updated += np.count_nonzero(update)

    return num_updated
```

**Comment by lericson** [comment]
I should clarify "breaks", the np.isclose now has the wrong shape for some reason -- that is not my issue -- rather, I do not now obtain a useful traceback. Instead it gives an exception on the `@njit` line.

**Comment by lericson** [comment]
Second addition, this issue is fixed in my code by having my own overload of `np.isclose` that does actually work with non-contiguous arrays (as the real `np.isclose` does), the use of `TypeError` over `NumbaTypeError` seems to make it so that the compiler never tries to use my version of `np.isclose`.

**Review by sklam — APPROVED** [review]
Changes look good

**Comment by sklam** [comment]
Numba devs will need to scan for more of these and fix as much as we can find.

**Comment by stuartarchibald** [comment]
Thanks again for highlighting the issues fixed by this PR @lericson, it turns out that there are _many_ instances of similar issues and the maintainers have attempted to assess the whole code base with view of fixing up problems caused by "hard-errors". This work is in #9837 and needs to go into the Numba 0.61.0 series as part of the RC2 builds. PR #9837 encompasses and supersedes the changes in this PR, and in the interests of keeping Numba's history and patching patterns simple, the maintainers would like to accept #9837 in favour of this one, however, the maintainers also want to make sure you are included as a contributor in the release notes for 0.61.0. Hope that's ok?! Thanks for your understanding and contributions to Numba.

**Pull request closed without merging**
