### PR TITLE
Add FAQ entry on how to reference Numba.

### LINKED ISSUE #2524: How to acknowledge Numba in research work?
Numba has been tremendously helpful in my research work, and we are about to publish a paper based on the simulation work Numb  helped speed up. I recall seeing some instructions regarding how to acknowledge Numba once upon a time (must be a couple of years ago now), but am having trouble finding it. Could someone link me to it, or perhaps add some documentation which clarifies this?

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

Closes #2524

### CODE REVIEW

**Comment by cdeil** [comment]
This article is behind a paywall.

Does an openly available version exist, or are you allowed to post it somewhere (e.g. the numba webpage)?

Would be much nicer and probably get you more citations - at least I would prefer to link to an openly available resource, i.e. as it stands not refer to the paper, but just http://numba.pydata.org/ .

**Comment by stuartarchibald** [comment]
@cdeil please could you open a new issue about this? This is a merged and closed patch and so won't be tracked. Thanks.

**Comment by cdeil** [comment]
@stuartarchibald - sure, I opened a new issue here: #3981

**Comment by stuartarchibald** [comment]
@cdeil great, thanks.

**Pull request merged**
