### PR TITLE
Avoid unnecessary ir.Del generation and removal

### PR DESCRIPTION
**Pull request by ehsantn**
Removes unnecessary ir.Del generation and removal in Parfor code, which used to be necessary. This simplifies the code (and may slightly improve compilation time).

### CODE REVIEW

**Comment by ehsantn** [comment]
I assume the docs failure is not relevant.

**Review by DrTodd13 — APPROVED** [review]
@ehsantn If it passes the regression tests I'm fine with it but do you remember why we got rid of del's originally?  About my only concern is that the code movement code is able to move dels around to enable fusion but if the regressions pass then I assume this is working since we test that.

**Comment by ehsantn** [comment]
Thank you @DrTodd13. I think we removed dels since our transformations would make them invalid (e.g. some variable is removed). Much easier to regenerate them than to consider them in every change.

**Comment by stuartarchibald** [comment]
Thanks for the patch @ehsantn, good to see less postproc use. The IR is `Del` free for a lot of the pipeline but some things unfortunately still need it.

**Comment by stuartarchibald** [comment]
Thanks for the review @DrTodd13 !

**Comment by stuartarchibald** [comment]
@ehsantn any chance in future you could please use your fork of Numba for creating patches, we try really hard to keep the `numba/numba` repo with just release branches and a few others kept for historical reasons. Many thanks for your cooperation.

**Comment by ehsantn** [comment]
Sorry, just a mistake. Will do.

**Comment by stuartarchibald** [comment]
> Sorry, just a mistake. Will do.

No worries, and thanks :)

**Pull request merged**
