### PR TITLE
Move a couple of CUDA-specific items into the CUDA target

### PR DESCRIPTION
**Pull request by gmarkall**
Dummy arrays and device ufuncs are only used by the CUDA target, and I think are not generally useful even for someone implementing a new target:

- The device ufunc implementation is quite different to how you'd want to write an implementation for a new target from scratch
- Numba targets should probably not provide their own device array implementation - some other library should provide it, for the Numba target to operate on (c.f. how the CUDA Array Interface allows Numba kernels to run on various array types like CuPy arrays, cuDF Series, etc.)

This PR moves them into the CUDA target, with the aim of making the core of Numba a little smaller and tidier.

### CODE REVIEW

**Review by stuartarchibald — DISMISSED** [review]
Thanks for the patch @gmarkall , seems like a good idea to move these modules to `cuda` for the reasons noted above. I also checked `numba-dpex` (another extension) and that doesn't seem to use these modules. Thanks again!

**Comment by stuartarchibald** [comment]
Looks like there's a few test failures that need addressing, didn't notice those previously, apologies. Will re-approve once resolved.

**Comment by gmarkall** [comment]
Thanks for the quick review @stuartarchibald ! I hadn't thought of the fact that I was moving files that weren't flake8-compliant, but I've fixed them up. The `TestIterate` case in `test_dummyarray` is super-weird but I don't want to get into fiddling with test cases as part of a simple move, so I've just added `noqa: F841` for it for now - I expect to do some tidying up of the dummy array stuff following this so I'll save it for that.

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
> Thanks for the patch @gmarkall , seems like a good idea to move these modules to `cuda` for the reasons noted above. I also checked `numba-dpex` (another extension) and that doesn't seem to use these modules. Thanks again!

Forgot to mention, I also checked Ramba and numbaWithOpenmp as well and didn't find any use of them there either.

**Comment by gmarkall** [comment]
gpuci run tests

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch and fixes.

**Pull request merged**
