### PR TITLE
Fixes ReST syntax error in PR#9099

### PR DESCRIPTION
**Pull request by sklam**
Addresses review comments for #9099.
Also merged main and resolved a conflict.

### CODE REVIEW

**Comment by sklam** [comment]
It's now failing on the same reason as https://github.com/numba/numba/pull/9099#issuecomment-1653761038

**Comment by sklam** [comment]
Failing tests are pending https://github.com/numba/numba/pull/9114

**Review by gmarkall — APPROVED** [review]
The RST fix results in the text rendering correctly. Will approve this and mark as waiting on CI, then we can test once the prerequisite PR is in.

**Comment by esc** [comment]
#9114 was merged and so this can be restested

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Pull request merged**
