### PR TITLE
Proposal: change integer typing

### PR DESCRIPTION
**Pull request by pitrou**
This adds a proposals section to the docs and a first proposal (do we call them NEPs? confusion with Numpy NEPs?).

### CODE REVIEW

**Comment by seibert** [comment]
I like this proposal, and it looks like it will fix one of our performance issues on the GPU, where aggressive promotion to int64 can hurt performance during array index calculations.

(I was about to write two different objections to this proposal, only to discover that I had misread it and your promotion rules had already addressed my objection.  :) )

**Comment by pitrou** [comment]
> I like this proposal, and it looks like it will fix one of our performance issues on the GPU

What is the supposed "bitness" of the GPU for Numba, btw? 32 bits?

**Comment by pitrou** [comment]
Oh and also, I don't think we need to discuss the proposal before the PR is merged; at least merging it will give a more readable view in the generated docs :)

**Comment by seibert** [comment]
32-bits is the most efficient word size (float and int) on all recent GPUs.  Below that, there is no performance improvement, and above that there can be serious performance drawbacks.  Future GPUs (at least from NVIDIA, though AMD seems to also be getting on-board with this) will have some hardware support for 16-bit floats, but we can ignore that for now.

Once upon a time, 24-bit integer multiplication (with a special intrinsic function that basically used the mantissa multiplier of the FPU) was fast in CUDA, and was used by CUDA programmers to speed up index calculation, but that hack has disappeared from the GPUs that Numba supports.

**Comment by seibert** [comment]
Before merging, can we add some kind of warning at the top of the proposal that indicates this proposal has not been accepted?  I don't want someone to accidentally think this has already been implemented yet.

**Comment by pitrou** [comment]
We could add a status field indeed. Let me see.

**Comment by pitrou** [comment]
Ok, I've added "Status: Draft" at the top.

**Comment by seibert** [comment]
OK, thanks!

**Comment by sklam** [comment]
The original typing semantic tries to match NumPy's.  Changing this will impact many code because ndarray.__getitem__ returns numpy scalars.

**Pull request merged**
