### PR TITLE
Remove remaining mentions of autojit in docs

### PR DESCRIPTION
**Pull request by cdeil**
This is a tiny docs cleanup PR - removing the mention of `autojit` that was deprecated years ago from the docs and examples.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the PR, this is timely with respect to https://github.com/numba/numba/pull/4041 where some clean up is being done. Change looks good, though I note there's one more use of `Autojit` here: https://github.com/numba/numba/blob/1de3cd5a687011d90b1a26070c6fe47abdf8a2a5/examples/notebooks/Using%20Numba.ipynb?short_path=ba1f63e#L137 which would be good to remove too. Thanks again!

**Comment by cdeil** [comment]
Should I do the edit in https://github.com/numba/numba/blob/1de3cd5a687011d90b1a26070c6fe47abdf8a2a5/examples/notebooks/Using%20Numba.ipynb?short_path=ba1f63e#L137 in this PR?

Is removing `numba.autojit` completely now an option? It's been deprecated for 5 or 6 years? If it can be done soon, maybe open a new issue or PR to discuss? (unless it's uncontroversial and I could just do it here in this PR)

**Comment by cdeil** [comment]
Concerning https://github.com/numba/numba/blob/1de3cd5a687011d90b1a26070c6fe47abdf8a2a5/examples/notebooks/Using%20Numba.ipynb - it's not using `numba.autojit`, it just has this in the text description / label for a matplotlib plot.

Another case of `numba.autojit`: https://github.com/numba/numba/blob/master/buildscripts/condarecipe.local/mandel.py
Is that used? I.e. should it just be deleted or updated?

CI is green here, so this could go in.

I think the notebooks pretty much need a complete re-structure and rewrite anyways?
There's `examples/notebooks`, and `tutorials` in this repository, but neither of which are exposed via the Numba docs.
Instead http://numba.pydata.org/ links to the ones in  https://github.com/numba/numba-examples and those are already in much better shape than the ones in `examples/notebooks` or `tutorials`.

**Comment by stuartarchibald** [comment]
> Is removing numba.autojit completely now an option? It's been deprecated for 5 or 6 years? If it can be done soon, maybe open a new issue or PR to discuss? (unless it's uncontroversial and I could just do it here in this PR)

It is an option. Numba core developers have been discussing this (discussion is ongoing) along with other deprecations/removals scheduled for 0.44. We have to be exceedingly careful when making these sorts of changes to Numba due to the core-dependency nature of the project.

> Concerning https://github.com/numba/numba/blob/1de3cd5a687011d90b1a26070c6fe47abdf8a2a5/examples/notebooks/Using%20Numba.ipynb - it's not using numba.autojit, it just has this in the text description / label for a matplotlib plot.

Correct, I still think it makes no sense? and I think can be changed in this PR.

> Another case of numba.autojit: https://github.com/numba/numba/blob/master/buildscripts/condarecipe.local/mandel.py
> Is that used? I.e. should it just be deleted or updated?

I think leave it for now, it'll require conda recipe change so I'd like to check it on the build farm (should be fine) and will open a PR accordingly.

> CI is green here, so this could go in.

CI is indicative only, a bit like a smoke test :) the Numba build farm is where the real testing takes place. I think in this case the patch should be fine.

> I think the notebooks pretty much need a complete re-structure and rewrite anyways?

Yes!

**Comment by cdeil** [comment]
OK, fine. I've updated and re-run `examples/notebooks/Using Numba.ipynb`. See 043381d9a .

I've renamed "typed" and "autojit" to "eager_jit" and "lazy_jit" following the terminology here:
http://numba.pydata.org/numba-doc/latest/user/jit.html

Not sure if showing both is useful - they result in the same compiled function and performance.

But since notebooks will have to be reworked anyways and something like this might just be deleted or moved elsewhere, I'm not sure it's worth spending time on improving further here (like e.g. possibly removing either eager or lazy jit from the performance comparison).

**Comment by seibert** [comment]
Can you merge the master branch into this PR?  There is now a conflict because this PR edits the example file which was removed by #4067.

**Comment by cdeil** [comment]
Done in edc5599ba . Ready to merge?

**Comment by seibert** [comment]
I think this is ready to merge now.

**Pull request merged**
