### PR TITLE
PowerPC reference counting memory fences

### PR DESCRIPTION
**Pull request by obilaniu**
## Fences in Reference Counting

The PowerPC has a weakly-ordered memory model. This means that the memory accesses of a single thread may be reordered with respect to other processors, and may be out-of-order, or even speculated in a predicted-taken conditional branch.

The current Numba RunTime implementation works on x86-derived architectures _only_ because the x86 architecture has such strong ordering that no explicit fences are needed for reference counter increment needs.

The needs of a reference counting implementation are as follows:

- *Increment*:
  - Must be done atomically
  - Must become globally visible within a finite amount of time
-  *Decrement*:
   - Must be done atomically
   - Must become globally visible within a finite amount of time
   - All memory accesses by the decrementing thread to the reference-count-protected object must become globally visible no later than the successful _store_ of an atomic decrement.
     - Otherwise, the thread that successfully zeroes the reference count does not have a guarantee from other threads that the object will be in a consistent state.
   - No memory accesses may be done by destructor code unless and until the thread successfully zeroes the reference count.
     - Otherwise, the destructor could perform speculative loads of stale data before zeroing the reference count, and then use this stale data even though other threads have updated the object with fresh data and committed it before the reference count's writeback.

On *x86*,

- Loads are not reordered with other loads
- Stores are not reordered with stores, with irrelevant exceptions
- The `lock cmpxchg` issues both a load and a store indivisibly and unconditionally
- Therefore, all loads and stores are ordered w.r.t. the atomic increment/decrement, and nothing further needs to be done.

On *PowerPC*,

- Loads can be reordered with other loads
- Stores can be reordered with stores to non-overlapping locations
- Loads can be reordered with stores to non-overlapping locations
- Speculative loads are allowed
- An atomic increment is a `lwarx / stwcx` (load & reserve, store-conditional) sequence
- Therefore, memory accesses before and after the atomic decrements may be reordered w.r.t. the atomic decrement (we don't care about that in the case of reference increments).

The proposed solution is to

  1. In increment, do nothing more.
  2. In decrement, use a `fence release` immediately before the atomic decrement loop, since it lowers to a `lwsync` that orders all data accesses before the `stwcx` store that writes back the new counter value.
  3. In decrement, use a `fence acquire` conditionally inside the branch that leads to the destructor, because its effect is not required if the destructor is not invoked and it orders all data accesses in the destructor after the `lwarx` that will end up feeding the successful `stwcx`. 

 ~Requires [llvmlite PR 330](https://github.com/numba/llvmlite/pull/330)~ Done.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the PR and detailed explanation. As noted in https://github.com/numba/numba/issues/2451 some issues in the LLVM code base are fixed in 6.0.0 which, as of a few days back, is now publicly released. I'm going to hold off on reviewing this until we've patched llvmlite and Numba internals to support LLVM 6.0, at which point this patch will have the most chance of giving an accurate picture of POWER8 support.

**Comment by obilaniu** [comment]
@stuartarchibald Completely fair. I await LLVM 6 support impatiently. Please ping me whenever you push the `llvm6` branch, I'll attempt to test it.

I do note that the patches above are necessary, but not enough on their own; The relocation troubles I explained on #2451 are by far the biggest problem, and LLVM 6 may or may not have solved them. That explains why I'm so anxious to test-drive LLVM 6.

**Comment by obilaniu** [comment]
@stuartarchibald I've noticed your llvmlite `wip/llvm6` branch includes changes related to LLVM 6's removal of the `jitdefault` code model. I assume this will also require changes in Numba to remove references to that code model. This makes my second commit in this series obsolete; Whenever Numba merges in LLVM 6 support and/or the removal of `jitdefault`, please ping me and I will withdraw that commit.

**Comment by obilaniu** [comment]
@stuartarchibald By merging llvmlite PR330, you've also cleared this PR's only dependency. This PR, however, only has any effect on `powerpc` machines, so of course cannot truly be tested with the buildbots. Moreover, while the fencing does solve several segfaults, it is not enough. The discussion in #2451 should probably have convinced you already that there's another bug, this one in LLVM 6, that causes far more segfault problems due to bad runtime dynamic linker relocations.

It's up to you: You can merge this PR in, knowing that when the LLVM relocation _(and in very rare cases, PPCCTRLoops)_ problems are solved Numba will work on PPC64; Or you can wait until LLVM JIT first makes itself usable on PPC64 before you import into Numba code for an untestable, currently-broken platform.

There is probably one more thing worth mentioning. As written, I enable the fencing only for `powerpc` triples. However, the same fix will be required for ARM 32-bit and 64-bit, and possibly many other architectures as well. I'd like to reverse the comparison, and _disable_ the fencing _only for x86-family architectures_, given their exceptionally strong memory ordering. But how to do that? I have to detect at least `x86-64`, `x86_64` and `i386` triples. Is there a more general function that just gives me a canonical architecture (`x86`, `powerpc`, `arm`, `mips`, `alpha`, ...)?

**Comment by obilaniu** [comment]
When this commit is rebased on top of 85178eb180ce5b44545d93072279007aea222202, all testcases seem to pass on PPC64LE so far.

When this commit is rebased on top of 35d29779650ef89c8a7b23dd006e73663055cad5 (current tip of `master`), many basic testcases break.

I don't think this is my commit's fault, because 1) Having this commit is strictly safer than not having it and 2) The errors happen even without this commit on testcases that didn't require fencing, so I think someone else broke the build somewhere after PR 2779 was merged yesterday morning. The guilty commit is somewhere here:

```
$ git log --oneline 85178eb180ce5b44545d93072279007aea222202..HEAD origin/master
35d2977 Merge pull request #2777 from stuartarchibald/wip/correlate_convolve
38309e0 Merge pull request #2847 from ehsantn/issue_2846
0b11f9a Merge pull request #2864 from stuartarchibald/fix/2863
a1985e1 Merge pull request #2867 from aolivas/master
17f17ce parfor index replace add comment
71ed95c refactor parfor loop body dummy return to use contextmanager
0bbef98 Respond to PR comments.
f3cd39e Rounded out the device attribute enums to support all currently known CUDA attributes.
72ae041 Correct C code to prevent compiler warnings.
706b41a generalize find_callname to support obj.func calls (not just array.func)
46a65c3 build_definitions bugfix use defaultdict
7052f22 test for inner loop parfor fusion after array generation
43f2bfe remove parfor build_definitions in array analyze
883362e test kmeans for nonparfor accesses
9dcf604 replace array access index in parfors recursively
647f4fd fix tuple matching
b55bfd9 refactor access replace and handle static cases
b5ffe4b test array access replace with multi-dim slice
0529d05 handle slices in multi-dim access replacement
605ae33 rename parfor test1/2
5324d52 test array allocs in lr example
1d5b274 build definitions for parfor body
b64dad4 refactor ir_utils build_definitions
fa8c041 improve parfor get/setitem replacement
3d4a587 autopep8 logistic regression example
4062f27 add missing docstring
5f11dac test np.dot access index replace
b4ef7a6 replace prange array index in multi-dim access
cd1e4b3 test assertion of prange index overwrite
65ba87d count arrays in parfor tests pi, fuse argmin
706ad27 remove dead parfor getitem/setitem fix
18a62aa test for multi-loop array access index replace
29d3121 test for array access index replace
d4c6b01 prange replace array access handle index copies in first body block
6453a76 refactor out unused ext_func option of apply_copy_propagate
49d815e replace array access indices in prange loop body
407c144 Fixes WRT review.
6ac35c0 Add support for np.correlate and np.convolve
```

**Comment by seibert** [comment]
OK, good to know.  We merged a bunch of PRs that had become blocked behind the LLVM6 patch, and maybe two of them are interacting badly.  Our CI system is catching up on master, so we can see what happened.

**Comment by obilaniu** [comment]
@seibert I know which one it is. PPC64 tests started breaking after #2777 was merged. Can't really explain why at this point, but the symptoms for me are

```
$ git reset --hard 35d29779650ef89c8a7b23dd006e73663055cad5
HEAD is now at 35d2977 Merge pull request #2777 from stuartarchibald/wip/correlate_convolve
$ ./runtests.py numba.tests.npyufunc.test_errors.TestFloatingPointExceptions.test_floordiv_float
F
======================================================================
FAIL: test_floordiv_float (numba.tests.npyufunc.test_errors.TestFloatingPointExceptions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/npyufunc/test_errors.py", line 139, in test_floordiv_float
    "invalid value encountered"])
  File "numba/tests/npyufunc/test_errors.py", line 133, in check_divmod_float
    self.assertPreciseEqual(res, expected)
  File ".local/anaconda2/envs/numbadev/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "numba/tests/npyufunc/test_errors.py", line 97, in check_warnings
    self.assertEqual(len(catch), len(messages))
AssertionError: 6 != 2

----------------------------------------------------------------------
Ran 1 test in 0.875s

FAILED (failures=1)
$ git reset --hard 38309e0ef398b8690d2d742983ee296a21f226dc
HEAD is now at 38309e0 Merge pull request #2847 from ehsantn/issue_2846
$ ./runtests.py numba.tests.npyufunc.test_errors.TestFloatingPointExceptions.test_floordiv_float
.
----------------------------------------------------------------------
Ran 1 test in 0.863s

OK
```

**Comment by obilaniu** [comment]
Hmm okay, the reason for those new testcase failures is that the testcases are expecting precisely 2 warnings but gets 6. The 6 warnings are the two expected ones plus 4 others that occur when Scipy is pulled in, and complain about a data structure size mismatch in Scipy:

```
'lib/python2.7/site-packages/scipy/linalg/basic.py:17:  numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88'
'lib/python2.7/site-packages/scipy/linalg/__init__.py:202:  numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88'
'lib/python2.7/site-packages/scipy/linalg/__init__.py:202:  numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88'
'lib/python2.7/site-packages/scipy/linalg/__init__.py:202:  numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88'
'numba/tests/npyufunc/test_errors.py:132:  divide by zero encountered in floordiv'
'numba/tests/npyufunc/test_errors.py:132:  invalid value encountered in floordiv'
```

Supposedly the size errors are not important, but I'm trying to work around them. This is probably not a PPC64-specific error, more likely a slightly-incompatible Scipy and Numpy. Could happen anywhere.

**Comment by sklam** [comment]
It looks like the dtype size changed warning can be safely ignored: https://github.com/ContinuumIO/anaconda-issues/issues/6678

**Comment by obilaniu** [comment]
@stuartarchibald @sklam Given that

- The above size warnings can be ignored and are not caused by my patch,
- That required patches have been merged in both LLVM ([[1]](https://reviews.llvm.org/rL328400), [[2]](https://reviews.llvm.org/rL329335)) and llvmlite ([[3]](https://github.com/numba/llvmlite/pull/330)),
- That running the full testsuite confirms that this patch eliminates the remaining segfaults for POWER8 (See #2451) and
- That this patch is small, only has effect on PowerPC and strictly strengthens the memory ordering guarantees over the current situation (as argued above),

May I call for this PR's merger into mainline?

**Comment by stuartarchibald** [comment]
@obilaniu Thanks for your efforts on this. This patch will help with POWER support and does not impact other platforms. When the time comes we can cherry-pick the LLVM patches from mainline and put them into the llvmlite LLVM bootstrap build. This patch can be merged for 0.38 RC (pending build farm being free!). Thanks for your contribution(s).

**Pull request merged**
