### PR TITLE
Fixes and cleanup of cuda resource management

### PR DESCRIPTION
**Pull request by sklam**
based on https://github.com/numba/numba/pull/1859

* avoid using ``__del__``
* fixed an issue with pointer ownership in derived pointer
* cleanups

### CODE REVIEW

**Comment by pitrou** [comment]
> fixed an issue with pointer ownership in derived pointer

Is it easy to add a test for this issue?

**Comment by sklam** [comment]
@pitrou,

> Is it easy to add a test for this issue?

 test added at e6faa19.

**Comment by pitrou** [comment]
Is this ready for merging or are you planning to push other changes?

**Comment by sklam** [comment]
Ready to merge

**Pull request merged**
