### PR TITLE
Fix errors introduced by the cloudpickle patch

### PR DESCRIPTION
**Pull request by sklam**
- Revert removal of `_RedirectSubpackage`
- pin pickle protocol to 4

### CODE REVIEW

**Comment by sklam** [comment]
BFID `numba_smoketest_cpu_yaml_18`

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by sklam** [comment]
This is introducing segfault in `numba.tests.test_parallel_backend`

**Comment by sklam** [comment]
At this point, i'm not sure if the failing in `test_parallel_backend` is a pre-existing problem.

**Pull request merged**
