### PR TITLE
Cherrypicks for 0.57 final

### PR DESCRIPTION
**Pull request by sklam**

### CODE REVIEW

**Comment by sklam** [comment]
BFID: `numba_yaml_342`

**Comment by sklam** [comment]
> numba_yaml_342

All green

**Comment by sklam** [comment]
Noticed the need for https://github.com/numba/numba/pull/8924 in the buildfarm run

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. Manually replaying the PRs in the `Numba 0.57 final` milestone onto `release0.57` and running `git diff` against this PR yields and empty diff, visual inspection of the patch against the same PRs suggests they are the same too.

**Review by stuartarchibald — APPROVED** [review]
This is re-approved following the addition of 64f56c2. I replayed the cherry-pick of the merge commit locally and resolved the conflict, the diff of the result matches the aforementioned commit, and the diff against this PR is empty, visual inspection also suggests it's valid. Thanks for the update @sklam.

**Pull request merged**
