### PR TITLE
Addition of PyCon India 2019 talk on Numba

### PR DESCRIPTION
**Pull request by animator**
Adding PyCon India 2019 talk to the Numba list of Talks/Tutorials.

Regards,
Ankit

### CODE REVIEW

**Comment by esc** [comment]
@animator Awesome! Thanks for submitting this. It looks good to me and I will mark it as ready for merge. I assume you did run sphinx locally to check that link is being displayed correctly?

**Comment by animator** [comment]
Thanks @esc ! 
Yeah I checked it. It was displaying correctly.

**Comment by esc** [comment]
@animator thanks for submitting and helping to improve and spread the word about Numba! This will probably be merged during our next merge window.

**Comment by animator** [comment]
Sounds Great! 
My only regret is that I came across Numba this year. Wish I had known about it a bit earlier. 
It is pure magic. Thanks to the entire numba dev team!

**Comment by DrTodd13** [comment]
I think some of your examples were parallelizable.  So, if you give the talk again, maybe try adding parallel=True and report the performance improvements there as well.  Well done on the talk and thanks again for supporting Numba.

**Pull request merged**
