### PR TITLE
Removed extra block copying in InlineWorker

### PR DESCRIPTION
**Pull request by kc611**
Based on #8989 ,

This PR checks if removing the secondary deep-copying for IR in `InlineWorker` fails any known tests in our test suite.

### CODE REVIEW

**Comment by JSKenyon** [comment]
Just checking in here @esc and @kc611 - I see this has been marked as abandoned. Isn't this an easy win for compilation performance? Or has it been superseded by other planned inlining improvements?

**Comment by gmarkall** [comment]
Putting this into the 0.59 milestone - this PR is considered a bit safer for that release as the object mode fallback pipeline will be removed in that release, and this deep copy may have made some operations in that mode safe. (even though CI passes for this at present)

**Comment by gmarkall** [comment]
Noting also that this looks like it will be good to merge once the object mode fallback has been removed.

**Comment by stuartarchibald** [comment]
Outcome of maintainer discussion is here: https://github.com/numba/numba/issues/8989#issuecomment-1715519353 and noted by @gmarkall here https://github.com/numba/numba/pull/8990#issuecomment-1669775041, essentially, the tests continue to pass and the concerns about mutation of IR and object-mode fallback will be mitigated by removal of this behaviour in 0.59 anyway. This PR should be ok as-is.

**Review by gmarkall — APPROVED** [review]
I'm happy to approve this based on the discussions we've had and the removal of object-mode fallback for 0.59.

**Comment by ehsantn** [comment]
The issue raised in https://github.com/numba/numba/issues/5824 is not a concern anymore? Would love to see compilation time improve, but Numba IR is mutable and optimization passes may change nodes. Making the IR immutable would require time to update all the optimization code.

**Comment by gmarkall** [comment]
> The issue raised in #5824 is not a concern anymore?

Can you be more specific here? I'm not sure I follow.

> Would love to see compilation time improve, but Numba IR is mutable and optimization passes may change nodes. Making the IR immutable would require time to update all the optimization code.

Can you provide an example of code that needs updating?

**Comment by ehsantn** [comment]
The concern is also with external code that uses Numba as a compiler toolkit and adds transformation/optimization passes, not just code inside the Numba code base. Unfortunately, this issue is too hard to reproduce with a small reproducer easily and needs full optimization passes to demonstrate.

Even inside Numba codebase, there are a lot of IR mutations (e.g. [here](https://github.com/numba/numba/blob/596e8a55334cc46854e3192766e643767bd7c934/numba/core/ir_utils.py#L406)). Unit tests may not be comprehensive enough to detect issues that require specific interactions of transformations.

**Comment by gmarkall** [comment]
@ehsantn In my understanding, this PR is not making Numba IR immutable. It is removing a redundant deep copy that discards / replaces something already copied by a prior deep copy:

> The problem (perhaps a bug, although I may have missed some subtlety) is that the first `deepcopy` (line 375) is followed by immediately discarding the contents of the body (line 376) and then repopulating it with additional deep copies (lines 377-379). It is this second set of copies that I am struggling to explain - surely those elements would already have been copied in the original `deepcopy` call?

(from @JSKenyon's description in #8989)

> Unfortunately, this issue is too hard to reproduce with a small reproducer easily and needs full optimization passes to demonstrate.

For the purpose of demonstrating that this PR breaks something, I think showing a full optimization pass that breaks under the application of this PR would be an appropriate starting point.

**Comment by gmarkall** [comment]
Following discussion in the public dev meeting: this will be marked RTM for now and merged, on the basis that it can easily be reverted if it proves to be an issue.

@ehsantn Following the merge, please do open an issue with a reproducer (large or small, as a starting point) if this turns out to be problematic.

**Comment by ehsantn** [comment]
Thanks for following up @gmarkall. The fact that this PR is just removing redundant copies makes sense. The comment about waiting for removal of object mode fallback was confusing to me since implied that the copy isn't redundant.

`Block` class doesn't have an explicit `__deepcopy__` method but I just checked CPython source code and manually verified that it does the right thing (attributes are deepcopied properly). I think merging this should be fine. I'll follow up if there were issues.

**Comment by JSKenyon** [comment]
Thank you to everyone who contributed to this - looking forward to testing it out.

**Pull request merged**
