### PR TITLE
Debugging travis CI 32bit linux.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
CC @mingwandroid, RE chat on IRC, this patch fixes the 32bit build as it limits to 7.2 series GCC.

**Comment by mingwandroid** [comment]
On it now, shouldn't take too long to fix this.

**Comment by stuartarchibald** [comment]
Great, thanks :)

**Comment by stuartarchibald** [comment]
Ignoring that Travis-CI thinks it failed (probably because I cancelled 80% of the irrelevant builds), https://travis-ci.org/numba/numba/builds/418752563 demonstrates in the last two builds a 32bit multilib system with a GCC 7.3 tool chain from the `c3i_test` channel working as expected. Relevant section from the logs:
```
gcc_impl_linux-32         7.3.0                he2ea625_1    c3i_test
gcc_linux-32              7.3.0                hd2c3c17_2  
gxx_impl_linux-32         7.3.0                h9268252_1    c3i_test
gxx_linux-32              7.3.0                hd2c3c17_2  
```
Thanks for the fast turnaround with a fix.

**Comment by stuartarchibald** [comment]
Fixed upstream. Closing. Thanks @mingwandroid

**Pull request closed without merging**
