### PR TITLE
Implement str.maketrans() based on CPython

### PR DESCRIPTION
**Pull request by densmirn**
I tried to implement static method `str.maketrans`, but was not able to overload such method. So could you please give me advice what is the correct way to overload static methods?

### CODE REVIEW

**Comment by densmirn** [comment]
The PR is in progress and has a question about overloading static methods. Could you please answer the question if it is possible?

**Comment by densmirn** [comment]
Could you please add label "question" for this PR?

**Comment by stuartarchibald** [comment]
Think it might be possible with the low level API.

**Comment by densmirn** [comment]
@stuartarchibald could you add someone to the PR who can answer the question?

**Comment by stuartarchibald** [comment]
@densmirn this has been discussed by the core developers, there is no immediate or trivial answer, someone will have to do some work to figure out the best way to do this. You are welcome to go and figure it out, I anticipate this will be needed http://numba.pydata.org/numba-doc/dev/extending/low-level.html.

**Comment by stuartarchibald** [comment]
This may help in figuring this out too: https://github.com/numba/numba/blob/master/numba/tests/pdlike_usecase.py

**Comment by stuartarchibald** [comment]
@densmirn just checking back in on this, did you want to proceed with it or is it best to close it for now? Thanks.

**Comment by densmirn** [comment]
It's better to close it now.

**Comment by stuartarchibald** [comment]
Thanks for confirming

**Pull request closed without merging**
