### PR TITLE
Modules can't be parfor races.

### LINKED ISSUE #5098: _lower_parfor_parallel function can mess up sequential_parfor_lowering flag disabling parallelization for the rest of the execution
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Repro:
```
class DummyType(types.Opaque):
    pass

dummy_type = DummyType("my_dummy")
register_model(DummyType)(OpaqueModel)

class Dummy(object):
    pass

@typeof_impl.register(Dummy)
def typeof_Dummy(val, c):
    return dummy_type

@unbox(DummyType)
def unbox_index(typ, obj, c):
    return NativeValue(c.context.get_dummy_value())

@overload_method(DummyType, "method1", jit_options={"parallel":True})
def _get_method1(obj, arr, func):
    def _foo(obj, arr, func):
        def baz(a, f):
            c = a.copy()
            c[numpy.isinf(a)] = numpy.nan
            return f(c)

        length = len(arr)
        output_arr = numpy.empty(length, dtype=numpy.float64)
        for i in prange(length):
            output_arr[i] = baz(arr[i], func)
        for i in prange(length - 1):
            output_arr[i] += baz(arr[i], func)
        return output_arr
    return _foo

@njit
def bar(v):
    return v.mean()

@njit
def test1(d):
    return d.method1(numpy.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]), bar)

print(numba.parfor.sequential_parfor_lowering)
test1(Dummy())
print(numba.parfor.sequential_parfor_lowering)
```
Prints
```
False
...some parfor warnings...
True
```

There are actually multiple issues:
* If `_create_gufunc_for_parfor_body` https://github.com/numba/numba/blob/master/numba/npyufunc/parfor.py#L239 throws an error `sequential_parfor_lowering` flag wont be restored
* The error itself looks like this
```
Traceback (most recent call last):
  File "/home/ibutygin/src/numba/numba/numba/errors.py", line 717, in new_error_context
    yield
  File "/home/ibutygin/src/numba/numba/numba/lowering.py", line 288, in lower_block
    self.lower_inst(inst)
  File "/home/ibutygin/src/numba/numba/numba/lowering.py", line 476, in lower_inst
    func(self, inst)
  File "/home/ibutygin/src/numba/numba/numba/npyufunc/parfor.py", line 241, in _lower_parfor_parallel
    bool(alias_map), index_var_typ, parfor.races)
  File "/home/ibutygin/src/numba/numba/numba/npyufunc/parfor.py", line 833, in _create_gufunc_for_parfor_body
    replace_var_with_array(races, loop_body, typemap, lowerer.fndesc.calltypes)
  File "/home/ibutygin/src/numba/numba/numba/npyufunc/parfor.py", line 1206, in replace_var_with_array
    replace_var_with_array_internal(vars, loop_body, typemap, calltypes)
  File "/home/ibutygin/src/numba/numba/numba/npyufunc/parfor.py", line 1203, in replace_var_with_array_internal
    block.body = replace_var_with_array_in_block(vars, block, typemap, calltypes)
  File "/home/ibutygin/src/numba/numba/numba/npyufunc/parfor.py", line 1189, in replace_var_with_array_in_block
    setitem_node = ir.SetItem(inst.target, const_var, inst.value, inst.loc)
  File "/home/ibutygin/src/numba/numba/numba/ir.py", line 573, in __init__
    assert isinstance(value, Var)
AssertionError
```
* Error get silently ignored if we use `@overload_method` (but it will fail compilation if we make `_foo` a free funtion)

Tested on `release0.47` branch and master (`40fb2d06859a782db9463ac6d7eae8405eb6a81d`)

### PR DESCRIPTION
**Pull request by DrTodd13**
Resolves #5098 

In #5098, there are two parfors.  The first one defines some variable of type module and that variable is used by the second parfor.  Since module vars can't be passed to gufuncs, ParallelAccelerator copies such module vars into parfor loop bodies as needed.  However, in this case, since the variable was defined in the first parfor and to liveness analysis was escaping that parfor, it looked like a race condition variable to parfor analysis.  Since we do this module var copying later in the pipeline, I just made it such that parfors don't identify module var as races.  The reason this caused a problem is that if a variable is a race variable, we create an array for it so that some value can be returned but we can't create arrays of modules and pass them to a gufunc so some of the machinery in the create gufunc code generated an exception which then propagated.

@stuartarchibald Please handle defining what the behavior should be when lowering generates an exception.  We probably don't want it to just stop executing if there is a fallback path that could work but we don't want it happening silently either.  I'm not sure how to test this particular issue in the test suite either so I'll also leave that up to you.  Commits to my PR branch are solicited.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
I've added a patch here https://github.com/stuartarchibald/numba/commit/4b73d7237c5577d5c2055326198852db8ee9357f that makes it so that `LoweringErrors` that appear during typing cause a hard stop. I think this makes it so that if a `LoweringError` occurs in the ` _create_gufunc_for_parfor_body` the stack will just unwind and the code will halt:
https://github.com/numba/numba/blob/cacb5c4adcb55a4c8951a1fa4131660fe554aa86/numba/npyufunc/parfor.py#L235-L239

I am of the view that lowering should succeed and it's an error if it does not. In the case presented I don't know what the best thing for parfors to do is, it seems like catching a `LoweringError` from that function, resetting the flag and then reraising that error might be the sensible thing to do? I'm very reluctant to mess about too much with the exception based control flow in typing as it is an incredibly nuanced area of the code base.

**Comment by Hardcode84** [comment]
@stuartarchibald 
> seems like catching a LoweringError from that function, resetting the flag and then reraising that error might be the sensible thing to do? 

There is already patch for that https://github.com/numba/numba/pull/5114

Regarding your patch - this issue was causing `AssertError` during ir construction initially, not `LoweringError` iirc. And in general, maybe better instead of whitelisting specific exceptions which we allow to propagate (and `AssertError` definitely should be in this list regardless of this issue) to list all exceptions we allow to be consumed and propagate all others?

**Comment by stuartarchibald** [comment]
> @stuartarchibald
> 
> > seems like catching a LoweringError from that function, resetting the flag and then reraising that error might be the sensible thing to do?
> 
> There is already patch for that #5114

Ah yes, thanks, forgot about that.

> Regarding your patch - this issue was causing `AssertError` during ir construction initially, not `LoweringError` iirc. And in general, maybe better instead of whitelisting specific exceptions which we allow to propagate (and `AssertError` definitely should be in this list regardless of this issue) to list all exceptions we allow to be consumed and propagate all others?

There's a lot of exception class rewriting and chaining going on, typically exceptions are rewritten to TypingError if they occurred during typing or LoweringError if they occurred during lowering. I think that this makes it relatively safe to say "if your code raises a LoweringError during typing, then propagate".

**Comment by Hardcode84** [comment]
> if your code raises a LoweringError during typing, then propagate

In this case opposite should be also true, e.g. consume only `TypingError` during typing and only `LoweringError` during lowering

**Comment by stuartarchibald** [comment]
As discussed out of band, I think that this can be merged once the conflicts are resolved?

**Comment by sklam** [comment]
Merged via #5247

**Pull request closed without merging**
