### PR TITLE
Fix #9222 - Don't replace `.` with `_` in func arg names in inline closures

### LINKED ISSUE #9222: Invalid closure handling in _create_function_from_code_obj
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Closure handling was updated as part of Python 3.11 upgrade to include [this line](https://github.com/numba/numba/blob/9f74128def1ca51deebfadecc663f0b80f641c57/numba/core/ir_utils.py#L1743) (`func_arg = func_arg.replace('.', '_')`), which replaces dots in function argument signature (to fix generated argument names I assume). However, this is invalid for default values that are float constants as demonstrated below (removed `InlineClosureLikes` to go through `MakeFunctionToJitFunction` code path which passes default values).

The commit that made this change ([here](https://github.com/numba/numba/commit/77c2672e22be8cb33e47f44884385fd75906881c)), mentions fixing `numba.tests.test_looplifting.TestLoopLiftingInAction.test_lift_listcomp_block0` but the test works with or without this change. Seems like the motivating problem may have been solved in the upstream calls and we can just remove the `func_arg = func_arg.replace('.', '_')` line. Is this correct?

```python
import numba
from numba.core.compiler import DefaultPassBuilder
from numba.core.untyped_passes import InlineClosureLikes

class TestPipeline(numba.core.compiler.CompilerBase):
    def define_pipelines(self):
        pm = DefaultPassBuilder.define_nopython_pipeline(self.state, "TestPipeline")
        for idx, (x, _) in enumerate(pm.passes):
            if x == InlineClosureLikes:
                break
        else:
            raise Exception("Could not find pass %s" % location)
        pm.passes.pop(idx)
        pm.finalize()
        return [pm]

@numba.njit(pipeline_class=TestPipeline)
def f(a):
    def g(x, y=1.1):
        return x+y
    return g(a)

# prints 15 instead of 5.1
print(f(4))
```

### PR DESCRIPTION
**Pull request by gmarkall**
This is suggested as a fix for Issue #9222 in its description, as it seems it may no longer be necessary.

Testing on CI for now.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
Tests ran OK for me locally on Python 3.11:

```
----------------------------------------------------------------------
Ran 11860 tests in 2518.960s

OK (skipped=576, expected failures=29)
```

**Comment by gmarkall** [comment]
gpuci run tests

**Review by esc — APPROVED** [review]
LGTM pending smoketest

**Comment by esc** [comment]
> LGTM pending smoketest

was green

**Pull request merged**
