### PR TITLE
naive tuple support and indexing arrays from arrays in nopython mode

### PR DESCRIPTION
**Pull request by rainwoodman**
Issue #985 
The idea is to add a `tuple` builtin function, that accepts Array input
and returns TupleArray . `getitem` then handles indexing via a TupleArray  .

After this patch, the following code shall work.
```
import numba
import numpy

@numba.jit(nopython=True)
def tuplefromarray(a, b):
    return a[tuple(b)]

@numba.jit(nopython=True)
def tuplefromtuple(a, b):
    return tuple((1, 2, 3))

a = numpy.arange(100).reshape(-1, 2)
b = numpy.ones( 2, dtype='i4')
print tuplefromtuple(a, b)
print tuplefromarray(a, b)
```

### CODE REVIEW

**Comment by pitrou** [comment]
Thank you for attempting this. I find the approach a bit too specialized; I think it would be nice to have generic support for arbitrary-sized tuples.

Also, some points:
- I do think checking the tuple size (at runtime presumably) is important; it's probably too easy to get a crash otherwise
- You need to add some tests for the new feature.

**Comment by rainwoodman** [comment]
Yes. Feature-wise, it only allows indexing array elements from integer arrays; it is essentially a fixed size tuple, for ndim of the indexed array is given.

What are the possible cases of an 'arbitrary' sized tuple in nopython mode?

We currently have Tuple and UniTuple, and ArrayTuple after this patch.  -- ArrayTuple is somewhat an arbitrary sized tuple (it is more or less just an alias of Array). 
tuple from an arbitrary iterable seems to be our of reach in nopython mode, but from a SimpleIterator seems to be feasible -- with another alias.

Here is a technical question that I need some input from you about checking the tuple size:  What is the preferred way to emit a runtime error? Is there an example in current numba code?

**Comment by pitrou** [comment]
It's true that generic tuples wouldn't be very useful right now. My main concern is that ArrayTuple is really "an array cast to a virtual tuple", which is very specialized. Perhaps we can live with that.

> What is the preferred way to emit a runtime error?

Right now, it's rather sketchy. This will be improved after PR #1000 gets merged, so you may want to rebase your work on that branch. See e.g. https://github.com/numba/numba/pull/1000/files#diff-ab60778f44b0fdba9b78415c79a02aeeL1184

**Comment by pitrou** [comment]
Note the afore-mentioned PR was merged.

**Comment by rainwoodman** [comment]
rebased. I'll look into the exception later.

**Comment by rainwoodman** [comment]
Seems to be able to raise an exception if the indexing array is shorter than ndim. Currently it would proceed if the indexing array is longer than ndim.

I will add the test cases later.

**Comment by rainwoodman** [comment]
Test cases are added. Could you please review this PR again? Thanks.

**Comment by seibert** [comment]
I think this PR has been superseded by all of the recently released support we have now for advanced indexing.  Closing...

**Pull request closed without merging**
