### PR TITLE
Fix #5537 Removed reference to `platform.linux_distribution`

### LINKED ISSUE #5537: `platform.linux_distribution` is deprecated
I was looking into the output of `numba -s` and found that the code is using `platform.linux_distribution` which is now [deprecated](https://bugs.python.org/issue1322).

The issue is located in [`numba_entry.py` line 98](https://github.com/numba/numba/blob/2b613798cf548e247e81b54b2cf0930d9865040b/numba/misc/numba_entry.py#L98)

A suggested alternative is to use the [distro package](https://pypi.org/project/distro/) or use some form of custom heuristic. 

Another way around it would be to simply ignore this information!

### PR DESCRIPTION
**Pull request by jagaudin**
Removed reference to `platform.linux_distribution` in `numba/misc/numba_entry.py`.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Looks good, thanks for the fix.

**Comment by stuartarchibald** [comment]
@jagaudin are you happy to move this out of draft status? Would be great to get it merged. Thanks.

**Comment by jagaudin** [comment]
@stuartarchibald I think I've changed the status now. Let me know if there's anything else needed.

**Comment by stuartarchibald** [comment]
@jagaudin congratulations on your first contribution to Numba!

**Pull request merged**
