### PR TITLE
Cherry pick/rc bugfixes for 0.60.0 final

### PR DESCRIPTION
**Pull request by esc**
Cherry-pick:

* #9603 
* #9602 
* #9586 

PR: #9596 was already merged to `release0.60` as b3dc3dffac3b815a5841f7f794b5644c919e86c6

### CODE REVIEW

**Review by kc611 — APPROVED** [review]
Changes look okay :+1: Manually checked changes across the cherry picked PRs just to be sure. Date changes also look good.

**Comment by esc** [comment]
@kc611 thank you, can you re-review, I've added the changelog entried for the four release candidate fixes.

**Review by kc611 — APPROVED** [review]
LGTM!

**Comment by esc** [comment]
close/open to restart CI

**Pull request merged**
