### PR TITLE
more general contextual info of runtime errors

### PR DESCRIPTION
**Pull request by complyue**
To locate a ZeroDivisionError within my lengthy code, I updated loc info planting logic to be in `return_user_exc()`, improving my last PR.

### CODE REVIEW

**Comment by complyue** [comment]
oops! it breaks equality test against exception msg...
Shall the tests be updated to use `startswith()` ? 
Please help.

**Comment by stuartarchibald** [comment]
@complyue apologies, this got overlooked. The idea is good, I've pushed up some changes that use the error rewrite mechanics to generate location information and fixed the tests. Thanks for the idea and contribution :)

**Comment by complyue** [comment]
glad to know :)

**Comment by stuartarchibald** [comment]
I unfortunately hit a bunch of problems with this approach in that the arguments to the exception classes end up being converted to strings, so have tried a new approach which synthesizes the last (currently missing) stack frame such that the `file/line/function` triple can reported. It works by storing this info in the machine code and then rehydrating this at the point of failure and injecting a frame into the exception traceback based on this info. PR is WIP here: https://github.com/numba/numba/pull/3325, if fixed up and merged I suggest we can close this.

**Comment by complyue** [comment]
Of course, I did not see my way quite idiomatic, while I don't have enough knowledge to go deeper. I'll be happy as long as compiled functions give accurate error stacktrace, keep up & thanks for your effort!

**Pull request closed without merging**
