### PR TITLE
Improve Numba import time by making some imports lazy

### PR DESCRIPTION
**Pull request by pitrou**
This reduces the import time (including Numpy, llvmlite) by 30%.

I initially tried to build a generic lazy importing system, but there are too many interferences with our registration system (and potentially other issues). Instead, the approch in this PR is to make some imports on demand by hand. It requires a little more care but doesn't suffer from side effects or unexpected oddities.

### CODE REVIEW

**Comment by seibert** [comment]
Looks like this conflicts with master now...

**Comment by pitrou** [comment]
Ok, I've fixed the conflicts.

**Comment by seibert** [comment]
This is failing on Python 2.6 for a couple reasons, one of which is that there is no `unittest.suite` package.

**Comment by pitrou** [comment]
I didn't manage to reproduce the 2.6 failure, but I committed a fix which seems to solve the issue.

**Comment by seibert** [comment]
More merge conflicts...

**Comment by pitrou** [comment]
Ok, merge done.

**Comment by seibert** [comment]
Apparently I'm just merging all the PRs in the wrong order today.  Github says there are conflicts again...

**Comment by pitrou** [comment]
Merge done again :)

**Comment by seibert** [comment]
OK, going to merge this PR first before I can break it.  :)

**Pull request merged**
