### PR TITLE
NumPy 1.10 support

### PR DESCRIPTION
**Pull request by pitrou**
Numpy 1.10b1 produces some failures in the test suite. The main changes are the following:
- Numpy is now more agressive when computing an array's contiguousness; for example an empty array is now always C- and F-contiguous regardless of shape
- Numpy's complex trigonometry functions have changed and can produce slightly different values
- casting of inputs and outputs when calling ufuncs has become stricter; some of our tests exercise cases which now raise a TypeError

### CODE REVIEW

**Comment by pitrou** [comment]
Note Travis-CI isn't indicative of this PR's readiness, since it tests with Numpy 1.9 :)

**Comment by seibert** [comment]
I assume we want to hold merging this patch until Numpy 1.10 is officially released, just to be sure?

**Comment by pitrou** [comment]
Yeah, we should wait for that. Although reviewing can certainly start earlier.

**Comment by pitrou** [comment]
I've checked this PR to work with 1.10rc2 now.

**Comment by seibert** [comment]
OK, going to try this on Jenkins now.

**Pull request merged**
