### PR TITLE
Remove `mk_unique_var` from `array_analysis.py`

### PR DESCRIPTION
**Pull request by guilhermeleobas**
xref: https://github.com/numba/numba/issues/8230

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for doing this refactoring!

**Comment by stuartarchibald** [comment]
This was reverted in #8289, due to #8288.

**Comment by guilhermeleobas** [comment]
Thanks Stuart, I'll take a look at it.

**Comment by stuartarchibald** [comment]
> Thanks Stuart, I'll take a look at it.

@guilhermeleobas many thanks! I'm pretty sure it's an issue with the scopes not being quite correct for the expected use.

**Pull request merged**
