### PR TITLE
Fix rstcheck in Azure CI builds, update sphinx dep and docs to match

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Doc build passed `rstcheck` using e5651ba, issue confirmed as `jinja2` update from 3.0 to 3.3.

**Comment by stuartarchibald** [comment]
a5b9592 failed with:
```
Warning, treated as error:
/home/vsts/work/1/s/docs/source/extending/low-level.rst:62:duplicate object description of as_numba_type.register, other instance in extending/low-level, use :noindex: for one of them
make: *** [Makefile:53: html] Error 2
```

**Comment by stuartarchibald** [comment]
de5fd15 failed with:
```
Warning, treated as error:
/home/vsts/work/1/s/docs/source/reference/pysupported.rst:1241:Unparseable C cross-reference: 'char'
Invalid C declaration: Expected identifier in nested name, got keyword: char [error at 4]
  char
  ----^
make: *** [Makefile:53: html] Error 2
```

**Review by sklam — APPROVED** [review]
Thanks for the patch!

**Pull request merged**
