### PR TITLE
Alter the `test_print.py` test to match previous.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This alters the "style" of the test to match something similar to what existed prior to the merge of #9330 (removal of `compile_isolated`) with view of "fixing" an NRT reference leak.

### CODE REVIEW

**Comment by sklam** [comment]
This just need testing on the farm

**Comment by sklam** [comment]
This test actually failed on the one that it should be fixing: https://dev.azure.com/numba/numba/_build/results?buildId=16486&view=logs&j=f6408ea9-ccc2-513a-5c09-13df1a476ff5&t=19427a42-3c67-579d-6c12-e1fdf54a08df&l=10786

**Comment by sklam** [comment]
I reran AzureCI to see if it's randomly failing and sadly it is.

**Comment by stuartarchibald** [comment]
> I reran AzureCI to see if it's randomly failing and sadly it is.

I wonder if there's now a few variations of some matching implementation present due to the shared context and a) there shouldn't be and b) because there is it's a dictionary order/hash seed problem.

**Comment by stuartarchibald** [comment]
This did not have the intended effect. Closing.

**Pull request closed without merging**
