### PR TITLE
Making typed.Dict a typing Generic (MutableMapping)

### PR DESCRIPTION
**Pull request by luk-f-a**
This PR adds typing information to the typed Dict, so in can be used as a MutableMapping in variable annotations, e.g.

```python
my_dict: Dict[str, int] = Dict()
my_dict['a'] = 1
my_dict[2] = 1 # would get a mypy error
f: str = my_dict['a'] # would get a mypy error
```

This is not related to checking Numba itself with mypy, this just allows users to check their typed.Dict code with mypy.

### CODE REVIEW

**Comment by luk-f-a** [comment]
Note to the reviewer: even though this is a typing PR, I have made a small change in the behaviour of the typed dictionary, based on the typing analysis.
The `setdefault` method had a default value for its `default` parameter equal to `None`, ie `def setdefault(self, key, default=None)`. Initially, I was going to type this as `default: Optional[VT] = None`. However, this does not make much sense for typed.Dict as it is not possible to set `None` as the value of a key, since `None` is of a different numba-type than `VT`. Passing `None` makes no sense, and neither does passing nothing (which will have the same effect). Having removed the default value, I found a failing test. This test (https://github.com/numba/numba/blob/3fd158f79a12ac5276bc5a72c2404464487c91f0/numba/tests/test_dictobject.py#L1568-L1572)
checks that calling `setdefault` without a second argument returns an error, but with a specific error message. This had to be adjusted as well. I believe that the normal error message returned by Python when not passing a mandatory argument is better than the current error message. Below I paste both errors for comparison:

New error message (Python's error message for missing arguments)
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: setdefault() missing 1 required positional argument: 'default'
```

Old error message
```python
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/home/.../numba/numba/typed/typeddict.py", line 205, in setdefault
    return _setdefault(self, key, default)
  File "/home/.../numba/numba/core/dispatcher.py", line 421, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/.../numba/numba/core/dispatcher.py", line 362, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function impl_setdefault at 0x7f89e85cfee0>) found for signature:
 >>> impl_setdefault(DictType[unicode_type,int64]<iv=None>, unicode_type, none)
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'impl_setdefault': File: numba/typed/dictobject.py: Line 846.
    With argument(s): '(DictType[unicode_type,int64]<iv=None>, unicode_type, none)':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<built-in function setitem>) found for signature:
    >>> setitem(DictType[unicode_type,int64]<iv=None>, unicode_type, none)
   There are 16 candidate implementations:
         - Of which 14 did not match due to:
         Overload of function 'setitem': File: <numerous>: Line N/A.
           With argument(s): '(DictType[unicode_type,int64]<iv=None>, unicode_type, none)':
          No match.
         - Of which 2 did not match due to:
         Overload in function 'impl_setitem': File: numba/typed/dictobject.py: Line 674.
           With argument(s): '(DictType[unicode_type,int64]<iv=None>, unicode_type, none)':
          Rejected as the implementation raised a specific error:
            TypingError: Failed in nopython mode pipeline (step: nopython frontend)
          No implementation of function Function(<intrinsic _cast>) found for signature:
           >>> <unknown function>(none, class(int64))
          There are 2 candidate implementations:
                - Of which 2 did not match due to:
                Intrinsic in function '_cast': File: numba/typed/typedobjectutils.py: Line 23.
                  With argument(s): '(none, class(int64))':
                 Rejected as the implementation raised a specific error:
                   TypingError: cannot safely cast none to int64. Please cast explicitly.
            raised from /home/.../numba/numba/typed/typedobjectutils.py:76
          During: resolving callee type: Function(<intrinsic _cast>)
          During: typing of call at /home/.../numba/numba/typed/dictobject.py (683)
          File "numba/typed/dictobject.py", line 683:
              def impl(d, key, value):
                  <source elided>
                  castedkey = _cast(key, keyty)
                  castedval = _cast(value, valty)
                  ^
     raised from /home/.../numba/numba/core/typeinfer.py:1071
   During: typing of setitem at /home/.../numba/numba/typed/dictobject.py (853)
   File "numba/typed/dictobject.py", line 853:
       def impl(dct, key, default=None):
           <source elided>
           if key not in dct:
               dct[key] = default
               ^
  raised from /home/.../numba/numba/core/typeinfer.py:1071
- Resolution failure for non-literal arguments:
None
During: resolving callee type: BoundFunction((<class 'numba.core.types.containers.DictType'>, 'setdefault') for DictType[unicode_type,int64]<iv=None>)
During: typing of call at /home/.../numba/numba/typed/typeddict.py (58)
File "numba/typed/typeddict.py", line 58:
def _setdefault(d, key, default):
    return d.setdefault(key, default)
    ^

```

**Comment by esc** [comment]
@luk-f-a thank you for updating this. What is the current state of this PR, do you think it can become part of 0.54?

**Comment by luk-f-a** [comment]
it's ready for review. I started it last year, and I improved it back in February after the PR about `typed.List` was merged (https://github.com/numba/numba/pull/5958). I took what I learnt there and put it here. 
I think it can be part of 0.54.

**Comment by esc** [comment]
@luk-f-a thank you for this. I have added it to the milestone for 0.54 -- now we need to find a (willing and able) reviewer!

**Comment by stuartarchibald** [comment]
Am just dealing with items in the 0.54 milestone, @luk-f-a any chance you could resolve the conflicts please? Thanks!

**Pull request closed without merging**
