### PR TITLE
Add support for numpy.moveaxis/normalize_axis_index and normalize_axis_list in nopython mode

### PR DESCRIPTION
**Pull request by guoqiangqi**
This patch provides the implementations of numpy.moveaxis/normalize_axis_index and normalize_axis_list in nopython mode.  
 And we should notice that this PR is a duplicate of previous one #5177 , i re-implement this part of code since i need this in my subsequent patch but the previous PR hasn`t been updated for a long time and it seems the author has no plans to update it.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@guoqiangqi thanks for opening this PR. As this is based on code in #5177, would it be possible to use the commits from that PR and then apply changes on top of those so as to preserve authorship? Many thanks.

**Comment by guoqiangqi** [comment]
> @guoqiangqi thanks for opening this PR. As this is based on code in #5177, would it be possible to use the commits from that PR and then apply changes on top of those so as to preserve authorship? Many thanks.

Okay, i would let you know when works done  :）.

**Comment by guoqiangqi** [comment]
@stuartarchibald This patch is ready for review now.

**Comment by RussianImperialScott** [comment]
Any updates on the status of this PR?

**Comment by gmarkall** [comment]
@RussianImperialScott Following discussion in today's triage meeting, this has now been moved into the 0.58 milestone and I'm assigned as the reviewer.

@guoqiangqi Looking over the history, @stuartarchibald's request was to preserve the authorship of the commits from the original PR, which has not been addressed by the changes - the commits all seem to show you as author of all code in this PR. Are you interested in / able to continue with this PR? If so, would you be willing to rewrite the history of this PR to incorporate the original commits from #5177 please? If this is something that you need some guidance in doing, please let me know and I can assist.

**Comment by guoqiangqi** [comment]
> @RussianImperialScott Following discussion in today's triage meeting, this has now been moved into the 0.58 milestone and I'm assigned as the reviewer.
> 
> @guoqiangqi Looking over the history, @stuartarchibald's request was to preserve the authorship of the commits from the original PR, which has not been addressed by the changes - the commits all seem to show you as author of all code in this PR. Are you interested in / able to continue with this PR? If so, would you be willing to rewrite the history of this PR to incorporate the original commits from #5177 please? If this is something that you need some guidance in doing, please let me know and I can assist.

Hi @gmarkall, thanks for your notice and sorry for the late reply, I'm afraid I don't have time to participate in the code modification because of some urgent matters, so I suggest closing this PR so that other developers can continue to contribute. Apologize again.

**Comment by gmarkall** [comment]
@guoqiangqi Many thanks for the quick response, and thankyou for your work so far - would you mind if we left this PR open for a short while until I can find someone to take over this work? (I'm worried if we close it right away the task might get lost entirely)

**Comment by RussianImperialScott** [comment]
If it matters, even though I bumped this a few days ago, I likely won't need this anytime soon. Still figuring out if `numba` helps my application at all.

**Comment by guoqiangqi** [comment]
> @guoqiangqi Many thanks for the quick response, and thankyou for your work so far - would you mind if we left this PR open for a short while until I can find someone to take over this work? (I'm worried if we close it right away the task might get lost entirely)

@gmarkall  It`s ok to me , anyone interested in this work can feel free to take over.

**Comment by gmarkall** [comment]
> If it matters, even though I bumped this a few days ago, I likely won't need this anytime soon. 

Thanks for advising, this is helpful for prioritising - it's presently in the 0.58 milestone so it won't be looked at immediately (getting everything done for 0.57 is more urgent) but I would like to see this through to completion sometime during the 0.58 cycle.

> Still figuring out if `numba` helps my application at all.

Thanks for clarifying - if you need any guidance or advice, please do post questions / example code / thoughts in a post on the [Numba Discourse](https://numba.discourse.group), or quick questions on [Gitter](https://gitter.im/numba/numba).

**Pull request closed without merging**
