### PR TITLE
fix numpy version

### PR DESCRIPTION
**Pull request by Tialo**
For some reason numpy version for numba installation is not fixated for >=1.22. Thus, you can install Numba==0.58 and numpy<1.22. Which after `import numba` results in exception https://github.com/numba/numba/blob/main/numba/__init__.py#L37

installation
```shell
pip install numba "numpy<1.22"
```

exception
```python
import numba
```

### CODE REVIEW

**Comment by esc** [comment]
@Tialo thank you for reporting this. It seems like there are some inconsistencies here. The version support table for 0.58 actually lists `1.21` as being the minimum supported version:

https://numba.readthedocs.io/en/0.58.0/user/installing.html#version-support-information

Screenshot 2023-09-25 at 11 56 06


I will investigate this some, thank you for the report.

**Comment by esc** [comment]
Checking the conda recipe, it looks good:

https://github.com/numba/numba/blob/main/buildscripts/condarecipe.local/meta.yaml#L44

https://github.com/numba/numba/blob/release0.58/buildscripts/condarecipe.local/meta.yaml#L43

**Comment by A-CGray** [comment]
> @Tialo thank you for reporting this. It seems like there are some inconsistencies here. The version support table for 0.58 actually lists `1.21` as being the minimum supported version:
> 
> https://numba.readthedocs.io/en/0.58.0/user/installing.html#version-support-information
> Screenshot 2023-09-25 at 11 56 06
> 
> I will investigate this some, thank you for the report.

Presumably this PR should also update this table then?

**Comment by Tialo** [comment]
I can do this, if necessary.

**Comment by esc** [comment]
> I can do this, if necessary.

Yes, that would be good, thank you!

**Comment by Tialo** [comment]
As you can see in my commit there was no release date in this table on master branch I added it.

**Comment by esc** [comment]
> As you can see in my commit there was no release date in this table on master branch I added it.

@Tialo yes, I think this PR will need a rebase once https://github.com/numba/numba/pull/9205/files is in `main`.

**Comment by Tialo** [comment]
Okay, will do it

**Comment by esc** [comment]
@Tialo excellent, thank you! I am hoping that #9205 will be merged soon, our CI system is currently being used for something else, so merges are on hold for the time being. I expect this to resolve within the next week or maybe two. As soon as that happens you can rebase this PR and the change of the release date should no longer be necessary on this PR.

**Comment by esc** [comment]
@Tialo ok, the merge happened last night, can you now please rebase this, thank you!

**Comment by Tialo** [comment]
Here you go @esc

**Comment by esc** [comment]
> Here you go @esc

awesome, thank you!

**Comment by esc** [comment]
This was cherry-picked into #9227 🍒 --so closing this one now.

**Comment by Tialo** [comment]
Am I right, this PR will take effect in numba 0.58.1? @esc

**Comment by esc** [comment]
> Am I right, this PR will take effect in numba 0.58.1? @esc

Yes, I am planning to get that released, the checklist should appear soon. The closed issues in the milestone are the PRs that will need a backport to `release058` branch. We usually create a PR targeting the release branch and cherry-pick the needed PRs one at a time from their merge-commit to `main`.

https://github.com/numba/numba/milestone/76?closed=1

**Pull request closed without merging**
