### PR TITLE
Only test managed allocations on Linux

### PR DESCRIPTION
**Pull request by gmarkall**
Seeing if avoiding the use of managed allocations on Windows avoids the build farm issues.

@stuartarchibald can we try this on the buildfarm please?

### CODE REVIEW

**Comment by stuartarchibald** [comment]
> @stuartarchibald can we try this on the buildfarm please?

Buildfarm ID: `numba_smoketest_cuda_124`

**Comment by stuartarchibald** [comment]
> > @stuartarchibald can we try this on the buildfarm please?
> 
> Buildfarm ID: `numba_smoketest_cuda_124`

This passed. I suggest a rerun or two to see if the issue is intermittent?

**Comment by stuartarchibald** [comment]
2nd run... Buildfarm ID: `numba_smoketest_cuda_125`

**Comment by stuartarchibald** [comment]
3rd run... Buildfarm ID: `numba_smoketest_cuda_126`

**Comment by stuartarchibald** [comment]
> 2nd run... Buildfarm ID: `numba_smoketest_cuda_125`

passed

**Comment by stuartarchibald** [comment]
> 3rd run... Buildfarm ID: `numba_smoketest_cuda_126`

passed

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
Would still be nice to work out what's going on with this test and windows !?!

**Comment by gmarkall** [comment]
Following triage meeting discussion, this PR will include a note in the docs that support is experimental on Windows.

**Comment by gmarkall** [comment]
@stuartarchibald As discussed in the triage meeting, I've added a note to this PR stating that managed memory is experimental on Windows.

**Review by stuartarchibald — APPROVED** [review]
Docstring addition is approved (89cf196). Thanks @gmarkall .

**Pull request merged**
