### PR TITLE
#3203 additional info in cuda detect

### PR DESCRIPTION
**Pull request by rawwar**
PR related to Issue #3203.

`numba.cuda.detect()` now prints `Watchdog Enabled` Status, `Compute Mode` and `Single precision to Double-precision performance ratio`

### CODE REVIEW

**Comment by gmarkall** [comment]
On my Windows machine:

```
(numba) C:\Users\Graham Markall> python -c "from numba import cuda; cuda.detect()"
c:\work\numbadev\numba\numba\__init__.py:106: UserWarning: llvmlite version format not recognized!
  warnings.warn("llvmlite version format not recognized!")
Found 2 CUDA devices
id 0      b'Quadro RTX 8000'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 21
                        Watchdog Enabled: 0
                            Compute Mode: TCC
             FP32/FP64 Performance Ratio: 32
id 1      b'Quadro RTX 8000'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 45
                        Watchdog Enabled: 1
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
        2/2 devices are supported
```

The watchdog status and driver mode aligns with `nvidia-smi` output:

```
(numba) C:\Users\Graham Markall> nvidia-smi
Tue Mar  9 15:25:56 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.40       Driver Version: 461.40       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     TCC  | 00000000:15:00.0 Off |                  Off |
| 33%   33C    P8    31W / 260W |      1MiB / 48767MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 8000    WDDM  | 00000000:2D:00.0  On |                  Off |
| 33%   44C    P8    35W / 260W |    918MiB / 49152MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by gmarkall** [comment]
On my Linux machine:

```
$ python -c "from numba import cuda; cuda.detect()"
Found 2 CUDA devices
id 0    b'NVIDIA Quadro RTX 8000'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 21
                        Watchdog Enabled: 1
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
id 1    b'NVIDIA Quadro RTX 8000'                              [SUPPORTED]
                      compute capability: 7.5
                           pci device id: 0
                              pci bus id: 45
                        Watchdog Enabled: 0
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
	2/2 devices are supported
```

The "Watchdog Enabled" status matches the "Interactive" setting in xorg.conf (as expected). However, showing a "Compute Mode" doesn't make sense here.

**Comment by rawwar** [comment]
> The "Watchdog Enabled" status matches the "Interactive" setting in xorg.conf (as expected). However, showing a "Compute Mode" doesn't make sense here.

Should I show this information only on NT platform?

**Comment by gmarkall** [comment]
> > The "Watchdog Enabled" status matches the "Interactive" setting in xorg.conf (as expected). However, showing a "Compute Mode" doesn't make sense here.
> 
> Should I show this information only on NT platform?

Yes, WDDM / TCC should be Windows-only.

> 
> EDIT: Please correct me if I am wrong. Once can understand that the compute mode is WDDM if Watchdog is Enabled right? Do you think this information is redundant?

I'm not sure whether you can have a watchdog in TCC mode - maybe you can. You can have a watchdog in Linux even though there is no WDDM / TCC. I would leave both the Compute Mode and Watchdog Enabled fields in.

> EDIT2: Wondering if the output is consistent with nvidia-smi's output on linux machine?

It was, yes. Apologies for the omission.

> EDIT3: I was going through [this link](https://docs.nvidia.com/nsight-visual-studio-edition/reference/index.html#tcc-about) and understand that TCC is a driver for windows. So, I am assuming that you meant, printing Compute Mode on linux machines is not relevant. Am i correct?

That is correct.

A couple of other small suggestions:

* As part of this PR, could you fix the capitalisation of the other fields to match your additions (e.g. "compute capability" -> "Compute Capability", etc.)
* Displaying "Watchdog: Enabled" or "Watchdog: Disabled" would be a bit nicer than "Watchdog Enabled: 0" (or "1").

**Comment by rawwar** [comment]
I updated the code with capitalisation, watchdog output and the following is the output now
```
In [3]: cuda.detect()
Found 1 CUDA devices
id 0    b'GeForce GTX 1660 Ti'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
        1/1 devices are supported
```

**Comment by rawwar** [comment]
My bad. Did not realize commit to my repo's branch would automatically trigger build

**Comment by gmarkall** [comment]
Thanks for the updates! Will re-review / re-test this tomorrow.

**Comment by gmarkall** [comment]
From my Linux machine:

```
$ python -c "from numba import cuda; cuda.detect()"
Found 2 CUDA devices
id 0    b'NVIDIA Quadro RTX 8000'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 21
                                Watchdog: Enabled
             FP32/FP64 Performance Ratio: 32
id 1    b'NVIDIA Quadro RTX 8000'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 45
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
Summary:
	2/2 devices are supported
```

Looks good, and agrees with `nvidia-smi`. Will check on Windows shortly.

**Comment by gmarkall** [comment]
On Windows:

```
id 0      b'Quadro RTX 8000'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 21
                                Watchdog: Disabled
                            Compute Mode: TCC
             FP32/FP64 Performance Ratio: 32
id 1      b'Quadro RTX 8000'                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 0
                              PCI Bus ID: 45
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
```

Also looking good and agreeing with `nvidia-smi`.

**Comment by esc** [comment]
BFID: `numba_smoketest_cuda_yaml_23`

**Comment by esc** [comment]
BF passed

**Comment by rawwar** [comment]
Accidentally pressed close.

**Review by sklam — APPROVED** [review]
re-approving to allow merge

**Comment by rawwar** [comment]
Fixes #3203

**Comment by stuartarchibald** [comment]
> closes #3203

Thanks, will close.

**Pull request merged**
