### PR TITLE
title() method implementation for unicode strings

### PR DESCRIPTION
**Pull request by rdesai16**
Enable support for title() method for unicode strings

### CODE REVIEW

**Comment by rdesai16** [comment]
@stuartarchibald @esc This PR is ready for review.

**Comment by esc** [comment]
@rdesai16 thanks, I will schedule it for a review.

**Comment by stuartarchibald** [comment]
@rdesai16 thanks for the PR, please resolve merge conflicts ahead of review.

**Comment by densmirn** [comment]
https://github.com/numba/numba/pull/4611 is continuation of this PR.

**Comment by stuartarchibald** [comment]
Closing in favour of https://github.com/numba/numba/pull/4611

**Pull request closed without merging**
