### PR TITLE
Update for 0.59.0 final

### PR DESCRIPTION
**Pull request by sklam**
All included patches only affect documentation and the testsuite; thus do not require a new RC.

### CODE REVIEW

**Comment by sklam** [comment]
BFID: `numba_yaml_425`

**Comment by sklam** [comment]
BFID: `numba_yaml_426`

**Comment by stuartarchibald** [comment]
> BFID: `numba_yaml_426`

This passed.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the updates to the 0.59.0 release. I've checked the cherry-pick sequence by replaying the same cherry-picks locally onto a copy of the `release0.59` branch and then making sure that the diff of that branch against this PR is empty. A manual check of the diff in the PR also suggests it is as expected.

**Pull request merged**
