### PR TITLE
patch to compile _devicearray.cpp with c++11

### PR DESCRIPTION
**Pull request by esc**
On OSX this resolves:

```
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - 1 warning and 3 errors generated.
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:100:19: error: use of undeclared identifier 'nullptr'
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject *m = nullptr;
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -                   ^
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:101:19: error: use of undeclared identifier 'nullptr'
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject *d = nullptr;
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -                   ^
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:102:23: error: use of undeclared identifier 'nullptr'
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject *c_api = nullptr;
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -                       ^
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:20:5: warning: private field 'ob_base' is not used [-Wunused-private-field]
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject_HEAD
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     ^
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO - /Users/ci/miniconda3/envs/testenv_96344ff4-013b-4e58-856d-c4b7bb365115/include/python3.6m/object.h:83:50: note: expanded from macro 'PyObject_HEAD'
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO - #define PyObject_HEAD                   PyObject ob_base;
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO -                                                  ^
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO - 1 warning and 3 errors generated.
```

### CODE REVIEW

**Comment by esc** [comment]
Note that, this issue was encountered during wheel building for OSX (potentially also for linux).

**Comment by esc** [comment]
We should probably discuss if this is enough, or if we should include the `-std=c++11` switch  elsewhere too?

**Comment by esc** [comment]
testing as `numba_wheel_33`

**Review by gmarkall — CHANGES_REQUESTED** [review]
There's already a bit of logic that adds C++11 flags for each platform: https://github.com/numba/numba/blob/master/setup.py#L243-L260 - perhaps that could be reused so that `_devicearray.cpp` is compiled with `extra_compile_flags=cpp11flags`?

Whilst making this change, it seems like a good opportunity to compile extensions that use `_dispatcher.cpp` and `typeconv.cpp` (`ext_dispatcher` and `ext_typeconv`) so as to not preclude the use of C++11 in them.

**Comment by esc** [comment]
@gmarkall probably a good idea, this was the minimal patch needed to get the wheels compile.

**Review by sklam — APPROVED** [review]

**Comment by esc** [comment]
🎉

**Pull request merged**
