### PR TITLE
add uintp as a valid type to the tuple operator.getitem

### LINKED ISSUE #3733: tuple getitem with unsigned index breaks parfors lowering
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

MWE:
```python
import numba as nb

def test1b():
    x = (1, 2, 3, 4, 5,)
    for i in nb.prange(len(x)):
        print(x[nb.types.uintp(i)])

nb.njit(test1b)() # broken
```
gives:
```
No definition for lowering <built-in function getitem>(tuple(int64 x 5), uint64) -> int64 
```
parfors generates unsigned `prange` indexes where possible, hence problem. Fix should be to just add `uintp` as a valid type to the tuple `operator.getitem,` lowering function.

### PR DESCRIPTION
**Pull request by luk-f-a**
In the lowering function for  operator.getitem on tuples, I have added uintp as a valid type

closes #3733 

Unit tests not added yet, pending positive review. No fails or errors on existing tests.

The test function in the original issue now runs

```
import numba as nb
def test1b():
    x = (1, 2, 3, 4, 5,)
    for i in nb.prange(len(x)):
        print(x[nb.types.uintp(i)])
```

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for making a start on this @luk-f-a, change looks good so far. Once some unit tests are added/updated to cover this use case it can be reviewed with view to merge.

**Comment by luk-f-a** [comment]
@stuartarchibald I have added a test that mirrors the existing getitem test, now with uintp variable.

**Comment by stuartarchibald** [comment]
Great, thanks for doing that, I think the equivalent test for `NamedTuple` needs adding and then this is good to merge.

**Comment by luk-f-a** [comment]
@stuartarchibald you're right, I focused on Tuple and I missed NamedTuple, I have now added the corresponding test.

**Comment by stuartarchibald** [comment]
@luk-f-a thanks for the additional fix. This looks good to merge on CI pass. Congratulations on your first contribution to Numba :)

**Comment by luk-f-a** [comment]
thanks @stuartarchibald, first contribution feels good!

**Comment by stuartarchibald** [comment]
Not quite sure what Azure is doing but it seems like its passed if you access the build pipeline URL directly.

**Comment by seibert** [comment]
FYI: the state of the checks is not correct.  Py27/NumPy 1.9 has already passed.

**Pull request merged**
