### PR TITLE
Issue #1288: add an import-time guard against restrictions on executable memory allocation

### PR DESCRIPTION
**Pull request by pitrou**
(note I don't have a SELinux system at hand to check that it raises, but trivially it should)

### CODE REVIEW

**Comment by seibert** [comment]
Does this PR also need to bump the minimum llvmlite version requirement?

**Comment by seibert** [comment]
Or maybe we wait until just before the next Numba release to bump the version requirement?

**Comment by pitrou** [comment]
> Or maybe we wait until just before the next Numba release to bump the version requirement?

I would opine so. Certainly we won't forget it :-D

**Comment by seibert** [comment]
Hah.  We can't bump the llvmlite version requirement anyway until there is a new official release of llvmlite, so we basically have to wait until release time to fix the dependencies.

**Pull request merged**
