### PR TITLE
Attempt to fix #2473

### LINKED ISSUE #2473: Dispatcher test cache failures.
@ghatwala reports the following in https://github.com/numba/numba/issues/2451#issuecomment-316605512, tracking in this ticket as the issue is separate to that reported #2451.

```
$ /home/amit/numba# ls -l /usr/local/lib/python2.7/dist-packages/ | grep llvmlite
drwxr-sr-x  6 root staff   4096 Jul 19 10:26 llvmlite
drwxr-sr-x  2 root staff   4096 Jul 19 10:26 llvmlite-0.19.0.dist-info

$ /home/amit/numba# python -m numba.runtests numba.tests.test_dispatcher.TestCache

........ipython version: 5.4.1
...FFE...
======================================================================
ERROR: test_non_writable_pycache (numba.tests.test_dispatcher.TestCache)
----------------------------------------------------------------------
OSError: [Errno 2] No such file or directory: '/tmp/numba-tests.0/test_cache-_knByx/__pycache__'

======================================================================
FAIL: test_non_creatable_pycache (numba.tests.test_dispatcher.TestCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/test_dispatcher.py", line 956, in test_non_creatable_pycache
    self._test_pycache_fallback()
  File "numba/tests/test_dispatcher.py", line 946, in _test_pycache_fallback
    self.check_pycache(0)
  File "numba/tests/test_dispatcher.py", line 644, in check_pycache
    self.assertEqual(len(c), n, c)
AssertionError: 2 != 0 : ['dispatcher_caching_test_fodder.add_usecase-27.py27.nbi', 'dispatcher_caching_test_fodder.add_usecase-27.py27.1.nbc']

======================================================================
FAIL: test_non_writable_pycache (numba.tests.test_dispatcher.TestCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/test_dispatcher.py", line 968, in test_non_writable_pycache
    self._test_pycache_fallback()
  File "numba/tests/test_dispatcher.py", line 946, in _test_pycache_fallback
    self.check_pycache(0)
  File "numba/tests/test_dispatcher.py", line 644, in check_pycache
    self.assertEqual(len(c), n, c)
AssertionError: 2 != 0 : ['dispatcher_caching_test_fodder.add_usecase-27.py27.nbi', 'dispatcher_caching_test_fodder.add_usecase-27.py27.1.nbc']

----------------------------------------------------------------------
Ran 16 tests in 5.865s

FAILED (failures=2, errors=1)
```
For the error shown above , seems like file creation is failing
```
OSError: [Errno 2] No such file or directory: '/tmp/numba-tests.0/test_cache-_knByx/__pycache__'
```
and failures are due to assertion errors
```
AssertionError: 2 != 0 : ['dispatcher_caching_test_fodder.add_usecase-27.py27.nbi', 'dispatcher_caching_test_fodder.add_usecase-27.py27.1.nbc']
```

### PR DESCRIPTION
**Pull request by stuartarchibald**
This attempts to fix #2473 by using chattr to cause immutability
in cache locations which is needed if building/testing as the
root user on *nix systems.

Fixes #2473

### CODE REVIEW

**Comment by seibert** [comment]
macOS does not have `chattr`, but `chflags uchg  [filename]` likely does the equivalent.

**Comment by seibert** [comment]
Or maybe `chflags schg [filename]`?  To be honest, due to the different semantics, I'd rather not do anything on macOS unless there is a reported problem.

**Comment by stuartarchibald** [comment]
Can probably just catch any exception? As it could be a FS which doesn't support `chattr` or some subset of flags too I guess?

Another approach would be to leave the `chmod` as is, then test a write to the location and if it succeeds then assume the user is root/has elevated rights and exit the test?

**Comment by seibert** [comment]
I think catching any exception makes sense, especially since this is just test code.

**Comment by stuartarchibald** [comment]
Agreed, unless this causes problems on OSX as a user with elevated rights, then I think this should be ok. Fixed in 97278ab.

**Comment by seibert** [comment]
OK, this looks good to me.  One @nehaljwani confirms this fixes his issue, we can merge.

**Comment by nehaljwani** [comment]
The patch doesn't tell me that I have to install something to get `chattr` in `PATH`, it just fails.
After installing it by `yum install -y e2fsprogs`, the test still fails, unfortunately. This time, it fails because `chattr` fails with:
```
chattr: Inappropriate ioctl for device while reading flags on /tmp/numba-tests.0/test_cache-7wh8axhs/__pycache__
```
And that's probably because I am running this inside a docker container where the filesystem doesn't support setting the immutable flag.

**Comment by nehaljwani** [comment]
Is supporting running the tests as the 'nobody' not to be considered at all?

One could do:
```
su -s /bin/bash -m nobody -c 'python -m numba.runtests -m -b'
```

**Comment by nehaljwani** [comment]
Oh crap, that assumes you are running as root anyway. Scratch that.

**Comment by stuartarchibald** [comment]
I think the situation can be summarised as follows:
> If you are `root`/elevated user and the FS has no manner to prevent writes, then the fall back mechanism will not ever be invoked.

As a result of this we should probably try and detect the condition ahead of time and skip as there is nothing to test?

**Comment by nehaljwani** [comment]
If I mount the host filesystem's /tmp to /tmp inside the container, then the tests pass.

**Comment by nehaljwani** [comment]
>As a result of this we should probably try and detect the condition ahead of time and skip as there is nothing to test?

Sounds reasonable to me.

**Comment by stuartarchibald** [comment]
I guess https://github.com/numba/numba/pull/2831#issuecomment-374684755 is because `xattr`s from the underlying FS are present. Whilst inadvisable, root installs may exist as per the original ticket, so I'm inclined to try and fix it.

**Comment by nehaljwani** [comment]
The updated patch works for my build environment.

**Comment by nehaljwani** [comment]
Oops, no `PermissionsError` in py<3.3 😢 

We probably need to catch OSError/IOError and look at errno for EPERM or EACCES, similar to what conda does: https://github.com/conda/conda/blob/4.5.0/conda/gateways/disk/permissions.py#L35-L37

**Pull request merged**
