### PR TITLE
Cleanup old support for Python 3.6 and earlier code

### PR DESCRIPTION
**Pull request by jamesobutler**
Numba set the minimum required Python version to 3.7 in https://github.com/numba/numba/commit/7bdd80023cc67a5896386ad8aa613ee26180b20f. This PR removes extra code that won't be executed based on this current minimum requirement of Python 3.7.

https://github.com/numba/numba/blob/aaa6a0099ac217959126d195ab43d37000f9624a/numba/__init__.py#L140-L141

### CODE REVIEW

**Comment by jamesobutler** [comment]
Similar to changes made in https://github.com/numba/numba/pull/7920, but that PR has seemingly become stale? I did not see this existing PR because it had fallen down to the 3rd page of the open PRs. Feel free to close this as a duplicate.

**Comment by esc** [comment]
@jamesobutler thank you for submitting this. I plan to look at this PR soon.

**Comment by esc** [comment]
@jamesobutler thank you for submitting this. I compared this with #7920 today. I think we will need to adopt some of the diff of this PR.

**Comment by esc** [comment]
@jamesobutler #7920 has been updated to include the "missing" changes from this PR. Would you have a spare moment to cross-check it? That would be most appreciated here since you've looked into this already! Thank you! 🙏

**Comment by esc** [comment]
@jamesobutler thank you again for your review of #7920! I will close this now as duplicate.

**Pull request closed without merging**
