### PR TITLE
[WIP] Python 3.11 tracing

### PR DESCRIPTION
**Pull request by AndrewVallette**
This is a work-in-progress for enabling tracing support with Python 3.11. The initial effort has been to get this to cleanly compile with an updated `C_TRACE` and related functions.

### CODE REVIEW

**Comment by sklam** [comment]
Test to verify cprofiling support is: `python -m numba.runtests numba.tests.test_profiler.TestProfiler.test_profiler`. Currently,  this patch is not passing the test. 

Related cython changes that are useful to study: https://github.com/cython/cython/commit/7537910a2d2e3892359ef639fe9262f017634461

**Comment by sklam** [comment]
I'm testing a patch at https://github.com/numba/numba/pull/8711/commits/85b7979e6e95cf245cf639e6a7f281db44e775b6

**Comment by AndrewVallette** [comment]
> I'm testing a patch at [85b7979](https://github.com/numba/numba/commit/85b7979e6e95cf245cf639e6a7f281db44e775b6)

Thanks, I'll begin testing again next week :)

**Comment by sklam** [comment]
@AndrewVallette, i picked this up again today and I see that all that is left is minimizing the amount of code copied from Python. I made the changes at https://github.com/numba/numba/pull/8711/commits/00641246f37b20ab3704fc22c0476c8f3e8e404c. The diff at #8711 is a lot smaller now and it's ready for some reviews if it passes CI. (note, the py3.11 base branch still doesn't fully pass all tests)

**Pull request merged**
