### PR TITLE
Skip some failing-on-32-bit tests (may be windows only)

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by gmarkall** [comment]
Thanks very much for the PR, I've queued it for review.

**Comment by mingwandroid** [comment]
Thanks @gmarkall, if you want the backtraces in the commit message then I will amend. Here they are:

```
======================================================================
ERROR: test_homogeneous_tuples (numba.tests.test_hashing.TestTupleHashing)
----------------------------------------------------------------------Traceback (most recent call last):
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 80, in check_hash_values
    self.assertEqual(nb_hash, hash(val))
  File "C:\ci\numba_1600191962740\_test_env\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\ci\numba_1600191962740\_test_env\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 207041508 != -168982784During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 242, in test_homogeneous_tuples
    self.check_tuples(self.int_samples(), split2)
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 218, in check_tuples
    self.check_hash_values(tuples)
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 85, in check_hash_values
    print(abs(val), hashing._PyHASH_MODULUS - 1)
TypeError: bad operand type for abs(): 'tuple'Stdout:
val, nb_hash, hash(val)
(0, 0) 207041508 -168982784
abs(val), hashing._PyHASH_MODULUS - 1======================================================================
ERROR: test_heterogeneous_tuples (numba.tests.test_hashing.TestTupleHashing)
----------------------------------------------------------------------Traceback (most recent call last):
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 80, in check_hash_values
    self.assertEqual(nb_hash, hash(val))
  File "C:\ci\numba_1600191962740\_test_env\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\ci\numba_1600191962740\_test_env\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 207041508 != -168982784During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 259, in test_heterogeneous_tuples
    self.check_tuples(self.int_samples(), split)
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 218, in check_tuples
    self.check_hash_values(tuples)
  File "C:\ci\numba_1600191962740\_test_env\lib\site-packages\numba\tests\test_hashing.py", line 85, in check_hash_values
    print(abs(val), hashing._PyHASH_MODULUS - 1)
TypeError: bad operand type for abs(): 'tuple'Stdout:
val, nb_hash, hash(val)
(0, 0.0) 207041508 -168982784
abs(val), hashing._PyHASH_MODULUS - 1
----------------------------------------------------------------------
```

**Comment by gmarkall** [comment]
Thanks for the backtraces - I don't feel that there's any need to amend the commit message.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/blob/c448052c875d7a84e8d067f8483a1a1caa1dfe9b/numba/cpython/hashing.py#L267
should probably read `(x >> types.uint64(19))`.

**Comment by mingwandroid** [comment]
I tested @stuartarchibald's change and our CI passes fine with it on all platforms. Closing this! Thanks all.

**Pull request closed without merging**
