### PR TITLE
Split parfor pass into 3 parts. (old)

### PR DESCRIPTION
**Pull request by DrTodd13**
Split parfor pass into 1) parfor conversion, 2) fusion, and 3) post-fusion miscellaneous passes.  Adding a lowerer tag to the parfor node, which defaults to the existing lowerer.  Applications that change the pipeline can insert passes between 1) and 2) that change the lowerer.  Parfors with different lowerers will then not fuse.  The lowerer tag is then used during the lowering phase to lowerer this parfor.  This allows different parfors in the same function to be lowered differently, e.g., for CPU or GPU.

### CODE REVIEW

**Comment by DrTodd13** [comment]
@sklam @stuartarchibald This PR is failing on tests.test_inlining.TestInlining.test_inline_call_after_parfor.  This test is:

**Comment by sklam** [comment]
@DrTodd13, Do you need this PR for the 0.57 release?

**Comment by DrTodd13** [comment]
@sklam I was looking at another PR of mine (#7171) that is tagged for inclusion in 0.57 and @stuartarchibald didn't like the approach I took there but I just realized that this PR is the solution that Stuart wanted.  If during the gufunc compile we change the pipeline to include the third parfor stage (but not the first two) then I think we get the same effect as PR 7171.  I will experiment with this in the afternoon so given that we were going to include 7171 in 0.57 and this PR is very likely to be correct then perhaps we should combine them for 0.57.  What do you think?

**Comment by DrTodd13** [comment]
@sklam Okay....I got parfor gufunc compilation working with a very minimal pipeline that includes the prelowering parfor phase but not the other parfor phases.

**Comment by sklam** [comment]
ok, i'm adding this for 0.57 for now.

**Comment by sklam** [comment]
The latest commit is failing because of missing `cr` (the compiler result):

https://dev.azure.com/numba/numba/_build/results?buildId=14377&view=logs&j=cdf58ab6-1542-56e8-2141-f11736c48688&t=a6ad49d1-c022-53a8-dec0-947c577c759a&l=18299

**Comment by DrTodd13** [comment]
> The latest commit is failing because of missing `cr` (the compiler result):
> 
> https://dev.azure.com/numba/numba/_build/results?buildId=14377&view=logs&j=cdf58ab6-1542-56e8-2141-f11736c48688&t=a6ad49d1-c022-53a8-dec0-947c577c759a&l=18299

Fixed.

**Comment by sklam** [comment]
superseded by https://github.com/numba/numba/pull/8804

**Pull request closed without merging**
