### PR TITLE
unicode isalpha operation implementation

### PR DESCRIPTION
**Pull request by dmitrii-zagornyi**
This PR is implements `isalpha` operation.
This PR is ready for review.

### CODE REVIEW

**Comment by seibert** [comment]
Hi, this implementation isn't going to work for Numba.  Reacquiring the GIL is something we try to avoid as much as possible, and users will be surprised to see that a boolean test like isalpha prevents multithreading.

**Comment by seibert** [comment]
While talking this through with Siu, @sklam also noticed that this code assumes the `parent` pointer is populated, but that only exists for strings that originated in the interpreter.  A string constructed entirely in nopython mode will need to be boxed into a Python object, which makes me wonder how close the performance is between this approach and something like:

``` python
@overload_method(types.UnicodeType, 'isalpha')
def isalpha_unicode(string):
    if not isinstance(string, types.UnicodeType):
        raise TypingError('First parameter should be UnicodeType')

    def impl(string):
        with numba.objmode(result='bool')
            result = string.isalpha()
        return result

    return impl
```
(Note: I haven't tried this out yet, but this is the approach we would want to take with `format()`.)  Using the object mode block handles all the boxing and GIL reacquisition, but I think is still not preferable to an implementation that can access the unicode database directly.

@sklam has also found a way to get the symbols at runtime for the private symbols in `unicodetypes_db.h`, but we're trying to decide how dangerous that is compared to having a potentially out of date unicode database in Numba.

**Comment by seibert** [comment]
#4232 has been merged to master, and should allow this PR to be implemented without having to write additional C code

**Comment by stuartarchibald** [comment]
This PR was very helpful in prompting exploration around methods to obtain access to the unicode database and various other CPython internals. However, in light of #4232, which makes it possible to write this functionality in a manner that does not require GIL reacquisition or grabbing pointers to functions, I'm going to close this PR. The unit tests presented within have merit for use in testing a future implementation of this functionality and so it may be worth copying them out at a later date. Thanks for your understanding.

**Pull request closed without merging**
