### PR TITLE
Enable Azure CI batching

### PR DESCRIPTION
**Pull request by sklam**

### CODE REVIEW

**Comment by seibert** [comment]
This looks fine, and we can't really test it on a PR branch, so marking ready to merge.

**Comment by esc** [comment]
This looks good. Do I understand correctly, that this will mean Azure will complete one build fully before launching (parts of) the next one?

**Comment by stuartarchibald** [comment]
Kind-of, AIUI it waits for a build to complete, then batches up any subsequent patches to a branch and builds that batched version opposed to trying to build every patch that was added since the last build. Docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#batching-ci-builds

**Comment by seibert** [comment]
Yes, my interpretation is that in a merge party, we will get two builds, instead of N builds:
1. Merge of first PR which kicks off a build
2. All the remaining PRs, which will trigger when the first build is complete

**Pull request merged**
