### PR TITLE
Support views on pinned/mapped arrays

### PR DESCRIPTION
**Pull request by c200chromebook**
Adds support for views on pinned/mapped arrays, these required both stream and is_c_contiguous, which is moved to the device array base class.

### CODE REVIEW

**Comment by c200chromebook** [comment]
Limitations: 
Very bad things happen with views on managed arrays:
```
from numba import cuda
import numpy as np
b = cuda.managed_array(1, dtype=np.int)
b[:] = 0
print(b)
v = b.view('u1')
v[1] = 1
print(b)
```

**Comment by c200chromebook** [comment]
Now passing @gmarkall, let me know if this needs anything else

**Comment by gmarkall** [comment]
> Limitations:
> Very bad things happen with views on managed arrays:
> 
> ```
> from numba import cuda
> import numpy as np
> b = cuda.managed_array(1, dtype=np.int)
> b[:] = 0
> print(b)
> v = b.view('u1')
> v[1] = 1
> print(b)
> ```

I'm not seeing a problem on Linux (CUDA Toolkit 11.0, driver 455.28, Quadro RTX 8000):

```python
In [1]: from numba import cuda                                                                                                                               

In [2]: import numpy as np                                                                                                                                   

In [3]: b = cuda.managed_array(1, dtype=np.int)                                                                                                              

In [4]: b[:] = 0                                                                                                                                             

In [5]: print(b)                                                                                                                                             
[0]

In [6]: v = b.view('u1')                                                                                                                                     

In [7]: v[1] = 1                                                                                                                                             

In [8]: print(b)                                                                                                                                             
[256]
```

Additionally, making the following change to the tests also poses no issue for me:

```diff
diff --git a/numba/cuda/tests/cudadrv/test_host_alloc.py b/numba/cuda/tests/cudadrv/test_host_alloc.py
index daa99a531..7ae3f48ae 100644
--- a/numba/cuda/tests/cudadrv/test_host_alloc.py
+++ b/numba/cuda/tests/cudadrv/test_host_alloc.py
@@ -1,4 +1,5 @@
 import numpy as np
+from itertools import product
 from numba.cuda.cudadrv import driver
 from numba import cuda
 from numba.cuda.testing import unittest, ContextResettingTestCase
@@ -46,15 +47,16 @@ class TestHostAlloc(ContextResettingTestCase):
         self.assertTrue(sum(ary != 0) == 0)
 
     def test_views_arrays(self):
-        for ary_samp in [x(2, dtype=np.uint32)
-                         for x in
-                         (cuda.mapped_array,
-                          cuda.pinned_array,
-                          cuda.device_array)]:
+        array_types = cuda.mapped_array, cuda.pinned_array, cuda.device_array
+        dtypes = np.int32, np.uint32
+        for arrtype, dtype in product(array_types, dtypes):
+            ary_samp = arrtype(2, dtype=dtype)
             ary_samp[:] = 0
+            print(ary_samp, arrtype, dtype)
             ary_v = ary_samp.view('u1')
             ary_v[1] = 1
             ary_v[5] = 1
+            print(ary_samp, arrtype, dtype)
             self.assertTrue(sum(ary_samp) == 512)
 
     def test_host_operators(self):
(numba) 
```

with the output run under `cuda-memcheck` being:

```
$ cuda-memcheck python -m numba.runtests numba.cuda.tests.cudadrv.test_host_alloc -v
========= CUDA-MEMCHECK
test_host_alloc_driver (numba.cuda.tests.cudadrv.test_host_alloc.TestHostAlloc) ... ok
test_host_alloc_mapped (numba.cuda.tests.cudadrv.test_host_alloc.TestHostAlloc) ... ok
test_host_alloc_pinned (numba.cuda.tests.cudadrv.test_host_alloc.TestHostAlloc) ... ok
test_host_operators (numba.cuda.tests.cudadrv.test_host_alloc.TestHostAlloc) ... ok
test_views_arrays (numba.cuda.tests.cudadrv.test_host_alloc.TestHostAlloc) ... [0 0] <function mapped_array at 0x7f27fc4659d0> <class 'numpy.int32'>
[256 256] <function mapped_array at 0x7f27fc4659d0> <class 'numpy.int32'>
[0 0] <function mapped_array at 0x7f27fc4659d0> <class 'numpy.uint32'>
[256 256] <function mapped_array at 0x7f27fc4659d0> <class 'numpy.uint32'>
[0 0] <function pinned_array at 0x7f27fc4658b0> <class 'numpy.int32'>
[256 256] <function pinned_array at 0x7f27fc4658b0> <class 'numpy.int32'>
[0 0] <function pinned_array at 0x7f27fc4658b0> <class 'numpy.uint32'>
[256 256] <function pinned_array at 0x7f27fc4658b0> <class 'numpy.uint32'>
<numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f27f40a76a0> <function device_array at 0x7f27fc465670> <class 'numpy.int32'>
<numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f27f40a76a0> <function device_array at 0x7f27fc465670> <class 'numpy.int32'>
<numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f27f40b62b0> <function device_array at 0x7f27fc465670> <class 'numpy.uint32'>
<numba.cuda.cudadrv.devicearray.DeviceNDArray object at 0x7f27f40b62b0> <function device_array at 0x7f27fc465670> <class 'numpy.uint32'>
ok

----------------------------------------------------------------------
Ran 5 tests in 0.986s

OK
========= ERROR SUMMARY: 0 errors
```

@c200chromebook What platform / driver version / toolkit are you testing on?

**Comment by c200chromebook** [comment]
Ah, try running the whole cuda test set. I saw the same but it would bomb with the whole set. Running on 
Standard NC24_Promo on AWS on Win (k80s). Changing to int32 fixed it for me, but I can't tell why that would make sense.

**Comment by gmarkall** [comment]
@c200chromebook do you know what CUDA toolkit version and driver version that ran with?

**Comment by gmarkall** [comment]
See also #6371, this may be another way of causing the/an issue.

**Comment by c200chromebook** [comment]
Sure, v10.1.105 / 26.21.14.4122

**Comment by gmarkall** [comment]
Thanks for the info - I think this PR might be revealing that there's something fundamentally wrong / weird about the mapped and managed array implementations, but I'm still looking into the cause of the access violations that can be caused by operations on them from the host side.

**Comment by c200chromebook** [comment]
It's an interesting area but I recommend we punt it from this PR, which is a small gain, though more probably remains.

**Comment by gmarkall** [comment]
If changing the type between `int32` and `uint32` is enough to make an issue appear / disappear, then I think it shows that there's something underlying the functionality exercised by the tests added in `test_host_alloc` that is incorrect, so it's difficult to see how it makes sense to proceed until that is resolved - just because it works with a `uint32` on the systems that we've tried it with doesn't give me confidence that it's working in general.

I'm open to an alternative perspective if you think I'm misunderstanding the situation - do you see something that I'm missing here?

**Comment by gmarkall** [comment]
On another point - with this PR the test case from https://github.com/numba/numba/issues/2987 still fails. An updated reproducer:

```python
import numba.cuda as cuda

@cuda.jit
def output_one(x):
    x[0] = 1

arr = cuda.mapped_array(2)
output_one[1, 1](arr[:1])
```

which produces:

```
$ python repro.py 
Traceback (most recent call last):
  File "repro.py", line 10, in <module>
    output_one[1, 1](arr[:1])
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 772, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 879, in call
    kernel.launch(args, griddim, blockdim, stream, sharedmem)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 645, in launch
    self._prepare_args(t, v, stream, retr, kernelargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 717, in _prepare_args
    data = ctypes.c_void_p(driver.device_pointer(devary))
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2326, in device_pointer
    return device_ctypes_pointer(obj).value
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2334, in device_ctypes_pointer
    return obj.device_ctypes_pointer
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/devicearray.py", line 194, in device_ctypes_pointer
    if self.gpu_data is None:
AttributeError: 'MappedNDArray' object has no attribute 'gpu_data'
```

**Comment by c200chromebook** [comment]
Will take a look later this wk

**Comment by gmarkall** [comment]
I think this is the problem with `test_views_arrays`: https://github.com/numba/numba/issues/6505

**Comment by gmarkall** [comment]
@c200chromebook Could you test this branch: https://github.com/gmarkall/numba/tree/pr-6367-test locally on your setup and see if you have any issues with it please? It contains:

- This PR,
- PR #6510, which I think should fix the issues we've observed with this PR, and
- The patch from [this earlier comment](https://github.com/numba/numba/pull/6367#issuecomment-712161211), which tests with both `np.int32` and `np.uint32`.

If it works for you (and for me when I test on some other setups), then that should hopefully unblock this PR.

**Pull request closed without merging**
