### PR TITLE
CUDA: Lower launch overhead by launching kernel directly

### PR DESCRIPTION
**Pull request by gmarkall**
Instead of configuring a `driver.Function`, which creates a copy, we can directly launch with the configuration - it seems that we don't really do anything with the configured copy other than launch with it then immediately forget it anyway. Using the code from Issue #3003 (See
https://github.com/numba/numba/issues/3003#issuecomment-627872661)., timings on my system (i7-6700K, RTX 8000) before:

```
$ ipython repro.ipy
31.3 µs ± 71.5 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
46.1 µs ± 87.7 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
56 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
64.8 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
73.2 µs ± 91.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

After:

```
$ ipython repro.ipy
26.4 µs ± 78 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
41.4 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
51.1 µs ± 511 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
59.5 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
68 µs ± 87 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

i.e. a saving of about 5µs per kernel launch. I plan to make further changes in subsequent PRs to eat away at other sources of overhead (`_prepare_args`, etc.) at some point in the future.

### CODE REVIEW

**Comment by seibert** [comment]
Very excited to see this!

**Comment by seibert** [comment]
Looking forward to the dream where we can launch CUDA kernels directly from nopython mode on the CPU.  :)

**Comment by gmarkall** [comment]
> Looking forward to the dream where we can launch CUDA kernels directly from nopython mode on the CPU. :)

I made this PR because it seemed like a quick win, but it's really part of an experiment where I'm converting the kernel launches and argument preparation to be done by a generated wrapper function instead of using the Python driver API wrappers - I was doing this because I wanted boxing/unboxing extensions to work for CUDA, but as you point out, it's also a part of the road to being able to launch kernels from nopython mode.

**Comment by gmarkall** [comment]
To add another data point: this PR seems to cut the runtime of GPU-STUMP down by 59%: https://github.com/TDAmeritrade/stumpy/issues/245

**Comment by stuartarchibald** [comment]
Should this close https://github.com/numba/numba/issues/3003 ?

**Comment by gmarkall** [comment]
I don't think so, there's plenty more opportunity after this PR.

**Comment by stuartarchibald** [comment]
I've just taken a look at the patch and think this is a good change, however, it is altering behaviour, question is... does it warrant a deprecation cycle as it's advertised [public API](https://numba.readthedocs.io/en/stable/cuda-reference/kernel.html#dispatcher-objects)? Could something like:
```python
from numba import cuda

@cuda.jit
def foo():
    pass

foo_1_1 = foo.configure(1, 1)
foo_3_3 = foo[3, 3]

foo_1_1()
foo_3_3()
```
exist in the wild?

**Comment by gmarkall** [comment]
> I've just taken a look at the patch and think this is a good change, however, it is altering behaviour, question is... does it warrant a deprecation cycle as it's advertised [public API](https://numba.readthedocs.io/en/stable/cuda-reference/kernel.html#dispatcher-objects)? Could something like:
> 
> ```python
> from numba import cuda
> 
> @cuda.jit
> def foo():
>     pass
> 
> foo_1_1 = foo.configure(1, 1)
> foo_3_3 = foo[3, 3]
> 
> foo_1_1()
> foo_3_3()
> ```
> 
> exist in the wild?

This isn't changing a public API - the `configure` that is removed here is `numba.cuda.cudadrv.Function.configure`, not `numba.cuda.compiler.Dispatcher.configure` - your above example still works with the change in this PR.

I've just merged master and resolved conflicts - is this now ready for a buildfarm run?

**Comment by stuartarchibald** [comment]
> > I've just taken a look at the patch and think this is a good change, however, it is altering behaviour, question is... does it warrant a deprecation cycle as it's advertised [public API](https://numba.readthedocs.io/en/stable/cuda-reference/kernel.html#dispatcher-objects)? Could something like:
> > ```python
> > from numba import cuda
> > 
> > @cuda.jit
> > def foo():
> >     pass
> > 
> > foo_1_1 = foo.configure(1, 1)
> > foo_3_3 = foo[3, 3]
> > 
> > foo_1_1()
> > foo_3_3()
> > ```
> > 
> > 
> > exist in the wild?
> 
> This isn't changing a public API - the `configure` that is removed here is `numba.cuda.cudadrv.Function.configure`, not `numba.cuda.compiler.Dispatcher.configure` - your above example still works with the change in this PR.

Apologies, I evidently misread this and thought it was referring to the dispatcher config.

> I've just merged master and resolved conflicts - is this now ready for a buildfarm run?

I think so. Will schedule it.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_107`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_107`.

Passed.

**Review by stuartarchibald — APPROVED** [review]
Patch looks good, thanks @gmarkall

**Pull request merged**
