### PR TITLE
Add support for tuple concatenation to array analysis. (#5396 continued)

### PR DESCRIPTION
**Pull request by stuartarchibald**
This pulls the patch series for fixing #5383 from https://github.com/numba/numba/pull/5396 and rebases on mainline.

CC @DrTodd13 please could you take a look and make sure that this is what you intended in #5396, thanks.

### CODE REVIEW

**Comment by DrTodd13** [comment]
@stuartarchibald Looks good to me.  Thanks!

**Comment by stuartarchibald** [comment]
Thanks for providing the patch @DrTodd13, the code looks good. WRT: https://github.com/numba/numba/pull/5396#issue-389565234
>  There are other spots and there probably needs to be a comprehensive review of those cases.

I'm inclined to get this in as it fixes an immediate problem and consider the other cases as they arise, would that be ok?

**Comment by stuartarchibald** [comment]
> Thanks for providing the patch @DrTodd13, the code looks good. WRT: [#5396 (comment)](https://github.com/numba/numba/pull/5396#issue-389565234)
> 
> > There are other spots and there probably needs to be a comprehensive review of those cases.
> 
> I'm inclined to get this in as it fixes an immediate problem and consider the other cases as they arise, would that be ok?

Following discussion OOB at the Numba dev meeting, we decided to merge this and deal with other cases as they occur.

**Comment by stuartarchibald** [comment]
Turns out I can't approve this as I opened it, the code from @DrTodd13 looks good to me, @sklam please could you take a look? Thanks.

**Review by sklam — APPROVED** [review]

**Pull request merged**
