### PR TITLE
Add missing `numba.config` shim

### PR DESCRIPTION
**Pull request by eric-wieser**
Closes gh-5486

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch. Please could you add a short test, say similar to this one, https://github.com/numba/numba/blob/917f582433170893f32ae51e5ca8fd8a8a736914/numba/tests/test_refactor_moves.py#L117-L126 in about the same location to confirm the change. Many thanks.

**Comment by stuartarchibald** [comment]
@eric-wieser presume we can close in favour of https://github.com/numba/numba/pull/5498 ?

**Comment by eric-wieser** [comment]
Any reason not to merge this first anyway? Will make the diff a little less cluttered in #5498, and CI already passes here.

**Comment by stuartarchibald** [comment]
Can do, was just trying to reduce the number of things I'm going to have to immediately issue reverts for :) I'll approve this for merge in the next merge-window, reverts are less painful than fixing the problems in the first place!

**Pull request merged**
