### PR TITLE
NumPy device functions (formerly CUDA compatible dist_matrix)

### PR DESCRIPTION
**Pull request by sgbaird**
Here is a function `dist_matrix` with corresponding unit tests and refactored NumPy-like helper functions (and corresponding unit tests).

In addition to being pretty fast and versatile (I think a lot of people that use Numba could benefit), and if it's not too presumptuous, I think it could also be a good template/tutorial/starting point for people contributing NumPy functionality for Numba/CUDA similar to [discussion](https://github.com/numba/numba/issues/5754#issuecomment-900639137) with @gmarkall.

This took a very long time for me to create (for perspective, I had an @njit version up and running with just a few tweaks under an hour, but spent probably around 200 hrs getting this implemented). Obviously, if one of the core devs had written it, I'm sure it would have taken less time, but it did take ~2000-3000 searches scattered between Numba docs, Numba issues, Numba discourse, StackOverflow, CUDA docs, etc. for me to work through the many issues I experienced along the way. A bit of this included learning things like CUDA unit tests and building read-the-docs (10-20 hrs?). Pretty much every comment, issue, PR, or post I've made over the last month has been "along the way" to getting this.

While it's fast, I would love for it to be faster (it's still a bottleneck), but maybe that's for a later PR if speed-up ideas are more involved. Thank you to the core devs for the amicable and fast support, comments, and suggestions!

Looking forward to hearing your thoughts on this and how it can be improved (some of how I set things up is because I couldn't get it working using other ways I thought of/came across).

I'll add some specific comments to lines of code.

@gmarkall

## Reference an existing issue
#7368

### CODE REVIEW

**Comment by sgbaird** [comment]
xref: [#65](https://github.com/numba/numba-scipy/issues/65)

**Comment by sgbaird** [comment]
I'm stumped as to why it's failing the CUDA Simulator test. I've been stumped on this for a while, so eventually, I just stopped using CUDA Simulator. I didn't realize it's required for the build though (makes sense). Can someone take a look at this? @gmarkall @esc

I'm on Windows and I don't have a cuda-memcheck (no conda dist of Windows cuda-memcheck from what I can tell since conda cuda doesn't package it).

**Comment by gmarkall** [comment]
Many thanks for your contribution and efforts! It's great to see that you've produced an implementation of a complex algorithm that works efficiently using Numba's CUDA target.

For various reasons including the complexity of the implementation, the varied origins of different parts of the code, and the high level of functionality (as opposed to being more primitive building blocks, of which there are some inclusions in the Numba CUDA target) of the implementation, it isn't going to be practical to include this in Numba itself. In my view, the alternative routes for the continued maintenance and lifetime of the code are:

- A PR to https://github.com/numba/numba-examples - this really does make a nice example use case of Numba and the CUDA target, so it's tempting to suggest that it could be included there. 
- A PR to https://github.com/numba/numba-scipy - As this implements functionality very close to that of SciPy, this looks like an alternative route. At present, numba-scipy doesn't have a route to include code that runs on the GPU - in order to move forward with this implementation there, we'd need to determine how we'd go about including CUDA functionality and make some policy decisions there about how to handle things that are essentially offloads to accelerators like a CUDA device - this would be of significant complexity so it wouldn't be easy to make a quick contribution there.
- Release as a separate library that you maintain - in this case I'd suggest providing the code as a library that depends on Numba in its own repository, with its own CI, documentation, versioning, etc. This has the major advantage that doing it doesn't depend on working to bridge the gap between the existing Numba projects' (Numba, numba-examples, numba-scipy) codes and policies and the implementation proposed for merging here. It also means you can make changes and updates to the implementation without having to go down the route of making PRs to a Numba repository and getting them reviewed / tested / approved, etc., which would considerably slow down the speed on which you could respond to needs for change in your own implementation. There are various other libraries that provide functionality that depend on Numba to do so - some examples include:
  - https://github.com/hgrecco/numbakit-ode
  - https://clifford.readthedocs.io/en/latest/
  - Other libraries linked in this list of Numba CUDA Users: https://github.com/gmarkall/numba-cuda-users

I'd strongly suggest going towards maintaining this as your own separate library as the route best for making your existing work available to the community and soliciting further contributions back to it - I envision that over time, there would be portions of it that would become appropriate to contribute back to the Numba repositories once some of the hurdles have been overcome (e.g. figuring out a way to include accelerator-using code in numba-scipy, the Numba CUDA target becoming broad in scope enough to support integrating more functionality, and for the implementation presented here to have its robustness demonstrated through having a community of users).

Whichever option you choose to follow, I'm happy to provide what time / resources I have available in supporting you going forward (with the caveat that there are various other Numba-related demands that I'm also dividing my time / attention across, so I'd be providing my "best effort" to support you).

**Comment by sgbaird** [comment]
> Many thanks for your contribution and efforts! It's great to see that you've produced an implementation of a complex algorithm that works efficiently using Numba's CUDA target.

Thank you! It's been a great learning experience. Big fan of Numba and what the core devs do to maintain, extend, and support it.

> For various reasons including the complexity of the implementation, the varied origins of different parts of the code, and the high level of functionality (as opposed to being more primitive building blocks, of which there are some inclusions in the Numba CUDA target) of the implementation, it isn't going to be practical to include this in Numba itself. In my view, the alternative routes for the continued maintenance and lifetime of the code are:

😢 However, this makes sense to me. Now that you mention it, I think I can see how keeping it to the building blocks is important, esp. w.r.t. distance matrix computations which fall more into an `sklearn` or `scipy` implementation.

> * A PR to https://github.com/numba/numba-examples - this really does make a nice example use case of Numba and the CUDA target, so it's tempting to suggest that it could be included there.

After looking through numba-examples, I can see your point about uploading there. Esp. in terms of benchmarking, though it doesn't seem as well suited to teaching.

> * A PR to https://github.com/numba/numba-scipy - As this implements functionality very close to that of SciPy, this looks like an alternative route. At present, numba-scipy doesn't have a route to include code that runs on the GPU - in order to move forward with this implementation there, we'd need to determine how we'd go about including CUDA functionality and make some policy decisions there about how to handle things that are essentially offloads to accelerators like a CUDA device - this would be of significant complexity so it wouldn't be easy to make a quick contribution there.

Eventually, I plan to submit the `@njit`'ed version of what I showed to Numba-SciPy. I did open an issue [xref: #68](https://github.com/numba/numba-scipy/issues/68) since there have been other case(s) of people asking about CUDA compatibility.

> * Release as a separate library that you maintain - in this case I'd suggest providing the code as a library that depends on Numba in its own repository, with its own CI, documentation, versioning, etc. This has the major advantage that doing it doesn't depend on working to bridge the gap between the existing Numba projects' (Numba, numba-examples, numba-scipy) codes and policies and the implementation proposed for merging here. It also means you can make changes and updates to the implementation without having to go down the route of making PRs to a Numba repository and getting them reviewed / tested / approved, etc., which would considerably slow down the speed on which you could respond to needs for change in your own implementation. There are various other libraries that provide functionality that depend on Numba to do so - some examples include:
>   
>   * https://github.com/hgrecco/numbakit-ode
>   * https://clifford.readthedocs.io/en/latest/
>   * Other libraries linked in this list of Numba CUDA Users: https://github.com/gmarkall/numba-cuda-users

I don't have much familiarity with CIs, but I can see the appeal here. My initial instinct would be to either build on a fork of Numba or add it as a submodule and implement the same CIs that Numba does (within reason). Splitting it off into a separate library to eventually make it back into other Numba repositories seems like it could involve a lot of merging work compared with keeping it in-pace with the Numba-master branch through the incremental changes.

> I'd strongly suggest going towards maintaining this as your own separate library as the route best for making your existing work available to the community and soliciting further contributions back to it - I envision that over time, there would be portions of it that would become appropriate to contribute back to the Numba repositories once some of the hurdles have been overcome (e.g. figuring out a way to include accelerator-using code in numba-scipy, the Numba CUDA target becoming broad in scope enough to support integrating more functionality, and for the implementation presented here to have its robustness demonstrated through having a community of users).

Are user-contributed device functions that introduce NumPy functionality something acceptable for Numba PRs?

> Whichever option you choose to follow, I'm happy to provide what time / resources I have available in supporting you going forward (with the caveat that there are various other Numba-related demands that I'm also dividing my time / attention across, so I'd be providing my "best effort" to support you).

Thank you. Several of the core devs, especially you, have spent a lot of time helping and encouraging me. I really appreciate it. I will give this some more thought.

**Comment by sgbaird** [comment]
@gmarkall, I'm OK with closing the pull request, by the way. But I'm still interested in hearing about whether NumPy device functions are in line with the vision of CUDA/NumPy compatibility, or if there's a different direction that's planned for this.

**Pull request closed without merging**
