### PR TITLE
Allow pipeline manipulation by user

### PR DESCRIPTION
**Pull request by ehsantn**
This patch allows advanced users to manipulate the compiler pipeline with minimal changes to the core. All pipeline data structures can be accessed as well. Here is an example for adding a print stage before the backend stage:

```python
def print_ir(func_ir):
    func_ir.dump()

def add_print_stage(pipeline_manager, pipeline):
    pp = pipeline_manager.pipeline_stages['nopython']
    new_pp = []
    for (func,desc) in pp:
        if desc=='nopython mode backend':
            new_pp.append((lambda:print_ir(pipeline.func_ir), "print IR"))
        new_pp.append((func,desc))
    pipeline_manager.pipeline_stages['nopython'] = new_pp

numba.set_user_pipeline_func(add_print_stage)
```

### CODE REVIEW

**Comment by sklam** [comment]
This is very simple and perhaps too simple.  The global `user_pipeline_func` can be written to by any code and overwriting the previous value without warning.  There can only be one `user_pipeline_func` defined at any time as well.  

Can you explain what is the expected usecase of this pipeline manipulation API?

**Comment by ehsantn** [comment]
@sklam Yes, it has several restrictions. Ideally, we should enable addition of `user_pipeline_function` in the jit call as argument but it would require more core changes.

This code enabled getting the [hpat](https://github.com/IntelLabs/hpat) package that we discussed last week started.

**Comment by ehsantn** [comment]
@sklam  `jit` decorator takes `user_pipeline_funcs` as an argument now. It takes a list of functions to apply to pipeline. For example, the example above becomes `@jit(user_pipeline_funcs=[add_print_stage])`.

**Comment by stuartarchibald** [comment]
Could this perhaps be closed in favour of https://github.com/numba/numba/pull/2843 ?

**Comment by ehsantn** [comment]
Yes.

**Pull request closed without merging**
