### PR TITLE
Move to using windows-2019 images in Azure

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. The 2016 images are EOL Jan 2022.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
CI currently fails with:
```
======================================================================
FAIL: test_complex64_numpy4_usecase (numba.tests.test_svml.TestSVMLGeneration)
skipped CUDA tests
skipped CUDA tests
Parallel: 472. Serial: 34
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\1\s\numba\tests\test_svml.py", line 248, in test_runner
    self.fail("Process timed out.")
AssertionError: Process timed out.

======================================================================
FAIL: test_float64_prange8_usecase (numba.tests.test_svml.TestSVMLGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\1\s\numba\tests\test_svml.py", line 248, in test_runner
    self.fail("Process timed out.")
AssertionError: Process timed out.

----------------------------------------------------------------------
Ran 506 tests in 569.418s
```

**Comment by stuartarchibald** [comment]
Rerun... just one fail:
```
======================================================================
FAIL: test_complex64_numpy4_usecase (numba.tests.test_svml.TestSVMLGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\1\s\numba\tests\test_svml.py", line 248, in test_runner
    self.fail("Process timed out.")
AssertionError: Process timed out.

----------------------------------------------------------------------
Ran 506 tests in 459.280s

FAILED (failures=1, skipped=20)
```

**Review by sklam — APPROVED** [review]
Thanks for the patch!

Looks like the SVML error went away

**Comment by stuartarchibald** [comment]
> Looks like the SVML error went away

Think https://github.com/numba/numba/pull/7637 "fixed" it.

**Pull request merged**
