### PR TITLE
Misc/backport0.55 combine

### PR DESCRIPTION
**Pull request by sklam**
extending #8072

add #8082
add #8084
add cherrypick of #7786

### CODE REVIEW

**Comment by sklam** [comment]
BFID: numba_yaml_196

**Comment by sklam** [comment]
Rebased this PR so it is just #8103 #8095 #8084.

(Not sure how GH think there are 5 commits on the branch)

**Comment by esc** [comment]
> Rebased this PR so it is just #8103 #8095 #8084.
> 
> (Not sure how GH think there are 5 commits on the branch)

I think it was #8097 not #8095 that was merged.

There are 5 commits in this PR, because there are three commits with actual content and two merge commits.

**Comment by esc** [comment]
This has now been re-built and is pending `numba_smoketest_cpu_yaml_100`

**Comment by sklam** [comment]
Also started `numba_smoketest_cuda_yaml_130` and `numba_wheel_64`

**Comment by esc** [comment]
Happy to report that `numba_smoketest_cpu_yaml_100`, `numba_smoketest_cuda_yaml_130` and `numba_wheel_64` (and also `numba_wheel_m1_2`) were all green. 🟢

**Comment by esc** [comment]
Closing this, as the purpose has been served.

**Pull request closed without merging**
