### PR TITLE
PR 6096 continued

### PR DESCRIPTION
**Pull request by stuartarchibald**
Continues #6096...
* Adds public CI support
* Updates conda recipes
* Removes Python 3 version guards
* Removes references/support for TBB < 2021.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@Hardcode84 Are you happy with the contents of this patch? It's essentially a reduced version of #6096, TBB minimum version is raised to 2021 version 1.

**Comment by Hardcode84** [comment]
LGTM

**Comment by stuartarchibald** [comment]
> LGTM

@Hardcode84 Thanks for checking.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cpu_yaml_12`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cpu_yaml_12`.

This passed.

**Review by sklam — APPROVED** [review]
LGTM!

**Pull request merged**
