### PR TITLE
Improve array analysis for user-defined data types.

### LINKED ISSUE #5499: Operations over a custom object aren't fused
- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numpy
import numba
from numba import cgutils, types
from numba.extending import (box, intrinsic, make_attribute_wrapper, models,
                             overload_method, overload, register_model)
from numba.targets.boxing import box_array
from numba.typing import signature


class Dummy:
    def __init__(self, data):
        self.data = data

    def floordiv(self, other):
        return data // other.data

    def pow(self, other):
        return data ** other.data


class DummyType(types.Type):
    def __init__(self, data):
        self.data = data
        super().__init__(name=f'Dummy({self.data})')


@register_model(DummyType)
class DummyTypeModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [
            ('data', fe_type.data),
        ]
        super().__init__(dmm, fe_type, members)


make_attribute_wrapper(DummyType, 'data', '_data')


@intrinsic
def init_dummy(typingctx, data):
    def codegen(context, builder, sig, args):
        typ = sig.return_type
        data, = args
        dummy = cgutils.create_struct_proxy(typ)(context, builder)
        dummy.data = data

        if context.enable_nrt:
            context.nrt.incref(builder, sig.args[0], data)

        return dummy._getvalue()

    ret_typ = DummyType(data)
    sig = signature(ret_typ, data)

    return sig, codegen


@overload(Dummy, inline='always')
def dummy_overload(data):
    def ctor(data):
        return init_dummy(data)

    return ctor


@box(DummyType)
def box_dummy(typ, val, c):
    dummy = cgutils.create_struct_proxy(typ)(c.context, c.builder, value=val)
    data_obj = box_array(typ.data, dummy.data, c)
    class_obj = c.pyapi.unserialize(c.pyapi.serialize_object(Dummy))
    res = c.pyapi.call_function_objargs(class_obj, (data_obj,))
    c.pyapi.decref(data_obj)
    c.pyapi.decref(class_obj)

    return res


@overload_method(DummyType, 'floordiv', inline='always')
def floordiv_overload(self, other):
    def impl(self, other):
        return self._data // other._data

    return impl


@overload_method(DummyType, 'pow', inline='always')
def pow_overload(self, other):
    def impl(self, other):
        return self._data ** other._data

    return impl


@numba.njit(parallel=True)
def test_impl1(data, other_data):
    dummy = Dummy(data)
    other = Dummy(other_data)

    # After fusion, function test_impl1 has 2 parallel for-loop(s) #{0, 1}.
    res1 = dummy.floordiv(other)
    res2 = dummy.pow(other)

    return res1, res2


@numba.njit(parallel=True)
def test_impl2(data, other_data):
    # Parallel for-loop #3 is fused into for-loop #2.
    # After fusion, function test_impl2 has 1 parallel for-loop(s) #{2}.
    res1 = data // other_data
    res2 = data ** other_data

    return res1, res2


data = numpy.arange(10)
other_data = numpy.array([1, 2] * 5)
# not fused
res1, res2 = test_impl1(data, other_data)
# fused
res3, res4 = test_impl2(data, other_data)
```

Operations are not fused in `test_impl1`, but fused in `test_impl2`. In the first case the operations on arrays are performed inside of the custom object `Dummy`. Am I able to fuse such operations somehow?

Numba version: ef119bc

### PR DESCRIPTION
**Pull request by DrTodd13**
Resolves #5499 and #4277

Augment ArrayAnalysis to recognize that a.data and b.data (or a different a.data reference) are equivalent if a and b alias.

I'm open to testing recommendations.  The code for the original issue is quite large.  Would like some input from @stuartarchibald .

### CODE REVIEW

**Comment by sklam** [comment]
@DrTodd13

https://github.com/sklam/numba/commit/da55e904271cd31a79a33d036f5c245a8008a304 resolved the conflict.
https://github.com/sklam/numba/commit/a384261327d575508f775e401dcc880a77672dd4 adds a test for #5499 by `structref` to simplify making user-defined type.

**Comment by DrTodd13** [comment]
> @DrTodd13
> 
> [sklam@da55e90](https://github.com/sklam/numba/commit/da55e904271cd31a79a33d036f5c245a8008a304) resolved the conflict.
> [sklam@a384261](https://github.com/sklam/numba/commit/a384261327d575508f775e401dcc880a77672dd4) adds a test for #5499 by `structref` to simplify making user-defined type.

@sklam @stuartarchibald There was an issue with the way you resolved one of the conflicts.  I went ahead and by hand merged your changes in and fixed that one issue.  So, da55e90 is not needed anymore.  Please go ahead and merge a384261.

**Comment by sklam** [comment]
thanks, i'll go ahead with https://github.com/numba/numba/commit/a384261327d575508f775e401dcc880a77672dd4

**Comment by sklam** [comment]
@DrTodd13

The merge with master is affecting the following tests:

`numba.tests.test_parfors.TestParfors.test_tuple_concat`
`numba.tests.test_parfors.TestParfors.test_tuple_concat_with_reverse_slice`
`numba.tests.test_parfors.TestParforsMisc.test_issue5065`

The first two is new.

**Comment by DrTodd13** [comment]
> @DrTodd13
> 
> The merge with master is affecting the following tests:
> 
> `numba.tests.test_parfors.TestParfors.test_tuple_concat`
> `numba.tests.test_parfors.TestParfors.test_tuple_concat_with_reverse_slice`
> `numba.tests.test_parfors.TestParforsMisc.test_issue5065`
> 
> The first two is new.

@sklam Seems fine with my latest fixes now.  Thanks.

**Review by sklam — APPROVED** [review]
Thanks for the patch!

**Pull request merged**
