### PR TITLE
Correctly restore numba.parfor.sequential_parfor_lowering in case of …

### PR DESCRIPTION
**Pull request by Hardcode84**
…exception

Partial fix for https://github.com/numba/numba/issues/5098

Not sure how to write test for this (need to deliberately throw exception from `_create_gufunc_for_parfor_body`)

### CODE REVIEW

**Comment by Hardcode84** [comment]
@DrTodd13

**Comment by DrTodd13** [comment]
@Hardcode84 @stuartarchibald I think the base problem should be fixed.  However, in this modified code in this PR, if create_gufunc fails then I don't think it makes sense to continue lowering the parfor.  The next step is to call the generated gufunc which is also going to fail.  Maybe this exception will propagate all the way back to where the whole function is not compiled but interpreted instead.  I think this should just be a straight-up Numba error that stops everything.

**Comment by stuartarchibald** [comment]
I think the issue in #5098 is that when lowering fails, a `LoweringError` is raised, and because of the deeply nested pipeline the exception does not propagate to the user level and instead ends up being swallowed by `BaseFunction::get_call_type`. In this function there's a `try/except` block in use for trying out literal/non-literal variants of a function, the "with literal types" compilation path seems to fail because of the `LoweringError`, and the pipeline is then reentered under the "with non-literal" compilation path with the erroneous Parfors state set, which just so happens to succeed.

I'm not sure that making the failure of a `gufunc` compilation a survivable event is a good idea, as noted by @DrTodd13. I also think it'll just end up with a `LoweringError` capturing that there's undefined variables from the actual parfors lowering implementation?

I'd suggest:
1. Implementing a hard stop on failure as suggested by @DrTodd13 
2. Fixing whatever it is that is causing this invalid IR.

**Comment by Hardcode84** [comment]
@stuartarchibald @DrTodd13 
So what's about this patch?

Even if that lowering issue is fixed there can be more. End even if we make exception to halt compilation we still want compiler to be in valid state after that (e.g. we are running a bunch of tests and we expecting some of them my fail to compile, but we still want run remaining tests).

**Comment by DrTodd13** [comment]
@Hardcode84 @stuartarchibald I suggest that if an exception is caught that you set the sequential lowering flag and rethrow the exception.  Can you make that change?

I don't know how something like a test framework is handled.  You wouldn't want the test framework to totally stop on the first lowering error.  So, maybe I'd make the test framework have to catch the exception and keep going.  The default would be to terminate the process.

**Comment by Hardcode84** [comment]
> I suggest that if an exception is caught that you set the sequential lowering flag and rethrow the exception. Can you make that change?

@DrTodd13  `finally` is doing exactly that - restoring flag regardless if function returned normally or via exception if I understand you correctly.

> So, maybe I'd make the test framework have to catch the exception and keep going.
Our (SDC) tests are already working like that.

**Comment by DrTodd13** [comment]
@Hardcode84 Yes, you're right.  So, I'm fine with this PR.  thanks.

**Comment by Hardcode84** [comment]
Rebased

ping @stuartarchibald

**Comment by stuartarchibald** [comment]
Thanks @Hardcode84, we still need to find a way to reproduce that doesn't also rely on doing something that's a bug/is bad.

**Comment by stuartarchibald** [comment]
This got replicated and merged as part of https://github.com/numba/numba/pull/5250, thanks

**Pull request closed without merging**
