### PR TITLE
Flatten mangling dicts into a single dict

### PR DESCRIPTION
**Pull request by gmarkall**
Since we are attempting to mangle Numba types, mapping straight from Numba types to type codes is more direct than going through C type names, and avoids the issue of dealing with adding C type names for which there is no standard name (e.g. 16-bit floats).

See https://github.com/numba/numba/pull/7460#discussion_r768668206 for a discussion that spurred this.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Review by stuartarchibald — COMMENTED** [review]
Thanks for the patch. I think this flattening makes sense, it removes a seemingly unnecessary layer of indirection. I'm not sure if there's any use case where the C map would be needed, am going to wait for a response from @sklam in case there's some rare case that I've missed (maybe external C interop?).

**Review by sklam — DISMISSED** [review]
LGTM.

`C2CODE` is probably from legacy code. We don't need it anymore.

**Comment by sklam** [comment]
There's conflict with main

**Comment by stuartarchibald** [comment]
> LGTM.
> 
> `C2CODE` is probably from legacy code. We don't need it anymore.

Thanks for confirming @sklam, it's from around 7 years ago https://github.com/numba/numba/commit/a257cb1a26ef3dd7f69f5160f97abf37960bb1ea, and seems entirely unused!

**Review by stuartarchibald — APPROVED** [review]

**Comment by stuartarchibald** [comment]
@gmarkall this is approved but needs a conflict resolving. Please could you take a look when you have a moment? Many thanks.

**Comment by gmarkall** [comment]
@stuartarchibald Many thanks for the review. The conflict should now be resolved.

**Review by stuartarchibald — APPROVED** [review]
Thanks for fixing the conflict against mainline.

**Pull request merged**
