### PR TITLE
Fix pickling of jitclass type

### PR DESCRIPTION
**Pull request by sklam**
Related to https://github.com/numba/numba/issues/4250#issuecomment-509150125, https://github.com/numba/numba/issues/1846

Makes the type object of a jitclass pickleable.  But, jitclass instances are still not pickleable.
This is mainly to fix usability issue of jitclass instances in type inferred containers, i.e. typed-dict and typed-list.

The fix is to avoid references things that are not pickleable and breaking cyclic references by making `property` methods instead of storing the cyclic references as attributes.

### CODE REVIEW

**Comment by esc** [comment]
Perhaps add a test where JitClassses are stored in a typed dict? Just to ensure it does actually work as intended?

**Comment by sklam** [comment]
Added test using jitclass instances as value of a Dict.
Jitclass doesn't support overriding `__eq__` yet to be useful as a Dict key.

**Comment by esc** [comment]
@sklam that will suffice, thanks for adding.

**Comment by stuartarchibald** [comment]
Seems to be having issues on Py27:
```
ERROR: test_pickling (numba.tests.test_jitclasses.TestJitClass)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/test_jitclasses.py", line 896, in test_pickling
    @jitclass(spec=[])
  File "numba/jitclass/decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "numba/jitclass/base.py", line 200, in register_class_type
    _drop_ignored_attrs(others)
  File "numba/jitclass/base.py", line 271, in _drop_ignored_attrs
    del dct[k]
KeyError: '__dict__'
```

**Pull request merged**
