### PR TITLE
Remove refcount pruning pass

### PR DESCRIPTION
**Pull request by sklam**
because it is no longer valid. The pass was introduced in https://github.com/numba/numba/pull/2352 to avoid NRT-ops if the function doesn't need it. However, it's no longer possible to detect; at least with the current way we emit the LLVM-IR.

This fixes https://github.com/numba/numba/issues/5335, which provides a use-case where the `@intrinsic` added a hidden use of NRT allocation not observable from the pruning pass.

### CODE REVIEW

**Comment by sklam** [comment]
Note, the consequences of this PR is that https://github.com/numba/numba/issues/2350 will become a problem again

**Comment by sklam** [comment]
Some tests are failling. I think the pass was hiding refcount errors in simple array tests.

**Comment by stuartarchibald** [comment]
Performance vs leaks, I'd rather stop it leaking and dedicate time to an LLVM pass?

**Comment by sklam** [comment]
https://github.com/numba/numba/pull/5338#issuecomment-593966746

agree

**Comment by stuartarchibald** [comment]
Assuming this passes CI, this looks good.

**Comment by stuartarchibald** [comment]
> [#5338 (comment)](https://github.com/numba/numba/pull/5338#issuecomment-593966746)
> 
> agree

Right, let's proceed with acknowledgement that we do correctness over performance, and we know how to fix the performance. Schedule that for Q2.

**Pull request merged**
