### PR TITLE
Bump cuda array interface to version 2

### PR DESCRIPTION
**Pull request by sklam**
#4609 bumped the cuda_array_interface version to 2 in the docs but not in the code.
This bumps the version and added an extra test to check that unnecessary non-None strides still works.

### CODE REVIEW

**Comment by seibert** [comment]
Looks good.  Ready to merge once CUDA smoke test passes.

**Comment by jakirkham** [comment]
Maybe we should start listing the current version in [this doc]( https://github.com/numba/numba/blob/master/docs/source/cuda/cuda_array_interface.rst#cuda-array-interface )?

**Comment by seibert** [comment]
The current description of the `version` attribute says "An integer for the version of the interface being exported. The current version is 2.".  Are you suggesting we make that more prominent?

**Comment by jakirkham** [comment]
Ah I see that now. Yeah it would be nice if it were in the title (like "CUDA Array Interface (version 2)").

**Comment by seibert** [comment]
Makes sense.  @sklam: can you make that change?

**Comment by seibert** [comment]
Smoke test looks good.

**Comment by sklam** [comment]
Heh, I only noticed you were referring to the doc title after I changed the PR title.  But then I decided to wait until the morning as my brain is clearly not fully functional.

Anyway, it's updated now.

**Comment by seibert** [comment]
OK, don't need to wait for CI to finish.  This is ready to merge (and to cherry pick onto release branch).

**Comment by jakirkham** [comment]
Thanks @sklam! 😄

**Comment by leofang** [comment]
Oh boy, how come I missed that! Thanks for the followup @sklam.

**Pull request merged**
