### PR TITLE
Rtd/sphinx compat

### PR DESCRIPTION
**Pull request by esc**
Should fix the failing RTD builds, inspired by:

https://github.com/sphinx-doc/sphinx/issues/7747

### CODE REVIEW

**Comment by esc** [comment]
Build is here: https://readthedocs.org/projects/numba/builds/14032023/

**Comment by esc** [comment]
RTD Build passed: https://readthedocs.org/projects/numba/builds/14032023/

**Comment by stuartarchibald** [comment]
These type of URLs are working again! https://numba--7122.org.readthedocs.build/en/7122/

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
Question... Does this create a minimum sphinx version requirement or is the patch backward compatible?

**Comment by esc** [comment]
Screen Shot 2021-06-17 at 18 20 28

Deprecated since 1.8, removed with 4.0 -- yes, new minimum sphinx is now 4.0

**Comment by stuartarchibald** [comment]
> Screen Shot 2021-06-17 at 18 20 28
> 
> Deprecated since 1.8, removed with 4.0 -- yes, new minimum sphinx is now 4.0

Thanks, I guess we need to fix up the recipes and add a note in the docs too. Anything else?

**Pull request merged**
