### PR TITLE
Support bools from cffi in nopython.

### PR DESCRIPTION
**Pull request by corona10**
Support bools from cffi in nopython.

Fixes: #2641

### CODE REVIEW

**Comment by corona10** [comment]
For reviewers,

This is my first contribution to the numba project.
If test codes are needed please guide me to do it. :)
Thanks.

**Comment by corona10** [comment]
I checked now it runs well.

```
(py3) ➜  dev git:(master) ✗ python numba_cffi.py
<cdata '_Bool(*)()' 0x1040f8cd0>
(py3) ➜  dev git:(master) ✗ cat numba_cffi.py
import cffi
ffi = cffi.FFI()
ffi.cdef(r"""bool foo();""")
ffi.set_source("_example",
               r"""#include <stdbool.h>
               bool foo(){return true;}""")
lib = ffi.dlopen(ffi.compile())
from numba import jit
func_ptr = lib.foo
print(func_ptr)
@jit(nopython=True)
def func():
    return func_ptr()
func()
```

**Comment by stuartarchibald** [comment]
Thanks for the patch, this change is a good idea. As noted it needs testing before merge.

I would probably do something along the following lines:
 * Add to `numba/tests/cffi_usecases.py` definitions a bool function (that does something trivial to a bool arg) in both the inline module and the out of line module. Then also add the corresponding `C` implementations to the out of line module in the `cffi_usecases.py` source and into `_helpermod.c` around here https://github.com/numba/numba/blob/master/numba/_helpermod.c#L167. I expect some effort may be needed to get a bool type on Windows with Python 2.7 (or to fake one).
 * Once the above is done it should just be a question of adding type assertion checks to the tests in `numba/tests/test_typeof.py::test_cffi` and runtime tests in `numba/tests/test_cffi.py`.

Would you be happy to try this? If not I can cherry-pick the commit and continue.

Many thanks.

**Comment by corona10** [comment]
Thank you for the reponse.
If this issue is not thay urgent.
I will try it :)
I have really big interest in this project.
This issue looks good to start.

Thanks

**Comment by corona10** [comment]
@stuartarchibald
Updated! PTAL

**Comment by stuartarchibald** [comment]
@corona10 thanks very much for writing the tests, these are definitely on the right lines. The changes you've made add to the in-line module testing, something similar needs doing to the out-of-line module too (`cffi_usecases.py` has the source). Would you be happy to try, if not I can do it? Thanks very much for your work so far, I'll do a deeper review when the patches are complete.

**Comment by corona10** [comment]
Thanks. I will try it :)

**Comment by corona10** [comment]
@stuartarchibald @seibert 
Travis CI tests are failed with `AssertionError: 1 not greater than or equal to 5000`.
Can I get some help?

**Comment by stuartarchibald** [comment]
@corona10 thanks for having a try at this, the error you are seeing is because the test suite has a `power-on-self-test` like behaviour when it starts up to make sure that the test suite will actually a) run and b) run all the tests.

The patches you have supplied contain a statement that is syntactically invalid https://github.com/numba/numba/pull/2660/commits/a483124bb1028e49e28dec534492729abfe931b9#diff-94dae8281a0fd90054d68bf5c677f41eR52 (the `"""` needs to go on the same line as ` numba_complex = headers +`). As a consequence of having this invalid statement, the test suite fails to do the self test and gives the assertion error (the `1 < 5000` is from a trivial check for "are there more than 5000 tests discovered" https://github.com/numba/numba/blob/master/numba/tests/test_runtests.py#L27). I've added a ticket https://github.com/numba/numba/issues/2743 to update this error message to explain the likely cause to help future users!

**Comment by corona10** [comment]
@stuartarchibald 
Done!. PTAL Shame for my mistakes.
Next time, I should set up the dev environment on Docker.
(Is there any docker container images for developers? Cause I am not using conda for several reasons for the local environment)

**Comment by stuartarchibald** [comment]
@corona10 Thanks very much for your effort on these patches. I've taken a look through the code and it looks good. I'm going to run it through the buildfarm to make sure it works ok with windows and also as another check as the CI systems seem to have missed https://github.com/numba/numba/pull/2660/commits/cb4b88c2ad872e1efed99f3f99a4f0d0f93bb5de, quite possibly due to history rewrites. Assuming all is fine, it's good to merge.

**Comment by stuartarchibald** [comment]
Apologies for the delay on this. The buildfarm needed some maintenance, I'm running this through now.

**Comment by stuartarchibald** [comment]
Build farm has a test pass. Merging.

**Pull request merged**
