### PR TITLE
NumPy 1.25 support (PR #9011) continued

### PR DESCRIPTION
**Pull request by gmarkall**
This continues PR #9011, which has been closed as the original author is no longer working on it. The branch for this PR is the same as it was on #9011, with the `test_parfors.py` change reverted as requested in https://github.com/numba/numba/pull/9011/files#r1261153152.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Review by sklam — DISMISSED** [review]
I went through this PR and all conversation in #9011. I believe all review suggestions are addressed.

**Comment by gmarkall** [comment]
I just noticed we're only going up to NumPy 1.24 for Azure CI on Windows and macOS, which seems like an oversight. Going to update this to 1.25 and re-run CI.

**Comment by gmarkall** [comment]
@sklam @esc Just re-testing with NumPy 1.25 on Windows and macOS on Azure now (just added in the latest commit https://github.com/numba/numba/pull/9105/commits/f409e3af4e120fb5daf7274a43c01e40e6019ed3)

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by esc** [comment]
This passed on our build farm as `numba_yaml_380` 🍏

**Review by esc — COMMENTED** [review]
Reviewed by @sklam and completed testing on the build-farm.

**Review by esc — APPROVED** [review]
RTM

**Pull request merged**
