### PR TITLE
Refactor types module

### PR DESCRIPTION
**Pull request by pitrou**
Refactor the `numba.types` module into a subpackage.

Based on PR #1724.

### CODE REVIEW

**Comment by seibert** [comment]
Looks reasonable to me.  Main change (beyond chopping up the much-too-long types module) seems to be using `None` instead of `pyobject` in several locations.  Any concerns, @sklam?

**Comment by sklam** [comment]
I was just about to point out that `unify_pairs` behavior was changed in this PR.

**Comment by pitrou** [comment]
Returning `pyobject` created a recursive import problem between the various submodules of `numba.types`, which is why I changed the convention to `None`.

**Comment by sklam** [comment]
At https://github.com/pitrou/numba/blob/types_refactor/numba/typeinfer.py#L43
Shouldn't this be changed as well?

**Comment by pitrou** [comment]
> At https://github.com/pitrou/numba/blob/types_refactor/numba/typeinfer.py#L43
Shouldn't this be changed as well? 

Yes, you're right. Fixing it.

**Comment by seibert** [comment]
Alright, as soon as Travis-CI is happy, we can merge.

**Pull request merged**
