### PR TITLE
Pairwise sum implementation.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This switches the core array.sum() routine to behave more like
NumPy's, i.e. chunked and pairwise sum, for improved accuracy.

The chunk size is a magic number, 128 seems to be good locally.
A tree reduction is used to reduce the accumulated chunk sums, this
may or may not be a good idea (a repeated fold-and-add might be
faster and will use less memory).

### CODE REVIEW

**Comment by stuartarchibald** [comment]
This code tests the scaling:
```python
from numba import njit
import numpy as np
from IPython import get_ipython
from pandas import DataFrame as df
import pandas
import matplotlib.pyplot as plt
ipython = get_ipython()

#original impl in Numba
def basic_sum(arr):
    c = 0
    for v in np.nditer(arr):
        c += v.item()
    return c

# use impl from PR
def test_sum(arr):
    return np.sum(arr)


njit_test_sum = njit(basic_sum)
njit_test_fastmath_sum = njit(fastmath=True)(basic_sum)

njit_pairwise = njit(test_sum)
njit_fastmath_pairwise = njit(fastmath=True)(test_sum)

samples = [
    0,
    5,
    127,
    128,
    129,
    255,
    256,
    257,
    513,
    1022,
    1024,
    1028,
    2000,
    9128,
    501337,
    1234567]

for v in samples:
    print('-' * 80)
    print("Checking:", v)
    x = np.arange(np.float64(v))
    expected = np.sum(x)
    got = njit_pairwise(x)
    try:
        assert (got == expected)
    except BaseException:
        print(expected)
        print(got)
        raise

results = {
    'size': [],
    'NumPy': [],
    'pairwise': [],
    'pairwise(fastmath)': [],
    'linear': [],
    'linear(fastmath)': []}

for v in sorted([10**x for x in range(9)] + samples):
    x = np.arange(np.float64(v))
    print('-' * 80)
    print("Trying:", v)
    results['size'].append(v)
    results['NumPy'].append(ipython.magic("timeit -o -r1 np.sum(x)").best)
    results['linear'].append(ipython.magic(
        "timeit -o -r1 njit_test_sum(x)").best)
    results['linear(fastmath)'].append(ipython.magic(
        "timeit -o -r1 njit_test_fastmath_sum(x)").best)
    results['pairwise'].append(ipython.magic(
        "timeit -o -r1 njit_pairwise(x)").best)
    results['pairwise(fastmath)'].append(ipython.magic(
        "timeit -o -r1 njit_fastmath_pairwise(x)").best)

dt = df.from_dict(results).set_index('size')
dt.plot(logx=True, logy=True)
pandas.set_option('display.width', 120)
print(dt)
plt.grid()
plt.savefig('scaling.png', bbox_inches='tight')
```
which for me, on a 4 core Haswell with nothing special about it box, gives:
```
              NumPy        linear  linear(fastmath)      pairwise  pairwise(fastmath)
size                                                                                 
0          0.000002  2.272764e-07      2.275548e-07  2.882464e-07        3.301000e-06
1          0.000002  2.281953e-07      2.291000e-07  2.865296e-07        2.850222e-07
5          0.000002  2.326509e-07      2.276477e-07  3.649849e-07        2.927629e-07
10         0.000002  2.284571e-07      2.286534e-07  2.977195e-07        2.963740e-07
100        0.000002  2.844914e-07      2.860548e-07  3.615682e-07        3.651712e-07
127        0.000002  3.054542e-07      3.071739e-07  3.854084e-07        3.803392e-07
128        0.000002  3.624445e-07      3.049328e-07  4.717405e-07        3.905550e-07
129        0.000002  3.082632e-07      3.083067e-07  4.735211e-07        3.947905e-07
255        0.000002  4.028986e-07      4.003802e-07  5.643666e-07        4.801895e-07
256        0.000002  4.015541e-07      4.016812e-07  5.445286e-07        4.038303e-07
257        0.000002  4.024582e-07      4.020729e-07  5.450192e-07        4.012826e-07
513        0.000002  5.947136e-07      5.966150e-07  6.878719e-07        4.240259e-07
1000       0.000002  9.629170e-07      9.616235e-07  1.000783e-06        5.567731e-07
1022       0.000002  9.767695e-07      9.762763e-07  1.015213e-06        5.722066e-07
1024       0.000002  9.792467e-07      9.777346e-07  9.790544e-07        4.665091e-07
1028       0.000002  9.838077e-07      9.806185e-07  9.742974e-07        4.674372e-07
2000       0.000003  1.712075e-06      1.721355e-06  1.577153e-06        6.195382e-07
9128       0.000005  7.107405e-06      7.102972e-06  5.746576e-06        1.442058e-06
10000      0.000005  7.793760e-06      7.765270e-06  6.186172e-06        1.514019e-06
100000     0.000033  7.557200e-05      7.560249e-05  5.644813e-05        1.773984e-05
501337     0.000149  3.772953e-04      3.771005e-04  2.795946e-04        8.543269e-05
1000000    0.000317  7.667693e-04      7.629492e-04  5.719898e-04        1.880772e-04
1234567    0.000410  9.999941e-04      9.999374e-04  7.573595e-04        3.373861e-04
10000000   0.004814  8.487002e-03      8.473639e-03  6.737079e-03        5.045253e-03
100000000  0.048170  8.546364e-02      8.547800e-02  6.795772e-02        5.040893e-02


```


scaling


Suggestions for improvements are welcome. (Just noticed that the zeros could be a `np.empty` and then a zero fill after the assignment over tile space! Might be quicker?!)

**Comment by seibert** [comment]
Is this code interactingly strangely with parfors?  Seeing these test two failures in Travis CI:

```
======================================================================
ERROR: test_kmeans (numba.tests.test_parfors.TestParfors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 559, in test_kmeans
    decimal=1)
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 462, in check
    self.check_parfors_vs_others(pyfunc, cfunc, cpfunc, *args, **kwargs)
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 138, in check_parfors_vs_others
    njit_output = cfunc.entry_point(*copy_args(*args))
ZeroDivisionError: division by zero
======================================================================
FAIL: test_pi (numba.tests.test_parfors.TestParfors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 516, in test_pi
    self.check(test_impl, 100000, decimal=1)
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 462, in check
    self.check_parfors_vs_others(pyfunc, cfunc, cpfunc, *args, **kwargs)
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 143, in check_parfors_vs_others
    np.testing.assert_almost_equal(njit_output, py_expected, **kwargs)
  File "/home/travis/miniconda3/envs/travisci/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 581, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 1 decimals
 ACTUAL: 0.00088
 DESIRED: 3.1446
```

**Comment by stuartarchibald** [comment]
@seibert, yes, a spectacularly bad interaction, I'll take a look!

**Comment by seibert** [comment]
Yeah, I think it makes sense to add a couple tests after this one: 

https://github.com/numba/numba/blob/master/numba/tests/test_array_methods.py#L693

* Test with > 500 elements.  The current array sum tests don't even fill one tile and skip much of the body of the implementation
* Strided array
* Check that type promotion does what is expected (for boolean vs non-boolean array)

**Comment by stuartarchibald** [comment]
Closing for now, what is in current NumPy needs a re-review to ensure applicability of such a change.

**Pull request closed without merging**
