### PR TITLE
decorator for methods in jitclasses

### PR DESCRIPTION
**Pull request by sklam**
Add `@jitmethod` decorator for passing signatures and compiler options into methods of jitclasses.

This is a preliminary support for decorating methods of a jitclass to supply additional options to the compiler.  The `@jitmethod` decorator simply passes all the input to `@jit` under-the-hood.  When function signatures are given, users must not provide the type for `self`, which is resolved later when the method is bound to the jitclass.  (In fact, it is impossible to specify the type of `self`.)

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Will this allow to to use jitclass method without holding the GIL ?

**Comment by seibert** [comment]
that is the plan, but I don't know if this PR supports that yet

**Comment by seibert** [comment]
Would the syntax for the explicit signature be less confusing if we had the user put some placeholder in for the `self` type?  Skipping the argument in the signature seems like it will lead more confusion down the road.

**Comment by MatthieuDartiailh** [comment]
Out of curiosity is anything holding this back ? Being able to force nopython=True on jitmethod would be useful.

**Comment by sklam** [comment]
Close for now due to lack of progress.
There's question in terms of the spelling for self type.
And a bigger issue in the question of caching jit methods.

**Pull request closed without merging**
