### PR TITLE
Fix the doc build: docutils 0.18 not compatible with pinned sphinx

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Context: Current builds are failing, e.g. https://github.com/numba/numba/pull/7359 as the docs cannot build without warning. Error is:
```
# Ensure the README is correctly formatted
if [ "$BUILD_DOC" == "yes" ]; then rstcheck README.rst; fi
WARNING: while setting up extension sphinx.addnodes: node class 'meta' is already registered, its visitors will be overridden
# Ensure that the documentation builds without warnings
pushd docs
if [ "$BUILD_DOC" == "yes" ]; then make SPHINXOPTS=-W clean html; fi
~/work/1/s/docs ~/work/1/s
rm -rf _build/*
sphinx-build -b html -d _build/doctrees  -W source _build/html
Running Sphinx v2.4.4

Warning, treated as error:
node class 'meta' is already registered, its visitors will be overridden
Makefile:53: recipe for target 'html' failed
make: *** [html] Error 2
##[error]Bash exited with code '2'.
Finishing: Test
```

xref: https://github.com/sphinx-doc/sphinx/issues/9841

**Comment by gmarkall** [comment]
I will approve this if the build is green.

**Review by gmarkall — APPROVED** [review]
LGTM!

**Review by esc — APPROVED** [review]
LGTM!

**Pull request merged**
