### PR TITLE
CUDA: Don't add device kwarg for jit registry

### PR DESCRIPTION
**Pull request by gmarkall**
The device kwarg has no effect - the need for a device function is inferred by logic in the dispatcher. Therefore, we no longer need to get in front of the `cuda.jit` decorator to insert it for the JIT registry.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. I think this makes sense as a CUDA-dispatcher-to-CUDA-dispatcher call would imply the callee is a device function and `CUDADispatcher::get_call_template()` handles this.

**Comment by sklam** [comment]
BFID: `numba_smoketest_cuda_yaml_198`

**Comment by stuartarchibald** [comment]
> BFID: `numba_smoketest_cuda_yaml_198`

Passed.

**Pull request merged**
