### PR TITLE
pin setuptools to < 65 and switch from mamba to conda on RTD

### PR DESCRIPTION
**Pull request by esc**
This is a combination #8351 #8352 and #8353 -- in order to get docs building on `main` again.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by esc** [comment]
Note: this should probably be path of 0.56.1 too, to make sure we can get a clean docs build there too.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. Assuming the docs builds now pass, this can be merged.

**Comment by stuartarchibald** [comment]
> Note: this should probably be part of 0.56.1 too, to make sure we can get a clean docs build there too.

I agree, it's a good idea to preempt the issue for 0.56.1.

**Review by gmarkall — APPROVED** [review]
gpuCI-related changes look good to me.

**Comment by esc** [comment]
With #8356 -- we prefer that PR over this one. Hence this is no longer included in the 0.56.1 milestone.

**Pull request merged**
