### PR TITLE
Adapt Travis config for Trusty beta

### PR DESCRIPTION
**Pull request by pitrou**
This avoids having to install and activate a gcc backport. One other question is whether there are more resources allocated, i.e. are the builds faster?

See https://docs.travis-ci.com/user/trusty-ci-environment/

### CODE REVIEW

**Comment by pitrou** [comment]
Actually, looks like builds are slower this way.

**Comment by pitrou** [comment]
And now that regular builds have become even slower, these ones end up faster. It's probably worth waiting for a couple days and trying again :-)

**Comment by seibert** [comment]
Now that parallel testing is fixed again, it is worth merging master into this PR and seeing how fast things are.

**Comment by seibert** [comment]
Runtime looks about the same (within normal variance) of old Travis-CI config.  Not having to install the gcc backport is a nice improvement (and this is the future of Travis-CI anyway), so we might as well get on the beta train.

**Pull request merged**
