### PR TITLE
Fixes a bug in the relabelling logic in literal_unroll.

### PR DESCRIPTION
**Pull request by stuartarchibald**
The generated switch table IR must be immediatedly labelled with
respect to the user function IR else there may be label collisions
between labels in the switch table and non-local jumps in the
versioned loop body.

### CODE REVIEW

**Comment by seibert** [comment]
Does this need a new test?

**Comment by seibert** [comment]
internal CI: `numba_smoketest_cpu_4`

**Comment by stuartarchibald** [comment]
I'm not sure how to test it, the collision was between the bytecode offsets in the generated switch table IR and the non-local jumps in the versioned loop body, the trigger happened to be doing:
```
./runtests.py numba.tests.test_mixed_tuple_unroller.TestConstListUnroll.test_01  numba.tests.test_mixed_tuple_unroller.TestMixedTupleUnroll.test_01 
```
on Python 3.8. The first test having incremented this: https://github.com/numba/numba/blob/77cb53ba8966a38bfbd3413559e4f04b12812535/numba/ir_utils.py#L39 precisely the right number of times to cause a collision when added to the byte offsets present in the second test.

**Comment by seibert** [comment]
CI passed

**Pull request merged**
