### PR TITLE
Recognise future.types.newrange.newrange as range_type

### PR DESCRIPTION
**Pull request by gmarkall**
This is intended to fix the problem described in issues #972 and #1040, and also described in https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/TQa9cwYZiIs

### CODE REVIEW

**Comment by pitrou** [comment]
I see the following in numba.utils:

```
try:
    import builtins
except ImportError:
    import __builtin__ as builtins
```

Should we straighten it with an explicit Python 3 check? AFAIU, ``builtins`` is created by the ``future`` module on Python 2.

**Comment by pitrou** [comment]
Also, it seems this could be factored out with ``numba.utils.RANGE_ITER_OBJECTS``.

**Comment by gmarkall** [comment]
> Should we straighten it with an explicit Python 3 check? 

I think this would fix the original issue as well - the reason for `range` getting looked up as `future.types.newrange.newrange` is because `builtins` from the future package is getting imported as `numba.utils.builtins`, which is then used by the bytecode interpreter to look up builtins like `range`.

**Comment by pitrou** [comment]
Do we also want to support the ``future`` module's own ``range`` wrapper?

**Comment by gmarkall** [comment]
I don't know whether we want to, but we could add support for it to this PR. I note that range object has some methods we don't seem to support even in Python 3 (`start`, `stop`, `count`) etc, which we also wouldn't be supporting for the `future` `range` wrapper, so it wouldn't be inconsistent with what we already do.

**Comment by gmarkall** [comment]
I've added back support for the `future` module's `range`.

**Pull request merged**
