### PR TITLE
[WIP] add np's flip functionality

### PR DESCRIPTION
**Pull request by rteja1113**

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@rteja1113 thanks for your work on this patch, was just wondering about its current status? Seems like the implementation is there but it could do with some tests writing?

**Comment by rteja1113** [comment]
> @rteja1113 thanks for your work on this patch, was just wondering about its current status? Seems like the implementation is there but it could do with some tests writing?

Yes, I need to write tests. I'll finish that once I get home :)

**Comment by stuartarchibald** [comment]
> > @rteja1113 thanks for your work on this patch, was just wondering about its current status? Seems like the implementation is there but it could do with some tests writing?
> 
> Yes, I need to write tests. I'll finish that once I get home :)

Ah great, thanks very much.

**Comment by stuartarchibald** [comment]
Just checking in on the state of this PR. @rteja1113 was wondering if you have time to address the above, if not, don't worry, one of the core developers can take over to do the fixes. Thanks.

**Comment by rteja1113** [comment]
Hi @stuartarchibald,

Unfortunately, I won't be able to finish this PR. I realized that I need to
know more about the numba and I don't want to slow you guys down.
Sorry about that.

Thanks

**Comment by stuartarchibald** [comment]
@rteja1113 no problem, thanks for letting us know. If you think there's anything we can do to help speed up knowing enough about Numba to feel more comfortable writing PRs like this please do say, feedback is always welcome. Also, there's a guide to using `@overload` now [in the docs](http://numba.pydata.org/numba-doc/latest/extending/overloading-guide.html).

**Comment by stuartarchibald** [comment]
Closing, patches forwarded to https://github.com/numba/numba/pull/5313 with view to merge as part of that PR.

**Pull request closed without merging**
