### PR TITLE
ABC the target descriptor and make consistent throughout.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. Needed to enforce the interface for `@intrinsic` template
`generic` methods.

### CODE REVIEW

**Review by gmarkall — APPROVED** [review]
This passes tests locally for me with hardware and the changes seem to make sense.

We may still encounter issues with the typing and target contexts existing per-dispatcher in the CUDA target (which is presently needed in CUDA because things like the fast math flag are attached to the context) but being class members in the CPU target (as I understood from an earlier OOB conversation with @stuartarchibald ), but this is a move in the right direction.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_yaml_48`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_yaml_48`.

This passed.

**Comment by stuartarchibald** [comment]
> This passes tests locally for me with hardware and the changes seem to make sense.

Thanks for the review @gmarkall 

> We may still encounter issues with the typing and target contexts existing per-dispatcher in the CUDA target (which is presently needed in CUDA because things like the fast math flag are attached to the context) but being class members in the CPU target (as I understood from an earlier OOB conversation with @stuartarchibald ), but this is a move in the right direction.

Thanks for noting this, definitely something to investigate as part of the next refactor.

**Review by sklam — APPROVED** [review]
LGTM

**Pull request merged**
