### PR TITLE
[WIP] Don't visit already checked successors

### PR DESCRIPTION
**Pull request by gmarkall**
Just making the PR to try a (very tentative) fix for #6186 on CI.

### CODE REVIEW

**Comment by gmarkall** [comment]
The fail is due to #5973, unrelated to this PR.

@sklam what do you think of the changes?

**Comment by sklam** [comment]
@gmarkall, the changes make sense.

**Comment by sklam** [comment]
i'll try to get a reproducer in as part of the test

**Comment by sklam** [comment]
I have built upon this PR in https://github.com/numba/numba/pull/6195.

**Comment by stuartarchibald** [comment]
@gmarkall this ok to close? Thanks for working on the fix.

**Comment by gmarkall** [comment]
Sure, please do close it (can't seem to do that on the github android app)

**Comment by gmarkall** [comment]
Never mind, found the close button hiding in some pull up menu.

**Pull request closed without merging**
