### PR TITLE
Fix parallel test

### PR DESCRIPTION
**Pull request by sklam**
Multiprocessing test is broken on master.  All tests are categorized as serial.  This fixes it.

### CODE REVIEW

**Comment by pitrou** [comment]
@stefanseefeld, would you like to comment on this?

**Comment by stefanseefeld** [comment]
These changes look good. (I assume they were needed to fix issues with the hsa test suite ?)

**Comment by sklam** [comment]
@stefanseefeld, the changes is needed because everything were running in serial all the time.  The others are fixes because there were undefined symbols and PEP8.

**Comment by stefanseefeld** [comment]
Hmm, I wonder how that happened. When I worked on this code initially, it did run (the non-SerialSuite tests) in parallel. Not sure what specific change broke that.
But anyhow, I'm glad to see it work now. :-)
Thanks for the fix !

**Pull request merged**
