### PR TITLE
Additional math functions

### PR DESCRIPTION
**Pull request by pitrou**
This PR adds math.ldexp() and math.frexp().
Other functions in Python 3 are still unsupported: gamma(), lgamma(), erf(), erfc(). Supporting them involves copying a bunch of C code (because of Windows).

### CODE REVIEW

**Comment by seibert** [comment]
Looks great!  Very excited to see erf().

**Comment by Juanlu001** [comment]
Once the `gamma` function has been added, do you have the intention of adding `factorial` too? I needed it recently and implemented it myself, but it fails for large integers:

https://github.com/Pybonacci/poliastro/blob/69c82e6bc1c9188c81470db8a7a4646c7b913ea9/poliastro/math.py

**Comment by pitrou** [comment]
We do not handle anything bigger than int64, so that wouldn't solve your problem.

**Comment by Juanlu001** [comment]
Rather than providing a function that works for bigger integers as well, I was wondering if you are going to provide `math.factorial` too as a function working only on integers, with the known limitations. Naturally it is a cosmetic issue because I can ditch my `factorial` implementation and just use `gamma` one numba 1.8 is out.

**Comment by pitrou** [comment]
We could indeed (and probably will, at some point) provide that. Of course, rewriting factorial() by hand is pretty trivial (much more so than gamma()) :-)

**Comment by Juanlu001** [comment]
Very true :) Greetings for the great work, every numba release is more exciting than the previous one! :+1:

**Pull request merged**
