### PR TITLE
Support ir.Global/FreeVar in find_const()

### PR DESCRIPTION
**Pull request by ehsantn**
As title.

### CODE REVIEW

**Comment by ehsantn** [comment]
@seibert I know it's late but could this PR go to 0.44 since it is very simple and fixes potential bugs?

**Comment by stuartarchibald** [comment]
Thanks for the PR. I think this impacts dead branch pruning, and the effect of this change on that pass (which is on by default) is at present unquantified. I imagine the result will be that constants are baked in in the form of pruned branches? I am of the view, having seen what happens when branch pruning goes wrong, that this need a lot of testing and probably some time to incubate in development builds so the impact can be assessed.

**Comment by ehsantn** [comment]
Yes, the results will be baked in (similar to infer_constant methods used in other places). Ok.

**Comment by sklam** [comment]
This PR is waiting for:

- [ ] add tests around branch-pruning

**Comment by stuartarchibald** [comment]
@ehsantn here's some tests https://github.com/stuartarchibald/numba/commit/152da8af179bdba852726204fe05541b06a80522 which check branch pruning. Once added I think this can be re-reviewed. Thanks.

**Comment by stuartarchibald** [comment]
@sklam please could you review, this now contains code I wrote, thanks.

**Comment by ehsantn** [comment]
Thank you @stuartarchibald . I added the tests and merged master to fix conflicts.

**Pull request merged**
