### PR TITLE
Fix liveness for remove dead of parfors (and other IR extensions)

### PR DESCRIPTION
**Pull request by ehsantn**

### CODE REVIEW

**Comment by sklam** [comment]
The error from `test_alias_parfor_extension` without the fix in `ir_utils.py` looks very much like the kind of errors I am seeing in my SSA attempt.  And it would make sense because SSA will create many aliases as new versions of a variable is created.

**Comment by ehsantn** [comment]
Makes sense. One potentially related issue might be copy propagation not fully working since SSA generates extra assignments.

**Comment by sklam** [comment]
The test is failing on windows and 32-bit linux.  It needs a skip test.

**Comment by ehsantn** [comment]
done.

**Comment by stuartarchibald** [comment]
Thanks for the patch. I've checked this manually and I'm of the view that the fix makes sense. 

@sklam I recommend merge unless you have any other thoughts related to SSA?

**Pull request merged**
