### PR TITLE
Add generated_jit decorator

### PR DESCRIPTION
**Pull request by pitrou**
This adds the `@generated_jit` decorator as discussed.

### CODE REVIEW

**Comment by seibert** [comment]
How will this functionality interact with serialization?

**Comment by pitrou** [comment]
I should try that. It should work, since the Dispatcher's infrastructure is basically reused, but as long as it's not tested...

**Comment by pitrou** [comment]
Actually, serialization may require a little hackery...

**Comment by seibert** [comment]
Once we are sure everything is stable after the LLVM 3.7 merge, I think we can merge this.

**Comment by seibert** [comment]
OK, I think we are ready to merge.

**Pull request merged**
