### PR TITLE
Update cuda.local.array to clarify "simple constant expression" (e.g. no NumPy ints)

### PR DESCRIPTION
**Pull request by sgbaird**
Update the docs to clarify that NumPy ints aren't supported when defined as global variables and passed into cuda.local.array.

## Reference an existing issue

#7314

### CODE REVIEW

**Comment by sgbaird** [comment]
The checks are passing now.

**Review by esc — APPROVED** [review]
I looked at #7314 and then at this. It appears to be fine.

Thank you for the patch!

**Review by esc — DISMISSED** [review]
After OOB discussion with @gmarkall -- it seems a few more things could be added. Comments to follow soon, sorry for the confusion.

**Review by gmarkall — CHANGES_REQUESTED** [review]
Thanks for the PR! I think the suggested wording is a bit misleading, in that it doesn't quite characterize exactly what a "simple constant expression" is. (Note that it's actually quite hard to define exactly due to the behavior of constant propagation, etc).

I would suggest stating that a simple constant expression includes, but is not limited to:

* A literal (e.g. `10`)
* A local variable whose right-hand side is a literal or a simple constant expression (e.g. `shape`, where `shape` is defined earlier in the function as `shape = 10`)
* A global variable that is defined in the jitted function's globals by the time of compilation (e.g. `shape`, where `shape` is defined using any expression at global scope).

where the definition results in a Python `int` (i.e. not a NumPy scalar or other scalar / integer-like type).

**Comment by gmarkall** [comment]
@sgbaird Did you want to revise this shortly to try to get it into the 0.55 release in early November? Or shall we bump the target to 0.56 to give a bit more time?

**Comment by stuartarchibald** [comment]
Just checking in on the state of this PR. @sgbaird was wondering if you have time to address the changes above, if not, it's no problem, one of the core developers can adopt the patch as needed. Many thanks.

**Review by gmarkall — CHANGES_REQUESTED** [review]
Many thanks for the update - I think the wording is fine, but there's some issues with the rendering - I think the intention was for the changes to render as a numbered list, but they come out all as one paragraph. Also, there's a backtick missing which causes a problem rendering some of the code as code. Example shown:

image

**Comment by sgbaird** [comment]
@gmarkall good catch. I think this should be resolved now

image

image

**Review by gmarkall — APPROVED** [review]
Looks good. Many thanks for your patience on this one!

**Pull request merged**
