### PR TITLE
Add performance tips documentation.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This adds documentation of the most common flags associated with
achieving higher levels of performance from Numba compiled code.

### CODE REVIEW

**Comment by seibert** [comment]
This is awesome!  As soon as this is live, I want to make sure we promote this page in the docs as much as possible.

**Comment by ehsantn** [comment]
Parallel section could be before fastmath :)

**Comment by seibert** [comment]
I think the fastmath will be applicable to a wider range of situations, but I understand the preference.  :)

**Comment by seibert** [comment]
Ready to merge, pending #2748

**Pull request merged**
