### PR TITLE
Comments out the appveyor badge

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title, do not need to render this right now.

### CODE REVIEW

**Comment by seibert** [comment]
I would go one step further and simply remove it.  We aren't going back to Appveyor any time soon.

**Comment by stuartarchibald** [comment]
hmmm, the config got left in "just in case", time to remove that too perhaps?

**Comment by seibert** [comment]
yeah, we can remove the top level appveyor file as well.

**Comment by seibert** [comment]
Looks good!

**Pull request merged**
