### PR TITLE
Continuation of #4588

### PR DESCRIPTION
**Pull request by stuartarchibald**
Open for CI.

### CODE REVIEW

**Comment by seibert** [comment]
tagging #4588 in comments for Github cross-links (it doesn't seem to notice the ref in the title)

**Comment by stuartarchibald** [comment]
> tagging #4588 in comments for Github cross-links (it doesn't seem to notice the ref in the title)

thanks!

**Comment by seibert** [comment]
This PR seems to be failing one test:

https://dev.azure.com/numba/numba/_build/results?buildId=3698&view=logs&j=eb149424-352d-52d9-b16d-aeffaad6858a&t=cdac5993-002e-5764-1ca7-e646ebe78687&l=412

**Comment by stuartarchibald** [comment]
Whilst this PR ostensibly comes from me, @DrTodd13 did all the work over on the IntelLabs fork https://github.com/IntelLabs/numba/commits/continue4588, the patches here are just a result of some git surgery. The change set itself looks good to me, thanks for the fix @DrTodd13.

**Comment by seibert** [comment]
looks like this is passing the parfors tests everywhere on Azure, so I think this is ready to merge.

**Pull request merged**
