### PR TITLE
Make user facing error string use abs path not rel.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This fixes a bug that appeared on windows where the installation
and CWD were on different drives and as a result `os.path.relpath`
raises a ValueError. `os.path.abspath` will produce a longer but
more OS situation tolerant string.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Farm build ID `numba_smoketest_cuda_26`.

**Comment by stuartarchibald** [comment]
Farm build ID `numba_smoketest_cuda_26`, failed on 5c3274e.

New ID `numba_smoketest_cuda_27`.

**Comment by stuartarchibald** [comment]
`numba_smoketest_cuda_27` passed.

**Comment by seibert** [comment]
Looks good!

**Pull request merged**
