### PR TITLE
Fix some spelling typos

### PR DESCRIPTION
**Pull request by bwignall**
Should be non-semantic.

Uses https://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings/For_machines to find likely typos.

### CODE REVIEW

**Comment by esc** [comment]
@bwignall thanks for submitting this, the fixes look good but seem to have caused some followup flake8 errors.

**Comment by bwignall** [comment]
Thank you for highlighting that. I have added/squashed a commit that should handle that (a local flake8'ing showed the numba/tests/test_typedlist.py errors fixed and nothing in the other instances I checked).

**Comment by esc** [comment]
@bwignall thanks for submitting the fixes, they do look good and seem to fix the CI errors with flake8 we saw previously!

Once small note: within the Numba project we tend to avoid using squash/rebase and force pushes after PRs have been reviewed so that we can track what happened during the review process. It isn't a big deal in this case, but please do keep that in mind should you decide to contribute more to Numba in future.

**Comment by bwignall** [comment]
@esc , I am sorry for that. Some, but not all, projects prefer squashing, so I should not have assumed beforehand. I will try to keep this in mind in the future. Thank you!

**Comment by esc** [comment]
@bwignall no problem, thanks for being considerate, we appreciate it.

**Pull request merged**
