### PR TITLE
Add  `pinned` and `as_cuda_array` to cudasim mode

### PR DESCRIPTION
**Pull request by tornikeo**
I'm working with a small [cuda kernel project](https://github.com/tornikeo/cosine-similarity), and when testing my code with numba sim, I see that `cuda.pinned` has different arglist (single arg, instead of variadic *args) in these two modes for no good reason.

So, here's a small tweak to make it consistent.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
Did this cause an error in your project? Or is this an aesthetic change only?

**Comment by tornikeo** [comment]
@gmarkall  Not an error per se, but it forces me to monkeypatch the `cuda.pinned`. In a real run, I always pass several arrays in pinned. When I do testing, the pinned just errors out because of this. I'd expect a simulator to follow the real thing closely as possible (in syntax and everything).

**Comment by tornikeo** [comment]
@gmarkall anything I should do for "Check Release Notes" failing?

**Comment by gmarkall** [comment]
@tornikeo If you'd like a mention of your fix in the release notes, you could add a release note snippet RST as documented in: https://numba.readthedocs.io/en/stable/developer/contributing.html#release-notes - however, as this is a small change, I'm happy if you'd prefer me to just mark this to skip the release notes check, and then I don't think there's anything further you need to do - let me know what you'd prefer.

**Comment by tornikeo** [comment]
@gmarkall  Ah, it's a tiny change. No need to pollute the release notes with this. Thanks! :+1:

**Comment by tornikeo** [comment]
@gmarkall  somehow function `as_cuda_array` was missing from `numba/cuda/simulator/cudadrv/devicearray.py`. Ran into same issue when trying to test numba code on a gpuless machine. Added that function too.

**Pull request closed without merging**
