### PR TITLE
Testing NumPy 1.23 RC 3 on public CI.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. Do not merge.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Looks like this has the same errors as previously found with 1.23rc2:

<details>
<summary>Details:</summary>

```
======================================================================
ERROR: test_gpu_array_zero_length (numba.cuda.tests.cudapy.test_array.TestCudaArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/cuda/tests/cudapy/test_array.py", line 18, in test_gpu_array_zero_length
    dx = cuda.to_device(x)
  File "/home/vsts/work/1/s/numba/cuda/simulator/cudadrv/devicearray.py", line 281, in to_device
    sentry_contiguous(ary)
  File "/home/vsts/work/1/s/numba/cuda/simulator/cudadrv/devicearray.py", line 261, in sentry_contiguous
    core = array_core(ary)
  File "/home/vsts/work/1/s/numba/cuda/simulator/cudadrv/devicearray.py", line 241, in array_core
    return ary[tuple(core_index)]
IndexError: index 0 is out of bounds for axis 0 with size 0

======================================================================
ERROR: test_assign_empty_slice (numba.cuda.tests.cudapy.test_slicing.TestCudaSlicing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/cuda/tests/cudapy/test_slicing.py", line 33, in test_assign_empty_slice
    arr[:] = cuda.to_device(a)
  File "/home/vsts/work/1/s/numba/cuda/simulator/cudadrv/devicearray.py", line 281, in to_device
    sentry_contiguous(ary)
  File "/home/vsts/work/1/s/numba/cuda/simulator/cudadrv/devicearray.py", line 261, in sentry_contiguous
    core = array_core(ary)
  File "/home/vsts/work/1/s/numba/cuda/simulator/cudadrv/devicearray.py", line 241, in array_core
    return ary[tuple(core_index)]
IndexError: index 0 is out of bounds for axis 0 with size 0

======================================================================
ERROR: test_array_view (numba.tests.test_array_methods.TestArrayMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/tests/test_array_methods.py", line 414, in test_array_view
    check(arr, np.float32)
  File "/home/vsts/work/1/s/numba/tests/test_array_methods.py", line 375, in check
    expected = arr.view(dtype)
ValueError: To change to a dtype of a different size, the last axis must be contiguous

======================================================================
FAIL: test_devicearray_view_bad_not_c_contig (numba.cuda.tests.cudadrv.test_cuda_ndarray.TestCudaNDArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/cuda/tests/cudadrv/test_cuda_ndarray.py", line 175, in test_devicearray_view_bad_not_c_contig
    self.assertEqual(
AssertionError: 'To change to a dtype of a different size, the array must be C-contiguous' != 'To change to a dtype of a different size, the last axis must be contiguous'
- To change to a dtype of a different size, the array must be C-contiguous
?                                                ^^ ^         --
+ To change to a dtype of a different size, the last axis must be contiguous
?                                               + ^^^ ^^^

```

</details>


CC @seberg

**Comment by seberg** [comment]
Ah sorry, the first time around, I thought you had decided there were no important issues for me to dig into.

The first two are because `arr.strides[0] == 0` when the array is empty now, this is due to https://github.com/numpy/numpy/pull/21477.  I am not sure if these are just testing machinery to begin with?  Because while that is a change in behavior it was always possible to get such arrays before.  Maybe an approach like:
```diff
diff --git a/numba/cuda/simulator/cudadrv/devicearray.py b/numba/cuda/simulator/cudadrv/devicearray.py
index 12c68df94..1730fcea7 100644
--- a/numba/cuda/simulator/cudadrv/devicearray.py
+++ b/numba/cuda/simulator/cudadrv/devicearray.py
@@ -236,8 +236,8 @@ def array_core(ary):
     if not ary.strides:
         return ary
     core_index = []
-    for stride in ary.strides:
-        core_index.append(0 if stride == 0 else slice(None))
+    for dim in ary.shapes:
+        core_index.append(0 if dim == 0 else slice(None))
     return ary[tuple(core_index)]
```
but since I suspect it is testing, I guess you likely also ensured `0` as stride (e.g. using `broadcast_to`, so maybe should keep that check as well.

The other two seem due be due to https://github.com/numpy/numpy/pull/20722 I think the problematic part here is probably the removal of the long standing deprecation warning:
```
                        "Changing the shape of an F-contiguous array by "
                         "descriptor assignment is deprecated. To maintain the "
                         "Fortran contiguity of a multidimensional Fortran "
                         "array, use 'a.T.view(...).T' instead") < 0) {
```

**Comment by stuartarchibald** [comment]
> Ah sorry, the first time around, I thought you had decided there were no important issues for me to dig into.

Thanks for taking a look @seberg, I had indeed previously made a guess that the issues were likely things Numba had to handle opposed to something specifically broken in NumPy, and I still think that's the case. This is essentially just confirming that 1.23rc3 is in the same state as 1.23rc2, I'll try and be more clear about any concerns next time around, apologies for any confusion.

> The first two are because `arr.strides[0] == 0` when the array is empty now, this is due to [numpy/numpy#21477](https://github.com/numpy/numpy/pull/21477). I am not sure if these are just testing machinery to begin with?

`numba.cuda.simulator` is a simulator for Numba's behaviour on CUDA devices. It's used in debugging and testing.

> Because while that is a change in behavior it was always possible to get such arrays before. Maybe an approach like:
>
> ```diff
> diff --git a/numba/cuda/simulator/cudadrv/devicearray.py b/numba/cuda/simulator/cudadrv/devicearray.py
> index 12c68df94..1730fcea7 100644
> --- a/numba/cuda/simulator/cudadrv/devicearray.py
> +++ b/numba/cuda/simulator/cudadrv/devicearray.py
> @@ -236,8 +236,8 @@ def array_core(ary):
>      if not ary.strides:
>          return ary
>      core_index = []
> -    for stride in ary.strides:
> -        core_index.append(0 if stride == 0 else slice(None))
> +    for dim in ary.shapes:
> +        core_index.append(0 if dim == 0 else slice(None))
>      return ary[tuple(core_index)]
> ```
> 
> but since I suspect it is testing, I guess you likely also ensured `0` as stride (e.g. using `broadcast_to`, so maybe should keep that check as well.
> 
> EDIT: I relaly suspect you must keep it as well. I expect the code may just not be capable to deal with 0-sized dimensions when they are broadcast, although maybe the "broadcasting" just drops out correctly at the end due to the size (after all the result will also be empty in the end).

I see, thanks. We'll have to take a look at the code and try and work around it. CC @gmarkall (code owner for the CUDA target).

> The other two seem due be due to [numpy/numpy#20722](https://github.com/numpy/numpy/pull/20722) I think the problematic part here is probably the removal of the long standing deprecation warning:
> 
> ```
>                         "Changing the shape of an F-contiguous array by "
>                          "descriptor assignment is deprecated. To maintain the "
>                          "Fortran contiguity of a multidimensional Fortran "
>                          "array, use 'a.T.view(...).T' instead") < 0) {
> ```

I agree, I'm hoping these will be too hard to fix.

Thanks again for your help on this @seberg.

**Comment by stuartarchibald** [comment]
Closing, https://github.com/numba/numba/pull/8206 replaces as it's testing the released version.

**Pull request closed without merging**
