### PR TITLE
Skip the overhead of negative index tests when using an unsigned index

### PR DESCRIPTION
**Pull request by pitrou**
This improves performance when using indirect indexing, as reported in http://article.gmane.org/gmane.comp.python.numba.user/362

### CODE REVIEW

**Comment by shoyer** [comment]
Just ran this through the performance example in my newsgroup post and this makes the performance with unsigned integers just as fast as for signed integers with the bounds check. Thanks!

**Comment by seibert** [comment]
as a side task, we should add a benchmark for this case to https://github.com/numba/numba-benchmark

**Comment by pitrou** [comment]
> we should add a benchmark for this case

Do you think the grouped sum example is representative enough, or can you think of something more realistic?

**Comment by seibert** [comment]
I think that example would be good.  It's fairly short but highlights the issue.

**Comment by seibert** [comment]
Is this still WIP?

**Comment by pitrou** [comment]
I've added the benchmark in https://github.com/numba/numba-benchmark/commit/ef41bf153dcceaf4de2995361f1724562feead51

**Comment by pitrou** [comment]
Not really WIP, no. I thought that we might review the other uses of indexing but we can just as well merge this PR as is.

**Comment by seibert** [comment]
Looks like this needs a merge with master again.

**Comment by sklam** [comment]
For future reference, `llvm.assume` (llvm 3.6 feature) may help as well.

**Pull request merged**
