### PR TITLE
Fix #3027 - Numba reassigns sys.stdout

### LINKED ISSUE #3027: Numba reassigns sys.stdout
## Reporting a bug

- [*] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [*] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```
import sys
import numba


@numba.njit
def f0(a,b):
  return a+b


@numba.njit
def f1(begin1, end1, begin2, end2):
  if begin1 > begin2: return f1(begin2, end2, begin1, end1)
  return end1 + 1 >= begin2

sys.api_version, sys.stdout = 12345, None


print>>sys.stderr, sys.api_version, sys.stdout  # 12345, None
f0(0,1)      # Does not reassign stdout
print>>sys.stderr, sys.api_version, sys.stdout  # 12345, None
f1(0,1,2,3)  # Reassigned stdout
print>>sys.stderr, sys.api_version, sys.stdout  # 12345, file object


assert sys.api_version == 12345  # Pass. From which we can infer reload was not called
assert sys.stdout is None  # Fail. sys.stdout was assigned and not reset.
```

I came across this because it breaks the IntelliJ unittest runner (which sets sys.stdout before numba), like so: https://youtrack.jetbrains.com/issue/PY-23940 , which causes and exception after running unit tests.

It would be more friendly if numba didn't poke at sys.

Seen in: numba==0.38.1

### PR DESCRIPTION
**Pull request by stuz5000**
Fixes 3027 by using a new colorama library.

Added a unittest to check that compilation leaves sys.stdout/err as they were.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for investigating this and producing a PR. I think that whilst this solves the problem it also creates a dependency for Numba on `colorama` for pip users. As Numba is often used as core computational package having the absolute minimal number of dependencies is critical. It should be noted that the `colorama` package is entirely optional and is employed purely to enhance the appearance of error messages. I therefore think that perhaps an approach to resolving this issue in a manner compatible with minimal dependencies would be:
 * To add a version check at the time there is an attempted import of `colorama`.
https://github.com/numba/numba/blob/5d981560ed4e17bc969d2246de95e5755d88fba6/numba/errors.py#L85-L92
 * If the version being imported is known to have the problems outlined in #3027 then issue a warning to the user that this is the case.

I'm not sure how well adopted it is, but it appears (from a quick search) that pip has a convention of using `optional-requirements.txt` for holding reference to optional packages, perhaps colorama with its specific version could be added there?

Finally, to "fix" the issue with IntelliJ, perhaps either update colorama OR set the env var [NUMBA_DISABLE_ERROR_MESSAGE_HIGHLIGHTING](http://numba.pydata.org/numba-doc/dev/reference/envvars.html#envvar-NUMBA_DISABLE_ERROR_MESSAGE_HIGHLIGHTING) ? The upcoming release will let you do that permanently for a project via a [config file](http://numba.pydata.org/numba-doc/dev/reference/envvars.html#environment-variables).

**Comment by stuartarchibald** [comment]
@stuz5000 I'm going to fix this up so that it gets into the next release and will push the necessary to your branch.

**Comment by stuartarchibald** [comment]
@seibert please could you review? this now contains my code!

**Comment by seibert** [comment]
Looks good!

**Pull request merged**
