### PR TITLE
Add SciPy 2019 talks to docs

### LINKED ISSUE #4895: Numba talks -- scipy 2019
There was 3 Numba related talk at scipy 2019 (one of them is mine):

- https://www.youtube.com/watch?v=-4tD8kNHdXs
- https://www.youtube.com/watch?v=0pUPNMglnaE
- https://www.youtube.com/watch?v=cLpIh8Aiy2w

in case you want to add them to https://numba.pydata.org/numba-doc/latest/user/talks.html

### PR DESCRIPTION
**Pull request by GabrielMajeri**
Adds three videos of talks about numba from SciPy 2019.

Closes #4895

### CODE REVIEW

**Comment by esc** [comment]
@GabrielMajeri many thanks for submitting this and welcome to the Numba project! (GitHub is telling me you are a first-time contributor). I just reviewed your submission and I would recommend to move Stan's talk to the talks section like the other two since it was a 30 min talk in the talks track. Tutorials at SciPy are usually 4h in-depth sessions about a topic.

While you are working on this part of the docs, you might as well include the following 'tutorial' that I gave in Amsterdam last year:

https://www.youtube.com/watch?v=CQDsT81GyS8

**Comment by GabrielMajeri** [comment]
I've moved the talk as indicated and also added the new tutorial to the tutorials section.

**Comment by esc** [comment]
@GabrielMajeri awesome, thank you! LGTM (looks good to me) and RTM (ready to merge).

**Comment by esc** [comment]
@GabrielMajeri the PR has now be labelled as ready-to-merge and will be merged during our daily merge-window.

**Pull request merged**
