### PR TITLE
Release 0.54.0 final patches

### PR DESCRIPTION
**Pull request by sklam**
cherrypicked patches for 0.54.0 final

### CODE REVIEW

**Comment by sklam** [comment]
conda package constraints wise, it's looke like this:

```
numba 0.54.0rc3 np1.16py3.9h2fabc88_g2545cbf_6
----------------------------------------------
file name   : numba-0.54.0rc3-np1.16py3.9h2fabc88_g2545cbf_6.tar.bz2
name        : numba
version     : 0.54.0rc3
build       : np1.16py3.9h2fabc88_g2545cbf_6
build number: 6
size        : 3.6 MB
license     : BSD
subdir      : osx-64
url         : https://conda.anaconda.org/numba/label/ci/osx-64/numba-0.54.0rc3-np1.16py3.9h2fabc88_g2545cbf_6.tar.bz2
md5         : db8ed4f39ca5d442843efee767a9bbf8
timestamp   : 2021-08-18 22:04:42 UTC
constraints :
  - cudatoolkit >=9.2
  - libopenblas !=0.3.6
  - tbb >=2021
  - scipy >=1.0
dependencies:
  - libcxx >=10.0.0
  - llvm-openmp >=10.0.0
  - llvmlite 0.37.*
  - numpy >=1.17,<1.21
  - python >=3.9,<3.10.0a0
  - setuptools



llvmlite 0.37.0rc2 py39_2
-------------------------
file name   : llvmlite-0.37.0rc2-py39_2.tar.bz2
name        : llvmlite
version     : 0.37.0rc2
build       : py39_2
build number: 2
size        : 16.5 MB
license     : New BSD License
subdir      : osx-64
url         : https://conda.anaconda.org/numba/label/ci/osx-64/llvmlite-0.37.0rc2-py39_2.tar.bz2
md5         : d0b491d7a48b16332ad798b34c7a3c56
timestamp   : 2021-08-17 22:30:39 UTC
dependencies:
  - libcxx >=4.0.1
  - python >=3.9,<3.10.0a0
  - zlib >=1.2.11,<1.3.0a0

```

**Comment by sklam** [comment]
BFID: `numba_smoketest_cpu_yaml_40`

**Comment by sklam** [comment]
`numba_smoketest_cpu_yaml_40` is passing everything except aarch64 builds which hasn't complete yet

**Comment by sklam** [comment]
Also triggered a full build+test at `numba_yaml_82`

**Comment by sklam** [comment]
all green

**Comment by sklam** [comment]
On linux the package meta info is:

```
{
  "arch": "x86_64",
  "build": "np1.16py3.9h59fbc97_g2545cbf93_6",
  "build_number": 6,
  "constrains": [
    "tbb >=2021",
    "libopenblas !=0.3.6",
    "cudatoolkit >=9.2",
    "scipy >=1.0"
  ],
  "depends": [
    "libgcc-ng >=7.5.0",
    "libstdcxx-ng >=7.5.0",
    "llvmlite 0.37.*",
    "numpy >=1.17,<1.21",
    "python >=3.9,<3.10.0a0",
    "setuptools"
  ],
  "license": "BSD",
  "name": "numba",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1629332895302,
  "version": "0.54.0rc3"
}
```
It is correctly depending on `gcc>=7.5.0`

**Comment by gmarkall** [comment]
> It is correctly depending on `gcc>=7.5.0`

`libgcc-ng>=7.5.0`, right?

**Comment by sklam** [comment]
Yes, libgcc

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. I've replayed the merge sequence of PRs locally and checked the diff against this branch, the only difference is 2545cbf, which is expected.

**Pull request merged**
