### PR TITLE
CUDA: Remove catch of NotImplementedError in target.py

### PR DESCRIPTION
**Pull request by gmarkall**
Maybe this is more of a question than a PR, but I saw it added in #6948 and I'm not sure what it does. Removing it seems not to cause a problem - all tests still seem to pass without it.

### CODE REVIEW

**Comment by gmarkall** [comment]
From OOB discussion, it seems like this might have initially been added due to #701, which is no longer relevant because NumPy 1.6 is no longer supported, and it also appears that there is no way to trigger the `NotImplementedError` at import time. The PR has been updated to remove the `try` from the CPU target's import of `numba.np.npdatetime` as well.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. I've tried a few ways to trigger the noted exception and it seems like something else is always an issue before a `NotImplementedError` is hit. Further, it appears on inspection that the exception cannot be raised at import time as the control flow required to do so is always in a closure held by a lowering implementation and not actually executed as part of an import sequence.

This patch should get a CPU and CUDA smoke test and assuming both come back fine I think that would further confirm its validity.

Thanks again!

**Comment by stuartarchibald** [comment]
Waiting on merge of https://github.com/numba/numba/pull/7003

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cpu_yaml_30`.
Buildfarm ID: `numba_smoketest_cuda_yaml_62`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_yaml_62`.

Passed.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cpu_yaml_30`.

Passed

**Pull request merged**
