### PR TITLE
Fork-safe thread-safe random generation

### PR DESCRIPTION
**Pull request by pitrou**
This uses the C compiler's (and runtime linker's) support for thread-local variables in order to implement thread-local PRNG state. The state is lazily initialized with system entropy. Also, it is reinitialized after fork().

### CODE REVIEW

**Comment by pitrou** [comment]
All tested buildbots (Windows, OS X, Linux) seem ok.

**Comment by seibert** [comment]
Haven't reviewed this yet, but SUPER excited about this.  :)

**Comment by sklam** [comment]
I am testing whether I can set the random state explicitly.  I find that the first `rnd_set_state` call is getting overridden by the rnd_implicit_state.  

Here's the script I am testing with: https://gist.github.com/sklam/cf1f01b6ea2300ead526500ffabe77b8 .  Notice that the two random sequences mismatch in the first iteration, but they are fine in the second.

**Comment by sklam** [comment]
I think we should expose user utilities to synchronize the random states (among the ones in numba and the ones in python and numpy).  Perhaps, as something like a context manager or an option to `@jit`.   Such feature would be useful in incremental development where parts of the program is still in normal interpreted python.  Probably in another PR.

**Comment by pitrou** [comment]
> I am testing whether I can set the random state explicitly. I find that the first rnd_set_state call is getting overridden by the rnd_implicit_state(). 

Hmm, that seems to be because `numba.targets.random` is imported lazily.

**Pull request merged**
