### PR TITLE
Format project with `black`

### PR DESCRIPTION
**Pull request by max-sixty**
Based on the discussion at https://github.com/numba/numba/pull/9630#issuecomment-2289213439

Not expecting this to be merged immediately, but wanted to show that formatting doesn't have semantic changes.

(one caveat is that the presence of a `pyproject.toml` file can have some impacts in some corner-cases, so would need to confirm)

### CODE REVIEW

**Comment by max-sixty** [comment]
From the linked issue:

> As for the formatting, any PRs that auto-format are usually quite large and contain many false positives, so the usually just go through multiple rounds of reviews and eventually just become stale and are closed -- as this is not the most exciting task and contributors tend to disengage. Also, auto-formatting (and spelling corrections) will often break stuff, so it needs to be done very, very carefully and each lines needs to be reviewed in earnest. Also, any large scale reformatting PRs tend to break in-flight PRs so that causes additional strain.

To clarify, is this a claim that running `black` over the code would change its functionality?

That would be very surprising to me, and would be a bug in `black`.

Assuming it didn't change its functionality, would you support running black over all the code?

**Comment by esc** [comment]
> From the linked issue:
> 
> > As for the formatting, any PRs that auto-format are usually quite large and contain many false positives, so the usually just go through multiple rounds of reviews and eventually just become stale and are closed -- as this is not the most exciting task and contributors tend to disengage. Also, auto-formatting (and spelling corrections) will often break stuff, so it needs to be done very, very carefully and each lines needs to be reviewed in earnest. Also, any large scale reformatting PRs tend to break in-flight PRs so that causes additional strain.
> 
> To clarify, is this a claim that running `black` over the code would change its functionality?



> That would be very surprising to me, and would be a bug in `black`.
> 
> Assuming it didn't change its functionality, would you support running black over all the code?


> From the linked issue:
> 
> > As for the formatting, any PRs that auto-format are usually quite large and contain many false positives, so the usually just go through multiple rounds of reviews and eventually just become stale and are closed -- as this is not the most exciting task and contributors tend to disengage. Also, auto-formatting (and spelling corrections) will often break stuff, so it needs to be done very, very carefully and each lines needs to be reviewed in earnest. Also, any large scale reformatting PRs tend to break in-flight PRs so that causes additional strain.
> 
> To clarify, is this a claim that running `black` over the code would change its functionality?

Thank you for asking and allow me to clarify, I just recalled from memory that large-scale refactoring and reformatting PRs tend not to succeed. The most recent example here:

https://github.com/numba/numba/pull/9606

-- but that was more than just running `black`.

> That would be very surprising to me, and would be a bug in `black`.

Yes, I agree black _should_ not change the semantics.

> Assuming it didn't change its functionality, would you support running black over all the code?

It depends, I am not certain it would be acceptable to merge a PR where not every line has been reviewed by a human. If it can be reviewed -- for example by chunking into smaller PRs -- then maybe, but requires consensus. Also, it would be good to know how many in-flight PRs would be broken  (cause: merge-conflicts) by this change. I suppose it would be feasible to write a script to figure this out? Or is this information perhaps available via GitHub somehow these days? This information may aid the decision making process.

**Comment by max-sixty** [comment]
> It depends, I am not certain it would be acceptable to merge a PR where not every line has been reviewed by a human. If it can be reviewed -- for example by chunking into smaller PRs -- then maybe, but requires consensus from developers. Also, it would be good to know how many in-flight PRs would be broken (cause: merge-conflicts) by this change. I suppose it would be feasible to write a script to figure this out? Or is this information perhaps available via GitHub somehow these days? This information may aid the decision making process.

I think two main options here:
- A big bang. For example, I wrote in the original PR:
  > For formatting: we moved to black in a big bang in xarray, was very successful. The one-off merge conflicts are a bit annoying, but tractable ("merge up to the formatting commit, format with black, merge in the formatting commit"). 
  
  So if people are happy to follow that, then it works well, but it's still some minor disruption.
  
- A gradual transition — given that there doesn't seem to be overwhelming support from the maintainers, how we about take a small folder of files which aren't used much, format with black, and then see how that goes? If it annoys a couple of people who have outstanding PRs then don't expand; if it goes well then expand.
  
  It's harder to provide a couple of lines to update PRs like the previous example, since there's no single commit which formats, but it at least starts a path 
    
  (I had a look whether there's a way of formatting _changes_ with black's `--line-ranges` feature, but I don't think there is, otherwise that would be great to enable and then we'd gradually get the whole repo formatted, like Theseus's ship...)

  
My guess is that if you really need every line of code reviewed by a person, then this might not be feasible. I would respectfully push you a bit whether that's required though — between `black`s testing on thousands of repos, and numba's tests, what's the likelihood of a mistake? If there is a mistake, is a human reading monotonous diffs likely to spot it? How do you trade that off against improving the dev experience?

**Comment by sklam** [comment]
There is an ongoing large scale refactoring to implement a new type system. The effort will touch many files. This is not a good time for repository-wide code formatting.

**Comment by esc** [comment]
It looks like the reformatting broke a bunch of tests unfortunately and most of them seem to have timed out. I am re-running the tests to get a better read on what may have happened.

**Comment by esc** [comment]
> It looks like the reformatting broke a bunch of tests unfortunately and most of them seem to have timed out. I am re-running the tests to get a better read on what may have happened.

It looks like there is some kind of issue with restarting the Azure tests from github.

**Comment by esc** [comment]
Ok, looks like `/azp run` did the trick.

**Comment by esc** [comment]
This was the result of the first run:

Screenshot 2024-08-15 at 08 33 00

**Comment by max-sixty** [comment]
The tests that fail seem to be either `flake8`, since that has a different line length, or some tests that test for line numbers...

**Comment by esc** [comment]
> My guess is that if you really need every line of code reviewed by a person, then this might not be feasible. I would respectfully push you a bit whether that's required though — between `black`s testing on thousands of repos, and numba's tests, what's the likelihood of a mistake? If there is a mistake, is a human reading monotonous diffs likely to spot it? How do you trade that off against improving the dev experience?

I am unconvinced that committing 1000s of lines of modified source code without human review would be considered acceptable behaviour in an era of supply chain attacks.

**Comment by max-sixty** [comment]
I can imagine reasonable ways around the supply chain risk, such as you checking that the diff is only the result of `black`

I would add that once committed, auto-formatted code is much _harder_ to hide mistakes in

**Comment by esc** [comment]
It looks like there are still multiple timeouts across the tests -- since the build of `main` from last night fine --

https://dev.azure.com/numba/numba/_build/results?buildId=17641&view=results

-- I would conjecture that the timeouts are related to the changes introduced by `black`

**Comment by max-sixty** [comment]
> -- I would conjecture that the timeouts are related to the changes introduced by `black`

I agree this seems quite plausible. 

Happy to look more if we think there's a viable path forward conditional on resolving that. Otherwise fine to close if we don't think there is for the moment...

**Comment by esc** [comment]
> > -- I would conjecture that the timeouts are related to the changes introduced by `black`
> 
> I agree this seems quite plausible.
> 
> Happy to look more if we think there's a viable path forward conditional on resolving that. Otherwise fine to close if we don't think there is for the moment...

I think it can be closed, given what @sklam said:

> There is an ongoing large scale refactoring to implement a new type system. The effort will touch many files. This is not a good time for repository-wide code formatting.

Summary: this was a very useful exercise to determine and gather more information about re-formatting the Numba code base with `black`. We learnt that there may be subtle issues like tests failing because they make assumptions about specific lines of code being in a non-relative location and also suspected performance bugs that lead to the public CI timeouts. Overall, it does seem possible to use `black`, but questions about code review and amount of breakage across active pull requests remain unresolved. The changes may need a human review, which is no small feat given the size of the diff -- this needs to be discovered by the developers in an upcoming dev meeting. The amount of breakage can probably be estimated by writing a script to attempt a merge of every active PR and record any merge conflicts encountered. This could help to make an informed decision as to when would be a good time to attempt this re-format in earnest.

@max-sixty I hope this summarizes the findings of this endeavor succinctly and will provide a good foothold for the future, please feel free to add!

**Pull request closed without merging**
