### PR TITLE
Update overview.rst

### PR DESCRIPTION
**Pull request by jftsang**
fix a broken link

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Is the `skip_release_notes` broken for this PR?

**Comment by guilhermeleobas** [comment]
Is the `skip_release_notes` broken for this PR? @sklam

**Comment by gmarkall** [comment]
> Is the `skip_release_notes` broken for this PR? @sklam

I was under the impression you needed to close and open the PR to get the check to actually skip.

**Review by gmarkall — APPROVED** [review]
This does indeed fix the broken link - many thanks!

**Pull request merged**
