### PR TITLE
Refactor carray/farray to use @overload

### PR DESCRIPTION
**Pull request by guilhermeleobas**
ref: #8254

Refactor `carray`/`farray` to use `@overload`

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch, this looks like a direct refactor of existing code and appears valid on inspection, all tests passing adds to the confidence of this being valid. Thanks again!

**Comment by sklam** [comment]
@guilhermeleobas there's now a merge conflict

**Comment by guilhermeleobas** [comment]
@sklam fixed!

**Review by stuartarchibald — APPROVED** [review]
Conflict resolution looks valid, thanks.

**Pull request merged**
