### PR TITLE
Fix flake8 violations in numba.cuda.tests.cudadrv

### PR DESCRIPTION
**Pull request by gmarkall**

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
See https://github.com/numba/numba/pull/6303 for buildfarm pass.

**Review by stuartarchibald — APPROVED** [review]
Thanks for resolving conflicts etc. Change is still approved.

**Comment by gmarkall** [comment]
The fail seems to be a Conda error - does this need re-running?

**Review by stuartarchibald — APPROVED** [review]
Thanks for resolving conflicts again. Change is still approved.

**Pull request merged**
