### PR TITLE
Fix #1037: fix or remove obsolete examples

### LINKED ISSUE #1037: In-tree examples need fixing
It seems the examples in the `examples` directory aren't really fresh. For example:

```
$ python examples/queens.py 
Traceback (most recent call last):
  File "examples/queens.py", line 59, in <module>
    print(solve(8))
  File "/home/antoine/numba/numba/dispatcher.py", line 195, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) int64
```

```
$ python examples/fbcorr.py 
Traceback (most recent call last):
  File "examples/fbcorr.py", line 16, in <module>
    @jit(argtypes=(nd4type, nd4type, nd4type))
  File "/home/antoine/numba/numba/decorators.py", line 122, in jit
    raise DeprecationError(_msg_deprecated_signature_arg.format('argtypes'))
numba.decorators.DeprecationError: Deprecated keyword argument `argtypes`. Signatures should be passed as the first positional argument.
```

We should fix or remove the broken ones.

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by gmarkall** [comment]
I think these changes look good, but I am not sure structures.py had to go - the equivalent in current Numba might look like:

```python
# -*- coding: utf-8 -*-
from __future__ import print_function, division, absolute_import
from numba import jit
import numpy as np

record_type = np.dtype([('x', np.double), ('y', np.double)])
a = np.array([(1.0, 2.0), (3.0, 4.0)], dtype=record_type)

@jit
def hypot(data):
    result = np.empty_like(data, dtype=np.float64)
    # notice access to structure elements 'x' and 'y' via attribute access
    for i in range(data.shape[0]):
        result[i] = np.sqrt(data[i].x * data[i].x + data[i].y * data[i].y)

    return result

print(hypot(a))
```

Although `struct` is gone from Numba, it works directly with structured dtypes just fine.

**Comment by pitrou** [comment]
Good point. I've re-added your suggested example.

**Comment by gmarkall** [comment]
A couple of other things - fbcorr.py still looks odd in that it specifies arg types and sometimes uses range and xrange at other times.

findmulti.py doesn't seem to be doing anything, unless it's related to the pycc examples in a way I haven't understood. Also, are compile_with_pycc.py and pycc_example.py relevant anymore? Should they be compiled with the numba command line tool rather than pycc, for example?

**Comment by pitrou** [comment]
I don't know about findmulti, we can probably remove it (I don't know what the function is supposed to compute).
I don't think the `numba` command-line tool has replaced `pycc`. Actually only `pycc` is tested AFAIK.

**Comment by gmarkall** [comment]
I just tried pycc with the pycc_example.py and it seems to work - I had made the mistake of thinking that pycc didn't exist because it wasn't in the bin folder.

**Pull request merged**
