### PR TITLE
Remove use of `compile_isolated` from generator tests.

### LINKED ISSUE #8873: Generator test segfault on linux py3.11
`test_gen9` or `test_gen9_objmode` in `numba.tests.test_generators` are either segfaulting or hanging and causing the multiproc testsuite to timeout. Problem only occur on Linux and py3.11. Problem has occurred on x64, ppc64le, and aarch64.

Issue first occurred with the commit 201a2f8, merge of https://github.com/numba/numba/pull/8134.

The issue is hard to reproduce. Only consistent reproduction is in the buildfarm and with the buildfarm created package. 

Scripts to reproduce:

```bash
$ conda create -y -q -n testenv_f8901e13 -c numba/label/pynext_ci -c numba/label/pynext_dev -c conda-forge python=3.11 numba=0.57.0dev0=np1.23py3.11h3611171_g201a2f8d6_1571 numpy=1.24 pyyaml colorama scipy jinja2 cffi ipython flake8
$ conda activate testenv_f8901e13
$ NUMBA_ENABLE_CUDASIM python -m numba.runtests -m 4 -v numba.tests
```

`conda-forge` channel is not necessary. Problem has occurred on py3.11 + np1.23 from conda defaults.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. Use of `compile_isolated` leads to hard to track down life-time bugs such as that in #8873. Essentially the `CodeLibrary` containing the generator destructors was being free'd before the generators had actually had their destructors invoked such that the code that should have been executed was missing. This patch replaces `compile_isolated` with `jit` which has an easier to reason about lifetime behaviour for `CodeLibrary` instances etc.

Fixes #8873

### CODE REVIEW

**Comment by sklam** [comment]
BFID `numba_pynext_cpu_yaml_15`

**Review by gmarkall — DISMISSED** [review]
This looks good to me:

 - The `tryanother.py` example from #8873 has not segfaulted once in 20 runs.
 - I increased the iteration count of `tryanother.py` to 2000 (an order of magnitude increase) and it still has not segfaulted after another 20 runs, though it does take much longer to run (obviously). Memory usage slowly climbs to about 2GB during each run, which doesn't alarm me given the artificial nature of the test and the fact it's compiling over and over.
 - There are no more instances of `compile_isolated` in `test_generators.py`.

There's one small suggestion on the diff where I think a name got altered, but it's just a very minor point - I think if this runs fine on the build farm then it's good for unblocking the release from my perspective.

**Comment by stuartarchibald** [comment]
@gmarkall thanks for reviewing, the "minor point" should be addressed in 0dc45d9.

**Review by sklam — APPROVED** [review]
LGTM. Passed manual testing. Just waiting for buildfarm to finish.

**Comment by sklam** [comment]
> BFID `numba_pynext_cpu_yaml_15`

passed

**Pull request merged**
