### PR TITLE
Add FMA intrinsic support

### PR DESCRIPTION
**Pull request by njwhite**
[This function](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__DOUBLE.html#group__CUDA__MATH__DOUBLE_1gff2117f6f3c4ff8a2aa4ce48a0ff2070) in the C API. nb: this PR is dependent on https://github.com/numba/llvmlite/pull/380 .

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch, much appreciated :)

Note, core-devs: Push through build farm!

**Comment by sklam** [comment]
I have merged the dependent llvmlite PR.  Waiting for buildfarm to finish up the llvmlite build.  Then, we need to push this through the GPU tests.  Also, I think we may need to update the llvmlite dependency in the build scripts.

**Comment by stuartarchibald** [comment]
Dependencies updated in pending https://github.com/numba/numba/pull/3179

**Comment by sklam** [comment]
Kicked a build on buildfarm.

**Comment by sklam** [comment]
CUDA build passed

**Pull request merged**
