### PR TITLE
Add np.nanprod implementation

### PR DESCRIPTION
**Pull request by ml31415**
`np.nanprod` was added in numpy 1.10. This patch adds a numba implementation for it and extends the test suite.

### CODE REVIEW

**Comment by pitrou** [comment]
Thank you! This looks good to me. Can you add the function in `docs/source/reference/numpysupported.rst` (in the "reductions" section)?

**Comment by ml31415** [comment]
Done.

**Comment by ml31415** [comment]
Not sure, but the crash of appveyor seems unrelated to the latest change in the documentation.

**Comment by seibert** [comment]
Yeah, we noticed this problem with the Windows build last week, and are currently trying to resolve it.  I would not consider this a blocker for merging.

**Pull request merged**
