### PR TITLE
Remove inline declarations on C functions

### PR DESCRIPTION
**Pull request by pitrou**
For compatibility with MSVC.

### CODE REVIEW

**Comment by ovillellas** [comment]
If 'inline' is wanted, in some places use a macro that defines to __inline in MSVC (#ifdef _MSC_VER) while keeping inline for the rest.

**Comment by pitrou** [comment]
The use of "inline" was mostly pedantic, to be honest. I expect the compiler to infer that some of these short functions should be inlined indeed.

**Comment by seibert** [comment]
I'm never clear on how much modern compilers pay attention to the `inline` keyword.

**Comment by ovillellas** [comment]
@seibert not much AFAIK. If a function is static and pretty short it is very likely to get inlined anyways, especially if they are seldom used, as the compiler doesn't need to generate a stand-alone version.

**Pull request merged**
