### PR TITLE
Pre-commit update Flake8 and add basic pre-commit-hooks for linting

### PR DESCRIPTION
**Pull request by jamesobutler**
This is work branched off original PR #8347. This updates the Flake8 version defined in the pre-commit-config.yml and also updating it to use the Flake8 upstream and not the mirror at gitlab. I've also added basic pre-commit-hooks to the pre-commit-config which identified whitespace to be trimmed across files. I'm attempting this change to contain whitespace changes in a single commit where possible rather than intermixed with other commits. I'm going to see if the automated tests are able to run successfully with the amount of diff changes.

To keep the code base in compliance, I suggest a code owner attaching the numba repository to https://pre-commit.ci/ which will run an additional status check (see image below) and has the benefit of being able to contribute fixes to identified style issues automatically to PRs. This keeps developers doing the more important things by automating the fix me up style tasks. I utilized it in https://github.com/jamesobutler/numba/pull/2 by making a change to the pre-commit-config and then letting pre-commit.ci push a commit to fix things up and get things back in compliance with the new configuration. 

image

### CODE REVIEW

**Comment by jamesobutler** [comment]
@gmarkall Can you all re-run the `Linux py39_np121` job here? It is odd that all the other jobs passed successfully and only this one had a problem.

**Comment by gmarkall** [comment]
@jamesobutler Everything looks good WRT CI, I think?

**Comment by jamesobutler** [comment]
There was one job that was cancelled/failed so maybe someone else restarted that one if it wasn’t you. Anyways glad to see the CI green here.

**Comment by jamesobutler** [comment]
@gmarkall Anything I can do to help move this PR along?

**Comment by gmarkall** [comment]
@jamesobutler Thanks for asking - could I ask you to hold off from doing anything else for the time being please? Following some discussion in the triage meeting on Tuesday we've concluded that we (the Numba maintainers) need to adjust our approach regarding contributions of this nature, but I've not yet been able to find time to document the conclusions - many thanks for your efforts / time / patience so far.

**Comment by jamesobutler** [comment]
@gmarkall Any update re https://github.com/numba/numba/wiki/Minutes_2022_08_23#2-new-prs regarding the need to "Update PR Policy" and what that policy may be?

**Comment by gmarkall** [comment]
@jamesobutler Sorry for the delay, I didn't yet get round to writing an updated policy - broadly it's that whilst we appreciate the efforts of those who would like to contribute general / large-scale formatting fixes, in practice we're not able to accept them because of the workload it requires to manage them through to completion on top of the existing workload and the challenges that they present (e.g. creating many conflicts with other in-flight PRs).

So for these flake8 and linting PRs (#8347, #8360, #8361, #8364, #8365), we aren't going to be able to see them through to completion. I'd like to apologise that we're not able to make use of this work, and thank you for your understanding of the situation  and your efforts so far on these PRs. I hope this won't deter you from future contributions to other areas of Numba, and I look forward to the progress of #8319 which I understand is also being looked at by @esc.

**Comment by jamesobutler** [comment]
Hi @gmarkall are there updates the maintainers can make to the Contributing.md docs to indicate that the `numba` project is not actually enforcing certain coding conventions and is not going to accept any changes to improve compliance in files? This would help other future contributors avoid unnecessary work that will be denied due to the lack of maintainer support for them.

I had completed the coding conventions PRs specifically based on what is in the Contributing.md documents below.

https://github.com/numba/numba/blob/c61921276a0ae27d74c82126070014607d6bf460/docs/source/developer/contributing.rst#coding-conventions

https://github.com/numba/numba/blob/c61921276a0ae27d74c82126070014607d6bf460/CONTRIBUTING.md#quick-things

> Make a file that is not flake8 compliant meet the standard, a list of all failing files is in the exclude section of the [.flake8 config](https://github.com/numba/numba/blob/main/.flake8), then create a pull request with the change.

Side note - I was hoping at least this PR could be merged because the changes are pure whitespace changes that should be the easiest type of merge conflict to resolve. Removing whitespace changes in diff will improve readability when reviewing individual commits in a PR though I guess that is not really done here in this repo because linear history is not a convention followed as merge commits are used instead. I find merge commits to be destructive to understanding a specific change in an individual commit during the review process.

**Comment by gmarkall** [comment]
Hi @jamesobutler - many thanks for continuing the discussion here :slightly_smiling_face: 

> Hi @gmarkall are there updates the maintainers can make to the Contributing.md docs to indicate that the numba project is not actually enforcing certain coding conventions and is not going to accept any changes to improve compliance in files? This would help other future contributors avoid unnecessary work that will be denied due to the lack of maintainer support for them.

Yes - I'd like to do this, but had not yet got around to updating it.

> I had completed the coding conventions PRs specifically based on what is in the Contributing.md documents below.

Many thanks for identifying the sections that need updates :-)

> Side note - I was hoping at least this PR could be merged because the changes are pure whitespace changes that should be the easiest type of merge conflict to resolve. Removing whitespace changes in diff will improve readability when reviewing individual commits in a PR though I guess that is not really done here in this repo because linear history is not a convention followed as merge commits are used instead.

I'll bring this up at the dev meeting on Tuesday for discussion with the other maintainers.

> I find merge commits to be destructive to understanding a specific change in an individual commit during the review process.

I agree with you here - I do like to see a nice linear history of "additive" only commits. The difficulty is how this interacts with the review process on Github, which doesn't track changes well in conjunction with rebases after the review (I find things like Gerrit / Phabricator do a better job with this, but have their own hurdles to overcome).

**Comment by gmarkall** [comment]
> I'll bring this up at the dev meeting on Tuesday for discussion with the other maintainers.

A quick note, the agenda for Tuesday is at: https://hackmd.io/nvVHaxmWT865GP2RaEcUbw

**Comment by jamesobutler** [comment]
Rebased to fix merge conflicts and to allow pre-commit to automatically commit the trimming trailing whitespace fixes.

**Pull request closed without merging**
