### PR TITLE
Support for len on dict.keys, dict.values, and dict.items

### LINKED ISSUE #7585: Support for len(dict.key()), len(dict.values()), len(dict.items())
---

## Feature request

Python supports `len` on `dict.keys`, `dict.values`, and `dict.items`, but none of these seem to be supported in Numba. Should be a relatively simple change to support these.

Example:
```python
@njit
def foo(keys, vals):
    d = dictobject.new_dict(int32, float64)
    for k, v in zip(keys, vals):
        d[k] = v
    return len(d.items())

keys = [1, 2, 3]
vals = [0.1, 0.2, 0.3]
foo(keys, vals)
```

### PR DESCRIPTION
**Pull request by njriasan**
Support for len on various dict iterators by calling len on the stored parent.

## Reference an existing issue

Closes #7585

### CODE REVIEW

**Comment by njriasan** [comment]
The CI failures seem to be on `test_logspace3_with_num_basic`, which seems unrelated to this PR. Is there a known CI issue?

**Comment by gmarkall** [comment]
> The CI failures seem to be on `test_logspace3_with_num_basic`, which seems unrelated to this PR. Is there a known CI issue?

It may be resolved by https://github.com/numba/numba/pull/7588

**Comment by esc** [comment]
#7588 was merged

**Comment by esc** [comment]
> The CI failures seem to be on `test_logspace3_with_num_basic`, which seems unrelated to this PR. Is there a known CI issue?

yes, this was the case, it should be fixed now

**Review by stuartarchibald — DISMISSED** [review]
Thanks for the patch. Change looks good.

**Comment by njriasan** [comment]
> Thanks for the patch. Change looks good.

Thanks Stuart. I spotted a small docstring error in the tests so I updated those.

**Review by stuartarchibald — APPROVED** [review]
@njriasan thanks for the docstring update, re-approved.

**Pull request merged**
