### PR TITLE
Resolves #4251.

### LINKED ISSUE #4251: Potential regression in _analyze_op_call_numpy_reshape
The Numba intgration testing project may have revealed a regression in `_analyze_op_call_numpy_reshape` by testing pygbm.

https://github.com/numba/numba-integration-testing/pull/14

Full log output can be found attached to the pull-request mentioned above, there are  58 (about 1/3) of the tests that failed and they all seem to be pointing to `_analyze_op_call_numpy_reshape`.

@DrTodd13 I saw via `git blame` that you were the last person to modify that function, could you perhaps take a quick look?

### PR DESCRIPTION
**Pull request by DrTodd13**
Fix bug in reshape analysis.  Resolves #4251.

### CODE REVIEW

**Comment by esc** [comment]
This reduced the number of errors from 58 to 40. Here is the new log. It might be worth installing `pygbm`locally:

https://github.com/ogrisel/pygbm

The instructions are actually quite straightforward.

**Comment by esc** [comment]
[out.txt](https://github.com/numba/numba/files/3351051/out.txt) here is the new log

**Comment by DrTodd13** [comment]
I merged 4215 and 4251 and now I see 0 pygbm errors. @esc

**Comment by esc** [comment]
I can confirm that #4215 / #4223 and #4251 / #4262 together will fix all issues with pygbm 0.1.0.

**Pull request merged**
