### PR TITLE
Specialise arange dtype on arch + python version.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by seibert** [comment]
running through internal CI (build 49)

**Comment by seibert** [comment]
running through internal CI (build 50)

**Comment by stuartarchibald** [comment]
@seibert b248fc3 is the merge of master with the Azure scripting fix, it failed and seemingly correctly so, the subsequent commits attempt to mask of the failure on win64. Vague explanation:
https://github.com/numba/numba/pull/4896/files#diff-81d8f85ead1fb3ae948c94ed8d2a969eR3771-R3777

**Comment by seibert** [comment]
running through internal CI (build 52)

**Comment by seibert** [comment]
Enough of the CI has passed to make me confident this gets the unit tests working everywhere.

**Pull request merged**
