### PR TITLE
Remove restrictions on SVML version due to bug in LLVM SVML CC

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. For context see https://github.com/numba/numba/issues/6100

### CODE REVIEW

**Comment by stuartarchibald** [comment]
xref https://github.com/numba/llvmlite/pull/636 https://github.com/numba/llvmlite/pull/626

**Comment by esc** [comment]
I presume this will need to be tested, once an llvmlite "version with new SVML patch" becomes available?

**Comment by stuartarchibald** [comment]
> I presume this will need to be tested, once an llvmlite "version with new SVML patch" becomes available?

Yes. Ideally we'd sort out an LLVM IR reproducer for the SVML patch too.

**Comment by esc** [comment]
`numba/llvmlite#626` was merged - I don't think anything else is needed for this. Assuming that llvmlite 0.35.0 will ship with the correct  SVML patch we can merge this and then Numba 0.52.0 will no longer have this restriction.

**Pull request merged**
