### PR TITLE
Keyword arguments in JIT function calls

### LINKED ISSUE #728: Add keyword argument support for Overloaded objects
Numba generates PyCFunction that accepts keywords arguments, but the wrapper does not understand keyword arguments, yet.

### LINKED ISSUE #729: Support calling functions with keyword arguments inside a numba compiled function

### PR DESCRIPTION
**Pull request by pitrou**
Fix #728: Add keyword argument support for Overloaded objects.
Fix #729: Support calling functions with keyword arguments inside a numba compiled function.

### CODE REVIEW

**Comment by gmarkall** [comment]
This looks good to me.

**Comment by seibert** [comment]
Yeah, I needed this over the weekend.

**Comment by seibert** [comment]
Although, I think we need to get funcsigs into our binstar account (and then eventually into anaconda) before we merge this.  Requiring pip in a conda environment to get a Numba dependency is not something we want to do.

**Comment by pitrou** [comment]
Ok, I've pushed some conda packages for funcsigs.

**Comment by seibert** [comment]
Excellent.  I especially like that keyword argument support works when calling nopython mode functions from inside nopython mode.

**Pull request merged**
