### PR TITLE
DOC: pypi and conda-forge badges

### PR DESCRIPTION
**Pull request by raybellwaves**
I find these pypi and conda-forge badges useful to show the current version.

### CODE REVIEW

**Review by gmarkall — DISMISSED** [review]
Thanks for the PR - I like this idea, and the changes look good to me.

**Comment by gmarkall** [comment]
(Left as "Ready for Review" in case another maintainer has a strong opinion on this, but I like it and would otherwise move it to RTM)

**Comment by esc** [comment]
Question: do we want to promote the conda-forge packages or the ones from the `numba` channel? I am asking because we are not in control of the conda-forge builds and adding a badge to point in that direction may constitute an unwanted advertisment?

**Comment by raybellwaves** [comment]
> Question: do we want to promote the conda-forge packages or the ones from the `numba` channel? I am asking because we are not in control of the conda-forge builds and adding a badge to point in that direction may constitute an unwanted advertisment?

Fair point. Welcome to push to my branch and remove the conda badge

**Comment by esc** [comment]
@raybellwaves thank you for the patch. Will mark as Ready to Merge for now, the CI failures on Python 3.10 are unrelated.

**Review by esc — APPROVED** [review]
I viewed the badge as rendered in the branch `raybellwaves:patch-1` and it looks fine.

**Review by gmarkall — APPROVED** [review]
Still looks good to me.

**Pull request merged**
