### PR TITLE
Make Python 3.10 kwarg peephole less restrictive

### LINKED ISSUE #8043: Python 3.10 kwarg peephole rewrite failing in valid case (breaks mainline)
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This breaks on mainline and is a blocking issue for 0.56.
```python
from numba import njit, objmode

def func(*args):
    pass

@njit
def log(*args):
    with objmode():
        func(*args)

log()
```
the above reproducer is extracted from the failing tests found  by running on Python 3.10:
```
./runtests.py numba.tests.test_ndarray_subclasses
```

### PR DESCRIPTION
**Pull request by njriasan**
Closes #8043

Fixes a bug in peep_hole_call_function_ex_to_call_function_kw where we raised the error if we couldn't find the varargs in the basic block and no kwargs are passed. This is an inaccurate check and we should only raise an exception if we find the args have the wrong definition.

This also fixes a bug in `peep_hole_list_to_tuple` where the definition of the final assignment wasn't properly set.

### CODE REVIEW

**Comment by sklam** [comment]
I did a quick check. It does resolve the failure in `numba.tests.test_ndarray_subclasses.TestNdarraySubclasses`

**Comment by sklam** [comment]
smoketest BFID: `numba_smoketest_cpu_yaml_83`

**Comment by njriasan** [comment]
> > smoketest BFID: `numba_smoketest_cpu_yaml_83`
> 
> This passed on multiple build jobs with Python 3.10, and all other build jobs not impacted by some other unrelated issue.
> 
> Just checked into the few failing Python 3.10 jobs, there's still a couple that are reporting the issue in #8043. Need to take a closer look as to what has happened.

@stuartarchibald If you post the list of tests I'm happy to take a look.

**Comment by stuartarchibald** [comment]
> @stuartarchibald If you post the list of tests I'm happy to take a look.

Thanks @njriasan it's these two tests, same failures as in #8043:
* `numba.tests.test_ndarray_subclasses.TestNdarraySubclasses.test_my_array_return`
* `numba.tests.test_ndarray_subclasses.TestNdarraySubclasses.test_my_array_allocator_override`

What I'm not sure about is if this is caused by a genuine issue with this patch or there's something unusual going on in the farm builds.

Set up was Python 3.10, np 1.21, linux 64 bit system.

**Comment by njriasan** [comment]
@stuartarchibald I reran the whole test file manually using a ubuntu x86 docker image. I could not reproduce any failures. I'm inclined to believe this may be a build farm issue.

**Comment by sklam** [comment]
@stuartarchibald, I think we might be mixing up the result of two builds. I'm going to combine the two PRs (#8044 and #8046) to tests.

**Comment by stuartarchibald** [comment]
> @stuartarchibald, I think we might be mixing up the result of two builds. I'm going to combine the two PRs (#8044 and #8046) to tests.

Thanks @sklam

**Comment by stuartarchibald** [comment]
> @stuartarchibald I reran the whole test file manually using a ubuntu x86 docker image. I could not reproduce any failures. I'm inclined to believe this may be a build farm issue.

@njriasan Thanks for checking.

**Comment by sklam** [comment]
tested as part of #8053 and its all green

**Review by sklam — APPROVED** [review]
Thanks for the patch!

**Pull request merged**
