### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by esc**
'Forbidded' ain't a word and neither is 'iteratable'?! I know that
English can be bent and broken, but this goes too far..

### CODE REVIEW

**Comment by esc** [comment]
O.K. maybe 'iteratable'...:

https://www8.cs.fau.de/staff/milius/phd/M2.pdf

**Comment by esc** [comment]
@jrbourbeau -- ty, still not sure about 'iteratable'.

**Comment by jrbourbeau** [comment]
I'm not sure about "iteratable" either. Switching to "iterable" seems reasonable given that's what's in the class names (e.g. `ListTypeIterableType`) and it appears throughout the Python docs (e.g. https://docs.python.org/3/library/itertools.html#itertools.chain.from_iterable)

**Comment by stuartarchibald** [comment]
Bump for CI, else good to go. Thanks.

**Pull request merged**
