### PR TITLE
Fix issue1526

### PR DESCRIPTION
**Pull request by sklam**
This implements the fix described in https://github.com/numba/numba/issues/1526#issuecomment-153795680

### CODE REVIEW

**Comment by robintw** [comment]
Thanks for merging this so quickly.

Is there an easy way to get a numba dev build through conda, so I can try this out with my code - and hopefully get it all working?

**Comment by seibert** [comment]
Our CI system automatically builds new numba packages after each merge and posts them to the "numba" channel.  The workers are pretty slow virtual machines, so it may be a few hours before it shows up.  If you let me know what OS (win/mac/linux 32 or 64 bit), Python and NumPy version you are waiting for, I'll update this issue when it is ready.

**Comment by robintw** [comment]
Thanks - that's great.

I had a look at the numba channel, but couldn't see a `numba-dev` or equivalent package. All I could see was numba 0.22.1. Where should I find this once I'm ready?

For this specific project I'm running on OS X, 64-bit, Python 2.7, Numpy 1.10.

**Comment by seibert** [comment]
Packages in that channel should all be considered "dev".  Conda-build is cooking up the version number, which will look like 0.22.1 (the most recent tag), but the build number will be greater than zero.

When we do an official release, we tell the Anaconda repo maintainers to copy over just the release package, which has build 0 for the latest tag.

**Comment by seibert** [comment]
The fix is now available for your platform.  The package should be: numba-0.22.1-np110py27_13.tar.bz2 (that's build 13) or later.

**Comment by seibert** [comment]
`numba -c numba update numba` should get it.

**Pull request merged**
