### PR TITLE
np.cumproduct

### PR DESCRIPTION
**Pull request by guilhermeleobas**
As title suggests

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
PR is failing because of travis-ci

**Comment by stuartarchibald** [comment]
Before merge we should check if this API is actually still part of NumPy.

**Comment by guilhermeleobas** [comment]
`np.cumproduct` exists but it's not documented.

**Comment by stuartarchibald** [comment]
The comment here https://github.com/numba/numba/pull/4604#issuecomment-535528811 also applies to this PR. Thanks for your understanding.

**Pull request closed without merging**
