### PR TITLE
Link ELF obj as DSO for radare2 disassembly CFG

### PR DESCRIPTION
**Pull request by stuartarchibald**
This improves the amount of analysis r2 can do and also lets
DWARF info be used in the disassembly CFG output.

### CODE REVIEW

**Review by sklam — APPROVED** [review]
Manually confirmed that radare2 will see the debug information with this patch.

**Comment by stuartarchibald** [comment]
> Manually confirmed that radare2 will see the debug information with this patch.

Thanks @sklam, merging this makes the reversing experience much improved!

**Comment by stuartarchibald** [comment]
@sklam did the seek to the symbol work ok? Since the ABI encoding for the flags was added, the symbols have become a lot longer and it seems like `r2` can only match to the first 61 characters.

**Comment by sklam** [comment]
i only tested on short function names.

**Pull request merged**
