### PR TITLE
Remove dels for known dead vars.

### PR DESCRIPTION
**Pull request by DrTodd13**
If remove dead code removes a variable then make sure a later "del" doesn't generate an exception since the variable doesn't exist anymore.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch... is there any way we can easily test this?

**Comment by DrTodd13** [comment]
> Thanks for the patch... is there any way we can easily test this?

What would the goal of such a test be?  One option is just to make sure it superficially functions as intended...meaning that it gets rid of the right "del"s.  The other option is that it leaves all the data structures corresponding to the IR in a consistent state.  I don't know how to do a specific test for either of these easily.  Writing Python that we know will produce IR with dead var and dead dels and how consistent would the var names be for an IR check to verify the right things were gone?  To do the latter in an indirect way, that's essentially just adding something like your DCE patch and then seeing if anything breaks in the whole test-suite.

**Comment by stuartarchibald** [comment]
I've written a small test harness:
```python
from numba.compiler import Pipeline, Flags, _PipelineManager
from numba.targets import registry
from numba import types, ir_utils, bytecode
from numba.tests.support import TestCase


class Tester(Pipeline):

    @classmethod
    def mk_pipeline(cls, args, return_type=None, flags=None, locals={},
                    library=None, typing_context=None, target_context=None):
        if not flags:
            flags = Flags()
        flags.nrt = True
        if typing_context is None:
            typing_context = registry.cpu_target.typing_context
        if target_context is None:
            target_context = registry.cpu_target.target_context
        return cls(typing_context, target_context, library, args, return_type,
                   flags, locals)

    def rm_dead_stage(self):
        ir_utils.remove_dead(
            self.func_ir.blocks, self.func_ir.arg_names, self.func_ir,
            typemap=self.typemap)

    def compile_to_ir(self, func, DCE=False):
        """
        Compile and return IR
        """
        self.func_id = bytecode.FunctionIdentity.from_function(func)
        self.bc = self.extract_bytecode(self.func_id)
        self.lifted = []

        pm = _PipelineManager()
        pm.create_pipeline("pipeline")
        self.add_preprocessing_stage(pm)
        self.add_pre_typing_stage(pm)
        self.add_typing_stage(pm)
        if DCE == True:
            pm.add_stage(self.rm_dead_stage, "DCE after typing")
        pm.finalize()
        res = pm.run(self.status)
        return self.func_ir


class TestThing(TestCase):

    def test_foo(self):

        def foo(x):
            y = x + 1
            dead = 0xdead
            z = y + 2
            more_dead = 0xdeaddead
            ret = z * z
            return ret

        test_pipeline = Tester.mk_pipeline((types.intp,))
        no_dce = test_pipeline.compile_to_ir(foo)
        print(no_dce.dump())

        test_pipeline = Tester.mk_pipeline((types.intp,))
        w_dce = test_pipeline.compile_to_ir(foo, DCE=True)
        print(w_dce.dump())


if __name__ == '__main__':
    unittest.main()
```
which produces:
```
$ ./runtests.py numba.tests.test_dels.TestThing.test_foo
label 0:
    x = arg(0, name=x)                       ['x']
    $const0.2 = const(int, 1)                ['$const0.2']
    $0.3 = x + $const0.2                     ['$0.3', '$const0.2', 'x']
    del x                                    []
    del $const0.2                            []
    y = $0.3                                 ['$0.3', 'y']
    del $0.3                                 []
    $const0.4 = const(int, 57005)            ['$const0.4']
    dead = $const0.4                         ['$const0.4', 'dead']
    del dead                                 []
    del $const0.4                            []
    $const0.6 = const(int, 2)                ['$const0.6']
    $0.7 = y + $const0.6                     ['$0.7', '$const0.6', 'y']
    del y                                    []
    del $const0.6                            []
    z = $0.7                                 ['$0.7', 'z']
    del $0.7                                 []
    $const0.8 = const(int, 3735936685)       ['$const0.8']
    more_dead = $const0.8                    ['$const0.8', 'more_dead']
    del more_dead                            []
    del $const0.8                            []
    $0.11 = z * z                            ['$0.11', 'z', 'z']
    del z                                    []
    ret = $0.11                              ['$0.11', 'ret']
    del $0.11                                []
    $0.13 = cast(value=ret)                  ['$0.13', 'ret']
    del ret                                  []
    return $0.13                             ['$0.13']
None

label 0:
    x = arg(0, name=x)                       ['x']
    $const0.2 = const(int, 1)                ['$const0.2']
    $0.3 = x + $const0.2                     ['$0.3', '$const0.2', 'x']
    y = $0.3                                 ['$0.3', 'y']
    $const0.6 = const(int, 2)                ['$const0.6']
    $0.7 = y + $const0.6                     ['$0.7', '$const0.6', 'y']
    z = $0.7                                 ['$0.7', 'z']
    $0.11 = z * z                            ['$0.11', 'z', 'z']
    ret = $0.11                              ['$0.11', 'ret']
    $0.13 = cast(value=ret)                  ['$0.13', 'ret']
    return $0.13                             ['$0.13']
None
```
The above suggests that the all `dels` that are not associated with a live var at the terminator are being removed, think this may manifest as a reference count leak.

Having spoken a bit with @sklam, couple of thoughts:
1. We could not generate any `del` until all IR manipulation is complete (i.e. do necessary analysis and `ir.Del` injection just prior to lowering).
2. DCE tracks what's removed so that `ir.Del` removal corresponds (this should? be default, but optionally the current behaviour could be permitted for cases where `dels` are regenerated by later passes etc).

Thoughts?

**Comment by ehsantn** [comment]
Not generating dels until right before lowering sounds like a good idea to me. We usually have to regenerate dels anyways.

**Comment by stuartarchibald** [comment]
I think to put the `ir.Del` generation into a single location (i.e. just prior to lowering) will require similar to https://github.com/numba/numba/pull/3757 to be fully implemented and then integrated into the code base in places such as array inlining where there's analysis taking place that currently relies on `ir.Del` to determine e.g. liveness. Once that is done it should be possible to eliminate `ir.Del` insertion/deletion behaviours throughout the code base and have the single location for generation.

**Comment by stuartarchibald** [comment]
As an intermediate step, how about including this patch as-is, but also running the IR postprocessing at the tail of `remove_dead` if a mutation is detected in the IR (i.e. something got removed). It's not hugely efficient but I think has the desired effect of making the `Del` nodes consistent with those which are live, albeit in a round-about manner?

**Comment by sklam** [comment]
I agree.  We should use @stuartarchibald and unblock this PR.

However, the tests are failing in infiniteloop inside `remove_dead`.

Here's a list of tests that timed out on my machine:

<details>
- 'numba.tests.test_closure.TestInlinedClosure.test_inner_function'
- 'numba.tests.test_closure.TestInlinedClosure.test_inner_function_with_closure_3'
- 'numba.tests.test_np_functions.TestNPFunctions.test_extract_exceptions'
- 'numba.tests.test_np_functions.TestNPFunctions.test_partition_boolean_inputs'
- 'numba.tests.test_np_functions.TestNPFunctions.test_partition_empty_array'
- 'numba.tests.test_np_functions.TestNPFunctions.test_partition_exception_kth_multi_dimensional'
- 'numba.tests.test_np_functions.TestNPFunctions.test_trapz_numpy_questionable'
- 'numba.tests.test_np_functions.TestNPFunctions.test_tri_n_basic'
- 'numba.tests.test_np_functions.TestNPFunctions.test_tril_basic'
- 'numba.tests.test_np_functions.TestNPFunctions.test_vander_exceptions'
- 'numba.tests.test_np_functions.TestNPMachineParameters.test_MachAr'
- 'numba.tests.test_npdatetime.TestDatetimeArithmeticNoPython.test_comparisons'
- 'numba.tests.test_npdatetime.TestMetadataScalingFactor.test_datetime_npm'
- 'numba.tests.test_npdatetime.TestMiscCompiling.test_vectorize_explicit_signature'
- 'numba.tests.test_npdatetime.TestModuleHelpers.test_timedelta_conversion'
- 'numba.tests.test_npdatetime.TestTimedeltaArithmetic.test_abs'
- 'numba.tests.test_npdatetime.TestTimedeltaArithmetic.test_div'
- 'numba.tests.test_npdatetime.TestTimedeltaArithmetic.test_neg'
- 'numba.tests.test_npdatetime.TestTimedeltaArithmeticNoPython.test_div'
- 'numba.tests.test_npdatetime.TestTimedeltaArithmeticNoPython.test_le_gt'
- 'numba.tests.test_npdatetime.TestTimedeltaArithmeticNoPython.test_neg'
- 'numba.tests.test_nrt.TestNRTIssue.test_issue_with_refct_op_pruning'
- 'numba.tests.test_nrt.TestNrtMemInfo.test_fake_memoryview'
- 'numba.tests.test_nrt.TestNrtMemInfo.test_meminfo_refct_1'
- 'numba.tests.test_nrt.TestNrtMemInfo.test_memoryview'
- 'numba.tests.test_numberctor.TestScalarNumberCtor.test_complex2'
- 'numba.tests.test_numberctor.TestScalarNumberCtor.test_numba_types'
- 'numba.tests.test_numconv.TestNumberConversion.test_float32_to_float64'
- 'numba.tests.test_numconv.TestNumberConversion.test_float32_to_uint16'
- 'numba.tests.test_numconv.TestNumberConversion.test_float32_to_uint32'
- 'numba.tests.test_numconv.TestNumberConversion.test_float64_to_int16'
- 'numba.tests.test_numconv.TestNumberConversion.test_float64_to_uint16'
- 'numba.tests.test_numconv.TestNumberConversion.test_int16_to_int8'
- 'numba.tests.test_numconv.TestNumberConversion.test_int16_to_uint16'
- 'numba.tests.test_numconv.TestNumberConversion.test_int16_to_uint32'
- 'numba.tests.test_numconv.TestNumberConversion.test_int32_to_float64'
- 'numba.tests.test_numconv.TestNumberConversion.test_int64_to_int16'
- 'numba.tests.test_numconv.TestNumberConversion.test_int64_to_int8'
- 'numba.tests.test_numconv.TestNumberConversion.test_int64_to_uint16'
- 'numba.tests.test_numconv.TestNumberConversion.test_int8_to_float64'
- 'numba.tests.test_numconv.TestNumberConversion.test_int8_to_uint32'
- 'numba.tests.test_numconv.TestNumberConversion.test_int8_to_uint64'
- 'numba.tests.test_numconv.TestNumberConversion.test_int8_to_uint8'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint16_to_float32'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint16_to_int16'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint16_to_int32'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint16_to_int8'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint16_to_uint64'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint32_to_int16'
- 'numba.tests.test_numconv.TestNumberConversion.test_uint8_to_int16'
- 'numba.tests.test_numpy_support.TestArrayScalars.test_number_values'
- 'numba.tests.test_numpy_support.TestFromDtype.test_enum_type'
- 'numba.tests.test_numpy_support.TestFromDtype.test_number_types'
- 'numba.tests.test_numpy_support.TestFromDtype.test_string_types'
- 'numba.tests.test_numpy_support.TestFromDtype.test_struct_types'
- 'numba.tests.test_numpy_support.TestUFuncs.test_layout_checker'
- 'numba.tests.test_obj_lifetime.TestObjLifetime.test_del_before_definition'
- 'numba.tests.test_obj_lifetime.TestObjLifetime.test_looping2'
- 'numba.tests.test_obj_lifetime.TestObjLifetime.test_raising1'
- 'numba.tests.test_object_mode.TestObjectModeInvalidRewrite.test_dynamic_func_objmode'
- 'numba.tests.test_objects.TestAttributes.test_delattr'
- 'numba.tests.test_operators.TestMixedInts.test_and'
- 'numba.tests.test_operators.TestMixedInts.test_rshift'
- 'numba.tests.test_operators.TestMixedIntsOperatorModule.test_and'
- 'numba.tests.test_operators.TestMixedIntsOperatorModule.test_invert'
- 'numba.tests.test_operators.TestMixedIntsOperatorModule.test_mul'
- 'numba.tests.test_operators.TestOperatorModule.test_add_complex'
- 'numba.tests.test_operators.TestOperatorModule.test_add_floats_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_bitshift_left_ints'
- 'numba.tests.test_operators.TestOperatorModule.test_bitshift_right_ints_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_bitwise_ixor_bools'
- 'numba.tests.test_operators.TestOperatorModule.test_bitwise_ixor_bools_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_bitwise_not'
- 'numba.tests.test_operators.TestOperatorModule.test_div_errors_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_eq_scalar'
- 'numba.tests.test_operators.TestOperatorModule.test_floordiv_errors_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_floordiv_floats'
- 'numba.tests.test_operators.TestOperatorModule.test_floordiv_ints'
- 'numba.tests.test_operators.TestOperatorModule.test_gt_scalar'
- 'numba.tests.test_operators.TestOperatorModule.test_gt_scalar_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_iadd_complex_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_iadd_floats_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_imatmul'
- 'numba.tests.test_operators.TestOperatorModule.test_imul_floats'
- 'numba.tests.test_operators.TestOperatorModule.test_ipow_ints_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_isub_floats'
- 'numba.tests.test_operators.TestOperatorModule.test_itruediv_floats'
- 'numba.tests.test_operators.TestOperatorModule.test_itruediv_ints_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_lt_scalar'
- 'numba.tests.test_operators.TestOperatorModule.test_not_in_npm'
- 'numba.tests.test_operators.TestOperatorModule.test_pow_floats'
- 'numba.tests.test_operators.TestOperatorModule.test_pow_ints'
- 'numba.tests.test_operators.TestOperatorModule.test_truediv_complex'
- 'numba.tests.test_operators.TestOperatorModule.test_truediv_floats'
- 'numba.tests.test_operators.TestOperatorModule.test_truediv_ints'
- 'numba.tests.test_operators.TestOperators.test_add_floats'
- 'numba.tests.test_operators.TestOperators.test_add_ints'
- 'numba.tests.test_operators.TestOperators.test_add_ints_npm'
- 'numba.tests.test_operators.TestOperators.test_bitshift_left_ints_npm'
- 'numba.tests.test_operators.TestOperators.test_bitwise_not'
- 'numba.tests.test_operators.TestOperators.test_bitwise_not_npm'
- 'numba.tests.test_operators.TestOperators.test_bitwise_or_bools'
- 'numba.tests.test_operators.TestOperators.test_div_errors'
- 'numba.tests.test_operators.TestOperators.test_div_floats'
- 'numba.tests.test_operators.TestOperators.test_floordiv_errors_npm'
- 'numba.tests.test_operators.TestOperators.test_gt_scalar_npm'
- 'numba.tests.test_operators.TestOperators.test_idiv_ints'
- 'numba.tests.test_operators.TestOperators.test_imatmul_npm'
- 'numba.tests.test_operators.TestOperators.test_ipow_ints'
- 'numba.tests.test_operators.TestOperators.test_itruediv_floats'
- 'numba.tests.test_operators.TestOperators.test_le_scalar_npm'
- 'numba.tests.test_operators.TestOperators.test_mul_ints'
- 'numba.tests.test_operators.TestOperators.test_negate_npm'
- 'numba.tests.test_operators.TestOperators.test_not_in'
- 'numba.tests.test_operators.TestOperators.test_sub_complex_npm'
- 'numba.tests.test_operators.TestOperators.test_sub_ints_npm'
- 'numba.tests.test_operators.TestOperators.test_truediv_ints_npm'
- 'numba.tests.test_overlap.TestArrayOverlap.test_overlap2'
- 'numba.tests.test_parallel_backend.TestForkSafetyIssues.test_par_parent_os_fork_par_child'
- 'numba.tests.test_parallel_backend.TestForkSafetyIssues.test_serial_parent_explicit_mp_fork_par_child_then_par_parent'
- 'numba.tests.test_parallel_backend.TestMiscBackendIssues.test_single_thread_tbb'
- 'numba.tests.test_parallel_backend.TestParallelBackend.test_multiprocessing_fork_concurrent_guvectorize'
- 'numba.tests.test_parallel_backend.TestParallelBackend.test_multiprocessing_forkserver_concurrent_guvectorize'
- 'numba.tests.test_parallel_backend.TestParallelBackend.test_multiprocessing_forkserver_concurrent_mix_use'
- 'numba.tests.test_parallel_backend.TestParallelBackend.test_multiprocessing_spawn_concurrent_mix_use'
- 'numba.tests.test_pipeline.TestCustomPipeline.test_objmode_custom_pipeline'
- 'numba.tests.test_print.TestPrint.test_inner_fn_print'
- 'numba.tests.test_profiler.TestProfiler.test_profiler'
- 'numba.tests.test_pycc.TestCC.test_compile'
- 'numba.tests.test_pycc.TestDistutilsSupport.test_setup_py_distutils'
- 'numba.tests.test_pycc.TestLegacyAPI.test_pycc_pymodule'
- 'numba.tests.test_python_int.TestPythonInt.test_long_int_return_type_npm'
- 'numba.tests.test_random.TestInternals.test_perturb'
- 'numba.tests.test_random.TestRandom.test_numpy_beta'
- 'numba.tests.test_random.TestRandom.test_numpy_exponential'
- 'numba.tests.test_random.TestRandom.test_numpy_logistic'
- 'numba.tests.test_random.TestRandom.test_numpy_logseries'
- 'numba.tests.test_random.TestRandom.test_numpy_randn'
- 'numba.tests.test_random.TestRandom.test_numpy_random_permutation'
- 'numba.tests.test_random.TestRandom.test_numpy_uniform'
- 'numba.tests.test_random.TestRandom.test_random_normalvariate'
- 'numba.tests.test_random.TestRandom.test_random_paretovariate'
</details>

**Comment by stuartarchibald** [comment]
Thanks @sklam I think I've got to the bottom of this now...

DCE involves an infinite loop calling `remove_dead` that exits only when `remove_dead` reports nothing else is removed. The `remove_dead` code is now correctly stripping out all `ir.Del` for anything that is not live at the end of the block, as this mutation occurs the postprocessor is immediately run to fix up the `ir.Del`, which produces a valid IR for refcounting. However, `remove_dead` reports that a removal has occurred (because it has) and as DCE necessarily calls `remove_dead` again, it does the same strip of `ir.Del` and postproc again, removal is reported as having occurred again, and there's the non-terminating loop.

I think the fix is to move the postprocessing fix up as a call immediately after `remove_dead` and, in fact, I think I'm going write a DCE function that basically wraps up `remove_dead` and postproc calls so something valid is produced and there's less reliance on engineers to remember the state in which `remove_dead` leaves the code (an invalid state for refcount and array comp pass).

**Comment by stuartarchibald** [comment]
New proposed patch https://github.com/stuartarchibald/numba/commit/67ee22293f298116002e40b0377e509045aa0a70 with this applied this:
```python
from numba.compiler import Pipeline, Flags, _PipelineManager
from numba.targets import registry
from numba import types, ir_utils, bytecode
from numba.tests.support import TestCase
import unittest

class Tester(Pipeline):

    @classmethod
    def mk_pipeline(cls, args, return_type=None, flags=None, locals={},
                    library=None, typing_context=None, target_context=None):
        if not flags:
            flags = Flags()
        flags.nrt = True
        if typing_context is None:
            typing_context = registry.cpu_target.typing_context
        if target_context is None:
            target_context = registry.cpu_target.target_context
        return cls(typing_context, target_context, library, args, return_type,
                   flags, locals)

    def rm_dead_stage(self):
        ir_utils.DCE(self.func_ir, typemap=self.typemap)

    def compile_to_ir(self, func, DCE=False):
        """
        Compile and return IR
        """
        self.func_id = bytecode.FunctionIdentity.from_function(func)
        self.bc = self.extract_bytecode(self.func_id)
        self.lifted = []

        pm = _PipelineManager()
        pm.create_pipeline("pipeline")
        self.add_preprocessing_stage(pm)
        self.add_pre_typing_stage(pm)
        self.add_typing_stage(pm)
        if DCE == True:
            pm.add_stage(self.rm_dead_stage, "DCE after typing")
        pm.finalize()
        res = pm.run(self.status)
        return self.func_ir


class TestThing(TestCase):

    def test_foo(self):

        def foo(x):
            y = x + 1
            dead = 0xdead
            z = y + 2
            more_dead = 0xdeaddead
            ret = z * z
            return ret

        test_pipeline = Tester.mk_pipeline((types.intp,))
        no_dce = test_pipeline.compile_to_ir(foo)
        print(no_dce.dump())

        test_pipeline = Tester.mk_pipeline((types.intp,))
        w_dce = test_pipeline.compile_to_ir(foo, DCE=True)
        print(w_dce.dump())


if __name__ == '__main__':
    unittest.main()
```
does this:
```
label 0:
    x = arg(0, name=x)                       ['x']
    $const0.2 = const(int, 1)                ['$const0.2']
    $0.3 = x + $const0.2                     ['$0.3', '$const0.2', 'x']
    del x                                    []
    del $const0.2                            []
    y = $0.3                                 ['$0.3', 'y']
    del $0.3                                 []
    $const0.4 = const(int, 57005)            ['$const0.4']
    dead = $const0.4                         ['$const0.4', 'dead']
    del dead                                 []
    del $const0.4                            []
    $const0.6 = const(int, 2)                ['$const0.6']
    $0.7 = y + $const0.6                     ['$0.7', '$const0.6', 'y']
    del y                                    []
    del $const0.6                            []
    z = $0.7                                 ['$0.7', 'z']
    del $0.7                                 []
    $const0.8 = const(int, 3735936685)       ['$const0.8']
    more_dead = $const0.8                    ['$const0.8', 'more_dead']
    del more_dead                            []
    del $const0.8                            []
    $0.11 = z * z                            ['$0.11', 'z', 'z']
    del z                                    []
    ret = $0.11                              ['$0.11', 'ret']
    del $0.11                                []
    $0.13 = cast(value=ret)                  ['$0.13', 'ret']
    del ret                                  []
    return $0.13                             ['$0.13']
None


label 0:
    x = arg(0, name=x)                       ['x']
    $const0.2 = const(int, 1)                ['$const0.2']
    $0.3 = x + $const0.2                     ['$0.3', '$const0.2', 'x']
    del x                                    []
    del $const0.2                            []
    y = $0.3                                 ['$0.3', 'y']
    del $0.3                                 []
    $const0.6 = const(int, 2)                ['$const0.6']
    $0.7 = y + $const0.6                     ['$0.7', '$const0.6', 'y']
    del y                                    []
    del $const0.6                            []
    z = $0.7                                 ['$0.7', 'z']
    del $0.7                                 []
    $0.11 = z * z                            ['$0.11', 'z', 'z']
    del z                                    []
    ret = $0.11                              ['$0.11', 'ret']
    del $0.11                                []
    $0.13 = cast(value=ret)                  ['$0.13', 'ret']
    del ret                                  []
    return $0.13                             ['$0.13']
None
```

**Comment by stuartarchibald** [comment]
Seems like one test is failing on linux32, py27 np111, with a ref count problem. Seeing if it reproduces.

**Comment by stuartarchibald** [comment]
Going to re-run the test to see if it reproduces, for reference the error was:
```
======================================================================
FAIL: test_print_values (numba.tests.test_print.TestPrint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "numba/tests/test_print.py", line 89, in test_print_values
    check_values(types.List(types.int32), (x,))
  File "/home/vsts/miniconda3/envs/travisci/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "numba/tests/support.py", line 144, in assertNoNRTLeak
    "number of data allocs != number of data frees")
AssertionError: 2L != 3L : number of data allocs != number of data frees
```
this does not seem to want to reproduce on the build farm or on a local 32bit linux box.

**Pull request merged**
