### PR TITLE
Make UnicodeType inherit from Hashable

### LINKED ISSUE #5635: Unable to create set from unicode containing numba.typed.List
```python
from numba import njit
from numba.typed import List


@njit
def foo(l):
    return set(l)


print(foo(List((1,2,3))))
print(foo(List(("a","b","c"))))
```

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

Closes #5635

### CODE REVIEW

**Comment by stuartarchibald** [comment]
I've patched the immediate problem in 189ae25 though suspect this is going to run into refcounting problems as `set` predates things which are both hashable and refcounted.

**Comment by esc** [comment]
@stuartarchibald thanks for the fix, I can confirm this fixes #5635

**Comment by stuartarchibald** [comment]
From out of band discussion, this should be limited to:

* Make `UnicodeType` inherit from `Hashable`.
* Keeping the fix for correctly resolving the `operator.eq` in the set item comparator.
* Banning the use of refcounted types in sets (they leak).

**Comment by stuartarchibald** [comment]
@esc this is now fixed up to ban ref counted types from use in `set`, resolve `eq` correctly, and also makes sure that `unicode_type` inherits from `Hashable`.

**Comment by esc** [comment]
@stuartarchibald thanks for fixing this up. I tried to run the reproducer again from #5635 and this time around I received the following somewhat strange error message:

```
Traceback (most recent call last):
  File "issue5639.py", line 1, in <module>
    from numba import njit
  File "/Users/vhaenel/git/numba/numba/__init__.py", line 213, in <module>
    import numba.typed
  File "/Users/vhaenel/git/numba/numba/typed/__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "/Users/vhaenel/git/numba/numba/typed/typeddict.py", line 23, in <module>
    def _make_dict(keyty, valty):
  File "/Users/vhaenel/git/numba/numba/core/decorators.py", line 236, in njit
    return jit(*args, **kws)
  File "/Users/vhaenel/git/numba/numba/core/decorators.py", line 173, in jit
    return wrapper(pyfunc)
  File "/Users/vhaenel/git/numba/numba/core/decorators.py", line 187, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 670, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/Users/vhaenel/git/numba/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/Users/vhaenel/git/numba/numba/core/utils.py", line 331, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/vhaenel/git/numba/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/Users/vhaenel/git/numba/numba/core/base.py", line 259, in __init__
    self.init()
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 645, in __init__
    self._init(self._llvm_module)
  File "/Users/vhaenel/git/numba/numba/core/codegen.py", line 654, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
```

**Comment by stuartarchibald** [comment]
> TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

Probably llvmlite/numba mismatch in your local env.

**Comment by esc** [comment]
@stuartarchibald nevermind, I think the state of my repository on disk was awry. I tried with a fresh copy and the error message is now as expected:

```
Use of reference counted items in 'set()' is unsupported, offending type is: 'unicode_type'.

File "issue5639.py", line 7:
def foo(l):
    return set(l)
    ^
```

**Review by esc — APPROVED** [review]
LGTM!

**Comment by stuartarchibald** [comment]
Thanks for the review.

**Pull request merged**
