### PR TITLE
Refactor Numba, part I

### PR DESCRIPTION
**Pull request by stuartarchibald**
The basic idea in this PR is to start organising the Numba code base, this will be a multi-PR effort.

This PR:
 * Adds new submodules:
    * `core` - for core Numba compiler code e.g. compilation pipeline, type inference
    * `np` - for NumPy re-implementations e.g. `np.linalg`
    * `misc` - for miscellaneous re-implementations and other features/utilities e.g. CFFI support
    * `parfors` - for the Parallel Accelerator technology
    * `stencils` - for the `@stencil` decorator implementations
    * `cpython` for CPython implementation and Python language features e.g. tuples.
    * `experimental` for experimental features e.g. `jitclass`

It then contains largely (99%+) file-at-once moves of each file in the Numba code base to somewhere appropriate. No refactoring is performed other than that necessary to fix imports or fix circular dependencies (apart from <1%). The `numba.tests` submodule remains unchanged as do most of the C-extensions. The <1% refactoring is to permit re-exporting the extension API as `numba.extension` and to fix up a few other issues.

### CODE REVIEW

**Comment by sklam** [comment]
smoketesting at `numba_smoketest_cpu_11`

**Comment by eric-wieser** [comment]
This change breaks both the [`sparse`](https://circleci.com/gh/numba/numba-integration-testing/2486?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [`clifford`](https://circleci.com/gh/numba/numba-integration-testing/2488?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) numba code (links are to CI runs). To name a few issues:

* The disappearance of `numba.numpy_support.from_dtype`
* The import `from numba.targets.imputils import impl_ret_borrowed, lower_constant` no longer working

**Comment by stuartarchibald** [comment]
> This change breaks both the [`sparse`](https://circleci.com/gh/numba/numba-integration-testing/2486?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and [`clifford`](https://circleci.com/gh/numba/numba-integration-testing/2488?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) numba code (links are to CI runs). To name a few issues:
> 
>     * The disappearance of `numba.numpy_support.from_dtype`
> 
>     * The disappearance of `numba.numpy_support.as_dtype`
> 
>     * The import `from numba.targets.imputils import impl_ret_borrowed, lower_constant` no longer working

Thanks for reporting these, we anticipated that there would be some knock-on churn is code bases consuming Numba internals and can only apologise, but is it unfortunately necessary. The Numba code base was becoming unsustainable and increasingly hard to manage, house-keeping work was needed https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/CY7oXibUwXA. Part of this will be to define a public set of APIs as we identified users doing exactly as the above projects have done, using bits of Numba internals to make things work, and this is not sustainable for anyone.

Of the things listed above, the good news is that none of the things above have disappeared, they've merely moved and will likely be exported via the public API.

**Comment by eric-wieser** [comment]
Not a complaint, just though I'd record the downstream impact here. I assume we'll end up with some checking of `distutils.version.LooseVersion(numba.__version__)` to get around this once 0.49 is released.

**Comment by eric-wieser** [comment]
Although I'd perhaps encourage you to add back `numba.numpy_support` to re-export the old functions, and emit a deprecation warning upon import - I imagine that file is used by the most downstream projects.

**Pull request merged**
