### PR TITLE
Update the release template to include updating the version table.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title, to ensure that the final release date is included in the
release branch documentation.

### CODE REVIEW

**Comment by esc** [comment]
@stuartarchibald I think the cherry-pick should go from `releaseX.Y` branch to `main` that way we can release first w/o needing to merge something to `main` first. What do you think?

**Comment by stuartarchibald** [comment]
> @stuartarchibald I think the cherry-pick should go from `releaseX.Y` branch to `main` that way we can release first w/o needing to merge something to `main` first. What do you think?

I don't mind, but either way I think _both_ have to be specified else they get forgotten, cf. https://github.com/numba/numba/pull/8187.

**Comment by esc** [comment]
> > @stuartarchibald I think the cherry-pick should go from `releaseX.Y` branch to `main` that way we can release first w/o needing to merge something to `main` first. What do you think?
> 
> I don't mind, but either way I think _both_ have to be specified else they get forgotten, cf. #8187.

I think I would prefer to make the commit on the release branch first and then cherry-pick to `main`.

**Comment by stuartarchibald** [comment]
> requesting changes as indicated by: [#8198 (comment)](https://github.com/numba/numba/pull/8198#issuecomment-1168560549)

Addressed in 5801673.

**Review by esc — APPROVED** [review]

**Pull request merged**
