### PR TITLE
workaround and unittest for issue #3016

### LINKED ISSUE #3016: ipython kernel dies when using jit
I am using numba on Windows 10 (64-bit) with Anaconda3 (v 5.2), numba 0.38.0, and numpy 1.14.3.

When I run the code attached below for test, `ident_loops` works just fine, but the ipython kernel dies if I use `jit` (`jident_loops` in the code). I tested it on spyder and jupyter notebook, but the kernel dies in both cases.

I tested the identical code on my previous machine (Ubuntu 16.04) without any problem, but it kills the kernel now. (Currently I have only Windows so I cannot test it on Ubuntu again).

I deleted Anaconda and re-installed, but nothing changed.

```python
from numba import jit
import numpy as np

def ident_loops(x):
    r = np.empty_like(x)
    n = len(x)
    for i in range(n):
        r[i] = np.cos(x[i]) ** 2 + np.sin(x[i]) ** 2
    return r

@jit
def jident_loops(x):
    r = np.empty_like(x)
    n = len(x)
    for i in range(n):
        r[i] = np.cos(x[i]) ** 2 + np.sin(x[i]) ** 2
    return r

print(ident_loops(np.arange(1000)))
print(jident_loops(np.arange(1000)))
```

Any possible solution to this...?

Added: Some other examples, e.g., at [documentation](http://numba.pydata.org/numba-doc/0.38.0/user/examples.html) seem to work without problem. So now I guess my test code is seriously problematic...?

### PR DESCRIPTION
**Pull request by anton-malakhov**
LLVM does not take type into account when it calls short vector functions from SVML. It can calculate vector width using smaller input type while actually calling SVML function that works with bigger (float64) type. This misunderstanding between SVML and LLVM leads to wrong instruction set being used for wider vectors than available on the target architecture.

WIP workaround will try to force vector width replacing LLVM's broken heuristics.

Resolves #3016

### CODE REVIEW

**Comment by anton-malakhov** [comment]
@stuartarchibald The windows CI is rather limited, without icc_rt being installed and with `--tags important` which currently does not cover the tests I added. I guess I need to mark few of them as important. BTW, can you advice how to do this for auto-generated or existing tests?

**Comment by stuartarchibald** [comment]
There is something strange going on with the Appveyor build, log: https://ci.appveyor.com/api/buildjobs/6yf4fqy100rmty9t/log

Seems like the conda env doesn't contain `icc_rt`, and I'm guessing that is because the SciPy package is older. Clearly something is forcing the environment to be resolved in an unexpected way, I'll take a look.

**Comment by stuartarchibald** [comment]
This PR:https://github.com/numba/numba/pull/3021 forces a sufficiently up to date set of packages to be downloaded and therefore has `icc_rt` present. I'm not sure why conda doesn't upgrade to 4.5.x, might be that there is a two stage upgrade path, regardless, the effect of this patch is what is needed. I'll ask for it to be reviewed ASAP so this can be tested with it.

**Comment by stuartarchibald** [comment]
Just spotted a failure on the buildfarm for this patchset with a llvmlite+llvmdev built from https://github.com/numba/llvmlite/pull/363. Python 2.7 builds are failing at test discovery time:

https://github.com/numba/numba/blob/4d8af23372100a97223ac5be9a5228b3f384ffec/buildscripts/condarecipe.local/run_test.sh#L26

with:
```
numba.tests (unittest.loader.LoadTestsFailure)
AttributeError: 'instancemethod' object has no attribute 'tags'
```
I'm going to guess that https://github.com/numba/numba/pull/3019/files#diff-0a268a00f049cf3901afe532e1725618R239 is the issue.

Also, a couple of fixes have gone in for critical issues, please could you merge Numba master into this branch to obtain these so that the buildfarm stops reporting them :)? Thanks.

**Comment by stuartarchibald** [comment]
Build farm appears happy and I've manually checked the originally reported cases. Thanks for your work on this @anton-malakhov and @dvnagorny. Merging.

**Pull request merged**
