### PR TITLE
Fix #1771: use fallback cache directory when __pycache__ isn't writable

### LINKED ISSUE #1771: Numba cache should handle lack of write permissions
Currently numba's cache will fail if the user running the code lacks write permission for the directory that code is installed in. This has come up a few times with users installing library code using `sudo`, but then trying to import it with user privileges.

### PR DESCRIPTION
**Pull request by pitrou**
This vendors the `appdirs` module from https://pypi.python.org/pypi/appdirs, and uses the current user's platform-standard cache directory (e.g. `$HOME/.cache/numba` under Unix).

### CODE REVIEW

**Comment by seibert** [comment]
To comply with the MIT license of appdirs, I think we need to put a copy of their license with our source code as well.  We can call it `LICENSE.appdirs`, or something like that.

**Comment by pitrou** [comment]
Ok, I've added licenses for the libraries we vendor in Numba.

**Comment by Deewiant** [comment]
This appears to have broken `_IPythonCacheLocator`: `self` isn't defined at https://github.com/numba/numba/commit/c6e5563581d3c63aeca1f2d25d84cd8d4d9f94dd#diff-66adccf97cb99c68d3c33d8025531cc6R724 (now https://github.com/numba/numba/blame/master/numba/caching.py#L254).

**Comment by pitrou** [comment]
> This appears to have broken _IPythonCacheLocator

Thanks for noticing. I've submitted a fix in #1926.

**Pull request merged**
