### PR TITLE
add is_ascii flag to UnicodeType

### LINKED ISSUE #3994: ASCII flag for Numba Unicode
## Feature request

CPython's Unicode implementation includes an `ascii` flag ([here](https://github.com/python/cpython/blob/31e8d69bfe7cf5d4ffe0967cb225d2a8a229cc97/Include/cpython/unicodeobject.h#L211)), which indicates that all character values are less than 128 (note that 1 byte kind can be up to 256). This flag enables significant optimizations; for example, an ASCII string is a valid UTF-8 string and no conversion is required.

### PR DESCRIPTION
**Pull request by ehsantn**
As title. ASCII flag enables optimizations such as UTF-8 conversion. See #3994.

Resolves #3994.

### CODE REVIEW

**Comment by ehsantn** [comment]
@seibert could you take a look at the changes and let me know what you think? Thanks.

**Comment by seibert** [comment]
This looks good!  Are you done with the PR?

**Comment by ehsantn** [comment]
Thanks. Yes, I'm done.

**Comment by seibert** [comment]
Ok, great.  I think this is ready to merge.

**Pull request merged**
