### PR TITLE
Support constant dtype string in nopython mode in functions like numpy.empty.

### LINKED ISSUE #3058: Array allocation for dt64
## Feature request

The usual ways of allocation for dt64 such as `np.empty(n, dtype=np.dtype('datetime64[ns]'))` and `np.empty(10, dtype='datetime64[ns]')` are required for parallel support.

### PR DESCRIPTION
**Pull request by DrTodd13**
Fixes #3058

### CODE REVIEW

**Comment by ehsantn** [comment]
I think the typers that have `_parse_dtype` should have `support_literals = True` since strings are not always constant (e.g. string type extension as in HPAT, future Numba string type).

**Comment by DrTodd13** [comment]
@ehsantn What is your suggestion here?  Is this a suggestion for something to be done in this PR or just in general?  I don't know much about this support_literals thing.

**Comment by ehsantn** [comment]
I think it should be done in this PR. `support_literals` basically enables passing of constants to typers. For strings, constants are hard-coded but this is not reliable (e.g. other string types defined).

**Comment by ehsantn** [comment]
@DrTodd13 this is not what I meant. `support_literals` should be set for the typing class, not the returned typed. For example, `NdConstructor.support_literals = True`.

To test this, you can import HPAT after importing Numba and make sure it still works.

**Comment by DrTodd13** [comment]
@ehsantn Okay.  I tried what I think you meant.

```
@infer_global(np.array)
class NpArray(CallableTemplate):
    """
    Typing template for np.array().
    """
    def __init__(self, *args, **kwargs):
        self.support_literals = True
        super(NpArray, self).__init__(*args, **kwargs)

    def generic(self):
        def typer(object, dtype=None):
            ndim, seq_dtype = _parse_nested_sequence(self.context, object)
            if dtype is None:
                dtype = seq_dtype
            else:
                dtype = _parse_dtype(dtype)
                if dtype is None:
                    return
            return types.Array(dtype, ndim, 'C')

        return typer
```
This results in:

```
ERROR: test_0d_broadcast (tests.test_parfors.TestParfors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/home/taanders/numba/in2/numba/numba/tests/test_parfors.py", line 495, in test_0d_broadcast
    self.check(test_impl)
  File "/mnt/home/taanders/numba/in2/numba/numba/tests/test_parfors.py", line 461, in check
    cfunc, cpfunc = self.compile_all(pyfunc, *args)
  File "/mnt/home/taanders/numba/in2/numba/numba/tests/test_parfors.py", line 91, in compile_all
    cpfunc = self.compile_parallel(pyfunc, sig)
  File "/mnt/home/taanders/numba/in2/numba/numba/tests/test_parfors.py", line 79, in compile_parallel
    return self._compile_this(func, sig, flags=self.pflags)
  File "/mnt/home/taanders/numba/in2/numba/numba/tests/test_parfors.py", line 76, in _compile_this
    return compile_isolated(func, sig, flags=flags)
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 159, in compile_isolated
    flags, locals)
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 881, in compile_extra
    return pipeline.compile_extra(func)
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 368, in compile_extra
    return self._compile_bytecode()
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 812, in _compile_bytecode
    return self._compile_core()
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 799, in _compile_core
    res = pm.run(self.status)
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 246, in run
    stage()
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 460, in stage_nopython_frontend
    self.locals)
  File "/mnt/home/taanders/numba/in2/numba/numba/compiler.py", line 983, in type_inference_stage
    infer.propagate()
  File "/mnt/home/taanders/numba/in2/numba/numba/typeinfer.py", line 860, in propagate
    raise errors[0]
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid use of Function(<built-in function array>) with argument(s) of type(s): (int64)
 * parameterized
In definition 0:
    NotImplementedError: const(1) cannot be represented as a Numpy dtype
    raised from /mnt/home/taanders/numba/in2/numba/numba/numpy_support.py:136
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function array>)
[2] During: typing of call at /mnt/home/taanders/numba/in2/numba/numba/tests/test_parfors.py (492)
```

If this isn't what you meant or if you already know how to do what you think it should be then can you commit the changes?

thanks

**Comment by ehsantn** [comment]
Sure, I'll add the changes.

**Comment by DrTodd13** [comment]
@ehsantn Many tests failing.  Any ideas?

**Comment by ehsantn** [comment]
Looks like the problem is that `support_literals` enables literals for all argument, but typers can't handle `Const` types replaced for others like `Integer`. Ideally, we should have literals for only `dtype`.

I think we can fix a lot of the problems but might end up disabling this for some functions to limit the scope. Will take a look now.

**Comment by ehsantn** [comment]
There are a lot of problems with `Const` type just not working through typing and lowering pipelines. I see some weird problems like llvmlite type of `Const(3,3)` being `Pointer *i8` instead of `ArrayType [2*i64]`.

**Pull request closed without merging**
