### PR TITLE
Fix #2007 (part 1). Empty array handling in np.linalg.

### LINKED ISSUE #2007: Ensure empty arrays are handled in np.linalg
The functions in `np.linalg` need to handle empty arrays, and preferably in a consistent manner. Numpy does a variety of things including `LinAlgError`s due to non-squared-ness of the trailing dimensions or due to the emptiness of arrays, `ValueError`s due to reduction operations being invalid on empty arrays, and sometimes returns `0.0`.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This largely fixes and tests the handling of empty arrays in the
Numba np.linalg implementation. Without this patch PyFatals were
rightfully being raised from the LAPACK wrappers as arguments that
should be in Z^+ were being entered as 0.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Note: this is a (part 1), because the BLAS routines used for doing `np.dot` suffer the same problem, but the implementation for `np.dot` in Numba is written using `llvmlite.ir` and should probably be rewritten using `extending.overload` before adding the guard layer for empty arrays.

**Comment by seibert** [comment]
Looks like this is failing some tests still.

**Comment by stuartarchibald** [comment]
This indeed does appear to fail. Scanning the build matrix and the failure causes it seems like Numpy has altered its behaviour through various versions. I imagine that because applying fundamental linear algebra operations to empty matrices makes limited sense, the behaviour has just been whatever conveniently materialises as a result of the implementation. I think that in the patch supplied the Numba implementation does the right thing and it is the reuse of checking code that anticipates Numpy will not raise that is the root cause of the failures. As empty matrices are corner cases and the sole reason for this patch is to prevent them coming in contact with LAPACK (causes `PyFatal`), I'm going to adjust the test cases and implementation to simply ensure that Numba handles empty matrices in a safe way and not try to replicate Numpy.

**Comment by stuartarchibald** [comment]
I raised this https://github.com/numpy/numpy/issues/10573 with Numpy.

**Pull request merged**
