### PR TITLE
Update to LLVM8 memset/memcpy intrinsic

### PR DESCRIPTION
**Pull request by sklam**
by dropping the alignment argument.

Depends on https://github.com/numba/llvmlite/pull/485

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Blocked waiting for llvmlite change.

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/llvmlite/pull/511

**Comment by sklam** [comment]
This will need to use the `dev` label for CI. Moving the new llvmlite packages to `main` will trash CI for other PRs.

**Comment by seibert** [comment]
CI has passed with build 8 of llvmlite.  Ready to merge.

**Pull request merged**
