### PR TITLE
Fix flake8 violations in numba.cuda.simulator

### PR DESCRIPTION
**Pull request by gmarkall**
This also fixes violations in `numba.cuda.kernels` and `numba.cuda.tests.cudasim`.

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
See https://github.com/numba/numba/pull/6303 for buildfarm pass.

**Comment by gmarkall** [comment]
Merge conflicts now fixed - I see I also missed `numba/cuda/decorators.py` in an earlier PR, so I've fixed that up here too.

**Review by stuartarchibald — APPROVED** [review]
Thanks for resolving conflicts etc. Change is still approved.

**Pull request merged**
