### PR TITLE
Add Documentation for atomicity of typed.Dict

### PR DESCRIPTION
**Pull request by rteja1113**
I have added some documentation and an example function in `examples/dict_usage.py` about thread-safetiness of `numba.typed.Dict` based on the discussion I had with @stuartarchibald

### CODE REVIEW

**Comment by seibert** [comment]
Hi, thanks for this contribution!  Explaining the situation with Typed Dict and multithreaded code is tricky, and I worry that the current version of this PR is actually too detailed for a typical user to follow.  Perhaps this wording would be better?

```
It should be noted that ``numba.typed.Dict`` is not thread-safe.  Specifically, functions which modify a dictionary from multiple threads will potentially corrupt memory, causing a segmentation fault.  Dictionaries can safely be read from multiple threads as long as the contents of the dictionary do not change during parallel access.
```

Also, I don't think we want to include a sample of code that users should avoid writing in the examples directory.  Does this seem reasonable?

**Comment by stuartarchibald** [comment]
@seibert I agree with this change, but also think that `causing a segmentation fault` (memory access violation) is just one symptom of corruption and perhaps `leading to all the problems that this may cause` is less platform and state specific?

**Comment by seibert** [comment]
Agreed.  @rteja1113: can you change `potentially corrupt memory, causing a segmentation fault.` to `potentially corrupt memory, causing a range of possible failures.`

Thanks for your patience as we fine-tune the wording on this!

**Comment by seibert** [comment]
Great!  I have marked this as ready to merge when we do our next batch.  Thanks!

**Pull request merged**
