### PR TITLE
update flake8 version in pre-commit config

### PR DESCRIPTION
**Pull request by esc**
As title

### CODE REVIEW

**Review by gmarkall — APPROVED** [review]
I've been using 7.1.0 in numba-cuda without issue. Assuming the code conforms to the checks in 7.1.1 I think this is all good.

**Comment by gmarkall** [comment]
Looks like this is based on an older numba `main` without the fix for `I` which is causing the RTD failure.

**Comment by gmarkall** [comment]
This does pass the CI check for flake8 (e.g. https://dev.azure.com/numba/numba/_build/results?buildId=17631&view=logs&j=92a5d2dc-b1c1-5fd3-be4c-f2c5b5a37a8d&t=ebba113b-92c8-51ef-f1d6-addd9e14f1f7) so I think just a merge of `main` should be sufficient for CI to pass here.

**Comment by esc** [comment]
@gmarkall rebased to latest `main`.

**Comment by max-sixty** [comment]
Thanks @esc !

---

Relatedly (but not necessarily coupled to this), how about moving the `.flake8` file up to the root, so running just `flake8` works?

(I also offered over in #9630 to help with adding `black` & `ruff`, which both configure from `pyproject.toml`, and have largely replaced `flake8` in most of the projects I work with, let me know if that's of interest!)

**Comment by esc** [comment]
> Thanks @esc !
> 
> Relatedly (but not necessarily coupled to this), how about moving the `.flake8` file up to the root, so running just `flake8` works?

Worth a shot.

> (I also offered over in #9630 to help with adding `black` & `ruff`, which both configure from `pyproject.toml`, and have largely replaced `flake8` in most of the projects I work with, let me know if that's of interest!)

Yes, `black` is interesting and `ruff` too. I use `black` in https://github.com/numba/numba-rvsdg -- with great success and am considering moving that project to `ruff` in fact. Also, it uses `rennovate` to update the config for `pre-commit` and in addition a `makefile` to always lint with `pre-commit` such that the same versions of code run when developing locally and on GitHubActions via `make lint`. 😉

**Comment by max-sixty** [comment]
Thanks a lot for merging this! (will follow up on the dev tools in the other threads!)

**Pull request merged**
