### PR TITLE
Build script and CI cleaning

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Review by esc — COMMENTED** [review]
Looks good. Only one question: what is the rationale for removing the `conda remove` calls?

**Comment by stuartarchibald** [comment]
> Looks good. Only one question: what is the rationale for removing the `conda remove` calls?

Don't think it does anything relevant now: https://dev.azure.com/numba/numba/_build/results?buildId=8094&view=logs&j=1ff4b108-0112-514f-244f-ad14c6740773&t=a2e66a41-fc4d-56d0-598f-e4eb5ea889da&l=2387

**Comment by stuartarchibald** [comment]
43f0099 strips down the build matrix a bit, organises it by: python version->NumPy version->features, and renames the env to `azure_ci`.

**Review by esc — APPROVED** [review]
LGTM

**Comment by sklam** [comment]
https://github.com/numba/numba/pull/6787 will unblock this PR

**Pull request merged**
