### PR TITLE
Enable SVML for erf/erfc/gamma/lgamma/log2

### PR DESCRIPTION
**Pull request by anton-malakhov**
@sklam I checked it on all our configs and this seem to work. Is it outdated or do you have other platforms which needs `numba_` functions workarounds?
This patch also add `func_impl`-like variables everywhere just for sake of consistensy

### CODE REVIEW

**Comment by seibert** [comment]
Usually the most problematic platform is Windows + Python 2.7.  The runtime is the oldest because we have to build with VS2008 to be compatible with standard Python extensions.

**Comment by anton-malakhov** [comment]
It looks like you abandoned VS2008 recently while moving to LLVM 4.0

**Comment by seibert** [comment]
Not entirely, I don't think.  We go through a bit of a dance to make this work, where llvmlite contains a pure C wrapper around the parts of LLVM we need and we compile that with newer Visual Studio. 
 Then we call that C library through ctypes, while compiling the Numba Python extension using the standard compiler for Python.  I don't think that has changed, but @sklam should correct my memory if I have the details wrong.

**Comment by anton-malakhov** [comment]
I'm surprised to see failure even on Linux py35 for `test_gamma` - this one works for me. There is probably different libc version

**Comment by seibert** [comment]
@sklam: Can you test this PR on our internal buildbot systems?

**Comment by sklam** [comment]
The PR looks fine on our buildbot.  Merging.

**Pull request merged**
