### PR TITLE
Fix casting of start/stop in linspace

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Fixes mainline following merge of https://github.com/numba/numba/pull/7265.

**Comment by esc** [comment]
`Build numba_smoketest_cpu_yaml_64 has started`

**Comment by esc** [comment]
Screen Shot 2021-11-22 at 18 23 51

The build was fine, except for all the tasks related to Python 3.10 and/or Numpy 1.21

**Comment by esc** [comment]
In order to fix `master` and all the failing PRs, I will merged this now.

@stuartarchibald thank you for the patch!

**Review by esc — APPROVED** [review]

**Pull request merged**
