### PR TITLE
[WIP] Test with NumPy 1.26

### PR DESCRIPTION
**Pull request by gmarkall**
Testing with NumPy 1.26.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuCI is busted, but tests are OK locally on my machine.

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by esc** [comment]
@gmarkall can this be closed, now that #9227 is merged?

**Pull request closed without merging**
