### PR TITLE
Fix #8628: Don't test math.trunc with non-float64 NumPy scalars

### LINKED ISSUE #8628: CUDA fail on `main`: `type numpy.float32 doesn't define __trunc__ method`
Reproducer:

```
$ NUMBA_ENABLE_CUDASIM=1 python runtests.py numba.cuda.tests.cudapy.test_math.TestCudaMath.test_math_trunc
E
======================================================================
ERROR: test_math_trunc (numba.cuda.tests.cudapy.test_math.TestCudaMath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_math.py", line 658, in test_math_trunc
    self.unary_template_float32(math_trunc, np.trunc)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_math.py", line 222, in unary_template_float32
    self.unary_template(func, npfunc, np.float32, np.float32, start, stop)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_math.py", line 240, in unary_template
    cfunc[1, nelem](A, B)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 122, in __call__
    bm.run(grid_point, *fake_args)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 296, in run
    raise t.exception[0].with_traceback(t.exception[1])
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 189, in run
    super(BlockThread, self).run()
  File "/home/gmarkall/mambaforge/envs/numbadev/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 274, in target
    self._f(*args)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_math.py", line 204, in math_trunc
    B[i] = math.trunc(A[i])
TypeError: tid=[42, 0, 0] ctaid=[0, 0, 0]: type numpy.float32 doesn't define __trunc__ method

----------------------------------------------------------------------
Ran 1 test in 0.011s

FAILED (errors=1)
```

This probably stems from #8605, especially since it went through without a BuildFarm run (my bad decision and bad advocacy for such a decision), but I'm not sure how it got through CI in the first place.

### PR DESCRIPTION
**Pull request by gmarkall**
This fixes an issue introduced by the `test_math_trunc` test from PR #8605 - I have no idea how the problem initially managed to sneak past CI.

See numpy/numpy#13375. `__trunc__` is not defined for NumPy scalars other than `float64`, so we can't call `math.trunc(x)` in the CUDA simulator for NumPy scalars `x` if they are not `float64` type.

Fixes #8628.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by sklam** [comment]
it seems AzureCI is not picking up the new tests:

```
NUMBA_ENABLE_CUDASIM=1 $SEGVCATCH python -m numba.runtests -b -v -g -m $TEST_NPROCS -- numba.tests
/home/vsts/work/1/s/numba/core/decorators.py:240: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
/home/vsts/work/1/s/numba/core/decorators.py:240: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)

----------------------------------------------------------------------
Ran 0 tests in 0.000s
```

**Comment by sklam** [comment]
confirmed to be gitdiff problem: https://github.com/numba/numba/issues/8631

**Comment by sklam** [comment]
The later sliced test run should have picked up the test by there's no way to confirm

**Review by sklam — APPROVED** [review]
Fix confirmed manually

**Pull request merged**
