### PR TITLE
Fix ds_permute types and add tests

### PR DESCRIPTION
**Pull request by stuartarchibald**
This fixes the `ds_{,b}permute` intrinsic typing so that only
32bit types can be used in the source, whereas the index lane
can be int32 or int64. Tests are added.

### CODE REVIEW

**Comment by seibert** [comment]
Seems to be failing on ROCm worker due to missing type signatures.  Example:
```
ERROR: test_shuf_device_inclusive_scan (numba.roc.tests.hsapy.test_scan.TestShuffleScan)
----------------------------------------------------------------------
[snip]
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function ds_permute at 0x7fa696933730>) with argument(s) of type(s): (int64, int64)
Known signatures:
 * (int32, int32) -> int32
 * (int64, int32) -> int32
 * (int32, float32) -> float32
 * (int64, float32) -> float32
[snip]
```
Looks like tests are expecting ds_permute with `(int64, int64)` and `(int64, uint32)` signatures.

**Comment by stuartarchibald** [comment]
Thanks for pushing it through the build farm. I think the former signature is invalid as that would be a 64bit src, however the latter should be ok, I'll add that.

**Comment by stuartarchibald** [comment]
Root cause was that `scan` testing was written for `intp` moving this to `int32` fixes.

**Comment by stuartarchibald** [comment]
This needs https://github.com/numba/numba/pull/3294 before testing else the compiler will fail on lock assertions.

**Pull request merged**
