### PR TITLE
Unicode type iteration

### PR DESCRIPTION
**Pull request by stuartarchibald**
This makes the unicode type iterable and also fixes up a selection
of other things that were causing minor issues on the way. Not
limited to:

 * Contractual clarity over reference ownership in `iternext_impl`
 * Matching debug print with function names in C code
 * PEP8

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Closes https://github.com/numba/numba/issues/3836 and https://github.com/numba/numba/issues/3835

**Comment by seibert** [comment]
Is the reference ownership issue such that it makes sense to be explicit about `new_ref=False` in all the existing uses of `iternext_impl` as form of documentation?

**Comment by stuartarchibald** [comment]
RE:https://github.com/numba/numba/pull/3842#issuecomment-470989247 It could be, wonder if new, borrowed and untracked all ought to be quantified and specification required?

**Comment by stuartarchibald** [comment]
@seibert what do you think of https://github.com/stuartarchibald/numba/commit/83ae05190e49ad66caf7c5e8e7c8b3cef3c2a9c8?diff=unified ?

**Comment by seibert** [comment]
I think that is a good change.  Most booleans turn into enums anyway.  :)

**Comment by stuartarchibald** [comment]
@seibert thanks, I've appended that patch in 8aa830a

**Comment by seibert** [comment]
Need to merge master into this PR and fix the dictionary usage of `iternext_impl`.

**Comment by stuartarchibald** [comment]
This is ready for re-review, dictionaries are fixed up.

**Comment by seibert** [comment]
Looks good.  Ready to merge.

**Comment by ehsantn** [comment]
Are the changes to `@iternext_impl` breaking here? BTW, it is not documented in general.

**Pull request merged**
