### PR TITLE
Fix #1911: allow function annotations on jitclass methods

### LINKED ISSUE #1911: jitclass decorator fails when encountering annotations (numba 0.25)
When using jitclass decorator, if ANY of the methods in the class have annotations, the compilation fails. 
This is the code sample sufficient to trigger the error:
```
spec={
'obj':int32,
}

@jitclass(spec)
class TTT(object):
    def __init__(self, obj:int):
        self.obj = obj

    def add(self, v:int):
        return self.obj + v
```
This is the traceback:
```
python3.4 test.py 
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    class TTT(object):
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/base.py", line 170, in register_class_type
    __doc__=docstring))
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/base.py", line 70, in __new__
    outcls._set_init()
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/base.py", line 76, in _set_init
    argspec = inspect.getargspec(init)
  File "/usr/lib64/python3.4/inspect.py", line 936, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```
This is not really a major issue, but I am certain it is easy to fix. 
Thank you!

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by seibert** [comment]
This looks fine, but do we run the risk of misleading people into thinking Numba uses the type annotations?

**Comment by pitrou** [comment]
Hopefully they would quickly notice that whatever they put in the annotations doesn't change the way Numba compiles their functions.

**Comment by seibert** [comment]
Right, I don't think using annotations should ever be an error.  I wasn't sure if we should emit a warning telling users that Numba ignores Python 3 type annotations.

**Comment by pitrou** [comment]
I don't think so, as type annotations can be used for documentation or offline type checking (see e.g. https://www.python.org/dev/peps/pep-0484/).

**Comment by seibert** [comment]
OK, makes sense.

**Pull request merged**
