### PR TITLE
Fix cuda.In freeing devary before the kernel launch

### PR DESCRIPTION
**Pull request by sklam**
as titled.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch. Whilst this is being fixed, seems like the same patch series added a dependency on `six`?

https://github.com/numba/numba/blob/a4b70ccc3936b51e4932408e076ee5da84056494/numba/cuda/args.py#L1-L9

**Comment by seibert** [comment]
Oh, that's an issue.  We've vendored six functionality into Numba (since we only needed a small amount of it).  Is `add_metaclass` large, or can we add the implementation to `numba.six`?

**Comment by stuartarchibald** [comment]
It's already in I think, pretty sure I've used it elsewhere from `numba.six`.

https://github.com/numba/numba/blob/a4b70ccc3936b51e4932408e076ee5da84056494/numba/six.py#L782-L795

**Comment by seibert** [comment]
Ah, OK.  @sklam: Can you add a quick commit to this PR to switch where `add_metaclass` is imported from?

**Comment by sklam** [comment]
Done

**Comment by stuartarchibald** [comment]
Thanks for the fix @sklam, looks good, this can be merged as convenient on CI pass.

**Pull request merged**
