### PR TITLE
Refresh the registries in get_function early and always.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by gmarkall** [comment]
xref: https://github.com/numba/numba/issues/7507

**Comment by gmarkall** [comment]
Does this fix the issue for the reproducer in #7507?

**Comment by stuartarchibald** [comment]
> Does this fix the issue for the reproducer in #7507?

Yes. But it's costly in performance.

**Comment by gmarkall** [comment]
It does seem to do a lot of redundant work, like loading everything again, when really all we need to do is install new things from the registry added since last time. I wonder if on each refresh we can clear the registry from which typing refreshes, so that next time we refresh, it doesn't do the same things over and over?

**Comment by stuartarchibald** [comment]
> It does seem to do a lot of redundant work, like loading everything again, when really all we need to do is install new things from the registry added since last time. I wonder if on each refresh we can clear the registry from which typing refreshes, so that next time we refresh, it doesn't do the same things over and over?

This lazy approach is carried out to some extent at a relatively low level via: https://github.com/numba/numba/blob/805e24fbd895d90634cca68c13f4c439609e9286/numba/core/utils.py#L466-L482
it might be possible to improve the performance of the logic ahead of this though.

**Comment by stuartarchibald** [comment]
Closing for now, need to reduce the cost of the reload to make this feasible.

**Pull request closed without merging**
