### PR TITLE
Python 3.7 compat: _Py_Finalizing becomes _Py_IsFinalizing()

### PR DESCRIPTION
**Pull request by mingwandroid**
Hopefully a fairly simple one?

### CODE REVIEW

**Comment by stonebig** [comment]
when can we hope to see a numba dev for Python-3.7 ? python-3.7.0b4 is supposed ABI frozen

**Comment by seibert** [comment]
Our next Numba release candidate (0.39) is June 18, and we are aiming to have Python 3.7 support included in the release.  Some time during this development cycle we will work on it.

Note that beyond this minor C API change, we expect that changes will be required in Numba's front-end bytecode analyzer, since some of the bytecodes have changed in Python 3.7.

**Comment by stonebig** [comment]
ok, thank you for the information.

**Comment by stuartarchibald** [comment]
@mingwandroid  this is a quick impl of the new op codes https://github.com/stuartarchibald/numba/commit/5abd7d45dd400169d610a2fb84d6f6ec4a60d0b2, if you need something that actually runs to do Python 3.7 testing.

**Comment by seibert** [comment]
Looks good! @stuartarchibald will open another PR with the Python 3.7 bytecode fixes

**Comment by stonebig** [comment]
small remark (may be of interest for you, maybe not): 
- I have a strange issue on python-3.7.0b4 64 bit, when combining holoviews/datashader/bokeh/numba-0.38 compiled per cgohlke.
- alll is great on python-3.7.0b4 32 bit.

https://github.com/ioam/holoviews/issues/2738

**Comment by seibert** [comment]
Can you open a new issue on this?  If there is a Numba problem on Windows, it will be more easily tracked there.

**Comment by stonebig** [comment]
not sure it's because of numba or python-3.7.0b4, so I would be interested on seeing a true numba-0.39dev to re-check as soon as python-3.7.0rc is out.

**Comment by seibert** [comment]
@stonebig: Actually, this is sounding suspiciously like #2998.  Can you try running your test on Window 64-bit with `NUMBA_DISABLE_INTEL_SVML=1` set in your environment?

**Comment by stonebig** [comment]
a DOS variable  ?  trying

**Comment by stonebig** [comment]
also the other test gives a different result than the two listed in #2998 
numba-38-for-py37

**Comment by stonebig** [comment]
result is normal on my Pythn-3.7.0b4 32 bit: 10.0 everywhere

**Comment by stonebig** [comment]
did I give all informations you wanted ?

**Comment by stonebig** [comment]
hum same initial "1.0" problems on python-3.6 64 bit. re-checking my own issue there  ...

**Comment by stonebig** [comment]
so... aparently latest numba/llvmlite didn't solve my proble on python-3.7.0 64 bit, but downgrading to pandas-0.23.0 did. so my problem may rather  be related to https://github.com/bokeh/bokeh/issues/7916

**Comment by stonebig** [comment]
problem still there today on python-3.7.0 with pandas-0.23.3

**Comment by stuartarchibald** [comment]
@stonebig I'm not sure I follow, what precisely is the problem you are reporting? Numba >0.38.1 has fixes for the SVML problem above (https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/-zinTCxLUoQ) and Numba 0.39.0 (released a few days ago) works with Python 3.7.

**Pull request merged**
