### PR TITLE
[Experiment] Using env_manager.read_const(env_manager.add_const(...)) in boxers

### PR DESCRIPTION
**Pull request by asodeur**
Currently most boxers use `pyapi.unserialize(pyapi.serialize_object(MyClass))` to get the class object for boxing. Ths PR is using `env_manager.read_const(env_manager.add_const(MyClass)` instead. The benefit is to avoid unpickleing the class object which might help boxing performance.

The impact on memory is not fully understood, yet. On the one hand using `env_manager` will reduce 
the size of the resulting code as the string constant with the pickled object is avoided, on the other hand the class object might be kept alive for longer (but that should only be relevant for dynamically created classes).

One breaking API change is required: `env_manager` now is a mandatory argument to `pyapi.from_native_value` (was optional before).

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the PR. Nice use of `[Experiment]` :), indeed we'll need to spend some time looking into the impact of such a change. @sklam noted `add_const` seems to predate the `{de,}serialize` pattern.

**Comment by asodeur** [comment]
Turns out this does not neccessarily play nice with caching. Results in segfaults when a function using `env_manager` is called by another jitted function for example when unboxing native values. AFAIK this does not happen in the current Numba codebase as the only risk should be `objmode` blocks and those do not get cached due to dynamic globals.

The `{de,}serialize` pattern is safe in any case.

**Comment by stuartarchibald** [comment]
@asodeur ok, thanks for trying it out. Presume this can be closed now so am closing it. If you think otherwise please feel free to re-open. Thanks!

**Comment by asodeur** [comment]
Using the `{de,}serialize` pattern with a global constant avoids unpickling the class object for every instance to be boxed and should play nice with caching.

```python
def _get_serialized_constant(box_context, value, name=None, prefix='numba.cached.pyobject'):
    """global constant pyobject initialized from a serializable value

       The recommended pattern for getting hold of the Python class 'klass' in a boxer is
       context.pyapi.unserialize(context.pyapi.serialize_object(klass)). However, this can
       be expensive
    """
    mod = box_context.builder.module
    optional_typ = types.Optional(types.pyobject)
    ll_optional_typ = box_context.context.get_value_type(optional_typ)

    assert name or (hasattr(value, '__module__') and hasattr(value, '__name__'))
    name = name or f'{value.__module__}.{value.__name__}'
    gv = mod.add_global_variable(ll_optional_typ, name=f'{prefix}.{name}')
    gv.linkage = 'linkonce_odr'
    gv.initializer = cgutils.get_null_value(ll_optional_typ)

    opt_val = cgutils.create_struct_proxy(optional_typ)(box_context.context, box_context.builder, value=box_context.builder.load(gv))
    with box_context.builder.if_then(box_context.builder.not_(opt_val.valid)):
        val = box_context.pyapi.unserialize(box_context.pyapi.serialize_object(value))
        opt_val.valid = cgutils.true_bit
        opt_val.data = val
        box_context.builder.store(opt_val._getvalue(), gv)

    val = opt_val.data
    box_context.pyapi.incref(val)

    return val
```

**Comment by esc** [comment]
@asodeur thanks for the update on this. Would you like to re-open the issue?

**Comment by eric-wieser** [comment]
It seems numba already uses this pattern internally for dtypes, but nothing else:

https://github.com/numba/numba/blob/015dbf83df8b11bb25d0aa6b96cae809939dfaf6/numba/core/boxing.py#L398

https://github.com/numba/numba/blob/015dbf83df8b11bb25d0aa6b96cae809939dfaf6/numba/core/pythonapi.py#L1501

Are these uses safe despite the conslusion in this PR that broad application was unsafe?

**Comment by asodeur** [comment]
I think all current usage of `env_manager` is safe. It is the interaction of `env_manager` and cached code that will cause trouble.

**Pull request closed without merging**
