### PR TITLE
Improve errors / warnings for cuda vectorize decorator

### PR DESCRIPTION
**Pull request by gmarkall**
The CUDA vectorize decorator provides harsh feedback to users who provide it with unexpected arguments - an assertion failure with no further information. This commit changes the decorator in the following ways:

1. The `nopython` kwarg is now accepted, albeit with a warning that it is redundant on CUDA. The cpu and parallel targets do also accept this kwarg.
2. Provide a `KeyError` for other unsupported kwargs, consistent with the CPU and parallel targets.

The additional tests check the expected behaviour for all targets. For ths CPU target the decorator is tested with and without a signature, in order to check for normal ufuncs and dynamic ufuncs.

Minor changes:
- The `check_warnings` context manager is made available for tests by inheriting from `CheckWarningsMixin`, which contains an implementation from `tests/npyufunc/test_errors.py`.
- A small whitespace error in `test_vectorize_decor.py` is also corrected.

### CODE REVIEW

**Comment by gmarkall** [comment]
... Now I've just decided to make the PR, I've just realised the source of the issue: I'm running CUDA tests in the main `numba.tests` package, and it is not surprising that it doesn't work!

**Comment by gmarkall** [comment]
Now that I have the CUDA tests in the right place, things are looking better - I've removed the [WIP] tag and I believe this is ready for review.

**Comment by seibert** [comment]
running internal CI: `numba_65`

**Comment by seibert** [comment]
passing on Linux, not going to wait for windows workers to catch up...

**Pull request merged**
