### PR TITLE
Remove dependency on intel-openmp for OSX

### LINKED ISSUE #7468: Building w/OpenMP on macOS
This changeset ( https://github.com/numba/numba/commit/a23bc195096178e5849ebc0fb6dcedbd6f0cbeea ) was added to fix building on macOS previously. While packaging 0.54.1, we needed to switch to `llvm-openmp`. This seemed to work well despite issues previously. Given this, am wondering do we still need the custom handling here for macOS?

### PR DESCRIPTION
**Pull request by stuartarchibald**
Solely the llvm-openmp package can provide the necessary headers
and runtime.

Fixes #7468

### CODE REVIEW

**Comment by stuartarchibald** [comment]
This is likely going to need manual testing on OSX and almost certainly with conda-build, and quite possibly forcing the use of a NumPy without `intel-openmp` linked in, just to make sure that the `llvm-openmp` changes are ok.

**Comment by esc** [comment]
There is some mention of `intel-openmp` in the docs too:

https://github.com/numba/numba/blob/master/docs/source/user/installing.rst

it may very well be worth cleaning this up too as part of this PR!

**Comment by stuartarchibald** [comment]
> There is some mention of `intel-openmp` in the docs too:
> 
> https://github.com/numba/numba/blob/master/docs/source/user/installing.rst
> 
> it may very well be worth cleaning this up too as part of this PR!

Thanks, if this patch works, will grep and remove references.

**Comment by sklam** [comment]
I've tested this on my MBP.  👍 

```
__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: Intel
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.
```

**Comment by stuartarchibald** [comment]
> I've tested this on my MBP. +1
> 
> ```
> __Threading Layer Information__
> TBB Threading Layer Available                 : False
> +--> Disabled due to Unknown import problem.
> OpenMP Threading Layer Available              : True
> +-->Vendor: Intel
> Workqueue Threading Layer Available           : True
> +-->Workqueue imported successfully.
> ```

Thanks for testing/confirming @sklam.

**Comment by stuartarchibald** [comment]
> There is some mention of `intel-openmp` in the docs too:
> 
> https://github.com/numba/numba/blob/master/docs/source/user/installing.rst
> 
> it may very well be worth cleaning this up too as part of this PR!

@esc this is now done in https://github.com/numba/numba/pull/7786/commits/c19c741eaac490e749a4b0cbe6c5dbb2dc33d5b5, thanks!

**Review by esc — APPROVED** [review]
OK, great! Thank you, looks good!

**Pull request merged**
