### PR TITLE
Speed up import time by not importing `unittest` or `multiprocessing` until it is needed

### PR DESCRIPTION
**Pull request by eric-wieser**
This also avoids importing `multiprocessing` for the trivial `cpu_count()` function that [just wraps](https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/multiprocessing/context.py#L41-L47) `os.cpu_count()` in a way that isn't useful.

This reduces the import time by 7% on my machine (measured with `py -3.8 -S -Ximporttime -c "import numba"`, either by comparing before and after, or subtracting the components due to these imports). Here is the graph before this patch:

image

The two large pale-blue elements are the ones eliminated by this PR.
The next-lowest hanging fruit is #4927, which would contribute substantially to reducing the remaining import time.

### CODE REVIEW

**Comment by gmarkall** [comment]
Thanks very much for the PR, I've queued it for review.

**Comment by gmarkall** [comment]
gpuci run tests

**Review by gmarkall — CHANGES_REQUESTED** [review]
Many thanks for this! It speeds up import by about 2-3% on my machine (I had to import site though, to allow llvmlite to import the way I've got things set up).

The changes look good to me, with one exception - it appears to remove the configuration variable `NUMBA_DEFAULT_NUM_THREADS`, which is referenced here in the documentation: https://numba.readthedocs.io/en/latest/reference/envvars.html#envvar-NUMBA_NUM_THREADS (in the description).

Since `num_threads_default()` still runs at import time, can its result be kept in `NUMBA_DEFAULT_NUM_THREADS` so that this variable is still available, in case anyone is using it?

**Comment by gmarkall** [comment]
Note that #7627 is RTM, so this PR needs no further action.

**Comment by eric-wieser** [comment]
> it appears to remove the configuration variable `NUMBA_DEFAULT_NUM_THREADS`, which is referenced here in the documentation:

Ah, I assumes these were just local variables, I wasn't expecting something to be iterating through `locals()` and putting them in the global namespace!

**Comment by gmarkall** [comment]
> Ah, I assumed these were just local variables, I wasn't expecting something to be iterating through `locals()` and putting them in the global namespace!

Yes, `config.py` is horrible! :-)

**Comment by gmarkall** [comment]
... We have talked about making `numba.core.config` an object instead of a module, which would make it a bit more sane, but I think nobody's yet found the time to try out making that change.

**Pull request merged**
