### PR TITLE
Self-recursion hack

### PR DESCRIPTION
**Pull request by pitrou**
This PR revives the approach in PR #719. Self-recursion is supported, only with an explicit signature, and with the same signature in the recursive call(s).

### CODE REVIEW

**Comment by datnamer** [comment]
Awesome! Is this a step on the way to full higher order functions?

**Comment by seibert** [comment]
Not really.  This sidesteps the need for changes to our type inference algorithm by pre-registering the signature of the recursive function (which is why we require an explicit type signature for recursion support).  Higher order functions are a very different problem.  :)

**Comment by datnamer** [comment]
Makes sense. Are there any plans to pursue higher order functions?

**Comment by seibert** [comment]
It's not a high priority at this point.  We have a lot more basic issues to solve first.

**Pull request merged**
