### PR TITLE
patch to compile _devicearray.cpp with c++11

### PR DESCRIPTION
**Pull request by esc**
This is a copy of #6693 for `master`

----------------------------------

On OSX this resolves:

```
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - 1 warning and 3 errors generated.
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:100:19: error: use of undeclared identifier 'nullptr'
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject *m = nullptr;
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -                   ^
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:101:19: error: use of undeclared identifier 'nullptr'
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject *d = nullptr;
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -                   ^
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:102:23: error: use of undeclared identifier 'nullptr'
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject *c_api = nullptr;
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -                       ^
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO - numba/_devicearray.cpp:20:5: warning: private field 'ob_base' is not used [-Wunused-private-field]
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     PyObject_HEAD
[2021-02-05 04:26:34,227] {bash_operator.py:132} INFO -     ^
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO - /Users/ci/miniconda3/envs/testenv_96344ff4-013b-4e58-856d-c4b7bb365115/include/python3.6m/object.h:83:50: note: expanded from macro 'PyObject_HEAD'
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO - #define PyObject_HEAD                   PyObject ob_base;
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO -                                                  ^
[2021-02-05 04:26:34,228] {bash_operator.py:132} INFO - 1 warning and 3 errors generated.
```

### CODE REVIEW

**Review by gmarkall — APPROVED** [review]
Looks good to me.

**Comment by esc** [comment]
@gmarkall do we want to take this opportunity to discuss how to "do this properly"?

**Comment by gmarkall** [comment]
I'm wondering whether its a problem that will just go away in time - IIRC the issue this PR resolves happens building wheels on Mac because that uses an old compiler that defaults to C++03. Is there a point in the future where a newer compiler that defaults to C++11 would be used for wheels on Mac? (are there mac equivalents of things like "manylinux"? - I'm struggling to work out the landscape of Mac builds).

I'm concerned we could use a lot of time trying to find the "proper" way to do this, when in general it's hard to do anything "proper" in a setup.py, especially if we can just wait for the problem to go away. The fix presented in this PR isn't that egregious, so the benefit of the "proper" way might be quite limited.

**Comment by stuartarchibald** [comment]
> I'm wondering whether its a problem that will just go away in time

I suspect this to be the case. IIRC it's lack of C++11 as standard on system compilers causing this problem.

**Comment by esc** [comment]
@gmarkall @stuartarchibald ok great, I am happy with the solution also.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch!

**Pull request merged**
