### PR TITLE
Adds support for viewing the CFG of the ELF disassembly.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. Requires `radare2` to be installed on the system and
the prescence of the `r2pipe2` package. In jupyter-notebooks the
`graphviz` package is needed to get a SVG via dot format. On the
terminal nothing further is required.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
I've no intention for this to be merged yet, this is more so we have something and can work out what we want from it.

**Comment by stuartarchibald** [comment]
Note from Numba meeting. Move impl to `numba.misc.` and add note in docs about how to install and make work.

**Comment by stuartarchibald** [comment]
> I reviewed this PR by trying it in both `ipython` and `jupyter notebook` it works fine.

Thanks very much.

> The only thing that took me a while is to figure out that I need to call `inspect_disasm_cfg()` on the dispatcher object. While this may be obvious for seasoned Numba developers and users it wasn't for me initially. So, my recommendation is to add a tiny section to the developer docs with a simple example (and maybe two screenshots) showing the feature in action, maybe "notes on visualizing a CFG with radare2".

To be consistent with the other `.inspect_*` functions I've elected to update the reference documentation for the dispatcher, see http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#dispatcher-objects .

**Comment by stuartarchibald** [comment]
Marking for merged based on https://github.com/numba/numba/pull/5212#pullrequestreview-372965546. Thanks again for the review @esc.

**Comment by dlee992** [comment]
Hi, can we add a small feature to allow saving this cfg into a file when trying to get this cfg graph?
For example, I don't want to check this graph in an interactive way, I just want to compile everything and save all CFGs for further checking later.
If having this small feature, I think it would be nicer!

**Pull request merged**
