### PR TITLE
Fix CI failure due to missing files when installed

### PR DESCRIPTION
**Pull request by sklam**
https://github.com/numba/numba/pull/5174 failed internal CI because some files needed by testing is not included in the installation.

This patch adds two `__init__.py` so that `find_packages()` in `setup.py` will automatically pick up the needed directories.

### CODE REVIEW

**Comment by esc** [comment]
@sklam thanks for the fix.

**Comment by esc** [comment]
Will queue this for internal CI

**Comment by esc** [comment]
Running as `numba_107`

**Comment by esc** [comment]
@sklam do you know why this only appears on OSX?

**Comment by esc** [comment]
Also windows and some of the aarch stuff.

**Comment by sklam** [comment]
It's whether the test is running is the source root and whether numba is setup.py installed. The new `nested` module test are not installed.

**Pull request merged**
