### PR TITLE
fix #5199

### LINKED ISSUE #5199: Eq-Comparison of `Optional(unicode_type)` and `unicode_type` does not work
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import jit, types

@jit(types.boolean(types.unicode_type, types.Optional(types.unicode_type)), nopython=True)
def foo(x, y):
    return x == y

assert foo('horst', 'horst')    # should compare equal even though the second arg is forced to Optional()
```

### PR DESCRIPTION
**Pull request by asodeur**
fixes #5199

### CODE REVIEW

**Comment by esc** [comment]
@asodeur thanks for submitting this, you efforts to improve Numba are, as always, much appreciated! I have queued it for review now.

**Comment by stuartarchibald** [comment]
Thanks @asodeur. Fix looks valid, could do with 2x test though please, one for `==` and another for `!-=`. Thanks!

**Comment by asodeur** [comment]
Had to change the implementation strategy as the first attempt did fix the issue for the original reproducer but could still get bypassed in other cases. This PR now contains the following changes:

1. `typing.templates.FunctionTemplate` used to try and unpack optionals if the template did not match with optionals. This prevents templates later in the list being tried even if they would have matched including the optionals. This PR is now moving this logic to `types.functions.BaseFunction.get_call_type` such that all templates are tried without unpacking optionals first. Failing to match, all templates are tried again with unpacked optionals. (@sklam: @stuartarchibald asked me to loop you in on this on Gitter)
2. Implementations for `operator.eq` for `None` (`cython.builtins.gen_none_eq`) and `unicode_type` (`cython.unicode.unicode_(eq|ne)`) will no longer match if one of the arguments is optional.
3. Added explicitly unpacking implementations for `eq`, `ne`, and `contains` to `core.optional`
4. Added test cases for the original issue to `tests.test_unicode`

*WARNING*: I've seen unexpected complications when adding an explicitly unpacking implementation for `add`, [see](https://gist.github.com/asodeur/d79e7b08785a286ac024fc2c033af01f). Not sure this is an issue with this PR or with array expressions.

**Comment by sklam** [comment]
It seems like it is necessary complexity for handling `Optional`. I will need a little more time to review this and any potential complications.

**Pull request closed without merging**
