### PR TITLE
CUDA: Add Support to Creating `StructModel` Array

### PR DESCRIPTION
**Pull request by isVoid**
This PR adds support to creating a cuda array of user defined `StructModel` type. An example usage is like:

```python
from numba import cuda, types
from numba.core.extending import register_model, models, make_attribute_wrapper

class Float3(types.Type):
    def __init__(self):
        super().__init__(name='float3')

float3 = Float3()

@register_model(Float3)
class Float3Model(models.StructModel):
    def __init__(self, dmm, fe_type):
        members = [
            ("x", types.float32),
            ("y", types.float32),
            ("z", types.float32),
        ]
        super().__init__(dmm, fe_type, members)


make_attribute_wrapper(Float3, "x", "x")
make_attribute_wrapper(Float3, "y", "y")
make_attribute_wrapper(Float3, "z", "z")

@cuda.jit
def use_struct_array_kernel():
    x = cuda.local.array(3, dtype=float3)

use_struct_array_kernel[1, 1]()
```

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by isVoid** [comment]
Oops, apologies for the typo.

**Comment by gmarkall** [comment]
> Question: I think you meant to use the registered type to construct an array?
> 
> ```python
> x = cuda.local.array(3, dtype=types.Float3)
> ```

There isn't a `types.Float3` because `Float3` is part of the Numba extension that the example defines. The `dtype` should be a NumPy type or an instance of a Numba type, which is what `float3` is (from `float3 = Float3()` in the example).

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by ajschmidt8** [comment]
gpuci run tests

**Comment by ajschmidt8** [comment]
gpuci run tests

**Comment by ajschmidt8** [comment]
gpuci run tests

**Comment by ajschmidt8** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
/azp run
gpuci run tests

**Review by gmarkall — CHANGES_REQUESTED** [review]
I think this is looking good and almost ready to merge:

* I think the fail is because https://github.com/numba/numba/pull/7817 needs merging to resolve an issue with the docs build (unrelated to this PR, so shouldn't be an issue)
* Could you rename `utils.py` to `extension_usecases.py` in line with the naming of other files containing test use cases please?
* I was going to suggest editing the docs to mention that CUDA extensions can be used in shared and local memory now, but I note there's absolutely no documentation on extending the CUDA target that's part of the official documentation at the moment. This is something that we ought to fix, but not for this PR.

**Comment by gmarkall** [comment]
gpuci run tests

**Review by gmarkall — APPROVED** [review]
Many thanks for the latest round of changes - this now looks good to me!

**Comment by gmarkall** [comment]
@esc Could this have a CUDA smoketest buildfarm run please?

**Comment by esc** [comment]
`Build numba_smoketest_cuda_yaml_116 has started`

**Comment by esc** [comment]
> `Build numba_smoketest_cuda_yaml_116 has started`

Was 💚

**Comment by esc** [comment]
I think this can be marked as ready to merge!

**Pull request merged**
