### PR TITLE
Explicit Parallel Loop Support (prange)

### PR DESCRIPTION
**Pull request by ehsantn**
This provides support for specifying parallel loops using `prange`. Scalar reductions using in-place operators are inferred. This PR includes several improvements to ParallelAccelerator core such as liveness and copy propagation. This PR is also based on PR https://github.com/numba/numba/pull/2379.

This addresses #2183 #2371 #2087 #1193 #1403 issues (at least partially).

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for adding this, it's a nice feature. As this is an extension of #2379 I'll leave code review until that is merged to master and this rebased on it as it'll reduce the diff. From a functional point, here's a few samples that don't seem to behave as expected (most things I've tried work fine :-)).

```python
n = 4
A = np.ones((n), dtype=np.float64)

#segfault
def prange_test101(A):
    """ just hangs or segfaults"""
    s = 0
    for i in prange(n, 1):
        s += A[i]
    return s

# fail
def prange_test5(A):
    """ doesn't support step size other than 1, but this is step of 1?"""
    s = 0
    for i in prange(1, n - 1, 1):
        s += A[i]
    return s

# fail
def prange_test6(A):
    """ doesn't support step size other than 1, but this is step of 1?"""
    s = 0
    for i in prange(1, 1, 1):
        s += A[i]
    return s
```

**Comment by ehsantn** [comment]
Thanks for the test cases, @stuartarchibald . We will investigate ASAP.

**Comment by ehsantn** [comment]
@stuartarchibald PR is rebased to reduce diff.

**Comment by ehsantn** [comment]
The tests in https://github.com/numba/numba/pull/2391#issuecomment-306210322 work with sequential lowering and seem to be backend problems. @ninegua @DrTodd13

**Comment by ninegua** [comment]
The above mentioned tests run just fine for me. I have failures in test_mvdot and test_prange4, both in copy propagation, and this is after I cherry picked commit e36df80439fecfcda55cac5177eee909b3ce601b, without which there are more failures in copy propagation. Could very well be some python environment differences...

But what exactly is failing? The test about `np.ones((1,))`?

**Comment by ehsantn** [comment]
Sorry, please pull again (some test errors). For me test_prange5 and test_prange6 say `assert(step == 1) # We do not support loop steps other than 1` and test_prange7 throws seg fault.

Valgrind shows invalid memory read in threads if you can't reproduce seg faults.

**Comment by ehsantn** [comment]
Looks like `case09: np.ones(([x for x in range(3)]))` in `test_bulk_cases` somehow corrupts data structures! `ir_utils.visit_vars_extensions` becomes empty at some point. Without it, the copy propagation errors go away.

**Comment by stuartarchibald** [comment]
@ehsantn @ninegua I've added a few `prange` uses here, most have some problem at present and I've commented with what I can see. https://github.com/stuartarchibald/numba/commit/d41e3cfc57ed68358a13f8c501adcb56198c237c

To the current issues...
I can replicate the `assert(step == 1)` problem, seems like `step` is an `ir.Var` instance.

The bulk tests (https://github.com/numba/numba/pull/2391/files#diff-44914098195178c859436d0f2377912bR312) that add no value in this context can probably be dropped/moved to more a general ParallelAccelerator test. I think in the merged patch the tests ought to assert known behaviours opposed to the printing etc. As they were my doing, I'm happy to patch up to be consistent with the rest of the Numba test suite once the work on this branch is near finished if that's convenient?

**Comment by ehsantn** [comment]
@stuartarchibald thanks for the new test cases. We will investigate. Previous issues seem to be fixed now.

Feel free to fix the bulk cases and submit a PR against the prange branch. I don't think there will be conflicts.

**Comment by ehsantn** [comment]
@ninegua `test_prange8` has wrong output in parallel backend but works with sequential backend. The IR looks fine to me but I might have missed something. Could you take a look?

**Comment by ehsantn** [comment]
`test_prange9` is similar also.

**Comment by ehsantn** [comment]
@stuartarchibald I fixed the issue with `test_prange11` but I recommend removing it since `list.append` implemented [here](https://github.com/numba/numba/blob/master/numba/targets/listobj.py#L719) doesn't seem thread-safe.

**Comment by ninegua** [comment]
@ehsantn The debug print shows that for `test_prange8` there is no `array_size_var` for array `A`. The lowering relies on this information to pass array shapes when calling gufunc. I was under the impression that there the `array_size_var` is always defined for all arrays? If this is not the case, I'll stop relying on this information and instead get the size in lowering.

**Comment by ehsantn** [comment]
@ninegua `array_size_var` is supposed to be defined only when required but this is getting too complicated. Let's just use it for parfor generation and not rely on it afterwards. The size information is available in lowering anyways.

**Comment by ninegua** [comment]
The problem was actually `strides` was mistakenly used in place of `shape`, not related to `array_size_vars`. But in any case, I've removed the reliance of parfor lowering on `array_size_vars`. This fixed `test_prange8`.

The problem with `test_prange9` is related to initial values for reduction variable. For numpy array sum or product, this is initialized in `init_block`, but the parfor conversion for `prange` is not doing this, and `test_prange9` exposes a case where the accumulator starts with a non-zero value for `+`. I've fixed this problem by enforcing the initial value for reduction variables by operator name at lowering stage.

However, there is another problem with recognizing reduction variables. The logic in `get_parfor_reductions` is not entirely correct, e.g., it will mistakenly treat locally defined accumulator variables as reduction variables for the loop, but they were actually not defined outside the loop. The situation will quickly become nastier in nested case. We'll need a few more test cases for this.

**Comment by stuartarchibald** [comment]
@ehsantn @ninegua I've added something to make testing a bit easier/simpler here https://github.com/IntelLabs/numba/pull/11, it should apply cleanly on https://github.com/numba/numba/pull/2391/commits/81f927063342467a5962cd62b115c29353a5e0c9 if you are happy with it.

**Comment by ehsantn** [comment]
@stuartarchibald Thanks, looks good.

**Comment by ehsantn** [comment]
Here is summary of current errors:
`test_prange11`: I think the test is invalid since list.append is not thread-safe. The behavior is as expected.
`test_prange13`: back-end should cast range size to int64 if necessary.
`test_simple21`: we don't support vector dot but we probably should.
`test_simple05/06`: the errors are the same without parallel flag. Passing a list to `np.ones()` is invalid.
@stuartarchibald if you agree with this assessment, we can remove the invalid tests.

**Comment by stuartarchibald** [comment]
@ehsantn thanks, I agree with the assessment:
* `test_prange11`: Delete. I'll file a ticket.
* `test_prange13`: Delete. I'll file a ticket.
* `test_simple21`: mark as skip for now? I think this is documented as working, so perhaps un-document it or fix?
* `test_simple05/06`: Delete. I'll move them over to the  array comprehension constructor tests (https://github.com/numba/numba/pull/2400).

@ninegua mentioned needing a few more test cases here https://github.com/numba/numba/pull/2391#issuecomment-307641924 shall I try and conjure some up in relation to awkward accumulators etc?

**Comment by ehsantn** [comment]
@stuartarchibald I updated the tests and filed a ticket for the vector dot issue. Feel free to add more accumulator tests. Maybe a new ticket for reduction/accumulator tests is better to keep the diff small.

**Comment by stuartarchibald** [comment]
@ehsantn @ninegua @DrTodd13 many thanks to you all for your work on this, especially resolving issues found in testing. This is a great feature I'm happy to merge.

**Comment by ehsantn** [comment]
Thank you @stuartarchibald for helping us test and improve this.

**Pull request merged**
