### PR TITLE
Add location information to exceptions.

### PR DESCRIPTION
**Pull request by stuartarchibald**
~This is WIP, still has segfaults and other problems.~ Fixed and seemingly works.

The purpose is to synthesize a new frame in the traceback so that errors raised from jitted user code have location information present so that users can easily identify the source of the exception.

e.g. Without the patch this:
```
$ cat test11.py 
from numba import njit

@njit
def foo():
    raise ValueError('a')

foo()
```
does this:
```
Traceback (most recent call last):
  File "test11.py", line 7, in <module>
    foo()
ValueError: a
```
and with it, it does this:
```
<debug stuff elided>
Traceback (most recent call last):
  File "test11.py", line 7, in <module>
    foo()
  File "test11.py", line 5, in foo
    raise ValueError('a')
ValueError: a
```
vanilla Python does this:
```
Traceback (most recent call last):
  File "test11.py", line 7, in <module>
    foo()
  File "test11.py", line 5, in foo
    raise ValueError('a')
ValueError: a
```
essentially, this patch makes Numba match Python.

### CODE REVIEW

**Comment by sklam** [comment]
@stuartarchibald, the problem you are seeing is due to the `PyArg_ParseTuple` has reference-borrowing semantic and the `Py_DECREF(exc)` is releasing the only owner of `loc`.

https://github.com/numba/numba/blob/9011ab6783bf2effc9c7378eb579c1847dc43ced/numba/_helperlib.c#L909-L914

You can use `_PyObject_Dump(loc);` before and after the `Py_DECREF(exc)` to check for the refcount of `loc`.  Here's what I got:
```
===== before ======

object  : ('padding', 'foo', 'chk3325.py', 5)
type    : tuple
refcount: 1
address : 0x1131c8bd8
===== after ======

object  : <refcnt 0 at 0x1131c8bd8>
type    : tuple
refcount: 0
address : 0x1131c8bd8
```

**Comment by stuartarchibald** [comment]
Thanks @sklam, indeed that was it.

**Comment by stuartarchibald** [comment]
3eba267 has got this to the point where `npm` exceptions have a new frame injected into the traceback during exception handling if location information is available. This is probably sufficient for now.

**Comment by stuartarchibald** [comment]
This can be reviewed now. I'm probably going to take a hard look at it again myself, especially the Python C API part.

**Comment by sklam** [comment]
We should also check the reference count with the `-R` flag to `runtests.py` under a debug build of python.  See https://github.com/numba/numba/pull/607/files

**Pull request merged**
