### PR TITLE
prefer to import from collections.abc

### LINKED ISSUE #4733: Python 3.7 warns on `from collections import Iterable`
[This line](https://github.com/numba/numba/blob/master/numba/types/containers.py#L3) in `containers.py` is causing a `DeprecationWarning` on python3.7. Is that a known issue? The message is `Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

### PR DESCRIPTION
**Pull request by mattip**
fixes #4733

### CODE REVIEW

**Comment by esc** [comment]
The 'py35_np111_cov' errors will be fixed via

https://github.com/numba/numba/pull/4736

The 'macOS py27_np16'  errors point towards a missing c header. I am not sure if this is Numba's fault:



```
 ========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/runner/runners/2.158.0/work/_temp/e5bfcc1c-ec3f-4325-8d27-a6b9a7e46255.sh

# Build numba extensions without silencing compile errors
python setup.py build_ext -q --inplace
/Users/runner/miniconda3/envs/travisci/lib/python2.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '0.47.0dev0+71.gc3d6bbeda' to '0.47.0.dev0+71.gc3d6bbeda'
  normalized_version,
TBB not found
('Using OpenMP from:', '/Users/runner/miniconda3/envs/travisci')
running build_ext
building 'numba._dynfunc' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are installed.
C compiler: x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -isysroot /opt/MacOSX10.9.sdk -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9

creating build
creating build/temp.macosx-10.9-x86_64-2.7
creating build/temp.macosx-10.9-x86_64-2.7/numba
compile options: '-I/Users/runner/miniconda3/envs/travisci/include/python2.7 -c'
extra options: '-g'
x86_64-apple-darwin13.4.0-clang: numba/_dynfuncmod.c
clang-4.0: warning: no such sysroot directory: '/opt/MacOSX10.9.sdk' [-Wmissing-sysroot]
In file included from numba/_dynfuncmod.c:1:
In file included from numba/_dynfunc.c:6:
In file included from numba/_pymodule.h:6:
/Users/runner/miniconda3/envs/travisci/include/python2.7/Python.h:33:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
error: Command "x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -isysroot /opt/MacOSX10.9.sdk -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Users/runner/miniconda3/envs/travisci/include/python2.7 -c numba/_dynfuncmod.c -o build/temp.macosx-10.9-x86_64-2.7/numba/_dynfuncmod.o -g" failed with exit status 1
##[error]Bash exited with code '1'.
##[section]Finishing: Build
```

The 'py37_np116_tbb' build is shown as failing on github, but looking at the latest build on azure, this doesn't seem to be the case anymore:

https://dev.azure.com/numba/numba/_build/results?buildId=2932

**Comment by esc** [comment]
So, only the macOS issue remains which is unrelated to this PR and the flake8 exception is solved by: #4736

**Comment by esc** [comment]
The fix looks good, but maybe a better approach would be to add `Iterable` to this:

https://github.com/numba/numba/blob/master/numba/six.py#L782

And then import it from there?

**Comment by mattip** [comment]
Adding Iterable to `six.py` implies it is a python2-to-python3 change. `containers.abc` was added in python3.3 and the direct use of `containers` deprecated in 3.7, removed in 3.8.

**Comment by esc** [comment]
@mattip while I don't disagree with your statement, maybe we should be of the view that `six.py` has evolved more into a compatibility layer within the Numba project. Having said that, maybe`six.py` is the wrong place for those imports, maybe this should go in `numba/utils.py`? This also appears to have Python version compatibility code. What do you think?

**Comment by mattip** [comment]
makes sense, and I see there are others in six as well. Sorry for the noise. Done in 23f3022

**Comment by esc** [comment]
@mattip thanks for fixing this up! I'll wait for CI to complete and then mark it as ready to merge. One small note: I see that you rewrote the git history and then force pushed? Within the Numba project this is discouraged since we have had issues with Github not handling such situations correctly in the past.  I guess it doesn't really matter for this small PR but please be aware of this limitation for any future PRs you should wish to submit.

Thanks very much for submitting this, your efforts to improve Numba are appreciated!

**Comment by esc** [comment]
The CI status is good enough for me. Some of the tests have timed out, but I think it is inconsequential. The one failure on macOS is currently broken on the Azure side so it can be ignored safely. If something really did break, which none of us expect, it will show up in our internal CI system. Marking as ready for merge.

**Pull request merged**
