### PR TITLE
Add support for CUDA atomic subtract operations

### PR DESCRIPTION
**Pull request by testhound**
This pull request adds support for CUDA atomic subtract.

1. Adds support for atomic subtract
2. Adds units tests for integer, float32 and float64
3. Adds documentation for atomic subtract.

### CODE REVIEW

**Comment by gmarkall** [comment]
@testhound Many thanks for the PR! The tests are presently failing because the [CUDA Simulator](https://numba.readthedocs.io/en/stable/cuda/simulator.html) doesn't implement atomic subtract - to implement support for it, you can add a `sub` method to [`FakeCUDAAtomic`](https://github.com/numba/numba/blob/master/numba/cuda/simulator/kernelapi.py#L105) following a similar pattern to that implemented for `add`, `max`, etc.

A couple of general notes on testing: The public CI tests CUDA only with the simulator (mainly to ensure that the simulator functions correctly, but also there is no GPU CI for Numba). You can test locally with the simulator by setting the environment variable `NUMBA_ENABLE_CUDASIM=1`.

**Review by gmarkall — CHANGES_REQUESTED** [review]
On the whole the PR is looking great! There are some small suggestions on the diff, which are all minor things just aimed at making the code and docstrings a bit clearer / more comprehensible for the future - I know that the majority of this is derived from the existing implementations of atomic add, etc., so the things I'm pointing out are inherited from them, but I hope that for new code we can improve it a bit as we go along as well.

Between these small fixes, and the implementation of atomic subtract in the simulator, that should get this PR ready to go.

**Review by gmarkall — APPROVED** [review]
Many thanks for the changes! This is looking good to me, and passes all tests with the simulator and the device target.

**Comment by stuartarchibald** [comment]
Thanks for the PR. There's more scope in here for generating and sharing code across `add` and `sub` particularly in the testing, but I think in this case it's better to get the functionality in and refactor in a subsequent PR. Will run through the farm now.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_102`.

**Comment by stuartarchibald** [comment]
Buildfarm passed.

**Review by stuartarchibald — APPROVED** [review]

**Comment by stuartarchibald** [comment]
Thanks for reviewing @gmarkall 

Congratulations on your first contribution to Numba @testhound !

**Comment by testhound** [comment]
> Thanks for the PR. There's more scope in here for generating and sharing code across `add` and `sub` particularly in the testing, but I think in this case it's better to get the functionality in and refactor in a subsequent PR. Will run through the farm now.

@stuartarchibald can you provide some of your thoughts about additional code sharing? I am beginning work on the remaining atomics and would like to keep our ideas in mind.

**Comment by stuartarchibald** [comment]
> > Thanks for the PR. There's more scope in here for generating and sharing code across `add` and `sub` particularly in the testing, but I think in this case it's better to get the functionality in and refactor in a subsequent PR. Will run through the farm now.
> 
> @stuartarchibald can you provide some of your thoughts about additional code sharing? I am beginning work on the remaining atomics and would like to keep our ideas in mind.

I think in cases where there's a lot of repetition and the variations are just on a function from e.g. the `operator` module it's possible to make use of code generation and/or to write the invariant part and loop over the variations. Example of code gen: https://github.com/numba/numba/commit/9e54c7d78a2d35379724e9e8dfb1b225fd887d96

In the case of the unit tests, all the add/sub tests are identical apart from the operation, I would consider just iterating over the functions (add/sub) with the same test code in the loop body. This would make it so additional tests written would automatically get picked up for both `add` and `sub` and it present one test series to maintain instead of two.

@gmarkall are you happy with the above suggestion? There's a fine line between obfuscation and maintainability to tread but I think in cases like this shrinking the literal quantity of code is beneficial.

**Comment by gmarkall** [comment]
> @gmarkall are you happy with the above suggestion? There's a fine line between obfuscation and maintainability to tread but I think in cases like this shrinking the literal quantity of code is beneficial.

I'm happy with both suggestions - I was thinking that the duplication in `cudadecl` was going to get a little bit much (though that didn't worry me so much) but the atomics tests will get pretty long if a few more operations are added.

**Pull request merged**
