### PR TITLE
Remove separate _npymath_exports module

### PR DESCRIPTION
**Pull request by pitrou**
The registration logic for npymath functions is factored into _helperlib.

### CODE REVIEW

**Comment by seibert** [comment]
Can we add a test for this?

**Comment by seibert** [comment]
actually, I think I got ahead of myself.  Does this fix #1945?

**Comment by pitrou** [comment]
No, it doesn't. That's a preliminary, but the next steps are still uncertain.

**Comment by seibert** [comment]
Ah, OK.

**Pull request merged**
