### PR TITLE
WIP: @overload inliner

### PR DESCRIPTION
**Pull request by stuartarchibald**
Built on this https://github.com/numba/numba/pull/3743, contains the same bugs as a result :)

Intention is to be able to do this:

```python
from numba import njit, types
from numba.extending import overload

def bar(a):
    pass


@overload(bar, force_inline=True)
def _bar(a):
    if isinstance(a, types.Integer):
        def impl(a):
            return a + 10
    else:
        def impl(a):
            return a / 17
    return impl

@njit
def foo(z):
    x = z + 1
    y = bar(x)
    return y + 3


print(foo(10.2))
```
which does the IR change:
```
---------------------------------before inline----------------------------------
label 0:
    z = arg(0, name=z)                       ['z']
    $const0.2 = const(int, 1)                ['$const0.2']
    $0.3 = z + $const0.2                     ['$0.3', '$const0.2', 'z']
    del z                                    []
    del $const0.2                            []
    x = $0.3                                 ['$0.3', 'x']
    del $0.3                                 []
    $0.4 = global(bar: <function bar at 0x7fc07c9b5268>) ['$0.4']
    $0.6 = call $0.4(x, func=$0.4, args=[Var(x, inline_overload.py (20))], kws=(), vararg=None) ['$0.4', '$0.6', 'x']
    del x                                    []
    del $0.4                                 []
    y = $0.6                                 ['$0.6', 'y']
    del $0.6                                 []
    $const0.8 = const(int, 3)                ['$const0.8']
    $0.9 = y + $const0.8                     ['$0.9', '$const0.8', 'y']
    del y                                    []
    del $const0.8                            []
    $0.10 = cast(value=$0.9)                 ['$0.10', '$0.9']
    del $0.9                                 []
    return $0.10                             ['$0.10']
None
--------------------------------------------------------------------------------
-----------------------------------propagate------------------------------------
---- type variables ----
[$0.3.3 := float64,
 $0.4.4 := float64,
 $const0.2.2 := Literal[int](17),
 a.0 := float64,
 arg.a := float64]
-----------------------------------propagate------------------------------------
---- type variables ----
[$0.3.3 := float64,
 $0.4.4 := float64,
 $const0.2.2 := Literal[int](17),
 a.0 := float64,
 arg.a := float64]
---------------------------------Variable types---------------------------------
{'$0.3.3': float64,
 '$0.4.4': float64,
 '$const0.2.2': Literal[int](17),
 'a.0': float64,
 'arg.a': float64}
----------------------------------Return type-----------------------------------
float64
-----------------------------------Call types-----------------------------------
{a.0 / $const0.2.2: (float64, float64) -> float64}
----------------------------------after inline----------------------------------
label 0:
    z = arg(0, name=z)                       ['z']
    $const0.2 = const(int, 1)                ['$const0.2']
    $0.3 = z + $const0.2                     ['$0.3', '$const0.2', 'z']
    del z                                    []
    del $const0.2                            []
    x = $0.3                                 ['$0.3', 'x']
    del $0.3                                 []
    a.0 = x                                  ['a.0', 'x']
    del x                                    []
    $const0.2.2 = const(int, 17)             ['$const0.2.2']
    $0.3.3 = a.0 / $const0.2.2               ['$0.3.3', '$const0.2.2', 'a.0']
    del a.0                                  []
    del $const0.2.2                          []
    $0.4.4 = $0.3.3                          ['$0.3.3', '$0.4.4']
    del $0.3.3                               []
    $0.6 = $0.4.4                            ['$0.4.4', '$0.6']
    del $0.4.4                               []
    y = $0.6                                 ['$0.6', 'y']
    del $0.6                                 []
    $const0.8 = const(int, 3)                ['$const0.8']
    $0.9 = y + $const0.8                     ['$0.9', '$const0.8', 'y']
    del y                                    []
    del $const0.8                            []
    $0.10 = cast(value=$0.9)                 ['$0.10', '$0.9']
    del $0.9                                 []
    return $0.10                             ['$0.10']
None
--------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by stuartarchibald** [comment]
This is a long way from being ready, needs neatening and tests, but the general idea is there. CC @ehsantn @sklam.

**Comment by ehsantn** [comment]
Thank you @stuartarchibald . This is very useful. Looks like there will be a redundant compilation of `bar` during type inference as part of overload resolution. Can it be avoided for inlined overloads? In some cases, the overload implementation can contain placeholder functions that can't be lowered.

**Comment by stuartarchibald** [comment]
@ehsantn something like that in cf8ba15 might work? Basically, run the compiler frontend up to typing to allow the construction of a signature for future typing, but do not run the backend?

**Comment by stuartarchibald** [comment]
Also wonder if the notion of `"inline this function regardless"` should be indicated by a kwarg named `alwaysinline` cf. the llvm function attribute? This may be convenient if it ever becomes useful to do analyis for inlining/inline-hinting with respect to some thresholds as the kwargs can follow the same pattern. Alternatively, the kwarg could be `inlineattr` with a value set like `{'always', 'hint', 'noinline'}`?

**Comment by ehsantn** [comment]
@stuartarchibald yes, your commit seems to do the trick for avoiding the backend.

**Comment by ehsantn** [comment]
Having all the three inlining options makes sense to me and seems useful long term. But supporting the `hint` one can be challenging.

**Comment by ehsantn** [comment]
Note from previous core meeting: `@overload_method` can be supported here similarly.

**Comment by stuartarchibald** [comment]
Closing this, https://github.com/numba/numba/pull/4208 supersedes, @ehsantn thanks for the comments, #4208 attempts to accommodate.

**Pull request closed without merging**
