### PR TITLE
Deprecate the use of iternext_impl without RefType

### PR DESCRIPTION
**Pull request by stuartarchibald**
This adds back in support for the old API for iternext_impl but
adds in a deprecation warning, documents and tests this.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
CC @jpivarski, hope this helps.

**Comment by seibert** [comment]
rerunning CI because of glitched out anaconda.org last night

**Comment by seibert** [comment]
This looks great, and I'm glad you were able to coerce it into the existing decorator.   :)

**Comment by jpivarski** [comment]
Thanks! I've talked with known users of awkward-numba and our plan is to increase our minimum Numba version to the first version with the RefType API soon after it's officially released. I'm told there are some production systems downstream that will take a little effort to upgrade, but not substantial—thanks for the breathing room!

**Comment by stuartarchibald** [comment]
Thanks @seibert, the `None` default thankfully left things open for this sort of change.

@jpivarski no problem, thanks for orchestrating downstream. Hopefully the integration tests for awkward-numba will pass again as new builds start shipping.

**Comment by esc** [comment]
Indeed, integration-testing for awakward is fine again: https://circleci.com/gh/numba/numba-integration-testing/189

**Pull request merged**
