### PR TITLE
CUDA: Add NVVM test of all 8-bit characters

### PR DESCRIPTION
**Pull request by gmarkall**
This test case is adapted from https://github.com/numba/llvmlite/pull/53 and is used to ensure that the encoding used by llvmlite does not cause issues with NVVM.

This is as suggested in https://github.com/numba/llvmlite/pull/655#issuecomment-732255325

I've tested this with llvmlite using both the `latin1` and `utf-8` encodings, and it passes in both cases.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Bumped for CI.

**Comment by stuartarchibald** [comment]
might need merge in from mainline to pick up the changes that fix the doc builds

**Comment by gmarkall** [comment]
Merge made - hopefully this next build passes.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch, good to have this test in Numba.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_144`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_144`.

Passed.

**Pull request merged**
