### PR TITLE
implement aligned allocator

### PR DESCRIPTION
**Pull request by sklam**
* Implement memalign in nrt
* Align array data buffer to 32-bytes as recommended for AVX (see https://software.intel.com/en-us/articles/practical-intel-avx-optimization-on-2nd-generation-intel-core-processors)

### CODE REVIEW

**Comment by seibert** [comment]
This patch takes the approach of allocating aligned memory by padding the request, and then offsetting the returned pointer to meeting the alignment requirement.  Is there no portable way to ask the operating system for an aligned malloc directly?

**Comment by seibert** [comment]
To answer my own question, `aligned_alloc` is part of the C11 standard:

http://en.cppreference.com/w/c/memory/aligned_alloc

Of course, we can't require a C11 compiler for Numba, so maybe rolling our own aligned allocator is the only portable option.

**Comment by pitrou** [comment]
Another issue with the official aligned allocation APIs is that they don't provide a realloc() equivalent. Granted, we don't need one yet, but perhaps some day...

**Comment by sklam** [comment]
I should add that posix has memalign() in malloc.h and uses free() for deallocation. But, win32 uses _aligned_malloc(), which requires _aligned_free() for deallocation (https://msdn.microsoft.com/en-us/library/8z34s9c6.aspx).

**Comment by sklam** [comment]
There's a segfault on 32-bit platform that I need to debug.

**Comment by seibert** [comment]
this needs to remerge with master

**Comment by sklam** [comment]
Resolved issues with 32-bit platform.

**Pull request merged**
