### PR TITLE
Drop pre-3.7 code path (CPU only)

### PR DESCRIPTION
**Pull request by sklam**
Intentionally separating work for non-CPU code path.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@sklam is this intended for 0.57?

**Comment by sklam** [comment]
> @sklam is this intended for 0.57?

Sure. We already dropped py<3.7.

**Review by esc — CHANGES_REQUESTED** [review]
I compared #7920 and #8318 today. It turns out, that neither is complete and both contain changes not present in the other. Also, they can't be merged into each other due to conflicts..

Moving forward, I suggest @sklam picking the following changes:

https://github.com/numba/numba/pull/8318/files#diff-2df48118bba9e73a681d271761e063d5f84ea485bd00b65c7afd7799fba930c7L1107-R1114

https://github.com/numba/numba/pull/8318/files#diff-bf52cc8cc7ef5a7f153acd1c35784daeba459c55aff21631e7d399b83e65ee5cL2128-R2159

https://github.com/numba/numba/pull/8318/files#diff-b925aa196d8a9aa356e639fb4af8049c9ad14ebb16d8f71b9df2d976d46a29c2L4-R181

**Review by jamesobutler — COMMENTED** [review]
Yes my changes that were brought over here appear to make the coverage of dropping all pre-3.7 code complete 👍🏻

**Comment by esc** [comment]
@sklam thank you for fixing this up! @jamesobutler thank you for your review. I tried a few `git grep` combinations locally and only found two potentially remaining instances

This is comment, but it seems like it is a "dead comment" now:

https://github.com/numba/numba/blob/main/numba/tests/test_withlifting.py#L1109-L1110

This could be made more precise by using `== (3, 7)`: 

https://github.com/numba/numba/blob/main/numba/tests/test_withlifting.py#L767

**Comment by esc** [comment]
> > This is comment, but it seems like it is a "dead comment" now:
> > https://github.com/numba/numba/blob/main/numba/tests/test_withlifting.py#L1109-L1110
> 
> changed in [d2d76a6](https://github.com/numba/numba/commit/d2d76a663bcbb7d0df4eb0b81176f425362ee2ff)

Thank you

> > This could be made more precise by using `== (3, 7)`:
> > https://github.com/numba/numba/blob/main/numba/tests/test_withlifting.py#L767
> 
> I prefer to leave it as `<= (3, 7)`. I consider that as defensive programming

ok, that makes sense.

**Comment by esc** [comment]
`Build numba_smoketest_cpu_yaml_130 has started`

**Comment by esc** [comment]
> `Build numba_smoketest_cpu_yaml_130 has started`

Has passed fine.

**Comment by sklam** [comment]
@esc, can you approve this PR please?

**Review by esc — APPROVED** [review]
LGTM

**Comment by esc** [comment]
> @esc, can you approve this PR please?

done.

**Pull request merged**
