### PR TITLE
Enable fence for all architecture and add developer notes

### PR DESCRIPTION
**Pull request by sklam**
This patch makes the atomic refct fences enabled on all architecture.  This ensures that we are safe on all platform where this fences are effect-ful.  On x86/amd64, the fences are no-op, such that no assembly is emitted for them.  On PPC64LE, both acquire/release fences lowers to `lwsync`.   No check was done on ARM.

I have also checked the alternative to memory fence by putting the "ordering" attribute to the atomic operations directly.  I concluded that the usage of fences is probably better because the "acquire" fence is on a branch, whereas the ordering attribute will lowers to two unavoidable fences that are surrounding the atomic-op.

Developer notes are added because the memory-order fences are non-trivial.  It is important to note that the release fences go before the corresponding write, but the acquire fences go after the corresponding read.  

Last note, there's a interesting paragraph in https://en.cppreference.com/w/cpp/atomic/memory_order

> Typical use for relaxed memory ordering is incrementing counters, such as the reference counters of std::shared_ptr, since this only requires atomicity, but not ordering or synchronization (note that decrementing the shared_ptr counters requires acquire-release synchronization with the destructor)

### CODE REVIEW

**Comment by stuartarchibald** [comment]
On ARM this comes out as:
```asm
NRT_decref:
        .fnstart
        cmp     r0, #0
        bxeq    lr
        dmb     ish
.LBB5_1:
        ldrex   r1, [r0]
        sub     r2, r1, #1
        strex   r3, r2, [r0]
        cmp     r3, #0
        bne     .LBB5_1
        cmp     r1, #1
        beq     .LBB5_4
        bx      lr
.LBB5_4:
        dmb     ish
        b       NRT_MemInfo_call_dtor
.Lfunc_end5:
        .size   NRT_decref, .Lfunc_end5-NRT_decref
        .fnend
```
which I think is correct, `ldrex, strex` pair around the `sub`

**Comment by stuartarchibald** [comment]
Thanks for this, patch seems valid and covers all architectures at once!

**Comment by seibert** [comment]
Forgot to merge this after review.

**Comment by obilaniu** [comment]
@sklam I went into some detail about the exact requirements for reference count fencing in #2780 . [The reason why I was hesitant to make it unconditional](https://github.com/numba/numba/pull/2780#issuecomment-378887330) is that on x86 at least, an explicit fence _isn't_ quite a no-op. It's a tiny bit stronger, and unnecessarily so given the strong ordering of x86.

However, the fences did need to be enabled for ARM as well as for PowerPC, and the resulting ARM assembler above is indeed valid.

For the `release` fence, we don't actually need to enforce that all prior reads/writes complete _before the read of the reference counter_ (which is what the fence does). We only need to enforce that all prior reads/writes complete _before the successful **write back to** that reference counter_.

Then, _if_ that reference counter got dropped to zero, we don't necessarily have to enforce that all destructor read/write activity happens after the `0`-write to the reference counter becomes globally-visible; It's enough that the destructor read/write activity began strictly after a `1` was read from the reference counter, since from that moment the destruction of the object in the current thread is a foregone conclusion, and all changes made by other threads were ordered by the `release` fence before the store that fed this thread's load.

As I explained in #2780, x86's memory ordering is so strong that a RMW instruction, such as `lock`'ed atomic decrements or CAS, are sufficient to provide those guarantees (due to those instructions being both read and write, and due to the general lack of read-read or write-write reordering in x86). That is why x86 code already worked fine without the fences.

**Pull request merged**
