### PR TITLE
Merge py3.11 branch to main

### PR DESCRIPTION
**Pull request by sklam**
Based on ~https://github.com/numba/numba/pull/8814~ https://github.com/numba/numba/pull/8831. This merges py3.11 into main.

### CODE REVIEW

**Comment by sklam** [comment]
The only failure is due to https://github.com/numba/numba/issues/8824.

**Comment by sklam** [comment]
Buildscripts are untouched up to this point

**Comment by sklam** [comment]
`numba_pynext_cpu_yaml_3`

**Comment by sklam** [comment]
> `numba_pynext_cpu_yaml_3`

Essentially passed all tests on linux-64 for py[3.10, 3.11] x np[1.23, 1.24]. Only failures are caused llvm14 based llvmlite not picked up by the dag.

**Comment by sklam** [comment]
Notes for reviewer:
- https://github.com/numba/numba/pull/8822/commits/c4168f12a464108f7d5e1b98f5c5b4ac3cf56f8f merge `py3.11` onto `main`. `py3.11` branch changes to buildscripts are ignored. Commands roughly equal to: 
  ```bash
  git merge origin/py3.11
  git checkout origin/py3.11 buildscripts azure-pipelines.yml
  ```
- https://github.com/numba/numba/pull/8822/commits/be041fe7a9bed89068a9e6e0c03630c781d2ef2a undo a expectedFailure due to temporarily CI config changes on `py3.11` branch
- https://github.com/numba/numba/pull/8822/commits/c9562c30207b5d8bc91de81b92e11e8d178a0a03 update the CI to include python=3.11.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the PR @sklam, great to see the Python 3.11 branch merged to `main`. This is approved with knowledge of known test failures https://github.com/numba/numba/pull/8822#issuecomment-1478357791. The validity of this merge was checked through https://github.com/numba/numba/pull/8822#issuecomment-1478350653, it appears to be as expected.

**Pull request merged**
