### PR TITLE
Support for int * list

### LINKED ISSUE #7847: int * list isn't supported
---

## Feature request

operator.mul(int, list) doesn't work inside JIT code. Seems like an easy fix.

```python3
import numba

@numba.njit
def f():
    return 5 * [1]

print(f())
```

Output:
```python3
No implementation of function Function(<built-in function mul>) found for signature:
 
 >>> mul(Literal[int](5), list(int64)<iv=[1]>)
 
There are 12 candidate implementations:
  - Of which 10 did not match due to:
  Overload of function 'mul': File: <numerous>: Line N/A.
    With argument(s): '(int64, list(int64)<iv=None>)':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'mul': File: unknown: Line unknown.
    With argument(s): '(int64, list(int64)<iv=None>)':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128
       

During: typing of intrinsic-call at test.py (5)

File "test.py", line 5:
def f():
    return 5 * [1]


<!--

Please include details of the feature you would like to see, why you would
like to see it/the use case.
```

-->

### PR DESCRIPTION
**Pull request by njriasan**
Closes #7847

### CODE REVIEW

**Review by ehsantn — APPROVED** [review]
Looks good to me.

**Comment by gmarkall** [comment]
This seems to be for reflected lists, which are deprecated (https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types) - does it work with typed lists as well?

**Comment by njriasan** [comment]
@gmarkall `operator.mul` doesn't appear to be supported on typed lists at all. I can add support for that, but as a bridge I would like to maintain parity with reflected lists even if they are deprecated.

**Comment by esc** [comment]
> @gmarkall `operator.mul` doesn't appear to be supported on typed lists at all. I can add support for that, but as a bridge I would like to maintain parity with reflected lists even if they are deprecated.

I agree. We don't know when we can finally get rid of the reflected list, so I am also of the opinion that this should go in!

**Review by esc — APPROVED** [review]
I tried this locally and can confirm the patch does implement the feature correctly and the test does exercise it. Thank you!

**Pull request merged**
