### PR TITLE
Remove more unsupported Python versions from build tooling.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
> This looks good. I trawled through the code-base and found the following instances:

Thanks, am happy to patch these now if you are ok to take a look?

> https://github.com/numba/numba/blob/master/buildscripts/azure/azure-windows.yml#L28-L34

Yes, let's remove.
 
> https://github.com/numba/numba/blob/master/.binstar.yml#L27-L31

Will remove the entire file.

> https://github.com/numba/numba/blob/master/.travis.yml#L11-L27

Will remove the entire file.

> https://github.com/numba/numba/blob/master/setup.py#L1-L5

Let's remove.

Is the above analysis what you were thinking?

**Comment by stuartarchibald** [comment]
Above is done in d908dd9, can revert as needed.

**Comment by esc** [comment]
@stuartarchibald looks good to me.

**Comment by stuartarchibald** [comment]
Thanks @esc, will put it through the farm.

**Comment by stuartarchibald** [comment]
Farm ID `numba_smoketest_cpu_24`

**Comment by stuartarchibald** [comment]
`numba_smoketest_cpu_24` passed on everything that was online (power arch builders are currently offline).

**Pull request merged**
