### PR TITLE
Remove more references to the pycc binary.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. These were missed in #8335.

### CODE REVIEW

**Comment by esc** [comment]
Adding this to 0.57

**Comment by esc** [comment]
`Build numba_smoketest_cpu_yaml_132 has started`

**Comment by esc** [comment]
> `Build numba_smoketest_cpu_yaml_132 has started`

This was green, in the end.

**Review by esc — APPROVED** [review]
I ran this through the Anaconda build farm and also ran a local spot check building w/o `--no-test` and it was fine.

**Comment by stuartarchibald** [comment]
> I ran this through the Anaconda build farm and also ran a local spot check building w/o `--no-test` and it was fine.

Great, thanks for testing this @esc.

**Pull request merged**
