### PR TITLE
Enable Appveyor

### PR DESCRIPTION
**Pull request by pitrou**
This is a PR for enabling Appveyor Windows builds. Note I'm using my own account to test this. If we want to enable this permanently we should probably:
- use a Numba account on appveyor
- figure out how free open source builds work

Since appveyor is slow, the PR makes the following choices:
- only one build configuration (64-bit Python 3.5 w/ Numpy 1.10)
- only the "important" tests are run

Based on PR #1701.

### CODE REVIEW

**Comment by seibert** [comment]
I'm curious if this works better for you.  Last year I tried setting up an appveyor build for Numba and gave up because the >30 minute wait times in the free queue basically made it impossible to debug a tricky build script.

**Comment by pitrou** [comment]
Well my attempts above had no wait times basically, but that was with only one build enabled in the configuration matrix. It may also depend on the number of daily commits...

**Comment by seibert** [comment]
They may have also scaled up the number of free systems available with sponsorships or something.

**Comment by pitrou** [comment]
Example build at https://ci.appveyor.com/project/pitrou/numba/build/1.0.350

**Comment by seibert** [comment]
Alright, going to merge this.  We can decide how to handle the Appveyor account later.

**Pull request merged**
