### PR TITLE
Fix #3705: slicing error with negative strides

### LINKED ISSUE #3705: Slicing device array with negative step produces wrong result
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Consider
```python
import numpy as np
import numba
import numba.cuda as cuda
arr = np.arange(4)
d_arr = cuda.to_device(arr)

print('numba version', numba.__version__)
print('numpy array:',arr[::-1].__array_interface__)
print('numba.cuda device array', d_arr[::-1].__cuda_array_interface__)
```
that outputs
```
numba version 0.42.0
numpy array: {'data': (94375105644824, False), 'strides': (-8,), 'descr': [('', '<i8')], 'typestr': '<i8', 'shape': (4,), 'version': 3}
numba.cuda device array {'shape': (-3,), 'strides': (-8,), 'data': (None, False), 'typestr': '<i8', 'version': 0}
```
Clearly, the shape `(-3,)` of `d_arr[::-1]` is wrong, it should be `(4,)`.

As a result, `d_arr[::-1].copy_to_host()` fails:
```python-traceback
Traceback (most recent call last):
  File "pyarrow/tests/numba_bug.py", line 9, in <module>
    d_arr[::-1].copy_to_host()
  File "/home/pearu/miniconda3/envs/pyarrow-dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/pearu/miniconda3/envs/pyarrow-dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 240, in copy_to_host
    strides=self.strides, buffer=hostary)
ValueError: strides is incompatible with shape of requested array and size of buffer
```

### PR DESCRIPTION
**Pull request by sklam**
* Simplified and improved slice indexing in `Dim`.  it now matches `range()[sliceobj]`
* Disable `.copy_to_host()` on negative strided array.

### CODE REVIEW

**Comment by seibert** [comment]
Running on buildfarm now

**Comment by stuartarchibald** [comment]
Buildfarm passed.

**Comment by seibert** [comment]
Passes CUDA smoke test

**Comment by seibert** [comment]
Looks good.

**Pull request merged**
