### PR TITLE
[Experimental] Removed Set as type constraint from typed Dict key-value initialisation

### PR DESCRIPTION
**Pull request by kc611**
As titled,

This PR builds on top of typed set support PR #8741 and removes Set as a type constraint for dictionaries. This PR is separated from the original as the scope differs from the original PR.

### CODE REVIEW

**Comment by lgray** [comment]
I will try this soon. Thanks!

**Comment by kc611** [comment]
Closed this after discussion in the triage meeting. This patch actually removes the wrong constraints, (i.e. it un-restricts reflected sets instead of the newly added typed sets). 

Also, See: https://github.com/numba/numba/pull/8741#issuecomment-1557208561

**Comment by lgray** [comment]
@kc611 If this is not the correct way of doing things, how do I go about properly using a typed set back with #8741 (taking the example I posted, I have a full repro if you need)? If that PR is simply not enough for the functionality I require to move forward what can be done to get there?

**Comment by lgray** [comment]
Ah, reading through again. Here I can still use typed.Set and leave in the sentry on the python side. I'll see how far this PR gets me.

**Pull request closed without merging**
