### PR TITLE
flake8: made more files flake8 compliant

### PR DESCRIPTION
**Pull request by ashutoshvarma**
As title,

- numba/core/dispatcher.py
- numba/core/funcdesc.py
- numba/core/postproc.py

### CODE REVIEW

**Review by gmarkall — APPROVED** [review]
LGTM!

**Comment by esc** [comment]
@gmarkall thank you for looking at this PR. Is it now ready for merge or will it need a CUDA smoketest?

**Comment by gmarkall** [comment]
@esc I think it's good to merge - it's not CUDA specific, but I had a few minutes spare over the weekend so I thought I'd review this.

**Comment by esc** [comment]
Okay, I'll give a smoketest to make sure it's alright.

**Comment by esc** [comment]
`numba_smoketest_cpu_yaml_2`

**Comment by esc** [comment]
Build farm passed!

**Review by esc — APPROVED** [review]
Thank you!

**Pull request merged**
