### PR TITLE
`memcpy` static buffer content into newly allocated buffer

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Fixes issue #9097

### CODE REVIEW

**Review by stuartarchibald — COMMENTED** [review]
Thanks for the patch, is it possible to add a test for this change please? Many Thanks!

**Comment by stuartarchibald** [comment]
@guilhermeleobas this seems to be a reasonably reliable reproducer (I get a hit every time locally), it's based on the discussion on discourse RE long named tuple fields.
```python
from collections import namedtuple
from numba import jit, types, typeof

longname = 1024 * "a"

AType = namedtuple("AType", longname)
BType = namedtuple("BType", longname)

args = (AType(1), BType(1))

@jit(types.void(*(typeof(x) for x in args)))
def foo(arg1, arg2):
    pass

foo(*args)
```
If this reproduces for you, could this perhaps be a replacement for the unit test in this PR (which IIRC doesn't always reproduce?). Thanks!

**Comment by guilhermeleobas** [comment]
Done! @stuartarchibald

**Comment by stuartarchibald** [comment]
Thanks for adapting and adopting the suggestion @guilhermeleobas, the patch and test looks good to me, but as this now effectively contains my code, I'll ask @sklam for a final sign off. It's really great to get this fixed!

**Review by sklam — APPROVED** [review]
Changes make sense.

**Comment by stuartarchibald** [comment]
Thanks @sklam!

**Pull request merged**
