### PR TITLE
Fix typo on urem implementation

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Fix issue #4665. Apparently, there was a typo in the `np_int_urem_impl` which internally was using the signed remainder instruction `srem` instead of the unsigned one `urem`. I still need to write some tests to confirm this.

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
I've tried to create a test for this PR but the problem is that ufuncs are tests with the same input for both dividend and divisor. See:

https://github.com/numba/numba/blob/9eb26b300e361911731f1f128ce6b7234491d098/numba/tests/test_ufuncs.py#L296-L306

One can only specify one value and this value is used on the LHS and RHS of a ufunc. To circunvent this _problem_, one could change ufunc to accept an input with LHS and RHS but I am not soo sure if this would be the correct approach.

**Comment by stuartarchibald** [comment]
@guilhermeleobas Seems like a good idea. Thanks.

**Comment by guilhermeleobas** [comment]
@stuartarchibald,

Can you restart the CI? Two builds failed because of timeout.

**Comment by stuartarchibald** [comment]
@guilhermeleobas sure, done, thanks.

**Comment by guilhermeleobas** [comment]
Hi @stuartarchibald, one of the tests failed because it reaches the 1 hour limit.

Can you restart the CI for this PR? Thanks

Guilherme

**Comment by stuartarchibald** [comment]
Travis CI passed, from a CI point of view consider the PR as of e38adbf as "fine".

**Comment by stuartarchibald** [comment]
@guilhermeleobas did you want this queuing for review?

**Comment by guilhermeleobas** [comment]
Yes, please

**Pull request merged**
