### PR TITLE
Fix for #2862

### PR DESCRIPTION
**Pull request by Rik-de-Kort**
Added `type(value)` argument to call to `np.empty` in the implementation for `np.full`, works with integers now.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for this patch. Please could you add a test to demonstrate that the change fixes the issue? Thanks.

**Comment by Rik-de-Kort** [comment]
Curious. There doesn't seem to be any testing of np.full at all.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/blob/master/numba/tests/test_dyn_array.py#L633 ?

**Comment by stuartarchibald** [comment]
I think this is ready to go, but it'd be nice if the test went and lived with the other `np.full` tests, thanks :)

Incidentally, `./runtests.py -l` lists all tests, so that + grep and you can find most things.

**Comment by stuartarchibald** [comment]
@Rik-de-Kort I've added a [patch](https://github.com/numba/numba/pull/2905/commits/c4d9c55cee43345e2272d386154237aecd8956d1) to move this test to live with the other `np.full` tests with view of getting this merged.

@seibert please could you review and merge if you see fit. Thanks.

**Comment by stuartarchibald** [comment]
Force pushed to get Windows CI to run. Assuming it passes this is ready for review again @seibert .

**Pull request merged**
