### PR TITLE
Fix 3119, raise for 0d arrays in reductions

### LINKED ISSUE #3119: min/max behaves incorrectly on 0-size array
Consider the following code:
```python
In [324]: def test_0d_min(X):
     ...:     return np.min(X)
     ...:
     ...:

In [325]: test_0d_min(np.array([]))  # correct behavior
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
... (omitted)
ValueError: zero-size array to reduction operation minimum which has no identity

In [326]: nb.jit(test_0d_min)(np.array([]))  # incorrect
Out[326]: 0.0

In [328]: nb.jit(test_0d_min, parallel=True)(np.array([]))  # incorrect
Out[328]: 1.7976931348623157e+308
```

I guess that parallelization for reduction functions is done by calculating each block seperately and then combining them together, so an identity element is used as the initial result of each block. `np.finfo(np.float64)` shows that `1.7976931348623157e+308` is exactly the largest `np.float64` instance, which seems suitable as an identity element of `np.min`.

But actually reduction function (aka folding) and identity element are both defined over binary functions, while min function is obviously an n-ary function (a function that accepts down to 0, up to n arguments) mathematically.

As for non-parallel version of jitted function, I have no idea why it computes to 0.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

Fixes #3119.

TODO:
- [x] Tests

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@DrTodd13 Do you think the changes to parfors reductions are safe? I think they should be ok in that the fusion pass ought to spot the invariant checking code and push it up? Thanks.

**Comment by ehsantn** [comment]
@stuartarchibald Unfortunately, the fusion pass can't deal with control flow like this. I suggest wrapping this check inside a function and calling it.

**Comment by DrTodd13** [comment]
Have you tried Ehsan's suggestion?  That is what I would try first for now.  We haven't considered exceptions much.  Is this expected to work in regular nopython mode?  If so, parallel=True should support it.

**Comment by stuartarchibald** [comment]
Thanks for these suggestions. In 78c6a3d I jitted some functions as array checkers and then called them just after `numba.parfor.init_prange()`, added them to the globals for the closure inliner and they inline and are called fine, fusion seems to work with this pattern. The issue with this is that array temporary elimination is impacted in that there's e.g. an array reference that cannot be eliminated as an arg to the checker function. This breaks array counting tests and may not be desirable. I think it might be possible to switch out the arg to the checker function for the parent of the allocation/input that has been eliminated. Any thoughts?

**Comment by DrTodd13** [comment]
@stuartarchibald Was their an example in the checkin that illustrates this problem you mentioned about array temporary elimination?

**Comment by stuartarchibald** [comment]
@DrTodd13 the unit test for argmin fusion is sufficient I think:
```
$ ./runtests.py numba.tests.test_parfors.TestParfors.test_fuse_argmin
F
======================================================================
FAIL: test_fuse_argmin (numba.tests.test_parfors.TestParfors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<path>/numba/numba/tests/test_parfors.py", line 531, in test_fuse_argmin
    self.assertTrue(countArrays(test_impl, (types.intp,)) == 0)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 1.372s

FAILED (failures=1)
```

**Comment by DrTodd13** [comment]
@stuartarchibald In which sense is the checker being inlined?  I am seeing a call to argmin_checker.  I understand the problem now and will think about it over the weekend.

**Comment by DrTodd13** [comment]
Just to document our online discussion, my suggestion is to pass arr.shape instead of arr.  Then, in argmin_checker, use np.prod(shape).  ParallelAccelerator _should_ recognize the shape attr and replace with known sizes, which will eliminate reference to the array and allow it to be dead code eliminated.

**Comment by stuartarchibald** [comment]
Thanks @DrTodd13 I'll give this a try.

**Comment by stuartarchibald** [comment]
@DrTodd13 I've implemented the discussed, it seems to work locally, array temporary elimination still happens and the parfors counts are still correct.

As I've expanded testing I've had to add parfors support for `np.amax` and `np.amin` which are aliases for `np.max`/`np.min` respectively. Is the way I've done this suitable or should switching `np.amax` for `np.max` etc. be part of the canonicalization?

Thanks.

**Comment by DrTodd13** [comment]
@stuartarchibald  Looks fine to me.  Thanks.

**Comment by seibert** [comment]
Looks good.  Will merge once CI finishes.

**Pull request merged**
