### PR TITLE
CUDA: Fixes missing type annotation pass following #7704

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
gpuci run tests

**Review by gmarkall — APPROVED** [review]
Thanks for the fix - this looks good to me!

**Comment by gmarkall** [comment]
Also created #7710 to record the other changes we need to make following this.

**Comment by stuartarchibald** [comment]
> Also created #7710 to record the other changes we need to make following this.

Thanks!

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_yaml_110`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_yaml_110`.

Passed.

**Pull request merged**
