### PR TITLE
CUDA: Fix #6339, performance regression launching specialized kernels

### LINKED ISSUE #6339: CUDA: Performance regression launching specialized kernels
Presently launching a specialized kernel on master (9381206a03a3e7231d417f147474577745f6a720) takes around twice as long as it used to once a few arguments are involved. For the test case described in https://github.com/numba/numba/issues/3003#issuecomment-627872661, which looks like:

```python
from numba import cuda
import numpy as np

@cuda.jit('void()')
def some_kernel_1():
    return

@cuda.jit('void(float32[:])')
def some_kernel_2(arr1):
    return

@cuda.jit('void(float32[:],float32[:])')
def some_kernel_3(arr1,arr2):
    return

@cuda.jit('void(float32[:],float32[:],float32[:])')
def some_kernel_4(arr1,arr2,arr3):
    return

@cuda.jit('void(float32[:],float32[:],float32[:],float32[:])')
def some_kernel_5(arr1,arr2,arr3,arr4):
    return

arr = cuda.device_array(10000, dtype=np.float32)

%timeit some_kernel_1[1, 1]()
%timeit some_kernel_2[1, 1](arr)
%timeit some_kernel_3[1, 1](arr,arr)
%timeit some_kernel_4[1, 1](arr,arr,arr)
%timeit some_kernel_5[1, 1](arr,arr,arr,arr)
```

the timings are currently:

```
27.6 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
62.6 µs ± 278 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
87.9 µs ± 700 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
109 µs ± 405 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
131 µs ± 365 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

whereas they were previously much lower - e.g.:

```
26.4 µs ± 78 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
41.4 µs ± 185 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
51.1 µs ± 511 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
59.5 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
68 µs ± 87 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

with #6042 (now merged) when it was first opened.

### PR DESCRIPTION
**Pull request by gmarkall**
The behavior of the CUDA dispatcher is to not check the argument types when launching specialized kernels. Therefore, there is no need to resolve the argument types when launching a specialized kernel - the specialized definition can be used directly.

Prior to this commit, the benchmark:

```python
from numba import cuda
import numpy as np

@cuda.jit('void()')
def some_kernel_1():
    return

@cuda.jit('void(float32[:])')
def some_kernel_2(arr1):
    return

@cuda.jit('void(float32[:],float32[:])')
def some_kernel_3(arr1,arr2):
    return

@cuda.jit('void(float32[:],float32[:],float32[:])')
def some_kernel_4(arr1,arr2,arr3):
    return

@cuda.jit('void(float32[:],float32[:],float32[:],float32[:])')
def some_kernel_5(arr1,arr2,arr3,arr4):
    return

arr = cuda.device_array(10000, dtype=np.float32)

%timeit some_kernel_1[1, 1]()
%timeit some_kernel_2[1, 1](arr)
%timeit some_kernel_3[1, 1](arr,arr)
%timeit some_kernel_4[1, 1](arr,arr,arr)
%timeit some_kernel_5[1, 1](arr,arr,arr,arr)
```

Gives:

```
27.6 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
62.6 µs ± 278 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
87.9 µs ± 700 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
109 µs ± 405 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
131 µs ± 365 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

After this commit, it gives:

```
19.1 µs ± 49.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
31.8 µs ± 38 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
40.4 µs ± 42.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
48.5 µs ± 43.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
56 µs ± 30.8 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Tests pass for me locally with a Quadro RTX 8000 + Quadro P2200, in parallel and in serial.

### CODE REVIEW

**Comment by gmarkall** [comment]
The fails here appear to be conda HTTP errors.

**Comment by stuartarchibald** [comment]
> The fails here appear to be conda HTTP errors.

rerun requested.

**Comment by stuartarchibald** [comment]
Thanks for the patch. For me, mainline gives:
```
90.9 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
181 µs ± 1.61 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
256 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
332 µs ± 12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
402 µs ± 8.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
this patch gives:
```
64 µs ± 373 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
96.3 µs ± 385 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
120 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
143 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
165 µs ± 393 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
on a GeForce GTX 750 Ti.

**Review by stuartarchibald — APPROVED** [review]
Code change looks good. Thanks for the patch.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_118`.

**Comment by gmarkall** [comment]
Note: the force push is substituting "µ" for "u" in the commit message in order to enable the commit to be tested on platforms that don't support non-ASCII characters.

**Comment by stuartarchibald** [comment]
> Note: the force push is substituting "µ" for "u" in the commit message in order to enable the commit to be tested on platforms that don't support non-ASCII characters.

Many thanks @gmarkall

**Review by stuartarchibald — APPROVED** [review]
Force push to edit commit message also approved! Thanks!

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_119` is for 896f8be

**Review by sklam — APPROVED** [review]

**Comment by stuartarchibald** [comment]
Unfortunately `±` is now causing issues

**Comment by gmarkall** [comment]
> Unfortunately `±` is now causing issues

Pushed again with this swapped for `+/-`. I've checked it's all ASCII this time!

**Comment by stuartarchibald** [comment]
> > Unfortunately `±` is now causing issues
> 
> Pushed again with this swapped for `+/-`. I've checked it's all ASCII this time!

Thanks!

Buildfarm ID: `numba_smoketest_cuda_120` is for 3b6a17e

**Comment by stuartarchibald** [comment]
> > > Unfortunately `±` is now causing issues
> > 
> > 
> > Pushed again with this swapped for `+/-`. I've checked it's all ASCII this time!
> 
> Thanks!
> 
> Buildfarm ID: `numba_smoketest_cuda_120` is for [3b6a17e](https://github.com/numba/numba/commit/3b6a17e643f54b707be8545c808f60c6d1a5e4ec)

This passed.

**Review by stuartarchibald — APPROVED** [review]

**Pull request merged**
