### PR TITLE
Enable Boxing Unhashable Literals

### LINKED ISSUE #7707: Cannot Pass Literals are argument that aren't hashable
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Passing literals that aren't hashable fails at lowering in Numba. Here is a reproducer with a slice.

```python
import numba

@numba.njit
def f(x):
    slc = numba.literally(x)
    return slc

print(f(slice(1, 2)))
```

Which produces the following stack trace
```
Traceback (most recent call last):
  File "test_unhashable_literal.py", line 8, in <module>
    print(f(slice(1, 2)))
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 443, in _compile_for_args
    return_val = self._compile_for_args(*args)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 472, in _compile_core
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 349, in run
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typed_passes.py", line 398, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 292, in create_cpython_wrapper
    self.context.create_cpython_wrapper(self.library, self.fndesc,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/cpu.py", line 184, in create_cpython_wrapper
    library.add_ir_module(wrapper_module)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/codegen.py", line 727, in add_ir_module
    ir = cgutils.normalize_ir_text(str(ir_module))
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/module.py", line 242, in __repr__
    lines += self._get_body_lines()
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/module.py", line 212, in _get_body_lines
    lines += [str(v) for v in self.globals.values()]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/module.py", line 212, in <listcomp>
    lines += [str(v) for v in self.globals.values()]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 1002, in __str__
    self.descr(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 997, in descr
    self.descr_body(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 991, in descr_body
    blk.descr(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 1131, in descr
    buf += ["  {0}\n".format(instr) for instr in self.instructions]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 1131, in <listcomp>
    buf += ["  {0}\n".format(instr) for instr in self.instructions]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/_utils.py", line 48, in __str__
    s = self.__cached_str = self._to_string()
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 548, in _to_string
    self.descr(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/instructions.py", line 218, in descr
    .format(self.opname, return_value.type,
AttributeError: 'tuple' object has no attribute 'type'
```

The source of the problem appears to be `serialize_object` because the line `gv = self.module.__serialized[obj]` always fails when a literal isn't hashable.

I think a reasonable solution would be to support passing a key to `serialize_object`. `box_literal` could then construct a unique object to use as a key.

A possible implementation could build a wrapper type around the literal type that reuse the literal type's hash (but uses a different object to avoid collisions with actually serializing the type).

### PR DESCRIPTION
**Pull request by njriasan**
closes #7707

Provides support for boxing an unhashable literal (i.e. slice).  This updates serializing to avoid trying to place an unhashable object in a dictionary. It reuses the hashing implementation from the literal type but creates a new object type to avoid conflicts with serializing the actual type.

### CODE REVIEW

**Comment by sklam** [comment]
Interesting technique. 

Can you add a test for literal list? 

e.g.

```python
@njit
def foo():
    return [1,"2"], [1,"2"]

a, b = foo()
```
Would mutating `a` also mutate `b`?

**Comment by njriasan** [comment]
> Can you add a test for literal list?

Right now this test won't work because there is no Literal subclass defined for lists, leading to the error message:

```python
<class 'list'> cannot be used as a literal
```
Rather than opting to implement a literal list type, Numba appears to construct an actual list of literals. 

i.e. `[Literal[int](1), Literal[str](2)]`

This incorrectly lowers to the types instead of the actual implementation if handled naively and requires a more detailed implementation.

> Would mutating a also mutate b?

Within Numba all literals appear to be immutable (including lists which disallow static_getitem). Depending on how the literal type it constructed, its definitely possible.

We could extend this with a `is_mutable` flag for literals that always treats mutable literals as unequal.

However, even then we would need to ensure the actual literal value used internally isn't cached/reused for some implementations, such as if someone used an OpaqueModel, which I believe is outside the scope of this PR.

**Comment by njriasan** [comment]
I added an example of the mutable check. I'm of the opinion that this is probably important, but complicated, so it needs to be investigated with an actual mutable literal type as an example.

**Comment by njriasan** [comment]
@sklam I'm looking at finalizing this PR because I abandoned it for a while. It looks like Numba doesn't have any remaining literals that either don't have a boxing implementation or aren't hashable (at least based on the `ctor_map` of Literal). Would you like to me close this PR or is it possible to draft a new literal type (e.g. List as suggested) so I can test this behavior.

**Comment by kc611** [comment]
Re-opened the PR to trigger CI against latest tests.

**Comment by kc611** [comment]
> @sklam I'm looking at finalizing this PR because I abandoned it for a while. It looks like Numba doesn't have any remaining literals that either don't have a boxing implementation or aren't hashable (at least based on the ctor_map of Literal). Would you like to me close this PR or is it possible to draft a new literal type (e.g. List as suggested) so I can test this behavior.

Hey @njriasan :wave:, after some internal discussion with @sklam, this PR seems good to go even without the Literal list. Although it seems like for some reason CI can't find the remote ref (merge HEAD?) and fails. Could you try merging the current `main` into this PR branch so the CI can be triggered properly?

**Comment by njriasan** [comment]
> > @sklam I'm looking at finalizing this PR because I abandoned it for a while. It looks like Numba doesn't have any remaining literals that either don't have a boxing implementation or aren't hashable (at least based on the ctor_map of Literal). Would you like to me close this PR or is it possible to draft a new literal type (e.g. List as suggested) so I can test this behavior.
> 
> Hey @njriasan 👋, after some internal discussion with @sklam, this PR seems good to go even without the Literal list. Although it seems like for some reason CI can't find the remote ref (merge HEAD?) and fails. Could you try merging the current `main` into this PR branch so the CI can be triggered properly?

Yes can do.

**Comment by njriasan** [comment]
@kc611 Looks like everything passed except the release notes change. Is there anything else you need from me?

**Comment by kc611** [comment]
> @kc611 Looks like everything passed except the release notes change. Is there anything else you need from me?

Yep, it's looking good. Could you add a small test validating the changes and a release note summarizing the PR. :slightly_smiling_face:

**Comment by swap357** [comment]
Hello @njriasan
Thanks for keeping the branch open for maintainer edits. Since this PR is on milestone for upcoming release, I've pushed commits to merge in `main` and add release note.

**Comment by swap357** [comment]
I discussed this PR earlier today with @sklam. The intent for this PR when opened was to support boxing for then unhashable slice literal which was added on - https://github.com/numba/numba/pull/7714. 
As author notes on previous comment https://github.com/numba/numba/pull/7708#issuecomment-2327056969, Numba currently doesn't have any literals in the `ctor_map` that lack a boxing implementation or aren't hashable. The specific use case this PR was designed to address has been resolved, these changes are no longer required at this time. Closing this PR. Thank you all for contributions.

**Pull request closed without merging**
