### PR TITLE
Support NumPy 1.19

### PR DESCRIPTION
**Pull request by stuartarchibald**
Adds support for 1.19.

* Skips a tests which has problems on 1.19 (awaiting upstream patch
  for stability: https://github.com/numpy/numpy/pull/17457)
* Updates CI.

Closes https://github.com/numba/numba/issues/6181

### CODE REVIEW

**Comment by esc** [comment]
BFID: `numba_smoketest_cpu_73`.

**Comment by esc** [comment]
`numba_smoketest_cpu_73` passed fine, it included a Numpy 1.19 run of the suite.

**Comment by stuartarchibald** [comment]
> `numba_smoketest_cpu_73` passed fine, it included a Numpy 1.19 run of the suite.

Thanks @esc. Is this patch approved?

**Review by esc — APPROVED** [review]
Sure looks  good to me!

**Pull request merged**
