### PR TITLE
bump llvmdev dependency to 0.42.0dev for next development cycle

### PR DESCRIPTION
**Pull request by esc**
As title

### CODE REVIEW

**Comment by esc** [comment]
> This is missing a build for `llvmlite=0.42.0dev0`

I have launched a build-out new, hopefully the development artifact should become available within the next hour.

**Comment by esc** [comment]
> > This is missing a build for `llvmlite=0.42.0dev0`
> 
> I have launched a build-out new, hopefully the development artifact should become available within the next hour.

Restarted the build by open/close issue as artifacts have become avail.:

https://anaconda.org/numba/llvmlite/files?version=0.42.0dev0

**Comment by esc** [comment]
> > > This is missing a build for `llvmlite=0.42.0dev0`
> > 
> > 
> > I have launched a build-out new, hopefully the development artifact should become available within the next hour.
> 
> Restarted the build by open/close issue as artifacts have become avail.:
> 
> https://anaconda.org/numba/llvmlite/files?version=0.42.0dev0

public CI looks good!

**Review by kc611 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
