### PR TITLE
Support np.array() and array number constructors

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by seibert** [comment]
We should note in the documentation that np.array can be used to create multidimensional arrays using nested tuples, rather than nested lists, as may be the default behavior for most users.

**Comment by seibert** [comment]
I think this is ready to merge once we add an example to the docs showing the use of nested tuples (and warning against nested lists) to create a multidimensional array.

**Comment by pitrou** [comment]
Ok, I've added that.

**Comment by seibert** [comment]
Thanks!

**Pull request merged**
