### PR TITLE
fix exception during locale detection

### PR DESCRIPTION
**Pull request by esc**
Under certain circumstances for example if `$LANG` is unset in the
environment, `getdefaultlocale` can return the tuple `(None, None)`.
This in turn would cause an `Exception` to be raised by `join` at least
in Python 3.6, as it expects the iterable to contain `str`s. The result
was the following error message:

```
Error (locale): sequence item 0: expected str instance, NoneType found
```

Unfortunately the tests for the system info detection would then crash
making the test-suite fail. To mitigate this, we now cast everything
returned by `getdefaultlocale` to `str` to make sure that the call to
`join` will succeed. The output will then be `None.None` which is fine
as it indicates that no default locale was detected.

### CODE REVIEW

**Comment by esc** [comment]
This is a fix for changes introduced in #5591. Additional bugs were detected by the internal build farm and are fixed by this.

**Comment by esc** [comment]
Internal build-farm ID: `numba_175`

**Comment by stuartarchibald** [comment]
Pulled this into https://github.com/numba/numba/pull/5791 too.

**Comment by stuartarchibald** [comment]
Closing this as it got merged as part of #5791. Thanks for fixing @esc.

**Comment by esc** [comment]
🍰

**Pull request closed without merging**
