### PR TITLE
Show the offending module in "no direct replacement" error message

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch, I've merged it into https://github.com/numba/numba/pull/5494 as it touches the same code.

**Comment by esc** [comment]
@stuartarchibald can we close this issue as the patches are contained within #5494?

**Comment by stuartarchibald** [comment]
@eric-wieser Should probably include this in #5498 and close?

**Comment by eric-wieser** [comment]
Can we just merge it separately? It won't conflict.

**Comment by stuartarchibald** [comment]
I was hoping to get a test added for it, #5498 mutating such tests.

**Comment by eric-wieser** [comment]
Isn't this code already tested? Or do you specifically want to test the contents of the warning message?

The test changes in 5498 won't conflict with this PR either, as far as I can tell.

**Comment by eric-wieser** [comment]
Updated with a test

**Comment by stuartarchibald** [comment]
Yes RE specific contents, thanks for updating and adding the test.

I'm going to change the base branch on this PR to master so that we get a CI run. All 0.49 patches will be merged to master and then cherry-picked over as needed.

**Comment by eric-wieser** [comment]
Want me to rebase to remove @sklam's commit?

**Comment by stuartarchibald** [comment]
> Want me to rebase to remove @sklam's commit?

Good idea, that'd be helpful, thanks.

**Comment by eric-wieser** [comment]
Done

**Comment by eric-wieser** [comment]
CI now passes

**Pull request merged**
