### PR TITLE
generated_jit for CUDA kernels

### PR DESCRIPTION
**Pull request by sjperkins**

### CODE REVIEW

**Comment by seibert** [comment]
This is a great idea, BTW.

**Comment by sjperkins** [comment]
I don't think there's an easy way to support for a `@generated_jit` for device functions (as wished for in https://github.com/numba/numba/issues/2754). However I think supporting `@generated_jit` for CUDA kernels should be sufficient. For e.g. the following is possible:

```python
    def test_generated_jit_with_device_function(self):
        @generated_jit(target='cuda')
        def kernel(array):
            @cuda.jit(device=True)
            def device_add(array):
                i = cuda.grid(1)

                if i >= array.shape[0]:
                    return

                array[i] += 1

            @wraps(kernel)
            def _kernel(array):
                device_add(array)

            return _kernel

        array = np.zeros(200, dtype=np.float64)
        array = cuda.to_device(array)
        kernel[(1, 1, 1), (200, 1, 1)](array)

        host_out = array.copy_to_host()

        assert host_out.dtype == array.dtype
        assert np.all(host_out == 1)
```

**Comment by sjperkins** [comment]
What's the window for the 0.41 release like? It would be helpful to know from a planning perspective.

**Comment by seibert** [comment]
We want to tag the release candidate on Monday, Nov 19 (after which point, only critical bug fixes will be merged), and tag the final release on Nov 26.

Note that we are also considering a short 0.42 dev cycle following this one, with a release candidate tagged around Dec 11 and final release Dec 18 (exact dates TBD).

**Comment by sjperkins** [comment]
Tests seem to be failing because the 'cuda' target isn't in the registry (probably because CUDA + GPUs aren't available on the CI servers). Is this something that should be rectified in the test case (skip if cuda unavailable) or in the registry lookup mechanism?

**Comment by sjperkins** [comment]
I think this is ready for review. The test cases are failing for reasons described in https://github.com/numba/numba/pull/3450#issuecomment-439014080. Are there any suggestions for improving this?

**Comment by stuartarchibald** [comment]
@sjperkins thanks for working on this, as to the failing tests, I think if they can be run under the CUDA simulator then they should be. Worse case they'll have to be switched off unless CUDA hardware is present. Ping @sklam RE registry availability.

**Comment by stuartarchibald** [comment]
@gmarkall is this something you'd be interested in picking up/fixing? Thanks.

**Comment by gmarkall** [comment]
@stuartarchibald Apologies for missing this before - it's something I'm interested in looking at, but I need to find some time to look over it. Will post an update once I've looked.

**Comment by gmarkall** [comment]
Now that `@overload` is supported on CUDA, and `@generated_jit` is something we'd like to move away from, I think it is appropriate to close this PR. @sjperkins Many thanks for your efforts in this direction, and I'm sorry that we didn't manage to bring them through to completion.

**Comment by sjperkins** [comment]
Thanks @gmarkall. Great to hear about `@overload` offering this functionality.

**Pull request closed without merging**
