### PR TITLE
Add env var to disable performance warnings.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
CC @shssf

**Comment by seibert** [comment]
Looks good!  We need to add the docs to: http://numba.pydata.org/numba-doc/latest/reference/envvars.html#debugging

**Comment by stuartarchibald** [comment]
@seibert thanks, docs in a623fc4

**Comment by seibert** [comment]
Looks good.  Ready to merge.

**Pull request merged**
