### PR TITLE
Prevent mutation of arrays in global tuples.

### LINKED ISSUE #7120: Arrays in tuples referred to in globals are erroneously writable.
here is a not-so-minimal reproducer (tested with Python 3.8):

```python
import numpy as np, numba
grid = (100, 10)
def fa(data):
    return (np.ones(5, dtype=int), np.zeros([data.shape[i] + 2 * 1 for i in range(2)]))
def fb(data):
    halos = [[(1 - (d == c)) for c in range(2)] for d in range(2)]
    dd = [np.zeros([[data[d].shape[c] + 2 * halos[d][c] for c in range(2)] for d in range(2)][d]) for d in range(2)]
    return (np.ones(5, dtype=int), dd[0], dd[1])
@numba.njit()
def atv_2d_axis0(focus, arrs, i, k=0):
    return arrs[0][focus[0] + int(i - .5), focus[-1] + int(k)]
@numba.njit()
def atv_2d_axis1(focus, arrs, k, i=0):
    return arrs[-1][focus[0] + int(i), focus[-1] + int(k - .5)]
@numba.njit()
def set(arr, i, k, value):
    arr[i, k] = value
@numba.njit()
def apply_scalar_impl(fun_outer, fun_inner, out, vec_arg1_outer, vec_arg1_inner):
    for i in range(1, grid[0]+1):
        for k in range(1, grid[1]+1):
            set(out, i, k, fun_inner(out[i, k], ((i, k), (vec_arg1_outer, vec_arg1_inner))))
            set(out, i, k, fun_outer(out[i, k], ((i, k), (vec_arg1_outer, vec_arg1_inner))))
@numba.njit()
def apply_scalar(fun_outer, fun_inner, out, vec_arg1_meta, vec_arg1_outer, vec_arg1_inner, scal_arg2_meta):
    scal_arg2_meta[0] = True
    apply_scalar_impl(fun_outer, fun_inner, out, vec_arg1_outer, vec_arg1_inner)
def mu(atv):
    @numba.njit()
    def upwind(init, flux):
        return init + atv(*flux, -.5) - atv(*flux, .5)
    return upwind
form = tuple([mu(atv) for atv in (atv_2d_axis0, atv_2d_axis1)])
ns = fa(np.empty([0]*2))
@numba.njit()
def step(a, b):
    return apply_scalar(*form, a[1], *b, ns[0])
step(fa(data=np.zeros(grid)), fb(data=(np.zeros((grid[0] + 1, grid[1])), np.zeros((grid[0], grid[1] + 1)))))
```

gives:

```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

works OK with `NUMBA_DISABLE_JIT` set to "1"

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

Fixes #7120

### CODE REVIEW

**Review by esc — DISMISSED** [review]
I tested this by trying the unit tests locally and breaking them intentionally. It looks good to me.

**Comment by esc** [comment]
@stuartarchibald there are still some conflicts to be resolved so I'll give it the final approval when those have been resolved.

**Comment by stuartarchibald** [comment]
> @stuartarchibald there are still some conflicts to be resolved so I'll give it the final approval when those have been resolved.

@esc thanks, mainline is merged in 567fe87

**Review by esc — APPROVED** [review]

**Comment by esc** [comment]
@stuartarchibald thank you for the patch!

**Comment by esc** [comment]
@stuartarchibald thank you for the patch!

**Pull request merged**
