### PR TITLE
Skip MVC test when libraries unavailable

### PR DESCRIPTION
**Pull request by gmarkall**
We can't test Minor Version Compatibility if cubinlinker and ptxcompiler are unavailable, so skip MVC tests in that case.

### CODE REVIEW

**Comment by gmarkall** [comment]
gpuci run tests

**Comment by esc** [comment]
@gmarkall thank you for the patch, there was a flake8 violation, for which I just pushed a fix.

**Comment by esc** [comment]
Thank you @gmarkall , this is going in today.

**Review by esc — APPROVED** [review]
LGTM, passed on the farm, such that the tests are skipped indeed.

**Comment by esc** [comment]
🍒 as https://github.com/numba/numba/pull/9003/commits/118b030284870bbc38ced784cdc508e9defa553a

**Pull request merged**
