### PR TITLE
Unset the memory manager after EMM Plugin tests

### PR DESCRIPTION
**Pull request by gmarkall**
Setting the EMM plugin to the internal memory manager is incorrect when the tests are being run with an external memory manager, e.g. with:

```
NUMBA_CUDA_MEMORY_MANAGER=rmm python -m numba.runtests numba.cuda.tests
```

After the EMM plugin tests execute, testing would continue with the internal memory manager instead of the specified external memory manager. The correct behaviour is to un-set it, so that when the new context is created, it is set to the chosen memory manager (either the internal one or an external one).

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Buildfarm ID `numba_smoketest_cuda_48`.

**Comment by esc** [comment]
@gmarkall @stuartarchibald will this be included in 0.49.1?

**Comment by gmarkall** [comment]
There's no hurry for it - I would not burden 0.49.1 with it.

**Comment by esc** [comment]
@gmarkall thanks for the update, I have set the milestone accordingly.

**Pull request merged**
