### PR TITLE
Add stub of str.format()

### PR DESCRIPTION
**Pull request by densmirn**
When I tried to implement `str.format()` got an issue with position arguments. Could you please give advice how to work with position arguments in particular in my case?

### CODE REVIEW

**Comment by densmirn** [comment]
Could you please mark the PR as WIP and question?

**Comment by stuartarchibald** [comment]
I think this may be hitting a bug in the Numba internals. Irrespective of this, I'm unsure how good an idea it is to try and implement the format spec directly in Numba, it's hugely involved https://github.com/python/cpython/blob/04c79d6088a22d467f04dbe438050c26de22fa85/Objects/unicodeobject.c#L2689.

**Comment by densmirn** [comment]
> I think this may be hitting a bug in the Numba internals. Irrespective of this, I'm unsure how good an idea it is to try and implement the format spec directly in Numba, it's hugely involved https://github.com/python/cpython/blob/04c79d6088a22d467f04dbe438050c26de22fa85/Objects/unicodeobject.c#L2689.

Maybe I could try to implement simple version of the method if you gave me advice how to work with position arguments.

**Comment by stuartarchibald** [comment]
> > I think this may be hitting a bug in the Numba internals. Irrespective of this, I'm unsure how good an idea it is to try and implement the format spec directly in Numba, it's hugely involved https://github.com/python/cpython/blob/04c79d6088a22d467f04dbe438050c26de22fa85/Objects/unicodeobject.c#L2689.
> 
> Maybe I could try to implement simple version of the method if you gave me advice how to work with position arguments.

I think this is hitting a bug, I don't think you can work with what you have written because of this bug. The bug will need fixing to make this possible, perhaps fix that first?

**Comment by stuartarchibald** [comment]
> > > I think this may be hitting a bug in the Numba internals. Irrespective of this, I'm unsure how good an idea it is to try and implement the format spec directly in Numba, it's hugely involved https://github.com/python/cpython/blob/04c79d6088a22d467f04dbe438050c26de22fa85/Objects/unicodeobject.c#L2689.
> > 
> > 
> > Maybe I could try to implement simple version of the method if you gave me advice how to work with position arguments.
> 
> I think this is hitting a bug, I don't think you can work with what you have written because of this bug. The bug will need fixing to make this possible, perhaps fix that first?

This bug got fixed on master, if you merge in this PR can continue.

**Comment by stuartarchibald** [comment]
@densmirn were you planning on continuing with this PR? It's just a stub at present. If not, I propose we close it? Thanks.

**Comment by densmirn** [comment]
> @densmirn were you planning on continuing with this PR? It's just a stub at present. If not, I propose we close it? Thanks.

Let's close the PR.

**Comment by stuartarchibald** [comment]
> > @densmirn were you planning on continuing with this PR? It's just a stub at present. If not, I propose we close it? Thanks.
> 
> Let's close the PR.

ok, thanks for confirming.

**Pull request closed without merging**
