### PR TITLE
Fix #6121

### LINKED ISSUE #6121: CUDA: Recent commit causes infinite loop (or a lot of recompiling)
Looking into an issue using 0.51.0rc1 with cuDF, it seems that this commit: https://github.com/numba/numba/commit/e203c9d8c00590882fb50a9f0e70d09f255bb4ab causes an infinite loop, or a lot of recompilation. I'm investigating this now and will post further details here as I progress.

### PR DESCRIPTION
**Pull request by gmarkall**
Opening this PR to fix #6121 and iterate on it. The problem is that `forall` always returns a new `Dispatcher`, which immediately compiles the specialization. Prior to #5709 being merged, the cache of compilations was used and any previously-compiled kernel could be returned by `specialize`. The fix in this branch introduces a cache of specialized `Dispatcher` objects to work around the issue.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_92` for 86241da

**Comment by stuartarchibald** [comment]
`numba_smoketest_cuda_92` passed, will try 4f17d85

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_93` for 4f17d85

**Comment by stuartarchibald** [comment]
`numba_smoketest_cuda_93` passed.

**Comment by gmarkall** [comment]
@stuartarchibald As far as I can tell from testing cuDF and other libraries, the issue appears to be resolved and I can't see that this introduces any new issues.

**Comment by stuartarchibald** [comment]
> @stuartarchibald As far as I can tell from testing cuDF and other libraries, the issue appears to be resolved and I can't see that this introduces any new issues.

Thanks for confirming. This will make 0.51.0.

**Pull request merged**
