### PR TITLE
update local references from master -> main

### PR DESCRIPTION
**Pull request by esc**
As title.

### CODE REVIEW

**Comment by esc** [comment]
All the other references to `master` should be OK:

```
 💣 zsh» git --no-pager grep master
CHANGE_LOG:* PR #6057: fix aarch64/python_3.8 failure on master
CHANGE_LOG:* PR #5738: Unbreak master on buildfarm
CHANGE_LOG:* PR #5232: Fixes a bad import that breaks master
CHANGE_LOG:* PR #5147: Update master for 0.48.0 updates
CHANGE_LOG:* PR #4302: Fix flake8 issue on master
docs/dagmap/template.html:        src="https://cdn.rawgit.com/jquery/jquery-mousewheel/master/jquery.mousewheel.min.js"></script>
docs/dagmap/template.html:    <script type="text/javascript" src="https://cdn.rawgit.com/jquery/jquery-color/master/jquery.color.js"></script>
docs/source/conf.py:# The master toctree document.
docs/source/conf.py:master_doc = 'index'
docs/source/developer/dispatching.rst:<https://github.com/numba/numba-benchmark/blob/master/benchmarks/bench_dispatch.py>`_
docs/source/index.rst:.. Numba documentation master file, created by
docs/source/proposals/external-memory-management.rst:  https://github.com/gmarkall/nbep-7/blob/master/nbep7/cupy_mempool.py - uses
docs/source/user/faq.rst:<https://github.com/numba/Numba-SC15-Paper/raw/master/numba_sc15.pdf>`_, in case
numba/_version.py:        # "stabilization", as well as "HEAD" and "master".
numba/np/arraymath.py:                # NOTE: there's a change in master which is not
numba/np/arraymath.py:                # NOTE: this is in master but not in any released
numba/np/linalg.py:        # https://github.com/numpy/numpy/blob/master/numpy/linalg/umath_linalg.c.src
numba/np/polynomial.py:        # https://github.com/numpy/numpy/blob/master/numpy/lib/polynomial.py
numba/tests/test_unicode.py:        # https://github.com/python/cpython/blob/master/Objects/unicodetype_db.h
versioneer.py:(https://travis-ci.org/warner/python-versioneer.png?branch=master)
versioneer.py:        # "stabilization", as well as "HEAD" and "master".
versioneer.py:        # "stabilization", as well as "HEAD" and "master".
```

**Comment by esc** [comment]
PR is currently broken, since the default branch has not yet been updated.

**Review by sklam — APPROVED** [review]
All good

**Comment by esc** [comment]
@sklam thank you for the review.

**Pull request merged**
