### PR TITLE
CUDA: Prevent auto-upgrade of atomic intrinsics

### PR DESCRIPTION
**Pull request by gmarkall**
LLVM 9 onwards auto-upgrade the atomic intrinsics into an atomicrmw form unsupported by NVVM. This commit prevents the auto-upgrade by changing the "nvvm" component of the intrinsic to "numba_nvvm" until after it has been parsed and dumped by LLVM.

With thanks to Stuart Archibald for the suggestion and initial patch, and Val Haenel for catching the issue in the buildfarm prior to release.

This should fix the issue described in https://github.com/numba/llvmlite/pull/606#issuecomment-669119556

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@esc please could you push this through the farm against the LLVM 10 stack. Thanks.

**Comment by stuartarchibald** [comment]
Manually tested this on linux with LLVM 10 from https://github.com/numba/llvmlite/pull/599 locally, worked fine.

**Comment by esc** [comment]
🍒 picked onto #599 as a373edde8e

**Comment by esc** [comment]
CUDA smoketest passed  on #5969 with this 🍒 picked

**Comment by gmarkall** [comment]
Did you intend to close this PR?

**Comment by gmarkall** [comment]
> Think it got scooped into the LLVM 10 patch series in #5969 as that toolchain is the only way we have to test it's working right now (anything LLVM 9 based would still have a patched LLVM)?

Ah - I saw it there, but the big "DO NOT MERGE" message in the description led me to believe it wouldn't be merged :-)

**Comment by esc** [comment]
yeah, my bad, this needs to go into `master` of course

**Comment by esc** [comment]
The reason I was confused was: there are two LLVM 10 related branches, one in the Numba repo, the other in the llvmlite one. For llvmlite (https://github.com/numba/llvmlite/pull/599) this branch will be merged before the release for Numba, #5969 it is only for testing and will be closed w/o merge after release. Numba master with a new llvmlite package. So, as a result in llvmlite the PRs will be 🍒 picked and closed but in Numba they need to be 🍒  picked, tested and then merged.

**Pull request merged**
