### PR TITLE
Implement str.index() based on CPython

### PR DESCRIPTION
**Pull request by densmirn**

### CODE REVIEW

**Comment by densmirn** [comment]
Could you please add the PR to the review queue?

**Comment by esc** [comment]
@densmirn this PR is labelled as implementing `str.index` but also implements `str.find`? Is this correct or is this the result of a git mistake?

**Comment by densmirn** [comment]
> @densmirn this PR is labelled as implementing `str.index` but also implements `str.find`? Is this correct or is this the result of a git mistake?

It's correct, because `str.index` depends on `str.find`, but `str.find` wasn't implemented completely.

**Comment by esc** [comment]
@densmirn yes, could you please split this PR into two separate PRs, one for `find` and one for `index` as it will make it easier for us to review it. Thanks!

**Comment by esc** [comment]
@densmirn thanks for splitting this, this PR now depends on #4866 and probably won't work without it. Let's wait until that one is merged to master and then I will continue to review this one.

**Comment by densmirn** [comment]
After updating the PR from master CI fails. Could you please fix it?

**Comment by esc** [comment]
@densmirn we are currently attempting to fix `master` at: https://github.com/numba/numba/pull/4880

**Comment by densmirn** [comment]
Could you please continue reviewing the PR?

**Pull request merged**
