### PR TITLE
IR node aliasing check

### PR DESCRIPTION
**Pull request by DrTodd13**
This PR adds code to detect re-use (aliasing) of nodes in the IR.  Typically we don't want such aliasing because if some pass changes one spot in the IR, it will assume that that is the only spot changed.  If something that is aliased were changed, that wouldn't be the case.

Some aliasing is okay.  There is lots of Loc and Scope aliasing.  Those are filtered out and not reported.

### CODE REVIEW

**Comment by DrTodd13** [comment]
Below is the IR node aliasing report for test_parfors.TestParfors.test_arraymap.  Things aren't printed in this order (there is some nesting) in the real output but here I've collated the results for each function together.

```
translate_bytecode has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
fixup_args has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
ir_processing has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
with_lifting has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
rewrite_semantic_constants has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
generic_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
inline_closure_likes has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
make_function_op_code_to_jit_function has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
inline_inlinables has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
find_literally has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
literal_unroll has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
nopython_type_inference has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
annotate_types has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
inline_overloads has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
pre_parfor_pass has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
nopython_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 5}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
parfor_pass has aliases in IR. Counter({<class 'numba.ir.Var'>: 33}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
ir_legalization has aliases in IR. Counter({<class 'numba.ir.Var'>: 33}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
nopython_backend has aliases in IR. Counter({<class 'numba.ir.Var'>: 28}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
dump_parfor_diagnostics has aliases in IR. Counter({<class 'numba.ir.Var'>: 28}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
translate_bytecode has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
fixup_args has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
ir_processing has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
with_lifting has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
rewrite_semantic_constants has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
generic_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
inline_closure_likes has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
make_function_op_code_to_jit_function has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
inline_inlinables has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
find_literally has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython.
literal_unroll has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
nopython_type_inference has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
annotate_types has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
inline_overloads has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
nopython_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 5}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
ir_legalization has aliases in IR. Counter({<class 'numba.ir.Var'>: 5}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
nopython_backend has aliases in IR. Counter({<class 'numba.ir.Var'>: 5}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython
dump_parfor_diagnostics has aliases in IR. Counter({<class 'numba.ir.Var'>: 5}) numba.tests.test_parfors.TestParfors.test_arraymap.<locals>.test_impl: nopython

ir_processing has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
with_lifting has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
rewrite_semantic_constants has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
generic_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
inline_closure_likes has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
make_function_op_code_to_jit_function has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
inline_inlinables has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
find_literally has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
literal_unroll has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
nopython_type_inference has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
annotate_types has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
inline_overloads has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
pre_parfor_pass has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
nopython_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
parfor_pass has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
ir_legalization has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
nopython_backend has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython
dump_parfor_diagnostics has aliases in IR. Counter({<class 'numba.ir.Var'>: 5, <class 'tuple'>: 1}) <dynamic>.__numba_parfor_gufunc_0x7f9158112cc0: nopython

translate_bytecode has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
fixup_args has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
ir_processing has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
with_lifting has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
rewrite_semantic_constants has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
generic_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
inline_closure_likes has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
make_function_op_code_to_jit_function has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
inline_inlinables has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
find_literally has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
literal_unroll has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
nopython_type_inference has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
annotate_types has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
inline_overloads has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
nopython_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
ir_legalization has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
nopython_backend has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython
dump_parfor_diagnostics has aliases in IR. Counter({<class 'numba.ir.Var'>: 6}) <dynamic>.__numba_array_expr_0x7f9157fe80b8: nopython

translate_bytecode has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
fixup_args has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
ir_processing has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
with_lifting has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
rewrite_semantic_constants has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
generic_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
inline_closure_likes has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
make_function_op_code_to_jit_function has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
inline_inlinables has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
dead_branch_prune has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
find_literally has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
literal_unroll has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
nopython_type_inference has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
annotate_types has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
inline_overloads has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
nopython_rewrites has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
ir_legalization has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
nopython_backend has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
dump_parfor_diagnostics has aliases in IR. Counter({<class 'numba.ir.Var'>: 48}) numba.targets.npyimpl._broadcast_onto: nopython
```

**Comment by ehsantn** [comment]
Maybe the IR needs to be read-only to allow reuse while preventing errors? In this case, passes need to replace the nodes instead of changing them.

**Comment by DrTodd13** [comment]
Yes.   That would work.  You could derive all the IR nodes from an immutable base class (like http://code.activestate.com/recipes/577207-immutable-objectsubclass/).  That would require fewer changes than making sure that absolutely nothing aliases.  Good idea Ehsan.

**Comment by ehsantn** [comment]
Sounds good. Thanks.

**Comment by DrTodd13** [comment]
Hmmm.... I tinkered with this a bit.  I take back saying this could limit changes as changes in this system have to percolate upwards.  If you want to change a Var in an expr you can't so you have to create a new expr with the new var but that expr is in an assign so you can't change the expr but have to create a new assign with the new expr.  But, you can't change the assign either so you have to create a new assign and propagate that back to the block level where you can finally stop.  I'll create a PR from what I've done so far so people can find the code but the first hit was in ir_utils/visit_vars_stmt where everything is being replaced in-place so this kind of change could be far reaching.

**Pull request closed without merging**
