### PR TITLE
Use PEP 508 compliant env markers for install deps

### LINKED ISSUE #4103: Depend on enum34 using PEP 508 environment markers
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This is a straight up copy of https://github.com/numba/llvmlite/pull/483 

Looks like the offending lines are https://github.com/numba/numba/blob/master/setup.py#L309-L312 as mentioned by @esc

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

Fixes #4103

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Not quite sure how to test this!?

**Comment by sklam** [comment]
I can check it manually

**Comment by sklam** [comment]
It works.

**Comment by stuartarchibald** [comment]
Thanks @sklam

**Pull request merged**
