### PR TITLE
NumPy 1.21 support

### PR DESCRIPTION
**Pull request by stuartarchibald**
This PR:
* adds NumPy 1.21 to the public CI build matrix. NumPy 1.17 is dropped (supported ended on July 26th, 2021 as per NEP=029 https://numpy.org/neps/nep-0029-deprecation_policy.html).
* Fixes up conda recipes, `setup.py`, `__init__.py` and docs for 1.21.
* Pulls in the `ufunc` C code patch (https://github.com/numba/numba/pull/7449/commits/df8442fafcbbc9d11531c3ed6be082e0a70355f3) from https://github.com/numba/numba/pull/7449 (with thanks to @seberg).

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks @seberg! Development builds (of e.g. llvmlite) are in the conda channel `numba/label/dev`.

**Comment by stuartarchibald** [comment]
Second local test run against 4df2640 passed.

**Comment by sklam** [comment]
BFID `numba_smoketest_cpu_yaml_56`

**Comment by esc** [comment]
The only failure on the build farm was the ppc64le build due to missing Numpy 1.21 package.

**Comment by esc** [comment]
@stuartarchibald I changed this to Ready for Review, I think it's ready, right?

**Comment by esc** [comment]
as per OOB conversation with @stuartarchibald -- we will give this a full build farm run and not just a smoketest. The labels remain accurate.

**Comment by esc** [comment]
I tried this locally with Numpy 1.21.4 from conda-forge and got:

```
 💣 zsh» python -m numba.runtests -v numba.tests.test_array_reductions.TestArrayReductions.test_median_npdatetime
test_median_npdatetime (numba.tests.test_array_reductions.TestArrayReductions) ... FAIL

======================================================================
FAIL: test_median_npdatetime (numba.tests.test_array_reductions.TestArrayReductions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/tests/test_array_reductions.py", line 729, in test_median_npdatetime
    self.check_nptimedelta(array_median_global)
  File "/Users/vhaenel/git/numba/numba/tests/test_array_reductions.py", line 710, in check_nptimedelta
    self._do_check_nptimedelta(pyfunc, arr)
  File "/Users/vhaenel/git/numba/numba/tests/test_array_reductions.py", line 690, in _do_check_nptimedelta
    self.assertPreciseEqual(cfunc(arr), pyfunc(arr))
  File "/Users/vhaenel/git/numba/numba/tests/support.py", line 361, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing 3 seconds and 4 seconds: numpy.timedelta64(3,'s') != numpy.timedelta64(4,'s')

----------------------------------------------------------------------
Ran 1 test in 1.816s

FAILED (failures=1)
```

**Comment by esc** [comment]
> I tried this locally with Numpy 1.21.4 from conda-forge and got:
> 
> ```
>  💣 zsh» python -m numba.runtests -v numba.tests.test_array_reductions.TestArrayReductions.test_median_npdatetime
> test_median_npdatetime (numba.tests.test_array_reductions.TestArrayReductions) ... FAIL
> 
> ======================================================================
> FAIL: test_median_npdatetime (numba.tests.test_array_reductions.TestArrayReductions)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/vhaenel/git/numba/numba/tests/test_array_reductions.py", line 729, in test_median_npdatetime
>     self.check_nptimedelta(array_median_global)
>   File "/Users/vhaenel/git/numba/numba/tests/test_array_reductions.py", line 710, in check_nptimedelta
>     self._do_check_nptimedelta(pyfunc, arr)
>   File "/Users/vhaenel/git/numba/numba/tests/test_array_reductions.py", line 690, in _do_check_nptimedelta
>     self.assertPreciseEqual(cfunc(arr), pyfunc(arr))
>   File "/Users/vhaenel/git/numba/numba/tests/support.py", line 361, in assertPreciseEqual
>     self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
> AssertionError: when comparing 3 seconds and 4 seconds: numpy.timedelta64(3,'s') != numpy.timedelta64(4,'s')
> 
> ----------------------------------------------------------------------
> Ran 1 test in 1.816s
> 
> FAILED (failures=1)
> ```

Right, it looks like this is a 1.21.3 %% 1.21.4 issue.

**Comment by seberg** [comment]
> Right, it looks like this is a 1.21.3 %% 1.21.4 issue.

Really?  The 4 is correct, right?  Isn't the 3 the numba result?  There was an integer division bug fix in 1.21.4, but overall it is a small release, so I am confused as to what interaction could cause this from NumPy.

**Comment by esc** [comment]
> > Right, it looks like this is a 1.21.3 %% 1.21.4 issue.
> 
> Really? The 4 is correct, right? Isn't the 3 the numba result? There was an integer division bug fix in 1.21.4, but overall it is a small release, so I am confused as to what interaction could cause this from NumPy.

Yes, it only happens on 1.21.3 and 1.21.4 for me on 3.9 on osx -- not with 1.21.2

**Comment by esc** [comment]
The first, `cfunc` is the Numba result yes, the `pyfunc` is the Numpy result.

**Comment by esc** [comment]
Question: can anybody else confirm this happens with 1.21.3 and above?

**Comment by stuartarchibald** [comment]
Reported here: https://github.com/numpy/numpy/issues/20376

**Comment by esc** [comment]
> Reported here: [numpy/numpy#20376](https://github.com/numpy/numpy/issues/20376)

Thank you @stuartarchibald

**Comment by esc** [comment]
`Build numba_smoketest_cpu_yaml_65 has started`

**Review by sklam — APPROVED** [review]
The changes on NaT looks good as well. 

Once NumPy stabilizes on the behavior for NaT comparison, we can come back to update the test. But for now, the changes here is avoiding tests that contains NaT in median.

**Comment by sklam** [comment]
Note: once this passes on the farm, it can be merged.

**Comment by esc** [comment]
Screen Shot 2021-11-22 at 23 41 45

Everything not Python 3.10 passed. So we will merge this tonight.

**Comment by esc** [comment]
@sklam @seberg @stuartarchibald @gmarkall thank you all!

**Comment by esc** [comment]
> Everything not Python 3.10 passed. So we will merge this tonight.

With the exception of the ppcle64 build, due to missing Numpy 1.21 -- as I just double checked -- @sklam still good to go?

**Comment by seberg** [comment]
One thing to note, is that on Python 3.8+, NumPy also uses `tp_vectorcall`, since I had first thought this might be backported too, I wanted to be a bit minimal and did not include that.

If keywords are being used, numba will have some extra overhad for e.g. `ufunc(x, out=y)`, implementing fastcall could be nice.

**Comment by christian-cahig** [comment]
Hi, is this supported in Numba 0.54.1?

**Comment by seibert** [comment]
This will be released in Numba 0.55.0, coming soon.

**Comment by kyoungseoun-chung** [comment]
> 

As far as I know, it doesn't. 

I think you should install numba by cloning the repository, otherwise, we need to wait for the new version release...

**Comment by seberg** [comment]
I expect the patch applies cleanly to 0.54.x, although I guess that won't help much...

**Comment by christian-cahig** [comment]
> If you are using conda, we also automatically build packages whenever a PR is merged, which you can install:
> 
> ```
> conda install -c numba/label/dev numba=0.55.0dev0
> ```
> 
> (Edit: Note that while these packages have to pass our full test suite, they don't have any of the community testing that comes with an official release. So be careful. :) )

Thanks, @seibert!

**Pull request merged**
