### PR TITLE
Move Azure builds to OSX 10.15.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by esc** [comment]
Taking a closer look, it seems like Numba will not compiler on the new OSX image yet. Here is a log snapshot:


```
python setup.py build_ext -q --inplace --debug $EXTRA_BUILD_EXT_FLAGS
TBB not found
Using OpenMP from: /Users/runner/miniconda3/envs/azure_ci
running build_ext
building 'numba._dynfunc' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/runner/miniconda3/envs/azure_ci=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/azure_ci/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/azure_ci/include

creating build
creating build/temp.macosx-10.9-x86_64-3.7
creating build/temp.macosx-10.9-x86_64-3.7/numba
compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include/python3.7m -c'
x86_64-apple-darwin13.4.0-clang: numba/_dynfuncmod.c
x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/azure_ci/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.7/numba/_dynfuncmod.o -o /Users/runner/work/1/s/numba/_dynfunc.cpython-37m-darwin.so
/Users/runner/miniconda3/envs/azure_ci/lib/python3.7/site-packages/setuptools/dist.py:487: UserWarning: Normalizing '0.55.0dev0+942.g074e73783' to '0.55.0.dev0+942.g074e73783'
  warnings.warn(tmpl.format(**locals()))
error: Command "x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/runner/miniconda3/envs/azure_ci/include -D_FORTIFY_SOURCE=2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.7/numba/_dynfuncmod.o -o /Users/runner/work/1/s/numba/_dynfunc.cpython-37m-darwin.so" failed with exit status 1
##[error]Bash exited with code '1'.
```

**Comment by esc** [comment]
Public CI is currently broken, because we were unable to solve this in time. Running on Azure now cancels the OSX builds and yields the following error message:

Screen Shot 2021-12-13 at 12 28 52

**Comment by esc** [comment]
When using the system compilers, we do get further, but we can't compile the whole thing:

```
2021-12-13T13:20:30.7376120Z ##[section]Starting: Build
2021-12-13T13:20:30.7397780Z ==============================================================================
2021-12-13T13:20:30.7400620Z Task         : Command line
2021-12-13T13:20:30.7401170Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2021-12-13T13:20:30.7402200Z Version      : 2.182.0
2021-12-13T13:20:30.7407980Z Author       : Microsoft Corporation
2021-12-13T13:20:30.7409000Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2021-12-13T13:20:30.7409650Z ==============================================================================
2021-12-13T13:20:30.9978780Z Generating script.
2021-12-13T13:20:30.9993090Z ========================== Starting Command Output ===========================
2021-12-13T13:20:31.0023820Z [command]/bin/bash --noprofile --norc /Users/runner/work/_temp/79182caa-5244-495a-aae8-29570b4cf11e.sh
2021-12-13T13:20:31.7414790Z 
2021-12-13T13:20:31.7477940Z # Build numba extensions without silencing compile errors
2021-12-13T13:20:31.7507420Z if [[ "$(uname -s)" == *"Linux"* ]] && [[ "$(uname -p)" == *"86"* ]]; then
2021-12-13T13:20:31.7519130Z     EXTRA_BUILD_EXT_FLAGS="--werror --wall"
2021-12-13T13:20:31.7523380Z else
2021-12-13T13:20:31.7524520Z     EXTRA_BUILD_EXT_FLAGS=""
2021-12-13T13:20:31.7525770Z fi
2021-12-13T13:20:31.7527450Z uname -s
2021-12-13T13:20:31.7528320Z 
2021-12-13T13:20:31.7529650Z if [[ $(uname) == "Darwin" ]]; then
2021-12-13T13:20:31.7530900Z     export MACOSX_SDK_VERSION=10.15
2021-12-13T13:20:31.7532180Z     export MACOSX_DEPLOYMENT_TARGET=10.15
2021-12-13T13:20:31.7533430Z     export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
2021-12-13T13:20:31.7535370Z     export OSX_SDK_DIR="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
2021-12-13T13:20:31.7636610Z     export USING_SYSTEM_SDK_DIR=1
2021-12-13T13:20:31.7710270Z     export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
2021-12-13T13:20:31.7747030Z     plutil -replace MinimumSDKVersion -string ${MACOSX_SDK_VERSION} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
2021-12-13T13:20:31.7758240Z     plutil -replace DTSDKName -string macosx${MACOSX_SDK_VERSION}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
2021-12-13T13:20:31.7763560Z fi
2021-12-13T13:20:31.7786040Z uname
2021-12-13T13:20:31.7791480Z xcode-select -p
2021-12-13T13:20:31.7853400Z xcode-select -p
2021-12-13T13:20:31.8346180Z xcode-select -p
2021-12-13T13:20:31.8481890Z python setup.py build_ext -q --inplace --debug $EXTRA_BUILD_EXT_FLAGS
2021-12-13T13:20:41.3353690Z /Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/setuptools/dist.py:487: UserWarning: Normalizing '0.55.0dev0+1017.g7d4140036' to '0.55.0.dev0+1017.g7d4140036'
2021-12-13T13:20:41.3463750Z   warnings.warn(tmpl.format(**locals()))
2021-12-13T13:20:41.3564260Z Using Intel TBB from: /Users/runner/miniconda3/envs/azure_ci
2021-12-13T13:20:41.3666540Z OpenMP not found
2021-12-13T13:20:41.3723750Z running build_ext
2021-12-13T13:20:41.3789030Z building 'numba._dynfunc' extension
2021-12-13T13:20:41.7779530Z Warning: Can't read registry to find the necessary compiler setting
2021-12-13T13:20:41.7781820Z Make sure that Python modules winreg, win32api or win32con are installed.
2021-12-13T13:20:52.0326050Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:20:52.0327330Z 
2021-12-13T13:20:52.0327780Z creating build
2021-12-13T13:20:52.0328990Z creating build/temp.macosx-10.9-x86_64-3.9
2021-12-13T13:20:52.0330160Z creating build/temp.macosx-10.9-x86_64-3.9/numba
2021-12-13T13:20:52.0332100Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:20:52.0333890Z clang: numba/_dynfuncmod.c
2021-12-13T13:20:53.1422650Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/_dynfuncmod.o -o /Users/runner/work/1/s/numba/_dynfunc.cpython-39-darwin.so
2021-12-13T13:20:54.1022690Z building 'numba._dispatcher' extension
2021-12-13T13:20:54.1126240Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:20:54.1127740Z 
2021-12-13T13:20:54.1229780Z creating build/temp.macosx-10.9-x86_64-3.9/numba/core
2021-12-13T13:20:54.1245510Z creating build/temp.macosx-10.9-x86_64-3.9/numba/core/typeconv
2021-12-13T13:20:54.1248980Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:20:54.1250860Z clang: numba/_dispatcher.cpp
2021-12-13T13:20:54.1277290Z clang: numba/_typeof.c
2021-12-13T13:20:54.1344470Z clang: numba/_hashtable.c
2021-12-13T13:20:54.1345920Z clang: numba/core/typeconv/typeconv.cpp
2021-12-13T13:20:55.0590450Z clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/_dispatcher.o build/temp.macosx-10.9-x86_64-3.9/numba/_hashtable.o build/temp.macosx-10.9-x86_64-3.9/numba/_typeof.o build/temp.macosx-10.9-x86_64-3.9/numba/core/typeconv/typeconv.o -L/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/lib -lnpymath -o /Users/runner/work/1/s/numba/_dispatcher.cpython-39-darwin.so
2021-12-13T13:20:56.0138200Z building 'numba._helperlib' extension
2021-12-13T13:20:56.0140360Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:20:56.0141240Z 
2021-12-13T13:20:56.0142570Z creating build/temp.macosx-10.9-x86_64-3.9/numba/cext
2021-12-13T13:20:56.0144380Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:20:56.0159490Z clang: numba/_helpermod.c
2021-12-13T13:20:56.0161800Z clang: numba/cext/dictobject.c
2021-12-13T13:20:56.0181690Z clang: numba/cext/listobject.c
2021-12-13T13:20:56.8751700Z clang: numba/cext/utils.c
2021-12-13T13:20:58.6387940Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/_helpermod.o build/temp.macosx-10.9-x86_64-3.9/numba/cext/dictobject.o build/temp.macosx-10.9-x86_64-3.9/numba/cext/listobject.o build/temp.macosx-10.9-x86_64-3.9/numba/cext/utils.o -L/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/lib -lnpymath -o /Users/runner/work/1/s/numba/_helperlib.cpython-39-darwin.so -headerpad_max_install_names
2021-12-13T13:20:58.7366900Z building 'numba.core.typeconv._typeconv' extension
2021-12-13T13:20:58.7440680Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:20:58.7473460Z 
2021-12-13T13:20:58.7505440Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:20:58.7511690Z clang: numba/core/typeconv/_typeconv.cpp
2021-12-13T13:20:58.7514200Z clang: numba/core/typeconv/typeconv.cpp
2021-12-13T13:20:59.8445700Z clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/core/typeconv/_typeconv.o build/temp.macosx-10.9-x86_64-3.9/numba/core/typeconv/typeconv.o -o /Users/runner/work/1/s/numba/core/typeconv/_typeconv.cpython-39-darwin.so
2021-12-13T13:20:59.9617630Z building 'numba.np.ufunc._internal' extension
2021-12-13T13:20:59.9651950Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:20:59.9656850Z 
2021-12-13T13:20:59.9659960Z creating build/temp.macosx-10.9-x86_64-3.9/numba/np
2021-12-13T13:20:59.9662280Z creating build/temp.macosx-10.9-x86_64-3.9/numba/np/ufunc
2021-12-13T13:20:59.9664090Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:20:59.9665100Z clang: numba/np/ufunc/_internal.c
2021-12-13T13:21:00.6019050Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/np/ufunc/_internal.o -L/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/lib -lnpymath -o /Users/runner/work/1/s/numba/np/ufunc/_internal.cpython-39-darwin.so
2021-12-13T13:21:00.6855650Z building 'numba.np.ufunc._num_threads' extension
2021-12-13T13:21:00.6901060Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:00.6911930Z 
2021-12-13T13:21:00.6930110Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:00.6939920Z clang: numba/np/ufunc/_num_threads.c
2021-12-13T13:21:00.9594970Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/np/ufunc/_num_threads.o -o /Users/runner/work/1/s/numba/np/ufunc/_num_threads.cpython-39-darwin.so
2021-12-13T13:21:01.0513130Z building 'numba.mviewbuf' extension
2021-12-13T13:21:01.0558510Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:01.0569220Z 
2021-12-13T13:21:01.0580170Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:01.0587470Z clang: numba/mviewbuf.c
2021-12-13T13:21:01.3819320Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/mviewbuf.o -o /Users/runner/work/1/s/numba/mviewbuf.cpython-39-darwin.so -headerpad_max_install_names
2021-12-13T13:21:01.4874030Z building 'numba.core.runtime._nrt_python' extension
2021-12-13T13:21:01.4954200Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:01.5056160Z 
2021-12-13T13:21:01.5098750Z creating build/temp.macosx-10.9-x86_64-3.9/numba/core/runtime
2021-12-13T13:21:01.5202010Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/include -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:01.5304580Z clang: numba/core/runtime/_nrt_pythonmod.c
2021-12-13T13:21:01.5408680Z clang: numba/core/runtime/nrt.c
2021-12-13T13:21:02.4033310Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/core/runtime/_nrt_pythonmod.o build/temp.macosx-10.9-x86_64-3.9/numba/core/runtime/nrt.o -L/Users/runner/miniconda3/envs/azure_ci/lib/python3.9/site-packages/numpy/core/lib -lnpymath -o /Users/runner/work/1/s/numba/core/runtime/_nrt_python.cpython-39-darwin.so
2021-12-13T13:21:02.4757460Z building 'numba.experimental.jitclass._box' extension
2021-12-13T13:21:02.4858570Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:02.4959630Z 
2021-12-13T13:21:02.5027120Z creating build/temp.macosx-10.9-x86_64-3.9/numba/experimental
2021-12-13T13:21:02.5078050Z creating build/temp.macosx-10.9-x86_64-3.9/numba/experimental/jitclass
2021-12-13T13:21:02.5118020Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:02.5154530Z clang: numba/experimental/jitclass/_box.c
2021-12-13T13:21:02.7164730Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/experimental/jitclass/_box.o -o /Users/runner/work/1/s/numba/experimental/jitclass/_box.cpython-39-darwin.so
2021-12-13T13:21:02.8188730Z building 'numba.cuda.cudadrv._extras' extension
2021-12-13T13:21:02.8290100Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:02.8390530Z 
2021-12-13T13:21:02.8462140Z creating build/temp.macosx-10.9-x86_64-3.9/numba/cuda
2021-12-13T13:21:02.8485040Z creating build/temp.macosx-10.9-x86_64-3.9/numba/cuda/cudadrv
2021-12-13T13:21:02.8520610Z compile options: '-g -Inumba -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:02.8554900Z clang: numba/cuda/cudadrv/_extras.c
2021-12-13T13:21:03.0896220Z clang -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/cuda/cudadrv/_extras.o -o /Users/runner/work/1/s/numba/cuda/cudadrv/_extras.cpython-39-darwin.so
2021-12-13T13:21:03.1831170Z building 'numba._devicearray' extension
2021-12-13T13:21:03.1861980Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:03.1864810Z 
2021-12-13T13:21:03.1867490Z compile options: '-g -Inumba -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:03.1869970Z extra options: '-std=c++11'
2021-12-13T13:21:03.1872100Z clang: numba/_devicearray.cpp
2021-12-13T13:21:03.4659000Z clang++ -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -Wl,-rpath,/Users/runner/miniconda3/envs/azure_ci/lib -L/Users/runner/miniconda3/envs/azure_ci/lib -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.9/numba/_devicearray.o -o /Users/runner/work/1/s/numba/_devicearray.cpython-39-darwin.so
2021-12-13T13:21:03.5626970Z building 'numba.np.ufunc.tbbpool' extension
2021-12-13T13:21:03.5692680Z C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64
2021-12-13T13:21:03.5729400Z 
2021-12-13T13:21:03.5763450Z compile options: '-g -I/Users/runner/miniconda3/envs/azure_ci/include -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c'
2021-12-13T13:21:03.5765340Z extra options: '-std=c++11'
2021-12-13T13:21:03.5769680Z clang: numba/np/ufunc/gufunc_scheduler.cpp
2021-12-13T13:21:03.5770490Z clang: numba/np/ufunc/tbbpool.cpp
2021-12-13T13:21:07.0725420Z error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -I/Users/runner/miniconda3/envs/azure_ci/include -fPIC -O2 -isystem /Users/runner/miniconda3/envs/azure_ci/include -arch x86_64 -g -I/Users/runner/miniconda3/envs/azure_ci/include -I/Users/runner/miniconda3/envs/azure_ci/include/python3.9 -c numba/np/ufunc/gufunc_scheduler.cpp -o build/temp.macosx-10.9-x86_64-3.9/numba/np/ufunc/gufunc_scheduler.o -std=c++11" failed with exit status 1
2021-12-13T13:21:07.2514270Z ##[error]Bash exited with code '1'.
2021-12-13T13:21:07.2780660Z ##[section]Finishing: Build
```

**Comment by esc** [comment]
Ideas:

* try the latest image
* find a way to open a debug console on Azure
* try: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=macos

**Comment by xhochy** [comment]
You could also set `CONDA_BUILD_SYSROOT`; at least in the conda-forge compiler scripts, this is used to find the correct SDK. Otherwise, it could also be that the `tapi` version and the SDK don't match.

**Pull request closed without merging**
