### PR TITLE
Add support for cuda-device-side print().

### PR DESCRIPTION
**Pull request by stefanseefeld**
This patch adds support for 'print()' calls inside cuda-jit'ed functions.

### CODE REVIEW

**Comment by stefanseefeld** [comment]
It appears the new tests require numba.cuda features that are not available with the cuda simulator. Should we disable to tests conditionally on ENABLE_CUDASIM ?

**Comment by seibert** [comment]
@gmarkall: What do you think is required to add support for this to the CUDA simulator?

**Comment by gmarkall** [comment]
The simulator already supports the print function, since it only emulates the
GPU threading model, and otherwise it is just executing code with the normal
Python interpreter. The issue here is arising because this PR changes the order
in which modules get imported.

The simulator sets itself up when `numba.cuda` is imported, where  it replaces
most of the cuda modules with its own modules (see
`numba.cuda.simulator.__init__`). However, importing `cudapy` inside numba's
top-level `__init__` module bypasses the replacement of modules, because
`numba.cuda.cudapy.plugins` imports several modules from the compiler before the
simulator modules get swapped in place of the "normal" cuda modules. The way to
avoid this issue is to avoid doing anything other than `from .  import cuda` in
the top-level `__init__` for Numba for CUDA-related functionality.

Fortunately, the contents of `plugins.py` is not really required here; the
insertion of the print implementation's registry of functions is a "trick" that
was required in NumbaPro to deal with the fact that the CUDA target context is
already initialised. To understand how the other registries of functions for the
CUDA target are initialised in Numba, look at the `CUDATargetContext.init`
method.  The print implementation's registry should also be initialised in this
way.

There are also some slight structural differences between NumbaPro and Numba -
in particular, the cudapy module from NumbaPro is equivalent to the `numba.cuda`
module in Numba, rather than Numba having a module explicitly called `cudapy`.

So, what I think needs to be done in order to make this PR pass the tests again
is not a case of making any fundamental changes, but just a restructuring of
things that avoids the "real" CUDA implementation getting in ahead of the
simulator when the simulator is supposed to be enabled:

- Delete the numba.cuda.cudapy module. The code from `nvvmutils.py` can move
  into `numba.cuda.nvvmutils`, along with the other declarations. `printimpl.py`
  should move to `numba/cuda`, where it will be alongside the other CUDA method
  implementations in `cudaimpl.py`. The code in `plugins.py` is superfluous,
  because the implementations will be registered in a different way.
- Modify `numba.cuda.target.CUDATargetContext.init` so that it also installs the
  print implementation's registry in a similar manner to that for `libdevice`,
  `cmathimpl`, `operatorimpl`, etc.
- The tests of the print implementation also require an implementation of
  `cuda.synchronize`, which is presently not implemented in the simulator. So
  you will also need to add a function to `numba.cuda.simulator.api`:

  ```python
  def synchronize():
      pass
  ```

  It does not matter that this does nothing, because the simulator executes code
  synchronously anyway.

There are also a couple of other changes which would be nice to make:

- Update the documentation to add `print` and a description of its limitations
  to the list of supported functions in CUDA Python.
- `test_print_array` is skipped because printing of strings is not implemented
  yet. However, printing of arrays is implemented but not tested. Modifying this
  test so that it tests `print(a)` where `a` is a numpy array inside a CUDA
  kernel and then removing the `skipIf` decorator would be desirable.

**Comment by stefanseefeld** [comment]
Thanks for the thorough review. I'm refactoring my patch and will resubmit a new pull request once the tests pass with and without NUMBA_ENABLE_CUDASIM=1.

**Pull request closed without merging**
