### PR TITLE
Skip part of slice array analysis if any part is not analyzable.

### LINKED ISSUE #5601: Failure in step: convert to parfors
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Code which used to compile successfully using older versions of Numba/llvmlite (verified on 0.43.1/v0.28.0) now raises the following error:

```
TypeError: Failed in nopython mode pipeline (step: convert to parfors)
'NoneType' object is not iterable
```

I have set up the following MWR:
```python
import numpy as np
from numba import jit, prange


@jit(nopython=True, fastmath=True, parallel=True, cache=True, nogil=True)
def reproducer(arr):

    n_valid_vals = 0

    for i in prange(arr.shape[0]):

        if arr[i] != 0:
            n_valid_vals += 1

        if n_valid_vals:
            print(arr[:n_valid_vals])


if __name__ == "__main__":
    arr = np.random.random((3,))
    reproducer(arr)

```

### PR DESCRIPTION
**Pull request by DrTodd13**
Resolves #5601 

Some variables are not present in array analysis.  One common case of that is, like this issue, where a variable is multiply defined.  If such a variable occurs in a slice then likewise the slice becomes not analyzable.  This PR implements this propagation of a slice part being unanalyzable to the whole of the slice.

### CODE REVIEW

**Comment by gmarkall** [comment]
Thanks very much for the PR, I've queued it for review.

**Comment by DrTodd13** [comment]
Just had another report of an issue related to this that is making me think my solution is too restrictive.      I'm going to try to enable later array associations to be built on this slice even though we can't relate this slice to anything that has come before.

**Comment by gmarkall** [comment]
> Just had another report of an issue related to this that is making me think my solution is too restrictive. I'm going to try to enable later array associations to be built on this slice even though we can't relate this slice to anything that has come before.

Does your commit 53589c9 make this PR ready for review, or is there more to add to address this?

**Comment by DrTodd13** [comment]
> > Just had another report of an issue related to this that is making me think my solution is too restrictive. I'm going to try to enable later array associations to be built on this slice even though we can't relate this slice to anything that has come before.
> 
> Does your commit [53589c9](https://github.com/numba/numba/commit/53589c94328e092e5725c26cb4568c7438872280) make this PR ready for review, or is there more to add to address this?

Thanks for the reminder.  I forgot to take off the in progress label.  It should be ready for review now.

**Pull request merged**
