### PR TITLE
Fix unicode join for issue #6405

### PR DESCRIPTION
**Pull request by John-Ted**
Implemented patch suggested in the discussion of issue #6405. The copy-pastable reproducer given there now works.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch. Please could you add the failing reproducer as a test in `numba.tests.test_unicode_array`? Many thanks.

**Comment by John-Ted** [comment]
Hi. I added the unit test and all checks pass.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch!

**Comment by stuartarchibald** [comment]
@John-Ted Congratulations on your first contribution to Numba!

**Pull request merged**
