### PR TITLE
[WIP] Fix #5713: cache typed dict and list functions

### LINKED ISSUE #5713: List() and Dict() always recompile _getitem,_setitem, _length, etc. every time; maybe should cache?
- [ x] I am using the latest released version of Numba: 0.49.1
- [ x] I have included below a minimal working reproducer 

Something that has been bothering me is that for the typed List() and Dict() types every time I use a new type outside of a jitted function it will recompile all of the primitive functions I use with it. For example this simple example:

```python
import numba
from numba.types import f8,u8,i8
from numba.typed import Dict,List
import time

start = time.time()
for t1 in [f8,u8,i8]:
	l = List.empty_list(t1)
	l.append(0)
	v = l[0]
	for t2 in [f8,u8,i8]:
		d = Dict.empty(t1,t2)
		d[0] = 1
		v = d[0]
		for x in d:
			pass
end = time.time()
print("Time elapsed: %.2f" % (end - start))
```
Takes about 5 secs to run. Note that that is a ton of time since its only doing like 9 total iterations.

But when I just change all of the @njits in typedlist.py and typeddict.py to @njit(cache=True) this same script takes just 0.12 seconds, which is at least a reasonable amount of time to wait for my script to start up.

This bug is pretty frustrating because I'm trying to speed up my code with numba, but there is this annoying sunk cost whenever i want to fill a List which gets worse for every additional type I use. And, yes I am aware that with these particular types at least for the Lists() I could just instead use an np.array() instead. Unfortunately my use case requires a lot of strings, and arrays aren't particularly amenable to strings at the moment.

I'm also wondering if this might have something to do with #4584

### PR DESCRIPTION
**Pull request by gmarkall**
Making this PR to test on CI.

### CODE REVIEW

**Comment by gmarkall** [comment]
There is more to fixinf #5713 than just caching all typed List and dict functions, so I'll close this to reduce PR clutter.

**Comment by stuartarchibald** [comment]
Reopening to see what the CI failures are.

**Comment by stuartarchibald** [comment]
Fails with multiple variations on:
```
ERROR: test_sort_in_jit_w_global_key (numba.tests.test_typedlist.TestListSort)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/core/caching.py", line 484, in save
    data_name = overloads[key]
KeyError: ((ListType[int64], type(CPUDispatcher(<function TestListSort.test_sort_in_jit_w_global_key.<locals>.keyfn at 0x7fa578f91400>)), bool), ('x86_64-unknown-linux-gnu', 'skylake-avx512', '+64bit,+adx,+aes,+avx,+avx2,-avx512bf16,-avx512bitalg,+avx512bw,+avx512cd,+avx512dq,-avx512er,+avx512f,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,+avx512vl,-avx512vnni,-avx512vpopcntdq,+bmi,+bmi2,-cldemote,+clflushopt,-clwb,-clzero,+cmov,+cx16,+cx8,-enqcmd,+f16c,+fma,-fma4,+fsgsbase,+fxsr,-gfni,+invpcid,-lwp,+lzcnt,+mmx,+movbe,-movdir64b,-movdiri,-mwaitx,+pclmul,-pconfig,-pku,+popcnt,-prefetchwt1,+prfchw,-ptwrite,-rdpid,+rdrnd,+rdseed,+rtm,+sahf,-sgx,-sha,-shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,-sse4a,+ssse3,-tbm,-vaes,-vpclmulqdq,-waitpkg,-wbnoinvd,-xop,+xsave,+xsavec,+xsaveopt,+xsaves'), ('46cbfcfe69df8133d3465e0dc3f7ea272b926c4e676029089355581f562a39e8', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vsts/work/1/s/numba/tests/test_typedlist.py", line 1265, in test_sort_in_jit_w_global_key
    self.assertEqual(udt(lst), udt.py_func(lst))
  File "/home/vsts/work/1/s/numba/tests/test_typedlist.py", line 1261, in udt
    lst.sort(key=keyfn)
  File "/home/vsts/work/1/s/numba/typed/typedlist.py", line 393, in sort
    return _sort(self, key, reverse)
  File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 433, in _compile_for_args
    raise e
  File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 366, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/vsts/work/1/s/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 824, in compile
    self._cache.save_overload(sig, cres)
  File "/home/vsts/work/1/s/numba/core/caching.py", line 668, in save_overload
    self._save_overload(sig, data)
  File "/home/vsts/work/1/s/numba/core/caching.py", line 678, in _save_overload
    self._cache_file.save(key, data)
  File "/home/vsts/work/1/s/numba/core/caching.py", line 493, in save
    self._save_index(overloads)
  File "/home/vsts/work/1/s/numba/core/caching.py", line 539, in _save_index
    data = self._dump(data)
  File "/home/vsts/work/1/s/numba/core/caching.py", line 567, in _dump
    return pickle.dumps(obj, protocol=-1)
TypeError: can't pickle weakref objects
```

**Comment by gmarkall** [comment]
@stuartarchibald Maybe @eric-wieser's solution to https://github.com/numba/numba/issues/6251 would help here

**Comment by stuartarchibald** [comment]
> @stuartarchibald Maybe @eric-wieser's solution to #6251 would help here

Yes, thanks, it does locally: https://github.com/numba/numba/pull/6287#issuecomment-699939379

**Pull request closed without merging**
