### PR TITLE
Fix DeviceNDArray null shape issue

### PR DESCRIPTION
**Pull request by testhound**
This pull request resolves: https://github.com/numba/numba/issues/5234. I was able to utilize the patch posted in the issue and added a test case.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch @testhound . CI failure is unrelated.

**Review by gmarkall — APPROVED** [review]
This looks good to me! It passes all tests locally with hardware and the simulator.

**Comment by gmarkall** [comment]
@esc could this have a buildfarm run please?

**Comment by esc** [comment]
Buildfarm ID: `numba_smoketest_cuda_yaml_19`

**Comment by esc** [comment]
BF passed!

**Comment by gmarkall** [comment]
Many thanks for the run - marking as RTM accordingly.

**Review by stuartarchibald — APPROVED** [review]
Patch looks good, thanks.

**Pull request merged**
