### PR TITLE
np.where with broadcasting

### PR DESCRIPTION
**Pull request by rjenc29**
Small extension to `np.where` to support use cases like:

```python
a = np.linspace(-2, 5, 20).reshape(4, 5)
cond = a > 0
mask = np.where(cond, 1, 0)
```

Initial commit for CI.

### CODE REVIEW

**Comment by rjenc29** [comment]
Hi, let me know what you think of this relatively simple extension.  Could arguably be taken further either in this PR or subsequently; might have incremental utility on its own.

**Comment by stuartarchibald** [comment]
Thanks for the patches. Am I right in thinking that this is with view of closing https://github.com/numba/numba/issues/3339 ?

**Comment by rjenc29** [comment]
I hadn't spotted that one to be honest, but it should fit the bill.  It was more of a thought experiment which turned into a PR :)

**Comment by stuartarchibald** [comment]
This is pending update RE #3650

**Pull request merged**
