### PR TITLE
Updates for llvmlite 0.25

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by sklam** [comment]
LGTM.  Just waiting for CI.

**Comment by seibert** [comment]
I think the numba channel now has llvmlite 0.25.0 builds posted.

**Comment by stuartarchibald** [comment]
Seems so... I think this build pass is valid. Merge?

**Comment by stuartarchibald** [comment]
Thanks @sklam :)

**Pull request merged**
