### PR TITLE
`numba.typed.typeddict.Dict.get` uses `castedkey` to avoid returning default value even if the key is present

### PR DESCRIPTION
**Pull request by czgdp1807**
Closes https://github.com/numba/numba/issues/7908

cc: @guilhermeleobas @stuartarchibald @MarcMassar

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@czgdp1807 thanks for the patch!

@guilhermeleobas could you review this one please? Many thanks.

**Review by guilhermeleobas — APPROVED** [review]
Thanks for the patch @czgdp1807

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch @czgdp1807, thanks for reviewing @guilhermeleobas.

**Comment by czgdp1807** [comment]
> Congratulations on your first contribution to Numba!

Interested in doing more and learning a lot in the process. :-)

**Pull request merged**
