### PR TITLE
Document lack of support for np.array(order='F')

### PR DESCRIPTION
**Pull request by jzwinck**
Related: #1971.

### CODE REVIEW

**Comment by pitrou** [comment]
Thank you. I think it would be more logical to add the mention in the "supported functions" / "other functions" paragraph (actually, a couple functions there already mention not supporting `order`: `np.flatten` and `np.ravel`; what do you think?).

**Comment by pitrou** [comment]
Also, it may be useful to add an entry to the FAQ page in the documentation, to explain how to create a Fortran-ordered array.

**Comment by jzwinck** [comment]
I'm fine with mentioning it anywhere on the page.  I'll leave it to you to decide where to put it and exactly how to phrase it.

**Comment by pitrou** [comment]
Fair enough, I'll open a new PR.

**Comment by pitrou** [comment]
I'm closing this in favour of PR #1973. Thank you for proposing a fix!

**Pull request closed without merging**
