### PR TITLE
Implement dominance frontier for SSA for the Numba IR

### PR DESCRIPTION
**Pull request by guilhermeleobas**
So far, I've implemented the dominance frontier using the algorithm described in the paper _"A Simple, Fast Dominance Algorithm" - K. D. Cooper, T. J. Harvey, and K. Kennedy._

I still need to write some tests but I would appreciate some feedback.

issue #3904

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Fixed flake8 errors and added code for testing the immediate dominator algorithm.

**Comment by sklam** [comment]
I added some tests basing on real python bytecode at https://github.com/sklam/numba/tree/pr/4149.  The algorithm seems to be working as expected.

**Comment by sklam** [comment]
@guilhermeleobas, I think this PR is feature complete for IDOM and DOMFRONT.  Do you have any addition to these algorithms?  I think other SSA related features should go in a separate PR.

**Comment by guilhermeleobas** [comment]
No, that’s all for dominance frontier and immediate dominators.

**Comment by sklam** [comment]
Ok, I'll remove the WIP tags on it.

**Comment by guilhermeleobas** [comment]
Should I wait for this PR to be merged or can I already create another PR for the rest of the SSA?

**Comment by sklam** [comment]
You can create another PR.  If there's any change on this PR, you can always merge it to the new PR.

**Comment by sklam** [comment]
@stuartarchibald, yes, we'll need the license and references to source SHA's from NetworkX.  @guilhermeleobas, we can merge the PR once you added those.

**Comment by guilhermeleobas** [comment]
Done! Let me know if you guys need any other modification. 

Regards

**Comment by seibert** [comment]
with reference added, this looks ready to merge.

**Pull request merged**
