### PR TITLE
Recommend miniforge instead of c4aarch64

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by esc** [comment]
@isuruf thank you for submitting this PR to Numba. I have added it to the queue for review.

**Comment by esc** [comment]
I reviewed the changes, the documentation renders correctly.

**Comment by stuartarchibald** [comment]
Before recommending it, should probably make sure Numba is using it in internal testing/build farm etc?

**Comment by stuartarchibald** [comment]
> Before recommending it, should probably make sure Numba is using it in internal testing/build farm etc?

CC @esc, am happy to review the patch.

**Comment by esc** [comment]
@stuartarchibald probably a good idea, hopefully that will happen this quarter.  Also, I just tried miniforge and got:

```
zsh» conda create mynumba                                                                                                                                       :(

CondaValueError: The target prefix is the base prefix. Aborting.
```

Probably an issue with my setup locally, but it did prevent me from any further testing for now.

**Comment by esc** [comment]
Ah, was missing the `-n` flag...

**Comment by esc** [comment]
FYI: I've started working on a new internal docker image that uses miniforge distribution so we can give this a spin through our build farm. For the old `conda4aarch64` there were some significant differences to the "regular" miniconda. I have some questions about this change, @isuruf perhaps you can confirm?

* The `base` env was called `root`. I believe this is no longer the case?
* We used to need to extra channels `conda-forge c4aarch64`. From what I can tell from the PR these are no longer needed.
* Lastly, the old distro would need `build-essentialls` installed to build and compile? Will this still be needed?

Thank you in advance for  your feedback. 🙏

**Comment by isuruf** [comment]
> The base env was called root. I believe this is no longer the case?

Yes, conda version bundled in conda4aarch64 installer was old and used the `root` name. Newer conda uses `base`.

> We used to need to extra channels conda-forge c4aarch64. From what I can tell from the PR these are no longer needed.

All the packages in `c4aarch64` are now in `conda-forge`. Miniforge adds `conda-forge` by default.

> Lastly, the old distro would need build-essentialls installed to build and compile? Will this still be needed?

Yes, it's still needed. As an alternative you can do `conda install compilers make` which should do the same.

**Comment by esc** [comment]
@isuruf excellent, thank you for the quick  response!

**Comment by esc** [comment]
Update on this: So I managed to build a new docker image and I did manage to compile `llvmdev` and `llvmlite` from scratch. But then I encountered

```
/opt/conda/conda-bld/llvmdev_1610049987043/work/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp:400: void llvm::RuntimeDyldELF::resolveAArch64Relocation(const llvm::SectionEntry&, uint64_t, uint64_t, uint32_t, int64_t): Assertion `static_cast<int64_t>(Result) >= (-2147483647-1) && static_cast<int64_t>(Result) <= (4294967295U)' failed.
Fatal Python error: Aborted
```

And:

```
qemu: uncaught target signal 6 (Aborted) - core dumped
```

So, now I will need to investigate. I doubt that it has something to do with the miniforge but I can not rule this out at this stage. As building and testing the stack is quite compute intensive, for example compiling `llvmdev` using docker/qemu on my Mac took about 6 hours, testing miniforge properly will probably take a few more days/weeks. But, since `c4aarch64` has been officially deprecated, we do need to move forward on this front.

**Comment by esc** [comment]
I builtout the Numba stack on a "real-hardware" stack from llvmdev through llvmlite to the Numba test suite and everything went well. I can report with confidence that miniforge works for our use case and think we should merge this PR. (FWIW: We will also proceed to use this in the `numba/ci`docker images.)

**Review by esc — APPROVED** [review]
Tested on real hardware.

**Comment by esc** [comment]
This is good to go in, both @seibert (OOB) and I are confident that miniforge will be fine.

**Pull request merged**
