### PR TITLE
Fix #829: allow setting the identity of a ufunc

### LINKED ISSUE #829: Add an option to set ufunc identity with vectorize?
Another way to write (some) custom aggregation functions, other than my suggested approach in #825, would be use plain old ufuncs.

This has the advantage of passing off the axis handling/looping to numpy's `ufunc.reduce` method. And in fact, it already *almost* works:

```
@vectorize(['float64(float64, float64)'])
def _nanadd(a, b):
    if np.isnan(b):
        return a
    else:
        return a + b

nansum = _nanadd.reduce
```

As a bonus, this method is consistently fast. It's generally slightly (~20%) slower than bottleneck, but it has better worst case performance: `bottleneck.nansum` slows down by a factor of 4x when aggregating over a non-contiguous dimension (e.g., `axis=0` for a 2-dimensional C contiguous array), but the nansum ufunc doesn't miss a beat. I suspect this is because numpy has some clever logic for picking the optimal ordering for nested iteration for ufunc.reduce.

What's missing? There's no way to set `_nanadd.identity = 0.0`, which we would need to ensure that the calculation is correct if any of the first values are missing.

So I propose that `vectorize` should gain the optional keyword argument `identity` to set this variable. Right now it is always set to `None`: https://github.com/numba/numba/blob/1f4bee0a86edc20c9d3de07046af0d77dfa75469/numba/npyufunc/_ufunc.c#L5

### PR DESCRIPTION
**Pull request by pitrou**
Add a "identity" keyword argument to @vectorize and @guvectorize.

### CODE REVIEW

**Comment by seibert** [comment]
We also should update the docstring for vectorize and guvectorize in https://github.com/numba/numba/blob/master/numba/npyufunc/decorators.py to describe the `identity` keyword argument specifically, since it is not shared with the `@jit` keyword arguments.

**Comment by shoyer** [comment]
This looks great -- but what exactly does the identity argument do for gufuncs? The reduce method on gufuncs doesn't work: `RuntimeError: Reduction not defined on ufunc with signature`.

**Comment by seibert** [comment]
That is a good point.  The identity is in the C API, but maybe no one has tried to define what `reduce` should look like for a gufunc.  It seems possible to define the semantics of `reduce` for binary gufuncs though.

**Comment by shoyer** [comment]
Looks like this will work for at least a few gufuncs (those with a "trivial core-signature"), so no harm leaving it in:
https://github.com/numpy/numpy/blob/3b22d87050ab63db0dcd2d763644d924a69c5254/numpy/core/src/umath/ufunc_object.c#L736

**Comment by pitrou** [comment]
Try this (IMO senseless, but apparently supported) piece of code:

```
import numpy as np

from numba import guvectorize


def func(a, out):
    res = 0
    for x in a:
        res += x
    out[()] = res

args = (['void(float64[:], float64[:])'], '(n)->()')

f = guvectorize(*args, identity=0)(func)
g = guvectorize(*args, identity=1)(func)
h = guvectorize(*args, identity=None)(func)

empty_array = np.empty(shape=(0,0))
out = np.empty(shape=())

f(empty_array, out=out)
print(out)
g(empty_array, out=out)
print(out)
h(empty_array, out=out)
```

**Comment by pitrou** [comment]
By the way, it's https://github.com/numpy/numpy/blob/3b22d87050ab63db0dcd2d763644d924a69c5254/numpy/core/src/umath/ufunc_object.c#L2282

**Pull request merged**
