### PR TITLE
Release0.56.1

### PR DESCRIPTION
**Pull request by apmasell**

### CODE REVIEW

**Comment by sklam** [comment]
need adding #8386, #8407, #8377, #8374

**Comment by sklam** [comment]
and need a changelog PR

**Comment by esc** [comment]
Probably also: https://github.com/numba/numba/pull/8392 needs a cherry-pick

**Comment by sklam** [comment]
Change set looks good. just pending CI

**Review by sklam — APPROVED** [review]

**Comment by esc** [comment]
We misssed https://github.com/numba/numba/pull/8411

**Comment by esc** [comment]
Also, this conflict resolution appears incorrect: https://github.com/numba/numba/pull/8392/files#diff-349d6f06fe6bf1cf27025463145a8f45c5d3a23847bf1ab146f11954eec86105R48

**Comment by esc** [comment]
a hotfix is here: https://github.com/numba/numba/pull/8414/files

**Pull request merged**
