### PR TITLE
Declare minimum sphinx version required for docs as 4.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. Patches up the build scripts to enforce and docs to note
this.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/pull/7122#issuecomment-863380498 confirming the minimum version.

**Comment by esc** [comment]
It looks like there are some issues building the documentation on Azure Pipelines with this PR. This is strange b/c #7122 was seemingly fine when building on RTD.

**Comment by esc** [comment]
Possibly this: https://stackoverflow.com/questions/63080103/how-to-reference-built-in-c-types-with-rst

**Comment by stuartarchibald** [comment]
> It looks like there are some issues building the documentation on Azure Pipelines with this PR. This is strange b/c #7122 was seemingly fine when building on RTD.

I think it's because of this: https://github.com/numba/numba/pull/7125/files#diff-319afae18279ecbf9d01cb17a6091e1103ddccadda228ace0a011a5590aa3667L88

**Comment by esc** [comment]
I tried the following patch:

```
 💣 zsh» gin stash show -p
diff --git a/docs/source/reference/pysupported.rst b/docs/source/reference/pysupported.rst
index d55c44c968..a50f285393 100644
--- a/docs/source/reference/pysupported.rst
+++ b/docs/source/reference/pysupported.rst
@@ -1229,29 +1229,29 @@ Third-party modules
 Similarly to ctypes, Numba is able to call into `cffi`_-declared external
 functions, using the following C types and any derived pointer types:

-* :c:type:`char`
-* :c:type:`short`
-* :c:type:`int`
-* :c:type:`long`
-* :c:type:`long long`
-* :c:type:`unsigned char`
-* :c:type:`unsigned short`
-* :c:type:`unsigned int`
-* :c:type:`unsigned long`
-* :c:type:`unsigned long long`
-* :c:type:`int8_t`
-* :c:type:`uint8_t`
-* :c:type:`int16_t`
-* :c:type:`uint16_t`
-* :c:type:`int32_t`
-* :c:type:`uint32_t`
-* :c:type:`int64_t`
-* :c:type:`uint64_t`
-* :c:type:`float`
-* :c:type:`double`
-* :c:type:`ssize_t`
-* :c:type:`size_t`
-* :c:type:`void`
+* :c:expr:`char`
+* :c:expr:`short`
+* :c:expr:`int`
+* :c:expr:`long`
+* :c:expr:`long long`
+* :c:expr:`unsigned char`
+* :c:expr:`unsigned short`
+* :c:expr:`unsigned int`
+* :c:expr:`unsigned long`
+* :c:expr:`unsigned long long`
+* :c:expr:`int8_t`
+* :c:expr:`uint8_t`
+* :c:expr:`int16_t`
+* :c:expr:`uint16_t`
+* :c:expr:`int32_t`
+* :c:expr:`uint32_t`
+* :c:expr:`int64_t`
+* :c:expr:`uint64_t`
+* :c:expr:`float`
+* :c:expr:`double`
+* :c:expr:`ssize_t`
+* :c:expr:`size_t`
+* :c:expr:`void`

 The ``from_buffer()`` method of ``cffi.FFI`` and ``CompiledFFI`` objects is
 supported for passing Numpy arrays and other buffer-like objects.  Only
```

But the resulting formatting isn't what we want:

Before

Screen Shot 2021-06-22 at 16 59 25

After

Screen Shot 2021-06-22 at 16 59 17

**Pull request closed without merging**
