### PR TITLE
Add ascontiguousarray

### PR DESCRIPTION
**Pull request by sklam**
Add support for single arg form of `ascontiguousarray()`.  This is to support situations like in gufunc that an array argument can only be in "Any" layout due to limitation of the numpy gufunc machinery even though the strides are representing a C-contig array.  Such situations will not benefit from many optimizations (e.g. loop vectorization) because the array is assume to be non-contiguous at compile time.  With `ascontiguousarray()` or `asfortranarray()`.  Users can convert the array into contiguous form at runtime; thus, allowing the aggressive optimizations and potential speedup.

Previously only the `asfortranarray()` is available and it is always copying the array into a new contiguous region if the array is of "Any" layout at compile time.  This patch also enhances the conversion logic in `asfortranarray()` an `ascontiguousarray()` such that an array of "Any" layout will be checked at runtime to bypass the copying.

Remaining tasks:

- [x] the new is_contiguous and is_fortran needs to be fixed for cases where the leading shapes are all 1s but the strides are non-contig.  In such case, the array is still contiguous.
- [x] the flags attributes needs to be updated to also check the runtime stride values.

### CODE REVIEW

**Comment by DrTodd13** [comment]
Can we get a usage example here?  For parfors, is it sufficient to call ascontiguousarray at the beginning of the gufunc for the parfor for each of the array arguments? @sklam

**Comment by sklam** [comment]
@DrTodd13 , `ascontiguousarray` will only work for the input arguments.  This patch implemented the single argument form of [numpy.ascontiguousarray(arr, dtype=None)](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ascontiguousarray.html).  

I have tried it on gufuncs like below:

```python
@guvectorize(...)
def foo(arr):
    arr = np.ascontiguousarray(arr)  
    <rest of the gufunc>
```

**Comment by DrTodd13** [comment]
@sklam So, if you do:
    b = arr * 2
b will still be seen as potentially non-contiguous?

**Comment by sklam** [comment]
@DrTodd13 , at the type level, `arr = np.ascontiguousarray(arr)` makes `arr` a C contiguous array.  Any operation that preserves the layout will continue to make C arrays.

So, `b = arr * 2` should makes `b` a contiguous array.

**Comment by sklam** [comment]
@DrTodd13, I think you may have accidentally merge your fork's master into this PR.  I have `git reset` the PR branch and forced push to unmerge.

**Comment by DrTodd13** [comment]
I was trying to do the opposite!

**Comment by sklam** [comment]
The patch is ready but there are still pending issues that can affect the auto-vectorization on gufunc.  

1. Can't ensure output to be contiguous without multiple code path.

We can't simply use the `ascontiguousarray` on the output arrays because it may make copies.  The safe way is to ensure that no copies are made by doing:
```python
    if out.flags.c_contiguous:
        out = np.ascontiguousarray(out)    # out is known to be contig but we still need to hint
```

However this needs to the second issue.

2. Variable defined in branches are forced to have the same type as the dominator and post-dominator.

So in the following case

```python
@guvectorize(["(f8[:], f8[:], f8[:])"], "(x),(x)->(x)", nopython=True)
def foo(x, y, out):
    x = np.ascontiguousarray(x)
    y = np.ascontiguousarray(y)
    if out.flags.c_contiguous:
        out = np.ascontiguousarray(out)  # <--- problem
        for i in range(out.size):
            out[i] = x[i] + y[i]
```

The problem is that `out = np.ascontiguousarray(out)` does not change the type of `out`.  Because,
currently numba treat assignment to existing variable in branches to be storing to the same variable as before.  So the hinting actually failed.  The compute loop will still think that `out` is of any layout.

This problem can be workaround by giving new names to the "hinted" variables.  So do:

```python

@guvectorize(["(f8[:], f8[:], f8[:])"], "(x),(x)->(x)", nopython=True)
def foo(x, y, out):
    xc = np.ascontiguousarray(x)
    yc = np.ascontiguousarray(y)
    if out.flags.c_contiguous:
        outc = np.ascontiguousarray(out)
        for i in range(out.size):
            outc[i] = xc[i] + yc[i]
```

**Comment by DrTodd13** [comment]
If you are just targeting manually written gufuncs then you can progress with this PR independently.  However, in the docs at least we may also want to mention an issue I found related to parfors turned into gufuncs.  We almost exclusively were using intp in ParallelAccelerator for indices and this signed value causes Numba to insert code to add the length of the array to the index if the index is negative.  These code paths will prevent the vectorizer from recognizing the array as being accessed as unit stride and therefore prevent vectorization.  I'm experimenting with changing most of those intp to uintp and all the parfor tests except for 2 work.  There's a test with "for i in prange(-(len(X)):".   I'm not sure what this is meant to test but it fails.  Also, test_parfor_options is failing with the actual and desired far off.

By the way, for parfors, if I'm going to call ascontiguousarray on an array then I rename the incoming parameter so that I can have a new variable on the left-hand side of the ascontiguousarray and so I don't run into this problem you mention.

**Comment by seibert** [comment]
Yeah, I think we'll merge this PR as-is, and working on removing other autovectorization barriers in future PRs.

The test you mention seems like it can't do anything, since `range()` of a negative integer is an empty list, so I would assume `prange()` in that case would similarly skip the entire loop.

**Pull request merged**
