### PR TITLE
Cherry picks 0.56.4

### PR DESCRIPTION
**Pull request by esc**
As Title

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. I replayed the merges from #8537, #8552 and #8553 manually onto a local copy of the `release0.56` branch and the `git diff` against this PR is empty, which suggests it is correct. Manually inspecting the changes, they look as expected. The RTD build looks ok on manual inspection too.

**Comment by stuartarchibald** [comment]
NOTE: The build failure on the `Linux py39_np120_doc` build is due to #8548 which is fixed on branch `main` by #8549 but not on target branch for this PR (branch `release0.56`). The issue is `rstcheck` related which only occurs on Azure CI, hence RTD and the buildfarm should be ok.

**Comment by esc** [comment]
@stuartarchibald thank you for the review!

**Comment by gmarkall** [comment]
gpuci run tests

**Pull request merged**
