### PR TITLE
Fix ``np.MachAr`` warning matching in test.

### PR DESCRIPTION
**Pull request by sklam**
Somehow #9347 changed the behavior of the filter.
The invisible characters from termcolor highlight now matters. But comparing the warning message before and after that PR does not reveal any visible difference.

Also added a `simplefilter("ignore")` to suppress any warning config from `PYTHONWARNINGS` in the python process.

### CODE REVIEW

**Comment by sklam** [comment]
To test this, make sure the environment has `colorama` and  `NUMBA_DISABLE_ERROR_MESSAGE_HIGHLIGHTING` is cleared.

Run: `NUMBA_DISABLE_ERROR_MESSAGE_HIGHLIGHTING= SUBPROC_TEST=1 python  runtests.py -k test_np_MachAr_deprecation_np122 -v`

**Comment by sklam** [comment]
BFID: `numba_yaml_423`

**Comment by stuartarchibald** [comment]
Thanks for fixing this @sklam. I debugged this a bit, AFAICT the actual strings in the message are the same, what I think is changing is what happens internally as part of the matching process, now the Numba warnings inherit from the standard library warnings the way the message strings are normalized internally is different:
https://github.com/python/cpython/blob/e0c6995b4fa9803a886fe1d88d6a9aec166a99e8/Python/_warnings.c#L657-L674

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch. I tested `main` manually against the reproducer in https://github.com/numba/numba/pull/9362#issuecomment-1855085927 and the test fails, application of this patch then makes it pass. The changes also make sense with respect to some debugging I did https://github.com/numba/numba/pull/9362#issuecomment-1855628388.

**Comment by sklam** [comment]
CI passed and enough buildfarm config has passed (e.g just windows ones are taking a long time and we don't want to wait for it)

**Pull request merged**
