### PR TITLE
WIP: fix-3456 support of numpy tile

### PR DESCRIPTION
**Pull request by lalitparate**

### CODE REVIEW

**Comment by lalitparate** [comment]
> @lalitparate thanks for the work so far on this, please do let us know when you'd like some feedback on it. Thanks again!

@stuartarchibald :-  I haven't handled all the cases till now. Sorry for delay. I am planning to complete it  to some extent by this weekend. 
By end of weekend i will be able to send it for review.

**Comment by stuartarchibald** [comment]
Just checking in on the state of this PR. @lalitparate was wondering if you have time to continue with this, if not, don't worry, one of the core developers can take over to do the fixes. Thanks.

**Comment by lalitparate** [comment]
> Just checking in on the state of this PR. @lalitparate was wondering if you have time to continue with this, if not, don't worry, one of the core developers can take over to do the fixes. Thanks.

Sorry didnt get time to work on this. I would appreciate if someone else work on it.

**Comment by stuartarchibald** [comment]
@lalitparate, no problem, thanks for letting us know.

**Pull request closed without merging**
