### PR TITLE
Issue #704: allow casting to numpy types

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by seibert** [comment]
This looks very useful.  Do we also want `np.intc` and `np.intp`?  (I'm never entirely sure how useful those types are in practice.)

**Comment by pitrou** [comment]
It seems those are aliases. But I could add tests, yes.

**Comment by seibert** [comment]
Now that we have merged the newdocs branch, can you add documentation for this?

**Comment by pitrou** [comment]
I added a small mention in the docs. I'm not sure if that needs to be spelled out more in detail.

**Comment by seibert** [comment]
That seems reasonable.

**Pull request merged**
