### PR TITLE
Make type.Optional str more representative

### LINKED ISSUE #4025: Make type.Optional string representation more friendly
## Feature request

For e.g.  `types.Optional(types.float64)` the current `str()` is `?float64` which is fine, but it may be more helpful for users to produce something like:
 `OptionalType(float64) i.e. type 'float64 or None'`
such that an error message might read e.g.:
```
Dict.value_type cannot be of type OptionalType(float64) i.e. type 'float64 or None'
```
instead of:
```
Dict.value_type cannot be of type ?float64
```

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Fixes #4025. Replace '?' with a 'or None' message on optional types.

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Just resolved the conflict and the PR is ready for review.

**Comment by esc** [comment]
It looks good to me, @stuartarchibald ?

**Comment by stuartarchibald** [comment]
Thanks for the PR. I think that the message presented needs further clarity. For example, the patch would make:
```
"Dict.value_type cannot be of type ?float64"
```
read as:
```
"Dict.key_type cannot be of type float64 or None"
```
but the I think this may be misleading as it seems like it's not permitted for `Dict.key_type` to be `'float64'` or `'None'` when the actual problem is the union type `Optional` i.e. `float OR None` is present. This is in part why I suggested:
```
Dict.value_type cannot be of type OptionalType(float64) i.e. type 'float64 or None'
```
so as to really spell out the problem. I'm wondering if `OptionalType` warrants an entry in the glossary too? Thoughts?

**Comment by esc** [comment]
@stuartarchibald yes, you are correct, I think being explicit about the `OptionalType` is probably to be preferred! I also think that adding `OptionalType` to the Glossary is probably a good idea.

**Comment by guilhermeleobas** [comment]
That makes sense. I've updated the code to reflect the changes.

**Comment by stuartarchibald** [comment]
Thanks for the update. I'm still unsure that this makes it any clearer to the user what the problem is as `OptionalType` is not spelled out and there's no definition elsewhere to reference?

**Comment by stuartarchibald** [comment]
@guilhermeleobas thanks for your work on this, with view of getting this merged for the 0.44 release candidate I've pushed a small code update and a glossary entry in a patch onto your branch. Hope this is ok?

@esc please could you re-review. Thanks.

Also, reminder to close  https://github.com/numba/numba/issues/4025 on merge.

**Comment by seibert** [comment]
This looks fine.  Ready to merge.

**Pull request merged**
