### PR TITLE
Exp/3.10+new with+np121

### PR DESCRIPTION
**Pull request by esc**
Experimental branch working towards #7381 

Currently (08 Nov 2021)  this branch compiles on OSX with Python 3.10 via anaconda and Numpy 1.21 via conda-forge. When running the test suite, we get:

```
Ran 9670 tests in 2401.378s

FAILED (failures=14, errors=6, skipped=742, expected failures=13)
python -m numba.runtests -m 12 numba.tests  12711.10s user 883.20s system 564% cpu 40:10.10 total
```

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Failing hashing tests are due to https://github.com/python/cpython/pull/25493. Looks like float hash of `nan` is now hash of the float object address.

**Comment by stuartarchibald** [comment]
@esc https://github.com/stuartarchibald/numba/commit/f6b405936226af44b0eddcfae155155b97d82933 should fix the hash problem.

**Comment by stuartarchibald** [comment]
@esc https://github.com/stuartarchibald/numba/commit/0881068405737df63e9af6bd84d9afa61ec01ec1 should fix the issue with the CFG comparison tests.

**Comment by stuartarchibald** [comment]
@esc `numba.tests.test_lists.TestLiteralLists.test_not_unify` is fixed by https://github.com/stuartarchibald/numba/commit/52c7b5802bb441d2737d401195e7358f4e2943e2

**Comment by esc** [comment]
@stuartarchibald thank you, I have implemented inlined-return-rewrite and cherry picked all your patches.

**Comment by stuartarchibald** [comment]
@esc tracing is potentially fixed by https://github.com/stuartarchibald/numba/commit/5b17d7767d415d47168ad4f8c9414d731656d2b4

**Comment by sklam** [comment]
@esc, https://github.com/numba/numba/pull/7554/commits/b631eae76c6ac6d5fbefff45b0be66884dfb5db7 is a single commit patch for test_flow_control and looplift

**Comment by stuartarchibald** [comment]
@esc https://github.com/stuartarchibald/numba/commit/af089f93c1756936f2ba05ee184af5e485929810 fixes the issue with `numba.tests.test_dicts.TestCompiledDict.test_dict_use_with_optional_value`.

**Comment by stuartarchibald** [comment]
@esc https://github.com/numba/numba/pull/7546 is needed for `numba.tests.test_dictobject.TestLiteralStrKeyDict.test_dict_not_unify`, the Python 3.10 return inlining triggered a bug. Once that's merged into this branch, there's more issues on the same test, am just taking a look.

**Comment by stuartarchibald** [comment]
RE: https://github.com/numba/numba/pull/7544#issuecomment-967049024 this fixes it: https://github.com/stuartarchibald/numba/commit/e1013e200c8d3067265cb27442d4974ce708a87b

**Comment by esc** [comment]
closing now

**Pull request closed without merging**
