### PR TITLE
Add max_registers Option to cuda.jit

### PR DESCRIPTION
**Pull request by njwhite**
Limiting registers is useful for improving occupancy, at the expense of spilling to local memory. Use the `CU_JIT_MAX_REGISTERS` argument when linking!

### CODE REVIEW

**Comment by njwhite** [comment]
“CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://repo.anaconda.com/pkgs/free/linux-64/repodata.json.bz2>”? Not a real Travis failure!

**Comment by stuartarchibald** [comment]
This PR failing testing on all platforms/CUDAs etc. The test:
```
numba.cuda.tests.cudapy.test_serialize.TestPickle
```
fails with
```
"<path>/numba/cuda/compiler.py", line 423, in _rebuild
    return cls(entry_name, ptx, linking)
TypeError: __init__() missing 1 required positional argument: 'max_registers'
```

**Comment by njwhite** [comment]
@stuartarchibald oops, pushed a fix.

**Comment by stuartarchibald** [comment]
Thanks for the fix up, it's running through the build farm now.

**Comment by stuartarchibald** [comment]
Combination `windows64+py37+np111` did not run CUDA tests because of unrelated CPU testing problems, however a `windows64+py37+np114` combination did run and pass (and all the other runs were ok) so I am marking this as ok.

**Comment by seibert** [comment]
Thanks for the contribution, @njwhite!

**Pull request merged**
