### PR TITLE
Add support for casting from int enums

### LINKED ISSUE #7573: numba 0.54.1 casting IntEnum regression
numba 0.54.1
python 3.7.3
windows 10

This was first reported in [discourse](https://numba.discourse.group/t/casting-intenum-to-numba-int16/1005)

This code works in plain python and numba 0.53.1 but fails with numba 0.54.1

```python
from enum import IntEnum
import numba

class PmtType(IntEnum):
    LEVELA = 1
    LEVELB = 2

@numba.njit
def tester():
    return numba.int16(PmtType.LEVELA)

print(tester())
```
Error is

> File “int_enum.py”, line 16, in
> print(tester())
> File “C:\work\git\mims\venv\lib\site-packages\numba\core\dispatcher.py”, line 482, in _compile_for_args
> error_rewrite(e, ‘typing’)
> File “C:\work\git\mims\venv\lib\site-packages\numba\core\dispatcher.py”, line 423, in error_rewrite
> raise e.with_traceback(None)
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No implementation of function Function(int16) found for signature:
> 
> (IntEnum(PmtType))
> 
> There are 2 candidate implementations:
> 
> Of which 2 did not match due to:
> Overload in function ‘make_callable_template..generic’: File: numba\core\typing\templates.py: Line 174.
> With argument(s): ‘(IntEnum(PmtType))’:
> Rejected as the implementation raised a specific error:
> TypingError: Casting IntEnum(PmtType) to int16 directly is unsupported.
> raised from C:\work\git\mims\venv\lib\site-packages\numba\core\typing\builtins.py:818
> During: resolving callee type: class(int16)
> During: typing of call at C:/work/git/ims_core/playground/erik/discourse/int_enum.py (14)
> 
> File “int_enum.py”, line 14:
> def tester():
> return numba.int16(PmtType.LEVELA)
> ^
> Process finished with exit code 1
>

### PR DESCRIPTION
**Pull request by testhound**
This PR fixes a enum to int cast problem documented in this issue: https://github.com/numba/numba/issues/7573 and introduced here: https://github.com/numba/numba/commit/f2311d20934a883dde3a2050ff947ff0f5d07977.

Fixes #7573

### CODE REVIEW

**Comment by testhound** [comment]
gpuci run tests

**Comment by gmarkall** [comment]
Can you add a test for the failing case please?

**Comment by gmarkall** [comment]
For the location of the test, it could go in `numba/tests/test_enums` in the `TestIntEnum` class.

**Review by gmarkall — CHANGES_REQUESTED** [review]
Thanks for adding the tests. I suggested some changes because there's already a test testing implicit coercion, so the uses of the `IntEnum` in this new case might as well all be casts - I suggested adding different types to cast to as well to ensure that casting to different widths also works.

**Comment by testhound** [comment]
gpuci run tests

**Review by gmarkall — APPROVED** [review]
Thanks for the update - looks good to me!

**Pull request merged**
