### PR TITLE
Upgrade to ubuntu-20.04 for azure pipeline CI

### PR DESCRIPTION
**Pull request by jamesobutler**
ubuntu-18.04 is deprecated and will have scheduled brownouts until fully unsupported on 2022-12-01. See for more details https://github.com/actions/runner-images/issues/6002

Microsoft-hosted pipelines supports the 2 latest versions of macOS, Windows and Ubuntu. Now that ubuntu-22.04 is available, ubuntu-20.04 will become the oldest supported version as ubuntu-18.04 is being deprecated.

### CODE REVIEW

**Comment by esc** [comment]
@jamesobutler thank you for submitting this. I have added it to my queue for review.

**Comment by esc** [comment]
@jamesobutler thank you for submitting this. The same comment as for #8319 applies to this PR too:

https://github.com/numba/numba/pull/8319#issuecomment-1214840973

**Comment by jamesobutler** [comment]
@esc Ok here is the upcoming brownouts where the CI won’t be working for Ubuntu.

> August 22, 12:00 UTC - August 22, 16:00 UTC
> August 30, 12:00 UTC - August 30, 18:00 UTC

**Comment by esc** [comment]
> @esc Ok here is the upcoming brownouts where the CI won’t be working for Ubuntu.
> 
> > August 22, 12:00 UTC - August 22, 16:00 UTC
> > August 30, 12:00 UTC - August 30, 18:00 UTC
> 
> you may want to consider this for the 0.56.x line because Ubuntu 18.04 will be completely unsupported before 0.57.0 is released.

OK; that is very good to know!!

**Comment by jamesobutler** [comment]
For same reason including https://github.com/numba/numba/commit/81702eb8967327677ce060dac045430da2bc1a97 for the 0.56.x line would be another good idea as macOS-10.15 image is fully unsupported on Azure DevOps by September 30th.

**Comment by esc** [comment]
> For same reason including [81702eb](https://github.com/numba/numba/commit/81702eb8967327677ce060dac045430da2bc1a97) for the 0.56.x line would be another good idea as macOS-10.15 image is fully unsupported on Azure DevOps by September 30th.

@jamesobutler is that commit on a PR somewhere?

**Comment by jamesobutler** [comment]
https://github.com/numba/numba/commit/81702eb8967327677ce060dac045430da2bc1a97 was merged into `main` by way of #8276. That commit has not made it to https://github.com/numba/numba/tree/release0.56 by direct commit or PR.

**Comment by esc** [comment]
> [81702eb](https://github.com/numba/numba/commit/81702eb8967327677ce060dac045430da2bc1a97) was merged into `main` by way of #8276. That commit has not made it to https://github.com/numba/numba/tree/release0.56 by direct commit or PR.

Thank you!! I've added a comment on #8276 -- we will cherry-pick this onto the `release0.56` branch prior to the release.

**Review by esc — APPROVED** [review]

**Comment by esc** [comment]
@jamesobutler thank you again for submitting this! I have reviewed it and it will be merged into `main` and cherry-picked for 0.56.1.

**Pull request merged**
