### PR TITLE
[ci_test] Temp/pr/5294 2

### PR DESCRIPTION
**Pull request by sklam**

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@sklam can this be closed?

**Comment by esc** [comment]
I have grabbed all the required patches made by @sklam and pushed them to #5294

**Comment by stuartarchibald** [comment]
ok, thanks @esc, closing assuming purpose is served.

**Comment by esc** [comment]
@stuartarchibald mostly, yes, there are still bugs in the branch but @sklam can re-open this if need be.

**Pull request closed without merging**
