### PR TITLE
Add support for numpy.isin

### LINKED ISSUE #3971: numpy isin
Hello here im using numba for my own lib for speedup data preprocessing and would love to see isin as numpy supported function :)
(I see in1d topic but following numpy docs -> We recommend using isin instead of in1d for new code)

### PR DESCRIPTION
**Pull request by andreapiso**
Closes #3971. 

Adds `numpy.isin` with support for `assume_unique` and `invert`. 

Most of the functionality is there, tagged this as WIP as docs and test are still missing. If possible, I'd like to know if the approach for this is acceptable:

In order to support `assume_unique` on `isin`, it is necessary to have `np.unique` supporting `return_inverse`. However, this is not possible right now due to #2949. So, I wrote an internal `_np_unique` function as a `@register_jitable` which supports the three optional returns for `np.unique` `return_index`, `return_inverse` and `return_count` while being statically typed i.e. the function always returns a tuple containing 4 numpy array `(uniques, index, inverse, counts)` where if the corresponding keyword is `False`, the array is empty. 

Clearly this is not compliant with the numpy API so I am not proposing it as an overload, on the other hand it allows other internal function to support extra keywords and functionalities that would otherwise not be possible at this stage. 

Once #2949 is here, it would be easy to extend the overload of `np.unique` simply by extracting the corresponding values from the tuple and returning a type compliant with the numpy api while maintaining a single implementation as close as possible to the original numpy in the `register_jitable` function. 

Looking forward to hearing your feedback on whether the approach is acceptable.  

**Todo:** 

- [x] Return scalar output for scalar input, instead of array. 
- [x] _np_unique right now sorts the input array in place while it should not. 
- [x] Documentation.
- [x] Tests.

### CODE REVIEW

**Comment by esc** [comment]
@andreapiso thanks for submitting this to the Numba issue tracker. Your effort in helping to improve Numba is appreciated. I have queued this PR for an initial review.

**Comment by stuartarchibald** [comment]
Thanks for the PR. The policy in Numba is "JIT transparency" which means the same code has to work the same way with/without the JIT decorators. Unless I have misunderstood it seems what you propose is compatible with this? The public API matches NumPy but there's some internal implementation detail around a `np.unique` variant that has specialisations applied for use within `np.isin` ?

**Comment by andreapiso** [comment]
Yes, that's correct. Since we can output only one type given an input type, the overloaded method returns an array for `np.unique`. However, `np.isin` needs `np.unique` to return a tuple instead, so I made that an internal non-overloading specialization.

**Comment by andreapiso** [comment]
Seems my tests fail on calling `np.unique` on the Linux py27_np111_32bit configuration. It's strange as the test was passing earlier and I did not make changes to `np.unique` since then. Also it does pass on the other 32bit configs. 

I'll look into this. In the meanwhile could I get a review for this PR if anyone has the time. I think it's at a decent stage.

**Comment by stuartarchibald** [comment]
I'm wondering if it's a knock-on effect of this https://github.com/numba/numba/pull/4770, this https://github.com/numba/numba/pull/4882, and some weirdness in the `np.long` dtype on 32 bit linux?

**Comment by andreapiso** [comment]
Will check this again soon once #4896 is merged.

**Comment by andreapiso** [comment]
Tests are finally passing after merging #4896. I think the PR is ready to be reviewed if anyone has the time.

**Comment by esc** [comment]
@andreapiso thanks, I have updated the label accordingly.

**Comment by stuartarchibald** [comment]
Just checking in on the state of this PR. @andreapiso any chance you could please resolve the merge conflicts, someone can then review it. Many thanks!

**Comment by andreapiso** [comment]
Awesome! I'll get to it.

**Comment by stuartarchibald** [comment]
@andreapiso great, thanks. There's been a lot of refactoring of the code base in Q1 2020, if the merge goes badly feel free to ping here for assistance.

**Comment by andreapiso** [comment]
I think the merge is OK now, if someone has time to take a look. that would be great!!

**Comment by jaistech-sp** [comment]
Hi there,
I am using numba 0.50.1 but np.isin is not already implemented. Is there any update on that point?
Best!

**Comment by gao462** [comment]
Is seems that `numpy.unique(*, return_inverse=True, return_counts=True)` is still not supported in 0.55.1.
Is there any update?

**Comment by claudio525** [comment]
I would be interested in picking this up. Based on the review comments above it looked like this PR was in reasonable good state, but given that that was in 2020, I'm not sure if thats still the case or if major changes would now be needed to implement this? @stuartarchibald? 
Also not sure if this would be suitable for a first issue.

**Comment by jaredjeya** [comment]
@claudio525 I have a PR #9338 going for this. Possibly some of the code here could be ported across.

**Pull request closed without merging**
