### PR TITLE
remove `mk_unique_var` from `parfor_lowering_utils.py`

### PR DESCRIPTION
**Pull request by guilhermeleobas**
xref: https://github.com/numba/numba/issues/8230

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
CI failure is not related to this PR.

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
@guilhermeleobas please could you merge `main` to get a doc build. Many thanks!

**Review by stuartarchibald — APPROVED** [review]

**Comment by stuartarchibald** [comment]
Thanks for resolving the conflicts @guilhermeleobas.

**Pull request merged**
