### PR TITLE
PR #5892 continued

### PR DESCRIPTION
**Pull request by stuartarchibald**
Continues #5892 

CC @DrTodd13 please could you check that the patch is as intended? Many thanks.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
CI is failing. Fails look legitimate: https://dev.azure.com/numba/numba/_build/results?buildId=6838&view=logs&j=918fcee1-4eae-552e-9a24-a8b2dfd583fd&t=d98730fe-8d16-587e-c0ef-eb51bb07d18a&l=517 IIRC this is where the original PR got to.

**Comment by DrTodd13** [comment]
> CI is failing. Fails look legitimate: https://dev.azure.com/numba/numba/_build/results?buildId=6838&view=logs&j=918fcee1-4eae-552e-9a24-a8b2dfd583fd&t=d98730fe-8d16-587e-c0ef-eb51bb07d18a&l=517 IIRC this is where the original PR got to.

@stuartarchibald Fix checked in.

**Comment by sklam** [comment]
The changes looks good to me. 
@stuartarchibald, do you think this need a buildfarm run?

**Comment by stuartarchibald** [comment]
> The changes looks good to me.

Me too, 

> @stuartarchibald, do you think this need a buildfarm run?

I think it's ok without, public CI is pretty good testing direct parfors logic changes.

**Comment by stuartarchibald** [comment]
> > CI is failing. Fails look legitimate: https://dev.azure.com/numba/numba/_build/results?buildId=6838&view=logs&j=918fcee1-4eae-552e-9a24-a8b2dfd583fd&t=d98730fe-8d16-587e-c0ef-eb51bb07d18a&l=517 IIRC this is where the original PR got to.
> 
> @stuartarchibald Fix checked in.

Thanks @DrTodd13

**Pull request merged**
