### PR TITLE
Add __name__ support for GUFuncs

### PR DESCRIPTION
**Pull request by testhound**
This pull request addresses issue 8272: https://github.com/numba/numba/issues/8272 for GUFuncs

### CODE REVIEW

**Comment by testhound** [comment]
gpuci run tests

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_yaml_146`.

**Comment by stuartarchibald** [comment]
> Buildfarm ID: `numba_smoketest_cuda_yaml_146`.

Passed.

**Pull request merged**
