### PR TITLE
NBEP: extension points

### PR DESCRIPTION
**Pull request by pitrou**
This is an enumeration of the current hooks for extending Numba with new types and operations, and a couple proposals to improve them.

I think the PEP is ready for committing in the repo, to allow for easier reading online.

### CODE REVIEW

**Comment by datnamer** [comment]
+1. Looking forward to this. Would it be possible to do this in pure python syntax or would it require dropping down into C?

**Comment by izaid** [comment]
@datnamer The question of Numba / DyND / Datashape interoperability is being actively thought about and discussed. For the moment, there's not much for me to weigh in on here.

**Comment by datnamer** [comment]
Ok great. Also wanted to throw out here non-array scientific use cases involving defining fast classes  (like agents in agent based models) and interoperability with existing libraries like networkx and scipy stats. Not sure if technically feasible, but I just wanted to put my vote in for anything that might enable simulations like these with numba.

**Comment by gdementen** [comment]
I have my own ndarray-like objects with labels (http://github.com/liam2/larray FWIW), that is very similar to xray (and a bit like Pandas too). Basically they are classes with a .data field which is an ndarray (in the simple case) and then some metadata in other fields. I would like functions using my objects to be njit'able. Is this kind of use case covered by these extension points? If it is, it would help if there was some kind of tutorial on "How to make my own classes jitable".

**Comment by seibert** [comment]
This is exactly the use case we want to support when this task is finished!

**Comment by datnamer** [comment]
@seibert , how about adding JIT interoperable scikit learn models? I want to create JIT classes that can have scikitlearn  objects/functions in their fields or methods. Any way that this would be able to make that work?

**Comment by datnamer** [comment]
I assume this would only work for python object that have concretely typed data structures or native code? 

Wouldn't work for regular python class with all its dynamic nature and indirection?

**Comment by seibert** [comment]
OK, going to merge this as a draft (so we can read it properly formatted by Sphinx) and we can discuss changes in a followup PR.

**Pull request merged**
