### PR TITLE
Fix #7713: Ensure _prng_random_hash return has correct bitwidth

### LINKED ISSUE #7713: Tests using float hashing fail on win32+Py3.10 for 0.55rc1
Details are sparse at present but essentially the hashing algs for floats were updated to deal with a change in `NaN` handling for Python 3.10. Tests that use this path on windows 32 are failing with a lowering error manifesting from `llvmlite`, message is `Type of #3 arg mismatch: i32 != i64` which usually indicates a `intp` (platform int size) related problem.

### PR DESCRIPTION
**Pull request by gmarkall**
When the hash width is 32 bits, `get_next_int32()` needs to be used because that returns a 32-bit integer, as opposed to `get_next_int()`, which returns a 64-bit integer regardless of the supplied bitwidth.

This commit also alters the signature of `_prng_random_hash()` to use `_Py_hash_t` as the return type - it will be equal to `types.intp`, but the intent should be clearer.

Tested so far on Python 3.10 on 32- and 64-bit Windows with:

```
python -m numba.runtests numba.tests.test_closure.TestObjmodeFallback.test_issue2955 numba.tests.test_dictobject.TestDictObject.test_issue6570_alignment_padding numba.tests.test_hashing.TestNumberHashing.test_complex numba.tests.test_hashing.TestNumberHashing.test_floats numba.tests.test_hashing.TestTupleHashing.test_heterogeneous_tuples numba.tests.test_hashing.TestNumberHashing.test_py310_nan_hash numba.tests.test_hashing.TestTupleHashing.test_homogeneous_tuples numba.tests.test_sets.TestFloatSets.test_constructor numba.tests.test_sets.TestFloatSets.test_iterator numba.tests.test_sets.TestUnboxing.test_numbers numba.tests.test_sets.TestSetReflection.test_reflect_clean numba.tests.test_sets.TestSetReflection.test_reflect_conditional numba.tests.test_sets.TestSetReflection.test_reflect_simple numba.tests.test_sets.TestExamples.test_type_coercion_from_update numba.tests.test_sets.TestUnboxing.test_tuples numba.tests.test_sets.TestFloatSets.test_update
```

This is the list of 16 failing tests reported in https://github.com/numba/numba/issues/7713#issuecomment-1009152734

Fixes #7713.

### CODE REVIEW

**Comment by esc** [comment]
Giving this a full build farm run over the weekend to see if it fixes #7713 on our CI too!

`Build numba_yaml_148 has started`

**Comment by esc** [comment]
Build farm green for win32 on e6df66d

**Comment by gmarkall** [comment]
@esc Thanks for the BF run - I've now marked this as ready for review (Iooks like I forgot to do that after the CI passed on Friday night).

**Review by esc — APPROVED** [review]
I checked for typos, read the description and ran this on the BF. It looks good. On the basis of what I have observed, I am marking this as ready to merge!

**Pull request merged**
