### PR TITLE
Allocate 1D iteration space one at a time for more even distribution.

### LINKED ISSUE #5778: prange reverts to serial when thread count doesn't divide iterations
## Bug report checklist

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

## Description

If the thread count doesn't divide the number of iterations in a Numba `prange` statement, the iterations that form the remainder are run in serial. If the thread and iteration count are similar, and/or individual iterations are expensive, this results in significant slowdown.

## Reproducer

```python
$cat numba_test.py
import numba as nb

@nb.jit(nopython=True, nogil=True, parallel=True)
def numba_func(num):
    for i in nb.prange(num):
        print("iteration", i)

if __name__ == '__main__':
    numba_func(20)

$NUMBA_NUM_THREADS=11 ./numba_test.py
iteration 0
iteration 1
iteration 6
iteration 4
iteration 10
iteration 2
iteration 9
iteration 5
iteration 11
iteration 7
iteration 3
iteration 8
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
```

### PR DESCRIPTION
**Pull request by DrTodd13**
Resolves #5778 

I don't think we need to add a test for this one.  I hand checked that the distribution is evenly spaced.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the patch. I think the proposed makes it so that the schedule is weighted more evenly, but the distribution over the schedule ends up with there being more work in the tail of the schedule array. Am wondering if this will have an adverse impact on e.g. TBB performance where working threads are more dynamic in that the less intensive bodies are will end up being run first this potentially leading to a less balanced load?

For example, #5778 reproducer looks like this with 12 chunks:
```
_lower_parfor_parallel done
loop range[0]: 0 20 (1)
do_scheduling_unsigned
num_dim = 1
ranges = ([0, 19], )
num_threads = 12
sched[0] = 0 0 
sched[1] = 1 1 
sched[2] = 2 2 
sched[3] = 3 3 
sched[4] = 4 5 
sched[5] = 6 7 
sched[6] = 8 9 
sched[7] = 10 11 
sched[8] = 12 13 
sched[9] = 14 15 
sched[10] = 16 17 
sched[11] = 18 19 
```

**Comment by DrTodd13** [comment]
@stuartarchibald Good suggestion.  I've front-loaded the larger iteration divisions.

**Comment by stuartarchibald** [comment]
Thanks @DrTodd13, with c9b0427 this appears:
```
loop range[0]: 0 20 (1)
do_scheduling_unsigned
num_dim = 1
ranges = ([0, 19], )
num_threads = 12
sched[0] = 0 1 
sched[1] = 2 3 
sched[2] = 4 5 
sched[3] = 6 7 
sched[4] = 8 9 
sched[5] = 10 11 
sched[6] = 12 13 
sched[7] = 14 15 
sched[8] = 16 16 
sched[9] = 17 17 
sched[10] = 18 18 
sched[11] = 19 19 
```
which looks front-loaded as discussed. It'd be nice one day to make the schedule accessible programmatically such that unit tests could assert properties, however, that's not for this PR. Thanks again for fixing, marking for merge.

**Comment by stuartarchibald** [comment]
Presume the force-push was an accident, rechecked the code, still fine to merge on c9b0427.

**Comment by DrTodd13** [comment]
> Presume the force-push was an accident, rechecked the code, still fine to merge on [c9b0427](https://github.com/numba/numba/commit/c9b042730b5d2053dd5da308dc5d039c26bae347).

I had accidentally pushed a change for one of my other PRs to this one.  Then I did a force-push to get rid of it.  It should be fine to merge.  Thanks!

**Pull request merged**
