### PR TITLE
[WIP] lowering of constant jitclass

### LINKED ISSUE #3781: Failure when trying to use a JitClass
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The following code produces an error message telling me to submit a bug report, so I am doing so.

I expected it to call `test.get_value()` and print the returned value of 1. If I remove the line `@nb.njit`, it does this.

```
import numba as nb

@nb.jitclass([])
class Test:
	def __init__(self):
		pass
	def get_value(self):
		return 1

test = Test()

@nb.njit
def use_test():
	return test.get_value()

print(use_test())
```

Here is the error message it gives:

```
Traceback (most recent call last):
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 499, in get_constant_generic
    impl = self._get_constants.find((ty,))
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 50, in find
    out = self._find(sig)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 59, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.targets.base.OverloadSelector object at 0x11c2e1a58>, (instance.jitclass.Test#7f9f394d82a8<>,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/errors.py", line 617, in new_error_context
    yield
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 308, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 449, in lower_assign
    value.value)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 502, in get_constant_generic
    raise NotImplementedError("Cannot lower constant of type '%s'" % (ty,))
NotImplementedError: Cannot lower constant of type 'instance.jitclass.Test#7f9f394d82a8<>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minrep3.py", line 16, in <module>
    print(use_test())
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 717, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 653, in backend_nopython_mode
    self.metadata)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 1048, in native_lowering_stage
    lower.lower()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 219, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/errors.py", line 625, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot lower constant of type 'instance.jitclass.Test#7f9f394d82a8<>'

File "minrep3.py", line 14:
def use_test():
	return test.get_value()
 ^

[1] During: lowering "$0.1 = global(test: <numba.jitclass.boxing.Test object at 0x11cd45f10>)" at minrep3.py (14)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

### PR DESCRIPTION
**Pull request by luk-f-a**
closes #3781

While working on numba-scipy, I wanted to test using jitclasses to implement statistical distributions. However, to achieve jit transparency, already instantiated scipy distributions must be available within jitted code (without being passed as arguments). This happens because Scipy.stats api is based not on classes that the user instantiates as needed, but but pre-instantiating an object (for each distribution!) and directing the user to call on the methods on that object.

I re-used the code from the constructor of the jitclass, but I don't know how to copy the attributes from `pyval` into the newly created structure. 

EDIT: This is early WIP in order to gather feedback. I am not even sure this is the right way to lower a constant jitclass. Once the main approach is solid, I'll create tests and fix the flake8 warnings.

### CODE REVIEW

**Comment by esc** [comment]
@luk-f-a thanks for submitting this, your efforts to improve Numba are appreciated as always. There are some remaining flake8 issues to be resolved:

```
numba/jitclass/base.py:19:1: F401 'llvmlite.ir' imported but unused
numba/jitclass/base.py:541:81: E501 line too long (100 > 80 characters)
numba/jitclass/base.py:542:9: E128 continuation line under-indented for visual indent
numba/jitclass/base.py:558:15: W292 no newline at end of file
##[error]Bash exited with code '1'.
Finishing: Flake8
```

FWIW: I have been able to largely eliminate such nuisances using the pre-commit hooks as described here: https://numba.pydata.org/numba-doc/dev/developer/contributing.html#coding-conventions -- maybe it could be helpful for you too?

**Comment by luk-f-a** [comment]
hi @esc , thanks! sorry, I should have said at the top that this is very early wip. I don't even know if this is the right way to lower a constant jitclass. It's also missing tests and flake8 polish.

**Comment by esc** [comment]
@luk-f-a no problem, I will label as 'in progress' for now. Please just ping us as usual if you get it into a reviewable state, thanks!

**Comment by asodeur** [comment]
Below is our attempt at lowering constant jitclasses. It is based on the unboxing code from `jitclass/boxing`. It comes with (at least) two wrinkles
1.  use of `add_dynamic_addr` breaks caching
2. the lowering code does not aquire a reference on `pyval`, only when the native result is assigned the `meminfo` gets `inref`ed (which will keep `pyval` alive for the lifetime of the `memnfo`). HOWEVER there is a  chance that `pyval` will get collected between leaving `_lower_constant_class_instance` and use of the native value

```python
from llvmlite import ir
from numba import cgutils, jit, jitclass, types
from numba.targets.imputils import lower_constant
from numba.jitclass import _box


@lower_constant(types.ClassInstanceType)
def _lower_constant_class_instance(context, builder, typ, pyval):
    def access_member(obj, member_offset):
        # Access member by byte offset
        offset = context.get_constant(types.uintp, member_offset)
        llvoidptr = ir.IntType(8).as_pointer()
        ptr = cgutils.pointer_add(builder, obj, offset)
        casted = builder.bitcast(ptr, llvoidptr.as_pointer())
        return builder.load(casted)

    struct_cls = cgutils.create_struct_proxy(typ)
    inst = struct_cls(context, builder)

    # get a pointer to pyval
    obj = context.add_dynamic_addr(builder, id(pyval), '')

    # load from Python object
    ptr_meminfo = access_member(obj, _box.box_meminfoptr_offset)
    ptr_dataptr = access_member(obj, _box.box_dataptr_offset)

    # store to native structure
    inst.meminfo = builder.bitcast(ptr_meminfo, inst.meminfo.type)
    inst.data = builder.bitcast(ptr_dataptr, inst.data.type)

    return inst._getvalue()


if __name__ == '__main__':
    spec = [
        ('value', types.float64)
    ]


    @jitclass(spec)
    class TestClass:
        def __init__(self, value):
            self.value = value


    const = TestClass(42.)

    @jit
    def get_const_jitclass():
        return const

    const2 = get_const_jitclass()

    assert const.value == const2.value

```

**Comment by nelson2005** [comment]
bump... I've run into this as well, more than a few times.  Any chance of this getting merged?

**Comment by esc** [comment]
@nelson2005 thank you for asking about this. I believe this PR or the suggested patch will need some more work (specifically: tests) before it can be scheduled for review.

**Comment by luk-f-a** [comment]
since structref is the future of jitclasses, I'm closing this PR. Anyone needing a work around for the current jitclass can use the one provided above.

**Comment by nelson2005** [comment]
> since structref is the future of jitclasses, I'm closing this PR. Anyone needing a work around for the current jitclass can use the one provided above.

What's the timeframe for for jitclasses meeting their structref incarnation?

**Pull request closed without merging**
