### PR TITLE
Fix np.allclose not handling default args

### PR DESCRIPTION
**Pull request by guilhermeleobas**
Fix issue #8860:
* Replace `TypeError` by `TypingError`
* Add a few tests to ensure exceptions are raised
* Add `float` class to `isinstance` comparison

Also, wondering if Numba should have the same checks on `np.isclose` implementation?

### CODE REVIEW

**Review by kc611 — APPROVED** [review]
LGTM!

**Comment by kc611** [comment]
> Also, wondering if Numba should have the same checks on np.isclose implementation?

Definitely would make sense to do so. `np.isclose` and `np.allclose` pretty much share a common input argument format so the error handling at type level can also be shared.

**Comment by gmarkall** [comment]
@kc611 if this looks good, is it ready to be RTM? Or does it need an additional look?

**Comment by kc611** [comment]
In it's current state it's RTM unless @guilhermeleobas wants to add the things he mentioned in the same PR (Although those ca be part of another PR as well.)

**Review by sklam — APPROVED** [review]

**Pull request merged**
