### PR TITLE
Add tolerance to network errors by permitting conda to retry

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Could probably do the same for windows scripts?

**Comment by seibert** [comment]
This looks good as a mitigation.  I have no idea how to do the equivalent in windows, so we can merge this as-is until a Windows failure reminds us to investigate that.

**Comment by mbargull** [comment]
`conda`'s network configuration parameters might be useful for you, too:
<details><summary><code>
conda config --describe
</code></summary>

```
...

# ######################################################                                                                                                                                                                                                                          
# ##              Network Configuration               ##                                                                                                                                                                                                                          
# ######################################################                                                                                                                                                                                                                          

...                                                                                                                                                                                                                                                                                  

# # local_repodata_ttl (bool, int)                                                                                                                                                                                                                                                
# #   For a value of False or 0, always fetch remote repodata (HTTP 304                                                                                                                                                                                                           
# #   responses respected). For a value of True or 1, respect the HTTP                                                                                                                                                                                                            
# #   Cache-Control max-age header. Any other positive integer values is the                                                                                                                                                                                                      
# #   number of seconds to locally cache repodata before checking the remote                                                                                                                                                                                                      
# #   server for an update.                                                                                                                                                                                                                                                       
# #                                                                                                                                                                                                                                                                               
# local_repodata_ttl: 1                                                                                                                                                                                                                                                           

...

# # remote_connect_timeout_secs (float)
# #   The number seconds conda will wait for your client to establish a
# #   connection to a remote url resource.
# #
# remote_connect_timeout_secs: 9.15

# # remote_max_retries (int)
# #   The maximum number of retries each HTTP connection should attempt.
# #
# remote_max_retries: 3

# # remote_read_timeout_secs (float)
# #   Once conda has connected to a remote resource and sent an HTTP
# #   request, the read timeout is the number of seconds conda will wait for
# #   the server to send a response.
# #
# remote_read_timeout_secs: 60.0

...
```
</details>

**Comment by esc** [comment]
@mbargull that is a good find. It seemingly has `remote_max_retries:` and `remote_connect_timeout_secs` and `remote_read_timeout_secs`.

**Comment by stuartarchibald** [comment]
Thanks @mbargull, this actually would work around a problem with the current script needing to defeat `set -e` (which it doesn't and hence doesn't work as intended) and also sort out windows.

**Comment by mbargull** [comment]
> defeat `set -e` (which it doesn't and hence doesn't work as intended)

For that you can simply replace
```bash
conda $cmd -q -y $*
if [ $? == 0 ]; then
        break;
else
```
by
```bash
local conda_failed=0
conda $cmd -q -y $* || conda_failed=1
if [ $conda_failed = 0 ]; then
        break;
else
```
or something equivalent.

Though, if some `conda config` customizations suffice to make `network_tolerant_conda` obsolete, that's surely preferable due to portability and less maintenance on Numba's end, yes :wink:.

**Comment by stuartarchibald** [comment]
@mbargull thanks, when I wrote this patch I just completely forgot there was a `set -e` so didn't do anything about it! I'm inclined to want to make `conda config` work as suggested as it's net less effort long term, #4030 tracks.

**Pull request merged**
