### PR TITLE
Fix SVML tests with LLVM 10 and AVX512

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
This PR makes the same job for SVML tests as #5757 made for ParallelAccelerator tests.

### CODE REVIEW

**Comment by sklam** [comment]
@esc, since you are looking at the llvm10 upgrade, this patch will be needed when testing numba

**Comment by esc** [comment]
As soon as we have an LLVM 10 compatible version, I'll test this patch.

**Comment by esc** [comment]
I cherry-picked 🍒 this to #5969 -- looks like this solves segfaults in the test-suite when running with SVML -- @PokhodenkoSA can you confirm?

**Comment by PokhodenkoSA** [comment]
I did not face segfaults but it does fix SVML tests with LLVM10. @esc, please, take it for the next release of Numba with LLVM 10.

**Comment by stuartarchibald** [comment]
If this "solves" the segfaults I wonder if that's actually just hiding a bug? This patch sets a preference for narrower instructions to be used, but it shouldn't be required?

**Comment by esc** [comment]
I just checked and this does not solve the segfault I am currently seeing on our internal build-farm.

**Comment by esc** [comment]
@PokhodenkoSA do you happen to have a log of the errors that this patch fixes? I am seeing some additional svml related failures on our farm --- even with the patch --- and trying to investigate.

**Comment by PokhodenkoSA** [comment]
@esc I am sorry for too late answer.
Without this patch I have:
test_svml (numba.tests.test_svml.TestSVML) ... FAIL
test_complex64_numpy8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_complex64_numpy8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float32_numpy8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float32_numpy8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float32_prange8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float32_prange8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float32_range8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float32_range8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float64_numpy8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float64_numpy8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float64_prange8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float64_prange8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float64_range8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_float64_range8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_int32_numpy8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_int32_numpy8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_int32_prange8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_int32_prange8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_int32_range8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL
test_int32_range8_usecase (numba.tests.test_svml.TestSVMLGeneration) ... FAIL

I run tests with command: `./runtests.py -v -m12 -k SVML`.

Full log is here: https://gist.github.com/PokhodenkoSA/3d6f5a770534c42bfe250239a7c4e54f

Error examples:
```
======================================================================
FAIL: test_svml (numba.tests.test_svml.TestSVML)
----------------------------------------------------------------------
...
AssertionError: '__svml_sin8_ha,' not found in '\t.text\n\t.file\t"<string>"\n\t.secti...

======================================================================
FAIL: test_complex64_numpy8_fastmath_usecase (numba.tests.test_svml.TestSVMLGeneration)
----------------------------------------------------------------------
...
AssertionError: False is not true : While expecting ['__svml_sinf16,', '__svml_coshf16,', '__svml_sinhf16,', '__svml_cosf16,', '__svml_expf16,'] and no [],
it contains:
	movabsq	$coshf, %r9
	movabsq	$sinhf, %rsi
	movabsq	$sincosf, %rax
...

```

**Pull request merged**
