### PR TITLE
Sorting

### PR DESCRIPTION
**Pull request by pitrou**
This PR implements Numpy array sorting and Python list sorting using quicksort.
The timsort implementation is included as an addition to the test suite.

This implementation is between 1.5x and 2.5x slower than Numpy's, regardless of the array size. Part of it seems to be due to LLVM not optimizing away tests for negative indexes.

### CODE REVIEW

**Comment by seibert** [comment]
I think we should put a warning in the docs about the performance being lower than Numpy sort.

**Comment by pitrou** [comment]
We don't really have a policy for doc warnings yet, but if we start warning about such differences I'm afraid the docs will have a lot of red in them. What do you think?

(actually I think it may be more important to document the possible O(n**2) worst case :-))

**Comment by seibert** [comment]
In this case, I think it a warning in the doc is warranted since we know our implementation is currently slower than Numpy's.  We are providing it as a convenience for use inside a larger function, and hopefully we can get LLVM to generate faster code in the future.

If a user's reasonable expectation is going to deviate from reality, we probably want a place to put those clarifying notes.  Either inline in the docs themselves, or on their own page of "limitations" that we can link to from various points in the docs.

**Comment by seibert** [comment]
This needs a remerge with master now.

**Comment by pitrou** [comment]
Ok, I've merged and added the performance warnings.

**Pull request merged**
