### PR TITLE
Add support for notebook testing.

### PR DESCRIPTION
**Pull request by stefanseefeld**
This patch moves the 'numba.testing' module into a proper sub-package to make room for additional functionality. It then adds some basic support for validating notebooks.

### CODE REVIEW

**Comment by stefanseefeld** [comment]
This PR fails on Python 2.6 as `python -m numba.testing` no longer works (being a package).
I added a new `numba.runtests` module that can be used instead, so if we change the CI logic to invoke that instead, this should work.

**Comment by pitrou** [comment]
You can simply change `.travis.yml` to run the right module.

**Comment by stefanseefeld** [comment]
OK, done. (The tests pass again.)

**Comment by stefanseefeld** [comment]
(Neither examples nor notebooks are tested by default yet. We need to document somewhere how to run those tests.)

**Pull request merged**
