### PR TITLE
Implement math.modf for CUDA target 

### PR DESCRIPTION
**Pull request by gabri94**
As title. Request reference: https://gitter.im/numba/numba?at=5e8f92d83a85536c431d086f

After the basic implementation by @stuartarchibald, I implemented the tests for float32 and float64 and edited the docs. 
The tests cover a range of 50 floats between 0 and 10, infinity, minus infinity and nan.

see #5545

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Many thanks for the PR!

@gmarkall please could you review this? Thanks!

**Comment by gmarkall** [comment]
@gabri94 Looks like your tests have some problems running on the simulator - you can try and reproduce them locally with the environment variable `NUMBA_ENABLE_CUDASIM=1` set.

**Comment by gabri94** [comment]
It was due to the bug I fixed in the last commit. I think it is fine now.

**Comment by gabri94** [comment]
I don't like to have the specific template for `modf` in the generic `TestCudaMath`. I think it should stay inside its scope. We could further abstract it into a generic Unary template with two returns, but if there are no more functions with this template I think it could be over-complex.

In the end I preferred to keep the two templates inside `test_math_modf` and split the test into 6 different subtests.

**Comment by stuartarchibald** [comment]
Patch looks good to me, thanks for doing the work @gabri94, thanks for reviewing/providing guidance @gmarkall. I'll push this through the farm now.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_47`.

**Comment by stuartarchibald** [comment]
Buildfarm passed.

@gabri94 congratulations on your first contribution to Numba!

**Pull request merged**
