### PR TITLE
Add str.encode() only for kind 1 and utf-8

### PR DESCRIPTION
**Pull request by densmirn**

### CODE REVIEW

**Comment by densmirn** [comment]
Could you please add the PR to the review queue?

**Comment by densmirn** [comment]
Could you please review the PR?

**Comment by stuartarchibald** [comment]
@densmirn just checking back in on this, did you want to proceed with it or is it best to close it for now? Thanks.

**Comment by densmirn** [comment]
It's better to close it now.

**Comment by stuartarchibald** [comment]
Thanks for confirming

**Pull request closed without merging**
