### PR TITLE
Fix CUDA @``intrinsic`` use

### LINKED ISSUE #6970: @intrinsic not working with CUDA
## Reporting a bug

- [x] I have tried using the mainline version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.
This:
```
./runtests.py numba.cuda.tests.cudadrv.test_cuda_array_slicing.CudaArraySetting.test_array_assign_all
```
and others, produce:
```
No implementation of function Function(<intrinsic to_fixed_tuple>) found for signature:
 
 >>> to_fixed_tuple(array(int64, 1d, C), Literal[int](2))
 
There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Intrinsic in function 'to_fixed_tuple': File: numba/np/unsafe/ndarray.py: Line 41.
       With argument(s): '(array(int64, 1d, C), int64)':
      Rejected as the implementation raised a specific error:
        KeyError: <class 'numba.core.extending_hardware.CUDA'>
          Traceback (most recent call last):
            File "<path>/numba/numba/core/types/functions.py", line 329, in get_call_type
              sig = temp.apply(nolitargs, nolitkws)
            File "<path>/numba/numba/core/typing/templates.py", line 347, in apply
              sig = generic(args, kws)
            File "<path>/numba/numba/core/typing/templates.py", line 905, in generic
              disp = dispatcher_registry[target_hw]
            File "<path>/numba/numba/core/registry.py", line 99, in __getitem__
              return super(TargetRegistry, self).__getitem__(item)
          KeyError: <class 'numba.core.extending_hardware.CUDA'>
  raised from <path>/numba/numba/core/registry.py:99

During: resolving callee type: Function(<intrinsic to_fixed_tuple>)
During: typing of call at <path>/numba/numba/cuda/cudadrv/devicearray.py (452)


File "numba/cuda/cudadrv/devicearray.py", line 452:
    def kernel(lhs, rhs):
        <source elided>

        lhs[to_fixed_tuple(idx[0], ndim)] = rhs[to_fixed_tuple(idx[1], ndim)]
        ^
```
xref: https://github.com/numba/numba/pull/6944, turns out that the dispatcher registration was needed, but not at exactly that point in the PR sequence to support this new extension functionality.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title. The CUDA dispatcher needs a target description as the
`@intrinsic` function templates query it.

Fixes #6970

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@sklam this fixes mainline for the CUDA target.

**Comment by stuartarchibald** [comment]
Also CC @gmarkall as code owner.

**Comment by stuartarchibald** [comment]
Buildfarm ID: `numba_smoketest_cuda_yaml_50`.

**Review by gmarkall — APPROVED** [review]
This fixes the CUDA tests locally for me.

**Comment by sklam** [comment]
Buildfarm passed

**Review by sklam — APPROVED** [review]
Thanks for the patch!

**Comment by sklam** [comment]
The CI failure will be fixed by #6966

**Pull request merged**
