### PR TITLE
Fix warnings struct ref typeguard

### PR DESCRIPTION
**Pull request by esc**
This adds a fix for the `StructRef` typeguard related issues in #6787

### CODE REVIEW

**Comment by esc** [comment]
Buildfarm ID: `typeguard_mypy_17`

**Comment by esc** [comment]
🎉 this actually passed on the new Typeguard DAG on the Anaconda internal build-farm!

**Comment by esc** [comment]
I have reviewed all of @stuartarchibald 's patches from https://github.com/numba/numba/pull/6767 and they are good to go!

**Comment by stuartarchibald** [comment]
> tada this actually passed on the new Typeguard DAG on the Anaconda internal build-farm!

Thanks @esc !

**Comment by stuartarchibald** [comment]
I approve e12d9d3, 28bfe55, f14fb77 for merge, but should not approve my own patches.

**Comment by sklam** [comment]
Approving commits up to https://github.com/numba/numba/pull/6789/commits/6d524fecafda4247d913acc083beb0f195e5ca53

**Comment by stuartarchibald** [comment]
> Approving commits up to [6d524fe](https://github.com/numba/numba/commit/6d524fecafda4247d913acc083beb0f195e5ca53)

Thanks @sklam, that covers all the remaining patches. Marking for merge.

**Review by stuartarchibald — APPROVED** [review]

**Pull request merged**
