### PR TITLE
Fixes to random.multinomial

### PR DESCRIPTION
**Pull request by juliusbierk**
First attempt at fixing https://github.com/numba/numba/issues/3426

### CODE REVIEW

**Comment by esc** [comment]
It may be worth checking how the Numpy variant of this is implemented. Perhaps they have some numerical tricky too.

**Comment by juliusbierk** [comment]
> It may be worth checking how the Numpy variant of this is implemented. Perhaps they have some numerical tricky too.

Hhmmm... they definitely also have issues with it:
https://github.com/numpy/numpy/blob/main/numpy/random/mtrand.pyx#L4239

But they don't seem to have to cap the probability at 1:
https://github.com/numpy/numpy/blob/ea7b0e281a8d221c847abb2cd760cb067fa8543b/numpy/random/src/distributions/distributions.c#L1679

**Comment by esc** [comment]
@juliusbierk thank you for your efforts on this front! Your efforts to improve Numba are appreciated. I've moved the PR back to in-progress. Please do let us know when you would like a review!

**Comment by juliusbierk** [comment]
Thanks @esc. Sorry for all the commits. I thought this was a really simple change, so I just did it online in github, but apparently I had misunderstood some inner workings of numba.
Anyway: I think I fixed it all now, and the PR is ready for review.

**Comment by esc** [comment]
@juliusbierk thank you for submitting this. I have added it to the queue for review. It may be some time however until someone finds the time to review it. Thank you for your patience.

**Comment by juliusbierk** [comment]
@esc Any update?

**Comment by esc** [comment]
> @esc Any update?

Not at this time, no. 

@stuartarchibald do you think this could profit from https://en.wikipedia.org/wiki/Kahan_summation_algorithm ?

**Comment by esc** [comment]
Judging from https://github.com/numpy/numpy/blob/main/numpy/random/mtrand.pyx#L4274 -- it does seem like NumPy is using Kahan sum for this? At least for some aspects?

**Comment by stuartarchibald** [comment]
@esc @juliusbierk Apologies for the delay, I've just taken a look at this patch and the reference implementation (NumPy). 

There's evidently issues with numerical sensitivity and these will likely be exacerbated through algorithmic difference, therefore I think the first thing to do is adjust the underlying Numba implementation so as to better match the implementation in NumPy.

I also suspect that whilst entirely well intentioned, adding absolute value checks like https://github.com/numba/numba/pull/7551/files#diff-342c40f4687a52b5620fde4998e02c94263bbc46f9b0802d1a5e60d5c99311deR1457 that do not correlate to the reference implementation will unfortunately lead to hard to track down numerical discrepancies.

**Comment by YannisZa** [comment]
Hi there @stuartarchibald , @esc . Are there any plans to fix this soon? Thank you.

**Comment by georgewambold** [comment]
@juliusbierk Just curious if you have any updates on this PR. I just ran into that same `ValueError: binomial(): p outside of [0, 1]` issue.

**Comment by juliusbierk** [comment]
@georgewambold I am not moving on this at the moment. The submitted PR does fix the issue, but as pointed out by 
@esc  and @stuartarchibald, it does not match exactly the numpy implementation, which e.g. uses Kahan summutation.
To be clear, the current implementation certainly also does not match the numpy implementation (since it fails).
Hopefully someone will take over the issue and fix it in line with how it is done in numpy. Otherwise, at some point I will have a look again.

**Comment by stuartarchibald** [comment]
Given the efforts being made to support `np.random.Generator` and in the process update all the RNG implementations, it might be a good idea to roll fixing this issue into that work. CC @kc611 what do you think?

**Comment by kc611** [comment]
I think going with a implementation for Kahan's summation would be the way to go over here. In the past, we did have instances where slight numerical differences ended up being a problem. 

Even with respect to efforts towards  `np.random.Generator`, when `multinomial` is implemented for `Generator`s we will anyways require a `kahan_sum` method as it is a part of both implementations. 

https://github.com/numpy/numpy/blob/7a3066c39002404e5c0b7ff316317604ef3f603b/numpy/random/_generator.pyx#L3924

@juliusbierk If you're fine with it, Can I take over this PR and go by Kahan's summation instead ?

**Pull request closed without merging**
