### PR TITLE
Enable CALL_FUNCTION_EX fix for py3.11

### LINKED ISSUE #8900: 0.57.0rc1 UnsupportedError when number of keyword arguments in CALL_FUNCTION_EX is 16 or more
Reported on discourse for the RC: https://numba.discourse.group/t/ann-numba-0-57-0rc1-and-llvmlite-0-40-0rc1/1879/2

minimal reproducer:

```python
import numba

@numba.njit
def foo(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q):
    return (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q)


@numba.njit
def bar(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q):
    return foo(a=a, b=b, c=c, d=d, e=e, f=f, g=g, h=h, i=i, j=j, k=k, l=l, m=m, n=n, o=o, p=p, q=q)

bar(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17)
```

traceback:
```
% NUMBA_DEVELOPER_MODE=1 python call_fn_ex.py
Traceback (most recent call last):
  File "/path/to/numba/call_fn_ex.py", line 12, in <module>
    bar(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17)
  File "/path/to/numba/numba/core/dispatcher.py", line 471, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/path/to/numba/numba/core/dispatcher.py", line 407, in error_rewrite
    raise e
  File "/path/to/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/compiler.py", line 742, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/compiler.py", line 460, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/compiler.py", line 528, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/compiler.py", line 507, in _compile_core
    raise e
  File "/path/to/numba/numba/core/compiler.py", line 494, in _compile_core
    pm.run(self.state)
  File "/path/to/numba/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/path/to/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/path/to/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/untyped_passes.py", line 86, in run_pass
    func_ir = interp.interpret(bc)
              ^^^^^^^^^^^^^^^^^^^^
  File "/path/to/numba/numba/core/interpreter.py", line 1363, in interpret
    flow.run()
  File "/path/to/numba/numba/core/byteflow.py", line 110, in run
    runner.dispatch(state)
  File "/path/to/numba/numba/core/byteflow.py", line 337, in dispatch
    fn(state, inst)
  File "/path/to/numba/numba/core/byteflow.py", line 1063, in op_CALL_FUNCTION_EX
    raise UnsupportedError(errmsg)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
```

### PR DESCRIPTION
**Pull request by sklam**
Tests were originally from https://github.com/numba/numba/pull/7866

Fix #8900

### CODE REVIEW

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch, the proposed changes make sense as a fix for #8900. The area of `Python/compile.c` in the CPython source that deals with `CALL_FUNCTION_EX` has changed slightly between 3.10 and 3.11 but just on inspection it doesn't look like anything has changed that would significantly alter bytecode emission with respect to what Numba is interested in. A spot check of the disassembled bytecode from calling functions with large numbers of kwargs suggests similar, i.e. no significant change that would impact the peephole optimiser that fixes up the bytecode for Numba post 3.10. Also, the tests being re-enabled are extensive with respect to the bytecode patterns that can be generated and that they are passing gives further confidence.

**Comment by sklam** [comment]
BFID `numba_pynext_cpu_yaml_20`

**Comment by stuartarchibald** [comment]
> BFID `numba_pynext_cpu_yaml_20`

Passed.

**Comment by stuartarchibald** [comment]
Manual check of reproducer in #8900 also passes.

**Pull request merged**
