### PR TITLE
Use process level locks for fork() only.

### LINKED ISSUE #4348: Global locks cause semaphore leaks.
#### Description

Importing `numba` causes semaphores to leak.

#### Steps/Code to Reproduce

```python
import multiprocessing as mp

import numba


def w():
    pass


def main():
    ps = [mp.Process(target=w) for _ in range(4)]
    [p.start() for p in ps]
    [p.join() for p in ps]


if __name__ == '__main__':
    p = mp.get_context('spawn').Process(target=main)
    p.start()
    p.join()
```

#### Actual Results

```bash
$ python3 blah.py
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
$
```

#### Expected Results

```bash
$ python3 blah.py
$
```

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

Fixes #4348

### CODE REVIEW

**Comment by stuartarchibald** [comment]
This will need putting through the build farm, and probably some discussion...

**Comment by sklam** [comment]
I haven't fully understood your explanation in https://github.com/numba/numba/issues/4348#issuecomment-513760791 but the patch itself looks reasonable.

And, yes, this will need buildfarm to smoke out any potential issue.

**Comment by seibert** [comment]
Running this PR through the buildfarm

**Comment by stuartarchibald** [comment]
7d3b23c adds a test.

**Comment by seibert** [comment]
This seems to have passed the buildfarm.

**Pull request merged**
