### PR TITLE
fix argument binding with var positional and kwargs

### LINKED ISSUE #5291: Compilation failure when overload contains *args and multiple keyword arguments
On the current master, compilation fails when an overloaded function contains `*args` and multiple keyword arguments.

Note: In the example below, if one deletes `bar`, compilation succeeds.

```python
from numba import njit
from numba.extending import overload

def foo(*args, **kwargs):
    # stub for overload
    pass


@overload(foo)
def foo_ovl(*args, bar1=None, bar2=None):
    def foo_impl(*args, bar1=None, bar2=None):
        return args

    return foo_impl


@njit
def test(a, b):
    return foo(a, b)


test(1, 2)
```

Output:
```
Traceback (most recent call last):
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\My User\Documents\numba\Untitled-2.py", line 22, in <module>
    test(1, 2)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "c:\Users\My User\Documents\numba\numba\core\utils.py", line 77, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
?[1m?[1m?[1mInvalid use of Function(<function foo at 0x0000027BE7E333A0>) with argument(s) of type(s): (int64, int64)
 * parameterized
?[1mIn definition 0:?[0m
?[1m    IndexError: tuple index out of range?[0m
    raised from c:\Users\My User\Documents\numba\numba\core\typing\templates.py:169
?[1mIn definition 1:?[0m
?[1m    IndexError: tuple index out of range?[0m
    raised from c:\Users\My User\Documents\numba\numba\core\typing\templates.py:169
?[1mThis error is usually caused by passing an argument of a type that is unsupported by the named function.?[0m?[0m
?[0m?[1m[1] During: resolving callee type: Function(<function foo at 0x0000027BE7E333A0>)?[0m
?[0m?[1m[2] During: typing of call at c:\Users\My User\Documents\numba\Untitled-2.py (19)
?[0m
?[1m
File "Untitled-2.py", line 19:?[0m
?[1mdef test(a, b):
?[1m    return foo(a, b)
?[0m    ?[1m^?[0m?[0m
```

### PR DESCRIPTION
**Pull request by ARF1**
Fixes and closes #5291.

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for the PR. Prior to review, please could tests be added to demonstrate that it works as intended! Thanks.

**Comment by ARF1** [comment]
@stuartarchibald I have been hunting for the right place to put the tests but could not find it. Can you help me locate the right place?

**Comment by ARF1** [comment]
@stuartarchibald I have been considering [https://github.com/numba/numba/blob/da89aa5ba0427ec185a925542137b88ef8a56cd8/numba/tests/test_extending.py#L980](https://github.com/numba/numba/blob/da89aa5ba0427ec185a925542137b88ef8a56cd8/numba/tests/test_extending.py#L980) but that is primarily `overload`.

The alternative would be [https://github.com/numba/numba/blob/da89aa5ba0427ec185a925542137b88ef8a56cd8/numba/tests/test_dispatcher.py#L669](https://github.com/numba/numba/blob/da89aa5ba0427ec185a925542137b88ef8a56cd8/numba/tests/test_dispatcher.py#L669) which is for `generated_jit`.

Since the issue is common to both, is there a place that tests the common underlying mechanisms somewhere?

**Comment by ARF1** [comment]
So in the current form this works in nopython mode. When called from python however there seems to be a bug in the typing code somewhere. The argument binding code is never reached. The error occurs earlier in the pipeline.

I am a bit at a loss where to start looking for the relevant code sections.

Following are the failures:
```python
from numba import njit, generated_jit

@generated_jit
def foo(*args, bar1=5, bar2=6):
    def foo_impl(*args, bar1=5, bar2=6):
        return args, bar1, bar2
    return foo_impl

print(foo(1, 2, bar1=7))
```

Outputs:
```
Traceback (most recent call last):
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "Z:\Systemdateien\Miniconda3\envs\python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "Z:\Systemdateien\Miniconda3\envs\python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "Z:\Systemdateien\Miniconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\My User\Documents\numba\numba\np\Untitled-4.py", line 9, in <module>
    print(foo(1, 2, bar1=7))
TypeError: missing argument 'bar2'
```

----
Second failure mode (calling with kwarguments only):

```python
print(foo(bar1=7))
```

Outputs:
```
Traceback (most recent call last):
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "Z:\Systemdateien\Miniconda3\envs\python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "Z:\Systemdateien\Miniconda3\envs\python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "Z:\Systemdateien\Miniconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\My User\Documents\numba\numba\np\Untitled-4.py", line 9, in <module>
    print(foo(bar1=7))
TypeError: not enough arguments: expected 3, got 1
```

**Comment by esc** [comment]
I'll pick this up now.

**Comment by ARF1** [comment]
@esc Thanks you for your help and for letting me know.

**Comment by stuartarchibald** [comment]
@ARF1 apologies, completely missed this, I see @esc is on it now :) Thanks @esc!

**Comment by esc** [comment]
Sorry for the delay, I am on it now. Looking at the tracebacks for the latest error, I see:

```
Traceback (most recent call last):
  File "foo017.py", line 9, in <module>
    print(foo(1, 2, bar1=7))
TypeError: missing argument 'bar2'
```

And I don't see any typing error or similar, so my initial guess is that this is an issue with the `@generated_jit` decorator, so I'll go and look there now.

**Comment by esc** [comment]
Further digging led me to figure out, that the second error casa above, the one that yields:

```
TypeError: not enough arguments: expected 3, got 1
```

May actually be raised from https://github.com/numba/numba/blob/master/numba/_dispatcher.c#L420

**Comment by esc** [comment]
And the first one, 

```
TypeError: missing argument 'bar2'

```

Is coming from:

https://github.com/numba/numba/blob/master/numba/_dispatcher.c#L485

**Comment by esc** [comment]
Since this may involve some intricate debugging and potentially a high impact patch at the C-level we decided to exclude this from the imminent (tomorrow 🤞) release. I am moving this to the https://github.com/numba/numba/milestone/34 milestone for now.

**Comment by ARF1** [comment]
@esc Understandable. The C debugging is what scared me off for now...

**Comment by guilhermeleobas** [comment]
Hi all, if there's still interest in this PR, I can review it.

**Comment by esc** [comment]
@guilhermeleobas  since @ARF1 has not been around for a while. I think that you would need to adopt this PR, in case you want to see it though.

**Pull request closed without merging**
