### PR TITLE
Isolate mutation on func_ir._definitions 

### PR DESCRIPTION
**Pull request by sklam**
WIP.  DO NOT MERGE

This is a refactor on the `func_ir._definitions` attribute usage.

• `._definitions` is now immutable and autogenerated from the IR so it is never out-of-sync.
• a new `.temp_definitions` is added to find places that does temporary mutation on it (like in array_analysis.py and inline_closurecall.py).  These temporary mutations are not yet visible in the IR, yet.  (TODO: refactor these mutations so we get remove `.temp_definitions`.

### CODE REVIEW

**Comment by sklam** [comment]
It is failing on py27 due to ChainMap usage.  Once we get rid of `.temp_definitions`, we can get rid of ChainMap as well.

**Comment by ehsantn** [comment]
how should transformations that change definitions as they go work?

**Comment by sklam** [comment]
Now that the definition-changing code is isolated, I think we can pull `temp_definitions` out of `func_ir`.  Once the transformation is done, `temp_definitions` can be discarded and the IR should reflect new definitions.

**Comment by sklam** [comment]
If code transformation should fail, the func_ir state is still self-consistent.

**Pull request closed without merging**
