### PR TITLE
test Numba on the buildfarm with LLVM 10 enabled llvmlite

### PR DESCRIPTION
**Pull request by esc**
DO NOT MERGE

### CODE REVIEW

**Comment by esc** [comment]
Build-farm id: `numba_185`.

**Comment by gmarkall** [comment]
@esc Could we test this branch again but with #6030 merged instead of using https://github.com/numba/numba/pull/5969/commits/703c4fe394b64a10e3e1adf7c608523ef4302fbc ? Instead of upping the opt level to 3, no optimization is done using LLVM 10.

**Comment by esc** [comment]
@gmarkall sure, however, internal build farm is currently down however, so it may be a few more days until I get around to it.

**Comment by gmarkall** [comment]
@esc thanks - I had heard about some things that needed to be done with it :-)

**Comment by esc** [comment]
@gmarkall I queued it for a Numba CUDA smoketest at BFID: `numba_smoketest_cuda_70`.

**Comment by esc** [comment]
BFID: `numba_smoketest_cuda_70` unfortunately failed to build, because the smoketest wasn't configured with the correct channels and was unable to find the correct llvmlite version.

**Comment by esc** [comment]
as Numba 0.51.0 and llvmlite 0.34.0 have been released, this branch is no longer needed. LLVM 10 support is now done.

**Pull request closed without merging**
