### PR TITLE
skip azure pipeline test if file not present

### PR DESCRIPTION
**Pull request by esc**
This test must not be executed if the azure config is not present, for
example in shipped conda packages or pypi source distributions or
wheels.

```
 zsh» python -m numba.runtests numba.tests.test_runtests.TestCase.test_azure_config
.
----------------------------------------------------------------------
Ran 1 test in 0.018s

OK
zsh» rm -rf azure-pipelines.yml
zsh» python -m numba.runtests numba.tests.test_runtests.TestCase.test_azure_config
s
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (skipped=1)
```

### Reference an existing issue

#7392

### CODE REVIEW

**Comment by esc** [comment]
BFID: `numba_smoketest_cpu_yaml_44`

**Comment by stuartarchibald** [comment]
> BFID: `numba_smoketest_cpu_yaml_44`

Status?

**Review by stuartarchibald — APPROVED** [review]
Thanks for the patch.

**Comment by esc** [comment]
> > BFID: `numba_smoketest_cpu_yaml_44`
> 
> Status?

The status was, that all the errors related to this disappeared and the issues probably resolved by #7386 start to manifest.

**Comment by stuartarchibald** [comment]
> > > BFID: `numba_smoketest_cpu_yaml_44`
> > 
> > 
> > Status?
> 
> The status was, that all the errors related to this disappeared and the issues probably resolved by #7386 start to manifest.

Thanks for confirming. Patch approved.

**Pull request merged**
