### PR TITLE
Compute fingerprint of class object (base for jitmethod caching)

### PR DESCRIPTION
**Pull request by sklam**
Based on #1958 .

To support jitmethod caching, we need to ensure that clones of class objects via serialization or copying do not consider as different classes.  We do this by computing a fingerprint base on the class members and other attributes.  The `ClassType` will use the fingerprint+spec as an unique identity and as the cache key.

The `ClassFingerPrint` class implements the logic for the fingerprint computation.  It gathers the class attributes/members, pickles them, and outputs a MD5 digest.

### CODE REVIEW

**Comment by ma-ba** [comment]
Am I right to assume this will also help resolving #1681? However, I guess this won't touch pickling of jitclass instances (#1846, https://github.com/numba/numba/issues/1681#issuecomment-200944838), right?

**Comment by sklam** [comment]
Right, this is the foundation for jitmethod caching (thus #1681) which I am developing concurrently.  This won't solve jitclass instance pickling, but it is a foundation for it too.

**Comment by pitrou** [comment]
Early comment on this PR: is the fingerprint computation really required, or can you simply identify a jitclass using its `__module__` + `__qualname__` + `__spec__`?

**Comment by sklam** [comment]
* ``__qualname__`` isn't specific enough for class defined in local scope.  It just have a "...<locals>..." in it.
* to cache, it need a way to tell if the methods have been change. Maybe MD5-ing the code.co_code is an overkill.  Perhaps, last modified timestamp.

**Comment by pitrou** [comment]
Last modified timestamp of the source file is what we're already using (for regular `@jit` functions). I suggest we re-use that scheme.

**Pull request closed without merging**
