### PR TITLE
fix missing incref on flags

### PR DESCRIPTION
**Pull request by esc**
Fixes: https://github.com/numba/numba/issues/4775

### CODE REVIEW

**Comment by esc** [comment]
Not sure if tests make any sense here, the corruption must be provoked differently on different OSs. I am not certain that a test would be reliable...

**Comment by stuartarchibald** [comment]
Given it's leaking right now, adding the thing that's segfaulting (at least on some platforms) as a test would provide evidence that this fixes it?

**Comment by esc** [comment]
Sure, better than nothing.

**Comment by esc** [comment]
doh!

**Comment by esc** [comment]
The last commit was faulty and had some debugging output left from a different branch. I amended the commit and force pushed, I think in this case it was  O.K. since no code review comments were left on the PR yet.

**Comment by esc** [comment]
Oh good; then the last commit did do the trick, good to know that old style classes will not work with `@jitclass`.

**Pull request merged**
