### PR TITLE
Fix old_style error capturing deprecation warnings

### LINKED ISSUE #9151: 0.58.0rc1 old-style error capturing warning issues
Issues:
- [x] Warnings about old-style error are raised regardless of whether the error is a `NumbaError`. (ref: https://matrix.to/#/!gFwSEpcuaweltInwDW:gitter.im/$5Mc1guc4peAryXvx3WjSWhD3TDxC_Nzb-mCQsl-s17k?via=gitter.im&via=matrix.org&via=matrix.kraut.space)
- [x] Reason of the warning is unclear (ref: https://numba.discourse.group/t/ann-numba-0-58-0rc1-and-llvmlite-0-41-0rc1/2078/2)

### PR DESCRIPTION
**Pull request by sklam**
Closes #9151

- da49bf39f31ece669b9d56fde5ab08143db63e20 fixes the invalid raising of deprecation warnings when the active exception is a NumbaError. I also have to fix a problem that warnings were suppressed if an exception is raised at typing.
- 8d04ce893ec0694b2dbbcc0ef0705e1ec9e41a4c clarifies the message.
- The remaining commits fine tunes the warning behavior
    - add origin of the exception to help developers find the source of the problem.
    - avoid showing deprecation warnings on a previous warning that are raised due to `-Werror`

### CODE REVIEW

**Comment by sklam** [comment]
Deprecation warning message now looks like:

```
numba.core.errors.NumbaPendingDeprecationWarning: Failed in nopython mode pipeline (step: nopython frontend)
Code using Numba extension API maybe depending on 'old_style' error-capturing, which is deprecated and will be replaced by 'new_style' in a future release. See details at https://numba.readthedocs.io/en/latest/reference/deprecation.html#deprecation-of-old-style-numba-captured-errors
Exception origin:
  File "/path/to/some/library/file.py", line 711, in function_name
    raise TypeError(
```

**Comment by sklam** [comment]
I think my force push is hidding a comment on this PR so i'm pasting it here:

https://github.com/numba/numba/commit/8d04ce893ec0694b2dbbcc0ef0705e1ec9e41a4c#commitcomment-125637047
> @sklam Currently, the warning is being output in many of my [unit tests](https://github.com/stumpy-dev/automate/actions/runs/5911747622/job/16034516552#step:10:32) when executing with them with Numba 0.58.0rc1 and llvmlite 0.41.0rc1. It's not clear whether these warnings are temporary OR if something in my code is triggering these warnings? Will I need to filter these warnings moving forward or is there a way for me to change my code so that these warnings are "fixed"?

**Review by gmarkall — APPROVED** [review]
I tested this locally to verify that it fixes fails in the CUDA test suite when running with `old_style` captured errors. The code changes look sensible to me.

**Comment by sklam** [comment]
All CI has passed. Marking it as RTM

**Pull request merged**
