### PR TITLE
Fix #6697: Wrong dtype when using np.asarray on DeviceNDArray

### LINKED ISSUE #6697: Wrong dtype when using np.asarray on DeviceNDArray
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

#### Reproduce Code

```python
>>> from numba import cuda
>>> import numpy as np
>>> arr = np.arange(10).astype(np.int16)
>>> arr.dtype
dtype('int16')

>>> darr = cuda.to_device(arr)
>>> darr.dtype
dtype('int16')

>>> arr = np.asarray(darr)
>>> arr.dtype
dtype('float64')
```

_Originally posted by @ashutoshvarma in https://github.com/numba/numba/issues/6563#issuecomment-774035027_

The `test_auto_transfer` is failing due the following change :-
Without it all tests pass without problem
```diff
@@ -107,7 +108,7 @@ class UFuncMechanism(object):
         """
         for i, ary in enumerate(self.arrays):
             if ary is not None:
-                self.argtypes[i] = ary.dtype
+                self.argtypes[i] = np.asarray(ary).dtype
```
Since `ary` would always be either `np.ndarray` or `DeviceNDArray` type,  keeping `ary.dtype` should be fine? (correct me if I missed something )

Ideally, the above change should not break anything, but for some reason, if `ary` is of DeviceNDArray type then `np.asarray(ary).dtype` gives the wrong dtype.
For DeviceNDArray ary, `np.asarray(ary)` will always be a `float64` ndarray irrespective of original dtype

```python
>>> x = np.arange(n, dtype=np.int32)
>>> dx = cuda.to_device(x)
>>> print(dx.dtype)
>>> print(np.asarray(dx).dtype)
int32
float64
```

After digging more, looks like problem might be in `DeviceNDArray.__array__()` method
https://github.com/numba/numba/blob/00ad12751725391e8423d67ef845ba56110c55df/numba/cuda/cudadrv/devicearray.py#L482-L486

In above, passing even `None` (dtype) to `__array__` of ndarray will return new array with default dtype (`float64`)
`ndarray.__array__` docs - https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__array__.html
```python
>>> import numpy as np
>>> a = np.arange(10, dtype=np.int16)   
>>> b = a.__array__(np.int16)          # no copy
>>> c = a.__array__(None)              # copy
>>> d = a.__array__()                  # no copy
>>> print(f"{a.dtype=}")
>>> print(f"{b.dtype=}")
>>> print(f"{c.dtype=}")
>>> print(f"{d.dtype=}")
a.dtype=dtype('int16')
b.dtype=dtype('int16')
c.dtype=dtype('float64')
d.dtype=dtype('int16')
```

Changing `__array__(dtype) ` to either `__array__(self.dtype) ` or `__array__() ` should fix this.

### PR DESCRIPTION
**Pull request by ashutoshvarma**
Closes #6697

I was not sure about where tests for this should go, for now, the test is in `numba/cuda/tests/cudadrv/test_array_attr.py`.

### CODE REVIEW

**Review by gmarkall — CHANGES_REQUESTED** [review]
Many thanks for tracking down this issue and making the PR! I think it is looking great in general:

- Tests pass for me locally with hardware and the simulator.
- The reproducer given in #6697 behaves correctly with this PR (it prints out `int16` three times instead of `int16` twice then `float64`).
- The starter patch from #6563 applied on top of this PR passes all tests, and also allows the example from https://github.com/numba/numba/issues/6563#issuecomment-769511140 to run correctly.

So, this PR really moves things in the right direction for both the issue #6697 and the feature request #6563.

Regarding the location of the test - the majority of tests that test device arrays, transferring them between the host and the device, and checking their dtypes and other properties are in `numba/cuda/tests/cudadrv/test_cuda_ndarray.py` - would you be happy to move the test there?

Many thanks again!

**Comment by ashutoshvarma** [comment]
Thanks for the review @gmarkall 
I moved the test to numba/cuda/tests/cudadrv/test_cuda_ndarray.py (`TestCudaNDArray`) as you requested.

**Review by gmarkall — APPROVED** [review]
Many thanks for the update - this is looking good to me!

@esc Could this have a CUDA buildfarm run please?

**Comment by esc** [comment]
@gmarkall sure `numba_smoketest_cuda_yaml_10`

**Comment by esc** [comment]
Screen Shot 2021-02-09 at 18 19 06

BF passed.

**Comment by gmarkall** [comment]
@stuartarchibald @sklam Do you want to look at this before it goes to RTM?

**Review by stuartarchibald — APPROVED** [review]
Looks good, thanks for the patch. Thanks for reviewing @gmarkall .

**Comment by gmarkall** [comment]
Many thanks for the contribution @ashutoshvarma !

**Pull request merged**
