### PR TITLE
Added error catching in Interval doctest

### PR DESCRIPTION
**Pull request by kc611**
Continuation of: https://github.com/numba/numba/pull/5113

Original code by @eric-wieser 

Built on top of #8220, split from #8220 to make it easier to review.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Can you merge master so that the diff updates?

**Comment by esc** [comment]
@eric-wieser is this what you had in mind?

**Review by eric-wieser — COMMENTED** [review]
This seems to be missing the patch to `box_interval` from #5113

**Comment by eric-wieser** [comment]
I've gone ahead and merged master with #5113; I'm not sure if it makes sense to continue this PR unless @kc611 thinks something was wrong with my attempt two and a half years ago.

**Comment by kc611** [comment]
No problem, if that PR is being continued, I am also of the opinion that this PR should be closed.

**Pull request closed without merging**
