### PR TITLE
update release date after delay

### PR DESCRIPTION
**Pull request by esc**
As title

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
@esc, should one add the `skip-releases-note` label?

**Comment by esc** [comment]
> @esc, should one add the `skip-releases-note` label?

Yes, but wanted to wait until Azure is done. I find that the only way to re-run testing after adding the label is to open/close the issue which then creates a backlog for CI. The situation is far from ideal. I've added it now.

**Comment by esc** [comment]
> > @esc, should one add the `skip-releases-note` label?
> 
> Yes, but wanted to wait until Azure is done. I find that the only way to re-run testing after adding the label is to open/close the issue which then creates a backlog for CI. The situation is far from ideal. I've added it now.

Oh I accidentally clicked "merge" rather than "close". Well, I guess that's a first. Feel free to retroactively approve the PR or disapprove it and I'll make another one. I was able to merge without a review, because branch protection is only on for the `main` branch..

**Comment by guilhermeleobas** [comment]
Can't approve it anymore as the PR was merged.

**Comment by esc** [comment]
> Can't approve it anymore as the PR was merged.

Hmmm, we should activate branch protections for release branches too.

**Pull request merged**
