### PR TITLE
CUDA SELP patch is failing tests

### LINKED ISSUE #2845: CUDA SELP patch is failing tests
On the farm, CUDA version and OS invariant fail of conda build of master branch since PR: https://github.com/numba/numba/pull/2835

Traceback is:
```
======================================================================
ERROR: test_selp (numba.cuda.tests.cudapy.test_intrinsics.TestCudaIntrinsic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/tests/cudapy/test_intrinsics.py", line 164, in test_selp
    branching_with_selps[n, 1](a, b, c)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 702, in __call__
    kernel = self.specialize(*args)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 713, in specialize
    kernel = self.compile(argtypes)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 728, in compile
    **self.targetoptions)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 36, in core
    return fn(*args, **kwargs)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 75, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 36, in core
    return fn(*args, **kwargs)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 64, in compile_cuda
    locals={})
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 780, in compile_extra
    return pipeline.compile_extra(func)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 363, in compile_extra
    return self._compile_bytecode()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 739, in _compile_bytecode
    return self._compile_core()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 726, in _compile_core
    res = pm.run(self.status)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 249, in run
    raise patched_exception
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 241, in run
    stage()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 455, in stage_nopython_frontend
    self.locals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 882, in type_inference_stage
    infer.propagate()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 846, in propagate
    raise errors[0]
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 1123, in resolve_call
    literals=literals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typing/context.py", line 204, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/types/functions.py", line 137, in get_call_type_with_literals
    raise errors.TypingError(failures.format())
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid usage of Function(<class 'numba.cuda.stubs.selp'>) with parameters (bool, float64, int64)
 * parameterized
In definition 0:
    rejected
[1] During: resolving callee type: Function(<class 'numba.cuda.stubs.selp'>)
[2] During: typing of call at /opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/tests/cudapy/test_intrinsics.py (80)
```

### PR DESCRIPTION
**Pull request by njwhite**
Maybe this will fix #2845 ?

### CODE REVIEW

**Comment by njwhite** [comment]
@stuartarchibald @seibert um, Travis is failing for something that looks unrelated? Are there known issues with master?

````
  File "/home/travis/miniconda3/envs/travisci/lib/python3.6/site-packages/llvmlite/binding/targets.py", line 215, in create_target_machine
    assert codemodel in CODEMODEL
````

**Comment by stuartarchibald** [comment]
It's LLVM 6 related. I'll restart the builder.

**Comment by njwhite** [comment]
@stuartarchibald @seibert more unrelated failures?

````
Traceback (most recent call last):
  File "/home/travis/build/numba/numba/numba/tests/test_parfors.py", line 1623, in test_vectorizer_fastmath_asm
    self.assertTrue('vaddpd' not in v)
AssertionError: False is not true

````

**Comment by stuartarchibald** [comment]
Yes, that's not this patch. That's the LLVM 6 vectorizer being markedly improved tripping a test :-)

Early next week we should have ironed all this out and service will resume as normal! Apologies.

**Comment by njwhite** [comment]
@stuartarchibald np, just want to make sure my selp patch isn’t causing more problems!

**Comment by stuartarchibald** [comment]
@njwhite I pushed this through the buildfarm and it's segfaulting on all build plans. Just to make entirely sure it is not due to some mismatched LLVM 6 thing, please could you rebase this on master or merge master into it so that the latest changes are picked up? I'll then give it another run. Thanks.

**Comment by njwhite** [comment]
@stuartarchibald  done, although I can't build locally until I upgrade my FC27 machine to LLVM 6 :/

**Comment by stuartarchibald** [comment]
@njwhite thanks v. much. There are llvmlite and llvmdev packages based on LLVM 6 in the numba channel if you are using conda?

**Comment by njwhite** [comment]
@stuartarchibald ah thanks, `conda install -c numba llvmlite` worked. This `test_intrinsic` PR passes locally, both on the GPU & in the simulator for me.

**Comment by sklam** [comment]
There's a weird out-of-resources error on win64 related to the selp test.

**Comment by njwhite** [comment]
@sklam where do you see that? https://travis-ci.org/numba/numba/builds/361857941 seems ok?

**Comment by njwhite** [comment]
@stuartarchibald hm, can I help with debugging? What logs / core dumps do you have? (I assume it fails every time you run it on win64 / nvidia hw)?

**Pull request merged**
