### PR TITLE
Fix flake8 issue on master

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title.

### CODE REVIEW

**Comment by sklam** [comment]
flake8 is still complaining these:

```
numba/tests/test_listobject.py:392:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:603:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:631:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:872:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:952:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:970:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:990:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1013:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1169:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1184:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1200:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1218:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1236:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_listobject.py:1251:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_typedlist.py:678:9: E306 expected 1 blank line before a nested definition, found 0
numba/tests/test_typedlist.py:693:9: E306 expected 1 blank line before a nested definition, found 0
```

**Comment by stuartarchibald** [comment]
Thanks, I'll have another go and add them in too.

**Comment by stuartarchibald** [comment]
hmmm, I can't replicate those flake8 errors locally, where are you seeing them @sklam ?

**Comment by seibert** [comment]
OK, this passed the flake8 test in Azure, so I think this is ready to merge.

**Comment by sklam** [comment]
hm... it showed up in both PR head and merged.

**Comment by sklam** [comment]
interesting, it is complaining in py35 but not on py37.

**Comment by sklam** [comment]
These is a known bug of E306 false positive in pycodestyle.  Avoid using py3.5 and make sure pycodestyle>=2.3.1 is used.

**Comment by esc** [comment]
That would explain why these didn't show up before...

**Pull request merged**
