### PR TITLE
Enable AVX everywhere possible except Sandy and Ivy Bridge.

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by seibert** [comment]
Remind me what platforms return "core-avx-i"?

**Comment by seibert** [comment]
Oh, I see, corei7-avx is for Sandy Bridge, and core-avx-i is returned on Ivy Bridge (because they added a few more instructions)

**Comment by seibert** [comment]
GCC 4.9 makes these names much more sensible, hopefully LLVM follows: https://gcc.gnu.org/onlinedocs/gcc-4.9.0/gcc/i386-and-x86-64-Options.html#i386-and-x86-64-Options

**Comment by pitrou** [comment]
While LLVM has chosen rather silly names, I hope they don't change them from release to release :) (which admittedly wouldn't be surprising from them)

**Comment by seibert** [comment]
GCC also used to use the same names as LLVM.  I assume they just deprecated the old ones, but still support them.

**Pull request merged**
