### PR TITLE
Fix #1206: propagate errors raised from Numba-compiled ufuncs

### LINKED ISSUE #1206: guvectorize silently swallows exceptions
```python
@guvectorize(["void(float64[:], float64[:])"], "()->()", nopython=True)
def test(source, result):
    raise ValueError('help')
    result[()] = -99  # this line is never reached
```
```
>>> test(1234)
4.8749457275155797e-320
```

### PR DESCRIPTION
**Pull request by pitrou**
Also plugs some reference leaks in object mode ufuncs.

Notes:
* before, a division by zero in a ufunc silently returned an arbitrary value (`0.0` apparently, but that's a result of undefined behaviour); now it raises a ZeroDivisionError
* a ufunc which may raise an exception (including ZeroDivisionError) will get a little slower as a result, because of the error status checking at function return

### CODE REVIEW

**Comment by seibert** [comment]
I'm worried about defaulting to non-Numpy behavior for division by zero in ufuncs.  We had one person raise this as an issue at Scipy, where they wanted the Numpy behavior rather than the Python behavior.  In a `@jit` function, the programmer intent is not obvious, but since `@vectorize` is only used with Numpy functions, I think we want to default to the Numpy behavior for division by zero.

Does this make sense?

**Comment by pitrou** [comment]
You mean returning `NaN` all the while emitting some kind of warning? That might be possible although I'm not sure yet with which amount of complication.

**Comment by seibert** [comment]
Correct.  A number of people depend on that behavior when doing array processing in NumPy.  (There may be an equal number of people confused when NaNs sneak into their array because they don't know about this behavior.)

**Comment by pitrou** [comment]
I've now added distinct error models for `@jit` and `@vectorize` functions. It controls the raising of an exception in standard operators.

**Comment by seibert** [comment]
Looks good!  Thanks!

**Pull request merged**
