### PR TITLE
Remove Python 2.

### PR DESCRIPTION
**Pull request by stuartarchibald**
This PR:

* Removes as much code as I could find that is now dead as a result of Numba's
  minimum version requirements moving to:
  * Python 3.6 (and by extension MSVC 2015+, therefore C99 maths compliance
     on all platforms)
  * NumPy 1.15
  * SciPy 1.0
* Removes `numba.six` and ports the few functions that are still needed into
  `numba.utils` (not sure why they were in `six` in the first place, presumably
   convenience).
* Makes a single definition of "Python version" `numba.utils.PYVERSION` and a
  single definition of "NumPy version" `numba.numpy_support.numpy_version`.
  These spellings are now used throughout. In general "spellings" of common
  things like "this needs BLAS" or "is this 32 bit" are now in `numba.utils`
  awaiting further refactoring and cleanup.
* Removes a number of now unused source files (e.g. ones with split Python 2/3
  syntax)
* Fixes up all the C code to now be Python 3 only.
* Removes `from __future__ import <python 2 backport>` imports.
* Removes `@tag()` from tests, they are not used any more.
* Patches up the code base against the above changes.

This is best effort, the code base is huge! If anything has been missed it can be cleaned in subsequent PRs.

### CODE REVIEW

**Comment by sklam** [comment]
I think there are C99 math problems on windows.

**Comment by sklam** [comment]
Started `numba_smoketest_cpu_10`

**Comment by sklam** [comment]
smoke test passed

**Comment by esc** [comment]
🎉

**Pull request merged**
