### PR TITLE
Use an object code-based JIT compilation cache

### PR DESCRIPTION
**Pull request by pitrou**
*Note*: I'd rather hold this until after 0.21 is released.

This is based on PR #1051 and saves the object code instead of the LLVM bitcode, which makes it more than 10x faster on loading than PR #1051 (and overall more than 100x faster than without caching).

### CODE REVIEW

**Comment by seibert** [comment]
Is #1051 ready for review now, or are you still working on it?

**Comment by pitrou** [comment]
It's based on the list object PR, and also I want to avoid crashes with ctypes :)

**Comment by seibert** [comment]
Now that #1051 seems to be passing on all platforms, I think this PR can be refreshed.

**Comment by pitrou** [comment]
Ok, I had some trouble with a large memory leak which was crashing the tests on Travis (technically a timeout, but probably due to heavy swapping). Then it turned out the faulthandler hook I had added somehow also was problematic in multi-process mode, so I removed it again :-) Now the test suite seems ok on Travis (I couldn't reproduce the timeouts locally).

**Pull request merged**
