### PR TITLE
Support "not in" as well as operator.contains()

### PR DESCRIPTION
**Pull request by pitrou**
Also support "in" on homogenous tuples.

Based on PR #1733.

### CODE REVIEW

**Comment by datnamer** [comment]
@pitrou in general can non-homogenous data structures be supported performantly and eventually by "generating explicit branches at compile time rather than relying on runtime dispatch.", as is proposed for Julia?

**Comment by pitrou** [comment]
Can you point to me what Julia's proposal is?

Numba already supports non-homogenous tuples, as well as Numpy structured arrays.

**Comment by seibert** [comment]
Github is still showing the diff with the types_refactor changes.  Can you try merging master to see if that cleans up the diff?

**Comment by pitrou** [comment]
Yes, done.

**Pull request merged**
